### ISSUE TITLE
Images déformées sur la page "Comment donner son avis" sur mobile

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1000]
![image](https://user-images.githubusercontent.com/657716/126659159-f511e781-6c31-46a3-b026-f4e8bf189625.png)

**Comment by lucaa** [comment]
Le problème est causé par le fait qu'une taille verticale a également été spécifiée avec la taille horizontale de 600 , pour le ticket #982 . 

Comme la vraie taille horizontale utilisée est 600 _ou_ 100% de la largeur de page et que le mobile est plus étroit que 600, la taille verticale étant toujours honorée, on se retrouve avec une image déformée.
La solution est de spécifier une seule dimension (l'horizontale) et laisser l'autre être calculée en fonction de la première.

**Comment by lucaa** [comment]
J'ai mis à jour la page en production aussi et dans les sources, pour enlever les hauteurs explicites.

Le résultat est désormais:
![image](https://user-images.githubusercontent.com/657716/126666504-41f0c29a-983a-4351-8257-c145383f642f.png)

@AnthonyBrunelli peux-tu confirmer qu'il n'y a pas de raison particulière d'avoir cette taille verticale explicite pour les images?

**Comment by AnthonyBrunelli** [comment]
Non, je ne vois pas de raison particulière. Peut-être qu'on en verra une quand il n'y en aura plus :) . Donc vas-y tu peux y aller.

**Comment by lucaa** [comment]
> Donc vas-y tu peux y aller.

C'est fait, depuis hier (depuis mon dernier commentaire).

**Comment by AnthonyBrunelli** [comment]
Contrôlé sur mobile, c'est ok !
