### ISSUE TITLE
Couleur de fond incomplète et bordures arrondies pour une ligne de tableau de l'observatoire en mode déplié

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1001]
Sur production:

![image](https://user-images.githubusercontent.com/657716/126660511-003dff04-3506-49a1-aca7-6a1826aa28f0.png)

Sur staging:

![image](https://user-images.githubusercontent.com/657716/126660629-94529bb9-41a6-455b-8260-49e35ee72228.png)

**Comment by lucaa** [comment]
Conséquence du changement de markup du tableau faite pour #846, il faut ajouter encore quelques règles CSS.

**Comment by lucaa** [comment]
Done, j'ai complété le CSS modifié pour #846 pour ajouter des règles supplémentaires.

**Comment by AnthonyBrunelli** [comment]
ça m'a l'air bon en staging.

**Comment by AnthonyBrunelli** [comment]
C'est ok!
