### ISSUE TITLE
Marge disproportionnée en dessous du texte de l'explication du critère "prise en compte handicaps", par rapport à la taille de la case blanche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1002]
Lors de la modification des textes pour le ticket #985 , le texte du critère "prise en compte handicaps" est devenu un peu long par rapport à la taille de la case blanche.

![image](https://user-images.githubusercontent.com/657716/126661930-6380b465-4b34-4004-bcc7-23fc07d6a65f.png)

@AnthonyBrunelli je te laisse décider si c'est gênant et tu veux modifier le texte ou bien si ce n'est pas un problème (dans quel cas il faudrait fermer avec label wontfix).

**Comment by ugodtn** [comment]
@lucaa J'ai vu avec Anthony, ce n'est pas bloquant pour le moment, car on va de toute façon revoir ces textes de nouveau. Mais il faudra corriger ça un jour.

Au passage, ce ne serait pas possible d'avoir des flexbox pour s'assurer que la case se redimensionne en conséquence (enfin que toutes les cases de la ligne, car elles doivent garder la même hauteur sur une ligne) ? Ça demande de peaufiner un peu, mais c'est faisable, il me semble.

**Comment by lucaa** [comment]
> Au passage, ce ne serait pas possible d'avoir des flexbox pour s'assurer que la case se redimensionne en conséquence (enfin que toutes les cases de la ligne, car elles doivent garder la même hauteur sur une ligne) ? Ça demande de peaufiner un peu, mais c'est faisable, il me semble.

Oui, effectivement, il faudra mettre du flex. Je ne l'avais pas fait initialement à cause de son support par les navigateurs, mais c'est tout à fait possible. 
D'ailleurs, c'est une question qui m’intéresse au niveau de la stratégie générale: quel est l'objectif en terme de support des navigateurs?

**Comment by lucaa** [comment]
> D'ailleurs, c'est une question qui m’intéresse au niveau de la stratégie générale: quel est l'objectif en terme de support des navigateurs?

Voir plus de discussions à ce sujet sur la tâche #841 et surtout dans la tâche #1025 .

**Comment by lucaa** [comment]
Cette amélioration sera couverte par l'implémentation de #1052 , dans la version 4.10.
@AnthonyBrunelli y-a-t-il une autre priorité à considérer ou c'est bon dans le cadre de #1052 ?
