### ISSUE TITLE
Les étiquettes des critères de l'observatoire sont décalées lors de l'affichage sur mobile

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1003]
En production:

![image](https://user-images.githubusercontent.com/657716/126674820-781fe221-185f-4329-878a-2d5ab2a969c8.png)

Sur le serveur de staging:

![image](https://user-images.githubusercontent.com/657716/126674856-7849985e-9bb5-42f7-8165-59d9d1268933.png)

C'est une conséquence de la modification de markup du tableau qui a été faite pour #846 .

**Comment by lucaa** [comment]
J'ai mis à jour le CSS pour les étiquettes sur mobile, pour prendre en compte l'entête de ligne, je ferme.

**Comment by AnthonyBrunelli** [comment]
ça a l'air bon en staging.
