### ISSUE TITLE
Bouton JDMA - accents dans l'URL

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1005]
Exemple: https://voxusagers.numerique.gouv.fr/Demarches/1878?&view-mode=formulaire-avis&nd_mode=en-ligne-entièrement&nd_source=button&key=965bf983e2413b74d17048ab787e3999

Le caractère accentué dans l'URL est contraire aux bonnes pratiques. Est-ce facile à modifier? Quelles seraient les conséquences?

**Comment by lucaa** [comment]
En réalité, le caractère en question n'est pas dans l'URL même mais dans un paramètre de l'URL. 
Les bonnes pratiques ne peuvent pas vraiment imposer des choses au niveau des paramètres car les paramètres sont censé transmettre des valeurs à la page en question (dans ce cas au formulaire) et, dans l'absolu, on ne peut pas restreindre le fait que toutes les valeurs soit ASCII. 
Aussi, dans le code fourni par l'embed il n'est pas présent, car il est correctement encodé pour que l'URL soit toute ASCII comme il faut (qui est la méthode correcte pour transmettre des caractères spéciaux dans les paramètres des URLs): 
```https://voxusagers.numerique.gouv.fr/Demarches/1878?&view-mode=formulaire-avis&nd_mode=en-ligne-enti%C3%A8rement&nd_source=button&key=[...]``` . Les navigateurs (une partie au moins), par contre, font de la "magie" et décodent automatiquement les caractères encodés et les montrent dans la barre d’adresse avec leur vraie valeur.

Maintenant, de tout cela on doit lire que c'est un sujet qui n'est pas tout simple simple et qui peut être complexe techniquement (on a vu plusieurs difficultés à l'intégration de ces URLs avec caractères encodés), et la question de l’éviter est complètement legitime (pas parce-que c'est pas une bonne pratique mais parce-que ça ajoute des complexités et des discussions). 

La réponse est **oui**, on peut trouver une manière de l’éviter complètement, en rendant le mode "en-ligne-entièrement" comme valeur par défaut pour l'avis enregistré, et donc enlever cette valeur complètement de l'URL. C'est une tache de **complexité moyenne**, car ça nécessite la prise en compte de tous les URLs existants et surtout des cas ou cette valeur pourrait ne pas être la valeur souhaité (il devrait pas y avoir, mais on sait jamais).

**Comment by lucaa** [comment]
Doublon de #1063 . Je marque comme doublon et je le ferme pour 4.10.
