### ISSUE TITLE
Refonte de la mise en page du footer et re-agencement des élements

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1006]
L'objectif est d'obtenir les footers suivants:

Formulaire d'avis:
Desktop:
![Selection_183](https://user-images.githubusercontent.com/657716/128638821-7c4a55d3-f816-463e-a59d-daa0de4bebac.png)

Mobile:
![Selection_185](https://user-images.githubusercontent.com/657716/128638825-cb07518c-6a3a-4296-a60c-63e8aec2af99.png)

Observatoire:
![Selection_184](https://user-images.githubusercontent.com/657716/128638829-d0d7a83d-740c-40ff-8825-cc623a197c14.png)

Note: par rapport à l'image, pour l'observatoire un lien supplémentaire "Connexion" sera à mettre en place à la fin de la liste des liens, après Contact.

Aujourd'hui le footer est déjà différentié entre le formulaire d'avis et l'observatoire, il s'agit uniquement de déplacer les elements et changer les logos.

L'implémentation doit se rapprocher du footer defini par https://www.systeme-de-design.gouv.fr/, les tailles & breakpoints doivent être reprises de l'element 'footer' du système de design, avec comme base une conversion de 1em = 16px.

**Comment by lucaa** [comment]
Note: pour l'instant, pour la largeur maximale du footer nous gardons les tailles bootstrap qui sont déjà en place, qui sont assez proches des tailles dsfr, et pour faciliter une implémentation incrémentale.

**Comment by lucaa** [comment]
Note: La mention « Je donne mon avis » dans le texte en pied de page du formulaire (en italique sur la maquette) doit être dans une balise <em>.

**Comment by lucaa** [comment]
Voir aussi #1011 pour les destinations des différents liens du footer.

**Comment by ClemDee** [comment]
Le footer de la page a été mis à jour afin d'obtenir un rendu le plus proche possible de la maquette tout en gardant les styles bootstrap.

Il reste un problème de duplication d'id au niveau du logo du header et du footer, qui sera traité dans la tache #1019.

**Comment by AnthonyBrunelli** [comment]
Je ne sais pas s'il y a un lien avec la note précédente mais, dans le doute: il manque le logo "SP+" qui doit être à la place de "L'observatoire" dans le footer.

**Comment by ClemDee** [comment]
Le logo "SP+" a été mis à jour dans le header et le footer en même temps lors de la tâche #1008.

**Comment by ugodtn** [comment]
Je reviens sur cette carte car, de mon côté, je ne vois pas le logo SP+ (ni la modification de petit texte dans le footer). Je suis sur https://observatoire.numerique-staging.devxwiki.com/

**Comment by ugodtn** [comment]
On y est presque, j'ai juste quelques remarques :

- [ ] Dans le header, en mobile, centrer verticalement le logo du menu (hamburger)
- [ ] Dans le footer, il y a une certaine largueur d'écran ou le logo Observatoire passe sous le logo RF, c'est gênant, est-ce que l'on peut empêcher ce comportement, par exemple en réduisant alors légèrement le logo Observatoire ?
- [ ] Il manque toujours les logo SP+ de mon côté, j'ai ajouté la remarque dans cette tâche https://github.com/DISIC/wikidemarches/issues/1008

**Comment by ugodtn** [comment]
On y est presque, j'ai juste une remarque: il y a une certaine largueur d'écran ou le logo Observatoire passe sous le logo RF, c'est gênant, est-ce que l'on peut empêcher ce comportement, par exemple en réduisant alors légèrement le logo Observatoire ?
