### ISSUE TITLE
Mise en place de la taille verticale du header aux proportions dsfr

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1007]
Objectif (approx.):
![Selection_186](https://user-images.githubusercontent.com/657716/128639182-9eaf1d45-b3f1-45d5-bbb3-ca1e123719b2.png)

à faire, dans cette tâche:
* rendre le logo plus petit verticalement - les recommandations ont changé et permettent un logo plus serré
* revue de l'espacement _haut et bas_ pour s'approcher du dsfr.

à ne pas inclure dans cette tâche:
* changement de couleurs ou mise en place des liens, 
* changement du comportement sur mobile,
* changement de largeur - on reste sur les tailles courantes de bootstrap,
* changement des espacements horizontaux (les tailles des gutters bootstrap).

L'implémentation ayant comme objectif de se rapprocher du header defini par https://www.systeme-de-design.gouv.fr/, les tailles & breakpoints peuvent être reprises de l'element 'header' du système de design, avec comme base une conversion de 1em = 16px.

**Comment by ClemDee** [comment]
Le logo a été réduit en taille et les l'espacement haut et bas du header ont été revu pour s'approcher du dsfr.

**Comment by ugodtn** [comment]
Je vois qu'il ne s'agit pas ici de revoir la couleur des liens dans le header, mais alors où ?

**Comment by ugodtn** [comment]
> Je vois qu'il ne s'agit pas ici de revoir la couleur des liens dans le header, mais alors où ?

J'ai créé une carte spécifique pour cette tâche : #1023.
