### ISSUE TITLE
Mise en place du logo Services publics + dans le header sur lécran d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1008]
Le logo courant (voxusagers.fr) est à remplacer avec le logo services publics +, sur la page de formulaire d'avis, pour le résultat suivant:

![Selection_187](https://user-images.githubusercontent.com/657716/128639283-9ea38d25-65ab-40be-8385-4fb7a4360f47.png)

Note: le comportement sur mobile n'est pas reste celui en place aujourd'hui.

**Comment by lucaa** [comment]
La tâche #1006 utilise normalement le même logo, à rapprocher les implémentations.

**Comment by ClemDee** [comment]
Le logo "voxusager" a été remplacé par "services publics +", et les tailles / marges ont été conformément ajustées.

**Comment by lucaa** [comment]
Le correctif de 389dd77 introduit un bug en changeant la stratégie de choix de logo: c'est désormais le logo observatoire qui est affiché sur les _autres_ URLs voxusagers (i.e. toutes les pages de contenu: Accessibilite, CGU, etc).

> Le logo SP+ s'affiche désormais sur la page du formulaire quel que soit le nom de domaine (observatoire ou voxusagers).

Ceci n'était pas un _bug_ de la tâche courante (qui demandait uniquement de changer l'image et pas de changer les règles d'utilisation de cette image), mais une nouvelle fonctionnalité par rapport à l'existant. 

> NB: ce point est à contrôler sur voxusager.numerique.etc en staging. Je ne l'ai pas vu parce que pas sous la bonne URL a priori.

Il n'y a aucune raison pour un utilisateur de se retrouver, en pratique, sur une URL d'avis du domaine observatoire. Si on veut implémenter cela, c'est une nouvelle fonctionnalité, à traiter dans un nouveau ticket.

**Comment by ClemDee** [comment]
Commit 389dd77 reverté.

**Comment by ugodtn** [comment]
Je reviens sur cette carte car, de mon côté, je ne vois pas le logo SP+ (ni la modification de petit texte dans le footer). Je suis sur https://observatoire.numerique-staging.devxwiki.com/

**Comment by ClemDee** [comment]
Le logo SP+ n’apparaît que sur le nom de domaine `voxusagers` du formulaire.
Vous pouvez le voir sur [cette page](https://voxusagers.numerique-staging.devxwiki.com/Demarches/1897?&view-mode=formulaire-avis&nd_mode=en-ligne-enti%C3%A8rement&nd_source=button&key=9f6d2a5cc93b91073224efed38082d1e) par exemple.

**Comment by ugodtn** [comment]
> Le logo SP+ n’apparaît que sur le nom de domaine `voxusagers` du formulaire.
> Vous pouvez le voir sur [cette page](https://voxusagers.numerique-staging.devxwiki.com/Demarches/1897?&view-mode=formulaire-avis&nd_mode=en-ligne-enti%C3%A8rement&nd_source=button&key=9f6d2a5cc93b91073224efed38082d1e) par exemple.

Ok, sur cette page c'est bon 👍.

**Comment by AnthonyBrunelli** [comment]
Sauf erreur de ma part, l'alternative n'a pas été mise à jour.
On est d'accord sinon que le logo n'a pas été ajouté sur le staging "classique"?

**Comment by ClemDee** [comment]
Je ne vois pas trop de quoi tu veux parler @AnthonyBrunelli , j'ai bien vérifié sur [l'instance de staging](https://observatoire.numerique-staging.devxwiki.com/), et tout y est :
- le logo SP+ au lieu de voxusagers pour formulaire (avec le nom de domaine `voxusager`, et pas `observatoire`)
- le logo Observatoire qui a été réduit pour ne pas déborder en dessous du logo RF

Il s'agit peut être d'un problème de cache de ton coté ?

**Comment by ClemDee** [comment]
Ah d'accord je n'avais pas compris que c'est de ça dont tu parlais!

**Comment by ClemDee** [comment]
Le texte alternatif du logo SP+ a été corrigé et est maintenant : "Services Publics +"
