### ISSUE TITLE
Ajouter un separateur (ombre) entre le header et le contenu

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1009]
Objectif visuel:

![Selection_188](https://user-images.githubusercontent.com/657716/128639332-0db4a246-1d75-46b6-a530-813be042699f.png)

L'implémentation ayant comme objectif de se rapprocher du header defini par https://www.systeme-de-design.gouv.fr/, les decorations peuvent être reprises de l'element 'header' du système de design, avec comme base une conversion de 1em = 16px.

**Comment by ClemDee** [comment]
Le séparateur a été ajouté conformément au style du Design System.

**Comment by ugodtn** [comment]
Ok 👍
