### ISSUE TITLE
Mise en place des polices du dsfr

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1010]
Voir https://www.systeme-de-design.gouv.fr/ .

L'objectif de cette tâche est de mettre en place les polices en question sans toucher, pour l'instant, aux tailles.

**Comment by AnthonyBrunelli** [comment]
Ok pour changer une fois par toute partout MAIS il faudra un contrôle rigoureux pour les effets de bord. On avisera si problème et si la police est changée ultérieurement sur le formulaire, ça n'est pas super super grave.

**Comment by lucaa** [comment]
Voici quelques notes pour l'implémentation, @ClemDee :
Les polices utilisées aujourd'hui sont Marianne et Inter. Les deux sont définies dans https://github.com/DISIC/wikidemarches/tree/master/wikis/xwiki/src/main/resources/Fonts dans des SSX avec des pièces jointes.
Le SSX de la police Inter est incluse partout, à partir de la skin (stylesheets.vm) et déclarée comme police standard du text dans le thème (DemarchesThème), tandis que Marianne est uniquement incluse et utilisée sur les pages qui en ont besoin.

Je pense que la meilleure approche pour cette tâche est de rendre les polices du DSFR disponibles partout ayant comme source la distribution DSFR (si les polices ne sont pas dans notre distro scoped, il faudra les ajouter), potentiellement avec un SSX spécifique contenant la déclaration des webfonts, s'il n'y a pas de CSS juste avec la déclaration des polices dans DSFR - l'idée est d’éviter d'inclure le core DSFR partout, pour éviter les effets de bord. Ensuite remplacer la police Inter dans le thème par la police des contenus utilisée dans DSFR et laisser le reste tel-quel. Normalement, les titres qui utilisent aujourd'hui Marianne devraient continuer à marcher, car la police Marianne sera disponible par l'intégration des polices du DSFR.

**Comment by ClemDee** [comment]
Les polices du wiki ont été mise à jour globalement aux polices Mariannes, et Arial comme polices de substitution (conformément aux spécifications du Design System).
Les polices Mariannes proviennent désormais du dsfr présent sur le wiki.
Les polices Inter, devennues inutilisées, ont été retirées.

**Comment by lucaa** [comment]
@ClemDee quelques remarques:
* le ssx qui s'apelle Marianne contient également la police spectral, idéalement le nom du SSX reflète son usage. Il faudra peut-être renommer le SSX ?
* dans le même SSX, les URLs des ressources (polices) ne devraient pas être en dur, il faut utiliser l'API pour produire l'URL vers la ressource (dépendent du deploiement de l'instance XWiki).

Je rouvre pour gérer ces 2 aspects.

**Comment by lucaa** [comment]
@ClemDee il faudrait aussi mettre à jour les instructions d'installation ici https://github.com/DISIC/wikidemarches/wiki/Installation-Instructions-v-4.x#war-setup suite au correctif du 2b5036b .

**Comment by lucaa** [comment]
@ClemDee : aussi, https://github.com/DISIC/wikidemarches/commit/fa118f78a4d47c7be4164a9ecd88f3bdd4c70785#r55662602 .

**Comment by ClemDee** [comment]
Le fichier MarianneWebFontSSX.xml contenant la déclaration des fonts du dsfr a été renommé en  DSFRWebFontSSX.xml, et le chemins vers les fontes du `dsfr-scoped` est maintenant résolu en vélocity.
Les définitions explicites des fonts Mariannes des fichiers du wiki ont été retirées, car devenus redondantes / inutiles.

**Comment by AnthonyBrunelli** [comment]
@ClemDee ça c'est de l'interne chez vous ou il faut qu'on contrôle quelque chose de notre côté? Si chez vous et si ok, je te laisse passer ça en Done & tested.

**Comment by ClemDee** [comment]
Cette tâche correspond à la mise en place des polices du dsfr au niveau du wiki, donc oui il faut contrôler que les polices s'affichent correctement et que rien n'a été cassé au niveau de l'affichage

Cf. ton message plus haut :
> Ok pour changer une fois par toute partout MAIS il faudra un contrôle rigoureux pour les effets de bord.

**Comment by AnthonyBrunelli** [comment]
Ok contrôle effectué c'est bon pour moi, je passe en Tested.
