### ISSUE TITLE
Vérification et mise en place des liens vers les pages de documentation du footer

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1011]
Il s'agit des pages:
* accessibilité, qui sera différente entre le footer du formulaire d'avis et le footer de l'observatoire
* CGU , Mentions legales et Données personelles - qui pointent tous vers la même pages, vers les sections dédiées
* la création de la page plan du site qui devra contenir les mêmes liens qui sont aujourd'hui dans la section plan du site du footer mais dans une page séparée

La mise à jour des contenus des pages en question sera à faire aussi dans cette tâche, si necessaire.

**Comment by lucaa** [comment]
2 remarques par rapport à la finalisation de ce ticket:
* Demarches ne me semble pas le bon espace pour loger cette page d'accessibilité (ça serait la première page avec des contenus editoriels "publics" dans cette espace). Je prefère essayer de garder les mêmes espaces pour ces pages que les espaces déjà utilisés (Main ou Aide), et de preference le même espace que la page "d'accessibilité principale"
* quelque soit l'emplacement de cette page, comme c'est une page de contenu à mettre en place en prod, il faut l'ajouter dans la liste des pages exclues de la mise à jour dans le pom du paquet de mise à jour https://github.com/DISIC/wikidemarches/blob/master/wikis/xwiki-upgrade/pom.xml .

**Comment by ClemDee** [comment]
La page d'accessibilité du formulaire a été déplacée dans l'espace "Main", et le lien du footer a été conformément mis à jour.
Les fichiers de contenu `Main.accessibilite-formulaire` et `Main.plan-site` ont été rajoutés dans le fichier `pom.xml` de mise à jour.

**Comment by AnthonyBrunelli** [comment]
Alors je pense qu'il faudra reparler de cette fiche, ça sera plus simple. Je vois un problème déjà: si je clique sur "Accessibilité : non conforme" j'arrive sur une page de l'Observatoire, avec en pied de page "Accessibilité : partiellement conforme"...

**Comment by lucaa** [comment]
Je rouvre, pour tracer le fait qu'il reste des choses à faire.

**Comment by ClemDee** [comment]
Les liens du footer s'affichent maintenant suivant le nom de domaine, et plus par rapport au fait qu'on se situe ou non sur le formulaire.

**Comment by lucaa** [comment]
> Je vois encore un petit soucis : quand on est sur le formulaire Je donne mon avis, et que l'on navigue vers les pages Accessibilité ou CGU, on reste bien sur le domaine voxusager mais le footer n'est plus bon : se sont ajouté les blocs Réseaux sociaux et Nos sites qui ne devraient pas être présents.

Effectivement, la condition doit être changée.

**Comment by AnthonyBrunelli** [comment]
Ok, ça me semble ok, et pour toi @ugodtn ?
NB: il va falloir rédiger les contenus.

**Comment by AnthonyBrunelli** [comment]
Vu avec Ugo, ok!
