### ISSUE TITLE
Rendre le formulaire d'avis plus étroit que le reste du site (et du header et footer)

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1012]
L'objectif est d'obtenir, pour le formulaire d'avis, une mise en page similaire au visuel suivant:

![Selection_189](https://user-images.githubusercontent.com/657716/128639933-8e1c2e19-3ad2-4e14-961d-57c2d1b0ea5b.png) .

La taille horizontale de ce formulaire est à choisir de la manière suivante:
* le nombre de colonnes bootstrap rapportés au conteneur fixe bootstrap (celui qui est mis en place actuellement) qui donnent la taille la plus proche de 809px sur un écran de 1440px
  * normalement ça doit être 8 ou 10 colonnes.

Pour le responsive, le tout doit passer à 100% pour la taille téléphone, <768px.

**Comment by lucaa** [comment]
À faire aussi:
mettre en place les marges pour obtenir l'espacement entre les latérales du conteneur du formulaire et le début du texte:

![Selection_190](https://user-images.githubusercontent.com/657716/128640112-7b828fe7-1dbf-4e4c-9dff-0a6dd392efcc.png)

Il faudrait détérminer à quoi correspondent ces distances. Normalement le système de design utilise aussi des colonnes, comme bootstrap, ces dimensions correspondent probablement à une colonne supplémentaire de chaque côté. 

Sinon, chercher dans le système de design de l'état des sources potentielles de ces tailles.

**Comment by AnthonyBrunelli** [comment]
Pas les droits/connaissance sur Sketch pour établir la règle. Comme facile à changer, on part sur la conversion px - em.

**Comment by ClemDee** [comment]
Le formulaire a été rendu plus étroit que le reste du site, et les marges intérieures ont été rajoutée converties en rem.

**Comment by ugodtn** [comment]
Ça me semble très bien. J'ai une remarque cependant, mais je ne sais pas si elle concerne cette carte (sinon laquelle ?) : il manque le fond bleu en haut par rapport à la maquette.

**Comment by ClemDee** [comment]
En effet, le fond bleu correspond au ticket #1013, et n'a pas encore été implémenté.

**Comment by ugodtn** [comment]
Ok, je valide donc cette tâche.
