### ISSUE TITLE
Fond d'écran bleu à mettre en place pour le titre du formulaire d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1013]
Objectif visuel:

![Selection_191](https://user-images.githubusercontent.com/657716/128640215-5fbd224c-7e71-4ca0-830e-d122247e00ff.png)

La couleur vient du système de design de l'état: https://www.systeme-de-design.gouv.fr/ .

L'objectif est de faire ce changement uniquement pour le formulaire d'avis, pour l'instant (techniquement dans une / des stylesheet(s) chargé(s) uniquement pour le formulaire d'avis).

**Comment by lucaa** [comment]
Je pense qu'il sera compliqué de mettre en place ce bandeau comme ça, vue la structure des conteneurs. Je baisse la priorité de cette tâche.
Il faudra chercher une solution pendant 0.5-1h et, si aucune solution ne se profile, revoir sa necessité.

**Comment by ClemDee** [comment]
Le fond bleu a été implémenté conformément à la maquette.

**Comment by lucaa** [comment]
> Le fond bleu a été implémenté conformément à la maquette.

Je pense qu'il y a un problème avec la solution trouvée, de mon côté j'ai une barre de scroll horizontale liée à la taille du header bleu (sur firefox mais aussi sur chrome):

![Selection_221](https://user-images.githubusercontent.com/657716/133467104-8755b390-9ea2-400f-9bf6-15d5aa318593.png)

![Selection_222](https://user-images.githubusercontent.com/657716/133467110-82ff3b49-22a2-494a-b6a2-9b2f9164ae2c.png)

Je rouvre pour vérifier cela.

**Comment by ClemDee** [comment]
Oh oui en effet ! C'est incroyable que je n'ai jamais ça pendant le développement ! Un petit `overflow-x: hidden` et devrait suffire je pense.

**Comment by ClemDee** [comment]
Le petit problème d'overflow a été fixé :slightly_smiling_face:
