### ISSUE TITLE
Intégration des éléments de formulaire du design system pour le formulaire d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1015]
Objectif visuel (partiel):

![Selection_194](https://user-images.githubusercontent.com/657716/128640560-7a54abd6-58cd-49e3-bb78-83aad635366a.png)

Cette tache concerne l'identification et mise en place des éléments du système de design de l'état ( https://www.systeme-de-design.gouv.fr/ ) pour les éléments du formulaire "standard", pour lesquels le design system propose un élément:
* boites de messages (succès, avertissement, erreur, info),
* bouton primaire en bas,
* cases à cocher,
* texte court (affiché lors de la séléction de l'option "autre" des questions présentant des choix),
* texte long (affiché pour le verbatim).

L'objectif est de faire ces changements uniquement pour le formulaire d'avis, pour l'instant (techniquement dans une / des stylesheet(s) chargé(s) uniquement pour le formulaire d'avis).

Des tâches séparées peuvent être créées pour chacun des éléments, si nécessaire, pour un meilleur suivi de l'avancement, mais le rendu globale ne doit pas être oublié.

**Comment by ClemDee** [comment]
Les composants indiqués dans cette tache ont été portés au Design System avec succès.

Une version "scopée" du dsfr a due être implémentée afin d'assurer l'application des règles de style par dessus celles de Bootstrap déjà existantes, et éviter toute propagation non voulue du thème à l'extérieur du formulaire.

Les labels et les marges entre les composants, prévus pour la tâche #1014, ont aussi été mis à jour dans cette tâche là.

**Comment by lucaa** [comment]
J'ai ajouté les instructions d'installation pour les resources DSFR (aussi pour ticket #1016 ) dans les instructions d'installation, à la fin de la section "war setup" ici https://github.com/DISIC/wikidemarches/wiki/Installation-instructions-v-4.x#war-setup .

**Comment by AnthonyBrunelli** [comment]
Sur la première page du formulaire, le bouton "Valider" doit être grisé tant que non activable.

**Comment by lucaa** [comment]
Je ne suis pas sure qu'il est raisonnable de garder ce ticket ouvert en attendant un correctif sur lequel nous n'avons pas le control, sachant que l'objectif fonctionnel de ce ticket est bien plus large et que tout le reste fonctionne sans problème (le défaut n'est pas bloquant).
Soit:
* on amène le correctif dans notre zone de control, en agissant sur le problème (implémenter un contournement du problème dsfr , ou proposant un PR), pour pouvoir avoir une visibilité du chemin vers la fermeture de ce ticket,
* on isole le seul manquant dans un ticket séparé, qui pourra rester ouvert plus longtemps, et on ferme celui-ci pour marquer que l'objectif plus large de ce ticket a été atteint.

Je préfère largement l'option numéro 2, surtout que l’élément manquant n'est pas bloquant pur l'objectif du ticket.

**Comment by ClemDee** [comment]
Le problème du bouton a été séparé dans un ticket isolé (#1021) afin de ne pas bloquer le reste du ticket.

**Comment by ugodtn** [comment]
J'ai remarqué que sur mobile, le bouton avait des bords arrondis, alors qu'il ne devrait pas.

**Comment by ugodtn** [comment]
> J'ai remarqué que sur mobile, le bouton avait des bords arrondis, alors qu'il ne devrait pas.

Je précise que j'ai ce comportement sur safari mobile sur iPhone.

**Comment by ClemDee** [comment]
Je n'ai pas moyen de tester ça de mon coté, mais je ne vois aucune règle du coté xwiki se rapportant au style du bord des boutons, donc cela provient probablement des styles par défaut de safari qui n'ont pas été correctement écrasés par les styles du DS. C'est peut-être un autre problème à creuser et à faire remonter au github du dsfr !

**Comment by AnthonyBrunelli** [comment]
@ugodtn je comprends que cette carte est 'résolu'. Je la passe en Tested, je te laisse la redéplacer autre part si tu l'estimes nécessaire.
