### ISSUE TITLE
Message explicatif à la fin du formulaire d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1017]
à la fin de la deuxième page du formulaire d'avis, lors du remerciement final, il faut ajouter une note sur l'utilisation de cet avis, ainsi:

Desktop:

![Selection_199](https://user-images.githubusercontent.com/657716/128641124-ecbfcad5-4cd8-457c-b074-2283bfc8b9f7.png)

Mobile:

![Selection_198](https://user-images.githubusercontent.com/657716/128641132-37a4d1ae-4317-44e5-8a19-df07b88435d9.png)

**Comment by lucaa** [comment]
@AnthonyBrunelli le lien de ce message mène vers la page d'accueil https://observatoire.numerique.gouv.fr ou vers l'observatoire lui même https://observatoire.numerique.gouv.fr/observatoire ?

**Comment by AnthonyBrunelli** [comment]
Plutôt vers la page d'accueil parce que sinon l'usager arrive en haut de tableau, pas sur sa démarche, du coup c'est mieux de passer par la présentation je pense.

**Comment by ugodtn** [comment]
Ça me semble ok. Pour les passages à la ligne, je ne suis pas certain de ce dont tu parles @AnthonyBrunelli, mais j'imagine que ça dépend juste de la taille de l'écran. Pour le pictos, j'hésite. Je n'avais pas pris dans le DS car c'est un peu trop limité pour le moment. Je crois que je préfère utiliser ce que j'avais prévu, qui proviennent de https://feathericons.com/.

**Comment by ugodtn** [comment]
> Ça me semble ok. Pour les passages à la ligne, je ne suis pas certain de ce dont tu parles @AnthonyBrunelli, mais j'imagine que ça dépend juste de la taille de l'écran. Pour le pictos, j'hésite. Je n'avais pas pris dans le DS car c'est un peu trop limité pour le moment. Je crois que je préfère utiliser ce que j'avais prévu, qui proviennent de https://feathericons.com/.

Je peux aussi vous les passer directement si besoin.

**Comment by ugodtn** [comment]
> > Ça me semble ok. Pour les passages à la ligne, je ne suis pas certain de ce dont tu parles @AnthonyBrunelli, mais j'imagine que ça dépend juste de la taille de l'écran. Pour le pictos, j'hésite. Je n'avais pas pris dans le DS car c'est un peu trop limité pour le moment. Je crois que je préfère utiliser ce que j'avais prévu, qui proviennent de https://feathericons.com/.
> 
> Je peux aussi vous les passer directement si besoin.

Les voici : 
[SVGs.zip](https://github.com/DISIC/wikidemarches/files/7097694/SVGs.zip)

**Comment by AnthonyBrunelli** [comment]
ça m'a l'air ok. @ugodtn tu confirmes?
