### ISSUE TITLE
L'id du logo du header est dupliqué dans la page, rendant l'HTML invalide

### ISSUE THREAD

**Issue by ClemDee** [DISIC/wikidemarches#1019]
La template `compagnylogo.vm` étant maintenant utilisée à la fois dans le header et le footer de la page, il faut transformer l'attribut `id="compagnylogo"` de cette template en attribut `class`, afin d'éviter la duplication de cet id rendant l'HTML invalide.

**Comment by ClemDee** [comment]
L'id dupliqué a été remplacé par une classe.

**Comment by AnthonyBrunelli** [comment]
@ClemDee Salut! Si c'est un truc chez vous qui est ok, tu peux passer ça dans la colonne Tested stp?
