### ISSUE TITLE
Rendre le bouton du formulaire grisé quand non activable

### ISSUE THREAD

**Issue by ClemDee** [DISIC/wikidemarches#1021]
Ce ticket sépare une sous tâche du ticket #1015, qui est en attente d'un fix de la part d'une de ses dépendances.

Le bouton de validation du formulaire doit être grisé lorsque celui-ci n'est pas activable. Cependant, les styles dsfr utilisés ne prennent pas en compte le cas spécifique de la balise `<input type="submit" />` désactivée, ne rendant pas le bouton grisé.

**Comment by ugodtn** [comment]
Étrange, selon la doc ce devrait être le cas. Tu as remarqué ça @benoitdequick ? Je vais explorer.

**Comment by ugodtn** [comment]
> Étrange, selon la doc ce devrait être le cas. Tu as remarqué ça @benoitdequick ? Je vais explorer.

Je viens de vérifier @ClemDee, c'est bien le cas normalement avec le DSFR, dès qu'on ajoute l'attribut `disabled` à un bouton, il prend l'état grisé. Cf. [la doc du système de design](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217284660/Boutons+-+Buttons#%C3%89tat-inactif).

**Comment by ClemDee** [comment]
L'input de type submit a été remplacé par un button de type submit, fixant le problème de styles lorsque celui-ci est désactivé.
Du coup, plus besoin d'attendre le fix des styles du DS.
