### ISSUE TITLE
Footer de l'Observatoire : petit bug d'affichage

### ISSUE THREAD

**Issue by ugodtn** [DISIC/wikidemarches#1022]
Il y a une certaine largueur d'écran où le logo Observatoire passe sous le logo RF, c'est gênant, est-ce que l'on peut empêcher ce comportement, par exemple en réduisant alors légèrement le logo Observatoire ?

**Comment by ClemDee** [comment]
Le logo de l'observatoire a été réduit dans le cas où il passait sous le logo RF afin d'éviter ce problème.

**Comment by AnthonyBrunelli** [comment]
@ugodtn C'est bon pour toi?

**Comment by ugodtn** [comment]
C'est ok pour les tailles d'écran qui posaient problème, mais je vois qu'il y a maintenant un soucis sur les tailles d'écran plus petites, type iPhone 5. Le logo de l'Observatoire se retrouve sous RF, ce qui n'est pas gênant, mais la marge à gauche est nulle. Elle devrait être la même que pour RF.

<img width="321" alt="Capture d’écran 2021-09-17 à 11 26 42" src="https://user-images.githubusercontent.com/34340568/133760547-001aba3a-6749-4096-a86e-00484bc39880.png">

**Comment by ClemDee** [comment]
Le logo secondaire est maintenant aligné s'il passe en dessous du logo RF.

**Comment by lucaa** [comment]
@ClemDee il y a plusieurs problèmes avec la solution de https://github.com/DISIC/wikidemarches/commit/c035893bea12c972fe185e1a288dc0ae22b59b22 :
* je ne pense pas que ça soit une super idée de mélanger des rems avec des px, en _supposant_ que le rem aura toujours 16px. Notamment, la taille du rem dépend de la taille de la police du navigateur _de l'utilisateur_, et ceci est ainsi pour des raisons d'accessibilité. 
* si on veut une solution résiliente, l'approche à favoriser est de chercher et d'utiliser _la même règle_ pour le padding gauche des deux éléments qui doivent être alignés, pour assurer qu'ils restent alignés même si la règle change. Ainsi, si on cherche le padding du logo marianne, on constate qu'il est à 15px, pas à 16, et je dirais que ce 15 n'est pas un 15 hardcodé mais la variable bootstrap @grid-gutter-width / 2 .

**Comment by ClemDee** [comment]
Mis à jour de la valeur du padding.

(Duplication de commit à cause de l'extension gitlab de l'instance XWiki)
