### ISSUE TITLE
Bouton de retour en haut de page sur le tableau de l'Observatoire

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1024]
Concernant le bouton de retour en haut de page:
1/ Supprimer l'animation
2/ Centrer le triangle (image ci-jointe)
3/ Dans la navigation clavier, le mettre *avant* le footer.

**Comment by AnthonyBrunelli** [comment]
(ah bah non le format n'est pas pris en charge donc pas de fichier joint).

**Comment by AnthonyBrunelli** [comment]
Le fichier: https://drive.google.com/file/d/1BqTofmwZo-OjcFpbtGkjVKpGm-BiWtCM/view?usp=sharing

**Comment by ClemDee** [comment]
Les tâches suivantes ont été réalisées :
* Suppression de l'animation au survol de la souris
* Élévation de la flèche afin de restaurer l'équilibre du bouton
* Mise en place du bouton avant le footer pour la navigation clavier
