### ISSUE TITLE
Rendre les couleurs du thème de couleurs coherents avec leur usage dans le navbar

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1027]
Pour #1023 une personnalisation des couleurs du navbar a été mise en place pour implémenter les couleurs du navbar, pour éviter d'impacter le footer.

La stratégie idéale est d'avoir une cohérence entre les noms et les valeurs des couleurs du thème et le résultat à l'écran.

Voir plus dans https://github.com/DISIC/wikidemarches/commit/4210232610dcd6e2df31dfe1d2db4a5cdb4e9d7f#r56514971 .

**Comment by ClemDee** [comment]
Après quelques recherches, il s'avère que ce problème provient des fichiers de style less par défaut du skin :
[skin/flamingo/less/layout.less](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-resources/src/main/resources/flamingo/less/layout.less#L281),
car la distribution par défaut considère que le footer est très simple et ne contient que le numéro de version de l’instance.

(`@navbar-default-brand-color` étant défini dans le fichier `less/bootstrap/variables.less` comme `@navbar-default-link-color`, valeur modifiée dans la page theme de l'instance)

Pour moi la solution la plus simple est de re-spécifier la couleur du texte du footer directement dans les règles customs du thème en la couleur du texte par défaut.

**Comment by ClemDee** [comment]
* Usage des variables de theme globales pour les navbar
* Re-spécifications de la couleur du texte du footer en la couleur du texte par défaut

@lucaa dis moi si la solution proposée te semble ok, ou si pour toi il y a plus à faire pour régler ce problème.

**Comment by lucaa** [comment]
> @lucaa dis moi si la solution proposée te semble ok, ou si pour toi il y a plus à faire pour régler ce problème.

C'est bon comme ça, c'est ce que je voulais. 
Il y aura des mises à jour du thème de couleurs en version 4.10 , de toute manière, occasion pour revoir tout ça.
