### ISSUE TITLE
Formulaire JDMA + graphes démarche en mode déconnecté : retirer les éléments role=“tabpanel” et aria-labelledby=“avis-tab”

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1030]

**Comment by lucaa** [comment]
Du markup similaire est présent également sur l'écran des graphes d'une démarche qui s'affiche lors du click sur le lien "graphes" dans l'observatoire.
Pour les utilisateurs connectés, ces écrans affichent la démarche avec toutes ses informations, donc avec les onglets qui rendent les attributs role et aria-labelledby utiles. Par contre, pour les utilisateurs non-connectés, il n'y a pas d'onglets et, comme pour le formulaire d'avis, ces attributs sont incorrects.

**Comment by lucaa** [comment]
Un correctif a été mis en place pour les 2 écrans, pour ne pas inclure le markup d'onglets dans un contexte mono onglet.

Par contre, pour l'écran des graphes d'une démarche, comme le markup est mis dans un cache qui est initialisé une fois par jour (#867) et qui n'est pas invalidé selon le type d'accès (connecté ou pas), le résultat dépend du contexte du premier accès du jour - il peut y avoir les attributs sur l’écran non-connecté si le premier accès est connecté et inversement.
Pour les démarches aux beaucoup d'avis du top250 le cache est pré-calculé en mode invité toutes les matins, donc ça devrait être correct pour ces démarches là.
Cette limitation sera corrigée par l'implémentation de #866 , à partir de laquelle le cache html ne sera plus nécessaire.

**Comment by AnthonyBrunelli** [comment]
Vu avec Ugo: 
- Ok pour le formulaire JDMA
- Non contrôlable pour graphes démarche en mode déconnecté (pas d'avis en staging sur l'Obs). 

Disons ok.
