### ISSUE TITLE
Site de l'Observatoire : sur mobile, il manque un bouton “fermer le menu”

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1032]

**Comment by ugodtn** [comment]
@lucaa j'ai demandé des avis d'experts et on est presque bon :
- visuellement, il faut remplacer l'icône burger par une croix (celle du DSFR tant qu'à faire) comme on s'était dit
- dans le markup, il faut juste modifier le texte associé au bouton pour qu'il passe de "Ouvrir le menu" à "Fermer le menu" lorsque le menu est ouvert, et inversement (il y a donc aussi une petite modification du texte lui-même)

**Comment by ugodtn** [comment]
Ah, j'allais oublier aussi @lucaa :
- [ ]  Si le JavaScript est désactivé, il faut dans ce cas garder le menu ouvert en permanence.

**Comment by lucaa** [comment]
> @lucaa j'ai demandé des avis d'experts et on est presque bon :
> 
> * [ ]   visuellement, il faut remplacer l'icône burger par une croix (celle du DSFR tant qu'à faire) comme on s'était dit
> * [ ]   dans le markup, il faut juste modifier le texte associé au bouton pour qu'il passe de "Ouvrir le menu" à "Fermer le menu" lorsque le menu est ouvert, et inversement (il y a donc aussi une petite modification du texte lui-même)

Je n'ai pas tant de connaissances de rgaa pour pouvoir trancher toute seule, mais est-ce qu'il est acceptable du pdv RGAA d'avoir 2 boutons qui sont cachés alternativement, ou il faut absolument que ça soit un seul bouton qui change de paramètres?

**Comment by ugodtn** [comment]
@lucaa j'ai posé la question à notre expert accessibilité @yaaax qui viendra directement te répondre ici ;).
Pour info, c'est Yaacov qui va aussi s'occuper de faire l'audit.

**Comment by yaaax** [comment]
Bonjour @lucaa,

Pour répondre à la question "est-il acceptable d'avoir bouton de menu accessible en utilisant 2 boutons alternativement cachés", je dirais oui, mais ce sera certainement plus compliqué à faire qu'en utilisant un bouton unique.

### Analyse de la solution actuellement en production

#### Des points positifs :
- l'attribut `aria-expanded` qui prend la alternativement la valeur `true` lorsque le menu est ouvert et `false` lorsqu'il est fermé ;
- l'attribut `aria-controls` qui connecte bien le bouton avec les liens de navigation (`xwikimainmenu`) ;
- le bouton a un intitulé explicite : "*Ouvrir la navigation*". Notons qu'il n'est accessible qu'aux technologies d'assistance (lecteur d’écran, afficheur braille, etc.)

#### Des points négatifs :
- lorsque le menu est ouvert, le _burger_ demeure et n'est pas remplacé, comme sur de nombreux sites, par une croix ou un autre symbole qui indiquerait visuellement que l'on peut refermer le menu ;
- lorsque le menu est ouvert, l'intitulé est toujours "*Ouvrir la navigation*", ce qui est incorrect ;
- lorsque javascript est désactivé, le menu reste fermé et il est impossible de l'ouvrir.

### Que faire ?

#### Le menu est-il réellement nécessaire ?
Vu qu'il n'y a que 2 entrées dans ce menu, il est tout simplement possible de supprimer le bouton de menu, c'est surement la meilleure chose à faire en terme de simplicité, de maintenance, d'écoconception, de design...
- Voir ce site en exemple : [Design Accessible](https://design-accessible.fr/) ;
- Une ressource intéressante au sujet des menus, de leur bouton, et des tables de matières : [Menus & Menu Buttons](https://inclusive-components.design/menus-menu-buttons/).

#### Corrections
- pour éviter une implémentation à 2 boutons dont la mise en accessibilité serait difficile, je suggèrerais de plutôt utiliser les CSS, en utilisant par exemple les pseudo-éléments `::before` et `::after` comme sur [Tasty CSS-animated hamburgers](https://jonsuh.com/hamburgers/) ;
- il faudrait remplacer l'intitulé "*Ouvrir la navigation*" par "*Fermer la navigation*" lorsque le menu est ouvert, via JavaScript ;
- il faudrait s'assurer que le menu est ouvert lorsque JavaScript est désactivé. On peut utiliser ce petit script (volontairement *bloquant*) dans le <head> du document html (avant le chargement des css) :
`<script>(function(){document.getElementsByTagName("html")[0].classList.add("js-ok");})();</script>` et faire en sorte d'utiliser cette nouvelle classe `.js-ok` dans les CSS pour n'appliquer `display:none` que lorsque JavaScript est activé. Donc peut-être remplacer `.collapse { display: none; }` par quelque-chose comme `.js-ok .collapse { display: none; }`.

Remarques :
- l'élément `<div id="xwikimainmenu">` gagnerait à être modifié en `<nav id="xwikimainmenu">`(voir [Élément <nav>](https://developer.mozilla.org/fr/docs/Web/HTML/Element/nav))
- l'intitulé du bouton pourrait aussi bénéficier à certaines personnes ne présentant pas de handicap visuel. Je pense aux personnes peu familières avec les codes du numériques pour qui 3 lignes horizontales ne signifient pas forcément "menu". Il n'est pas rare de trouver un label "Menu" à côté du traditionnel _burger_  (visible, par exemple, sur ce site en mode mobile : [Every Layout](https://every-layout.dev/))

**Comment by lucaa** [comment]
> Le menu est-il réellement nécessaire ?
> Vu qu'il n'y a que 2 entrées dans ce menu, il est tout simplement possible de supprimer le bouton de menu, c'est surement la meilleure chose à faire en terme de simplicité, de maintenance, d'écoconception, de design...

> Voir ce site en exemple : Design Accessible ;
> Une ressource intéressante au sujet des menus, de leur bouton, et des tables de matières : Menus & Menu Buttons.


Effectivement, mais 
nous essayons de mettre en place un header dsfr, pour lequel , si je comprends correctement, la recommandation (obligation?) est de mettre en place ce burger pour les "liens rapides":  https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222789846/En-t+te+-+Header#Menu-burger . Les exemples du répertoire exemples du dsfr ont, la plupart, 3 liens (si je me rappelle correctement) et sont cachés derrière un burger sur mobile...

Peut-on aller "contre" le dsfr? @ugodtn @yaaax

**Comment by lucaa** [comment]
> l'élément <div id="xwikimainmenu"> gagnerait à être modifié en <nav id="xwikimainmenu">(voir Élément )

Il s'agit en fait du déplacement de markup, il y a déjà un nav mais pas sur le bon élément , le ticket est #958 . _sauf_ si on peut les imbriquer, mais je doute fort que ça soit le cas...

**Comment by lucaa** [comment]
> l'intitulé du bouton pourrait aussi bénéficier à certaines personnes ne présentant pas de handicap visuel. Je pense aux personnes peu familières avec les codes du numériques pour qui 3 lignes horizontales ne signifient pas forcément "menu". Il n'est pas rare de trouver un label "Menu" à côté du traditionnel burger (visible, par exemple, sur ce site en mode mobile : Every Layout)

Même remarque sur le dsfr que ci-dessus, l'objectif est de suivre les recommandations du dsfr même si j'admets qu'il est possible de faire mieux. Je n'ai pas vu cette recommandation dans le dsfr mais je n'ai pas vu l'interdiction non plus :) , sauf qu'il faudra trouver un design qui respecte le dsfr et fait place à l'étiquette "menu".

**Comment by lucaa** [comment]
> Si le JavaScript est désactivé, il faut dans ce cas garder le menu ouvert en permanence.

Sauf test incomplet de ma part, ce n'est pas le cas pour le burger du header dsfr (je teste tout ça en local à partir des fichiers "exemple" de la distribution dsfr, à la version 1.1.0).
Comme nous n'utilisons pas directement le dsfr, il est, bien évidemment, possible de faire autrement que le dsfr avec un coût potentiellement moindre qu'un correctif du dsfr. La question est si on veut investir pour faire mieux que le dsfr ou pas, étant donnée la conclusion pour une question similaire ici #1025 .

**Comment by AnthonyBrunelli** [comment]
à voir par @benoitdequick ...

**Comment by lucaa** [comment]
> @lucaa j'ai demandé des avis d'experts et on est presque bon :
> 
> * [ ]   visuellement, il faut remplacer l'icône burger par une croix (celle du DSFR tant qu'à faire) comme on s'était dit

C'est fait, mais pas avec l'icône DSFR mais avec l'icône font awesome disponible par défaut dans la plateforme. Je vais créer une tâche séparée pour la mise en place des icônes DSFR, à implémenter avec la mise en place plus générale du style DSFR dans #1051 - car il faudrait d'abord rendre les icônes DSFR disponibles dans la plateforme.
Le bouton reste le même, il n'y a que l'icône qui change.

> * [ ]   dans le markup, il faut juste modifier le texte associé au bouton pour qu'il passe de "Ouvrir le menu" à "Fermer le menu" lorsque le menu est ouvert, et inversement (il y a donc aussi une petite modification du texte lui-même)

C'est fait aussi, finalement implémenté avec 2 éléments ```<span``` qui sont cachés alternativement. Comme le javascript qui gère le fonctionnement de ce menu est le javascript standard de bootstrap, j'ai préféré ne pas intervenir sur le javascript mais juste sur le markup et la surcouche CSS.
Pour la même raison (intervention sur le javascript), j'ai préféré, pour l'instant, ne pas changer le comportement par défaut en absence de javascript, en attendant la réponse à la question ci-dessus par rapport au comportement du dsfr.

**Comment by lucaa** [comment]
Je ferme ce ticket maintenant, si la réponse au sujet du comportement sans javascript dira qu'il faudra changer le comportement courant je propose de créer une nouvelle tâche pour le traiter, histoire de pouvoir livrer la modification du bouton dans 4.9 sans attendre d'autres correctifs.

**Comment by AnthonyBrunelli** [comment]
Vu pour la croix (point 1), pas vu parce que pas compris pour l'autre (point 2) mais ok @lucaa pour le passage en prod.
