### ISSUE TITLE
Porteur de démarche : remplacer le burger par un un bouton déconnexion

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1036]
Le burger pour le profil porteur n'a pas d'autre intérêt que la déconnexion: le remplacer donc pas un bouton de déconnexion.

**Comment by lucaa** [comment]
J'ai ajouté un bouton de déconnexion lors de l'implémentation de #1038 (c'est le bouton "connexion" qui devient "déconnexion" après authentification) , mais je n'ai pas enlevé le burger.

Si je comprends bien, il faut enlever le burger pour les utilisateurs "porteurs". 
Au niveau des rôles, il est plus facile, finalement, d'enlever ce menu pour tous les autres rôles sauf les admins dinum, et cela a du sens aussi car la seule chose intéressante dans ce menu est le lien vers l'administration, qui est présent uniquement pour les admins dinum. Est-ce que ça te va comme condition d'affichage de ce burger, @AnthonyBrunelli  ?

**Comment by AnthonyBrunelli** [comment]
Oui, c'est l'idée, c'est le même cas de figure que pour les porteurs, on fait comme pour les porteurs!

**Comment by lucaa** [comment]
C'est fait, les burger qui ouvre le menu tiroir XWiki est désormais affiché uniquement aux administrateurs.

**Comment by AnthonyBrunelli** [comment]
Vu ok pour non connecté et admin (pas vu pour les deux autres profils mais pas d'enjeu majeur).
