### ISSUE TITLE
Modification des liens rapides dans les header et footer de l'Observatoire

### ISSUE THREAD

**Issue by ugodtn** [DISIC/wikidemarches#1038]
Dans la maquette de revue des header et footer de l'Observatoire, il était prévu de modifier les liens rapides.

-  Au niveau du header, renommer le deux liens existants + ajouter un lien `Connexion`
-  Au niveau du footer : retirer le lien `Accès administration`

Cf. la maquette [ici](https://www.sketch.com/s/1b3497c0-5207-427a-b01c-d2cef8efabce/a/9PKRPM7).

**Comment by lucaa** [comment]
> renommer le deux liens existants 

@ugodtn : C'est à dire que le lien qui s’appelle aujourd'hui "À propos" et qui mène à la page https://observatoire.numerique.gouv.fr/Main/A%20propos doit s'appeller désormais "Le bouton Je donne mon avis" ?

**Comment by lucaa** [comment]
J'ai fait les 2 modifications de la description de ce ticket, avec le lien "Le bouton Je donne mon avis" pointant vers la page "a propos". 
À rouvrir s'il faut changer cela.

Aussi, j'ai essayé de mettre en place les séparateurs des menus (comme dans dsfr et comme sur la maquette), et cela demande un peu plus d'effort - le markup n'étant pas le même que sur dsfr, la mise en place de ces séparateurs est un peu plus élaborée. À créer un nouveau ticket pour les séparateurs, s'ils sont nécessaires.

**Comment by AnthonyBrunelli** [comment]
@AnthonyBrunelli le lien "Le bouton je donne mon avis" doit diriger vers https://observatoire.numerique.gouv.fr/Aide/Donner%20son%20avis

**Comment by lucaa** [comment]
@AnthonyBrunelli le lien a été mis à jour.

Notez que, suite  à ce changement, le seul lien vers la page "à propos" ( https://observatoire.numerique.gouv.fr/Main/A%20propos ) est dans le plan du site. Si ces explications sont importantes, il faut peut-être prévoir quelque chose dans le footer, peut-être?
Si c'est le cas, il faut ouvrir une nouvelle tâche pour l'ajouter.

**Comment by AnthonyBrunelli** [comment]
Ok vu pour la redirection, parfait merci! Pour la page "A propos", merci de l'alerte, c'est noté - si besoin, je referai un ticket.
