### ISSUE TITLE
Page création de profil: indiquer que le nom d'utilisateur sera utilisé pour la connexion.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1039]

**Comment by ClemDee** [comment]
@AnthonyBrunelli et @ugodtn : pouvez-vous décrire plus en détail le design attendu, ainsi que le texte d'affiché à l'utilisateur ?

Pour le moment, je suis parti sur une utilisation de tooltip qui affiche l'indication au survol de la souris, mais je peux modifier ça très facilement suivant vos retours : 

![Screenshot from 2021-09-24 12-25-18](https://user-images.githubusercontent.com/45625842/134660380-62ea73c5-175a-4ae5-b4a4-8cf663c183d3.png)

**Comment by lucaa** [comment]
@ClemDee : les tooltips  ne sont pas du tout super pour l'accessibilité, en general (les tooltips hover ne sont pas affichables sur les dispositifs mobiles car il n'y a pas de hover et il faudra vérifier le comportement du lecteur d'écran pour le popover bootstrap) donc ma préconisation est que cette solution ne passera pas - sauf si accessibilité est vérifiée et assurée.
Aussi, l'utilisation des ```<a>``` devrait être réservée aux vrais liens (cet article décrit en quelque sorte le problème https://a11y-solutions.stevenwoodson.com/solutions/navigation/link-anti-patterns/ ).

Je propose de reverter la solution courante.

**Comment by ClemDee** [comment]
Plutôt que de reverter la solution j'ai préférer la transformer, car c'était très simple à réaliser et ça permet de garder la logique et clés de traductions déjà mises en place.

Voici la nouvelle proposition d'affichage beaucoup plus accessible, en attente de retours : 

![image](https://user-images.githubusercontent.com/45625842/135285934-46883374-0d0b-45d1-b2c4-277f51fbf39c.png)

**Comment by AnthonyBrunelli** [comment]
Pour la phrase, plutôt:
"Votre nom d'utilisateur sera demandé pour vous connecter"

**Comment by ClemDee** [comment]
Le texte de description additionnel du nom d'utilisateur a été implémenté comme suit :

![image](https://user-images.githubusercontent.com/45625842/136036708-867a3bd7-ee5c-4ae0-9537-20a7333602c9.png)

**Comment by AnthonyBrunelli** [comment]
Ok c'est bon.
