### ISSUE TITLE
BUG JDMA Attestation vaccination COVID 19 (3000), les votes ne remontaient plus (ou ne sont plus accessibles).

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1042]

**Comment by AnthonyBrunelli** [comment]
![image](https://user-images.githubusercontent.com/35567048/133981458-cdea2d12-5806-4fff-bcce-639aac464a21.png)

**Comment by lucaa** [comment]
Les votes remontent correctement dans le tableau, mais la durée du chargement est très importante, à cause du volume: approx. 125 000 avis. Le temps de chargement que j'ai observé est d'approximatif 4-5 minutes.

L'erreur  dans la boîte de dialogue rouge n'est pas lié au chargement des avis et est une erreur passagère lié à la charge du serveur lors du premier affichage de la synthèse des avis de cette démarche, mais comme il y a un cache pour cet affichage pour des raisons de performance, l'erreur a persisté jusqu'à l'invalidation de ce cache (ce matin). Ainsi, aujourd'hui l'erreur n'est plus affichée et la synthèse d'avis est correctement calculée.

**Comment by jrenauxdinum** [comment]
Génial, effectivement cela fonctionne désormais. Merci Anca !

**Comment by AnthonyBrunelli** [comment]
Je ferme et je classe.
