### ISSUE TITLE
Problème lors de l'actualisation de la page sur le formulaire JDMA.

### ISSUE THREAD

**Issue by ugodtn** [DISIC/wikidemarches#1044]
Lorsque je me trouve sur la deuxième page du formulaire JDMA, si j'actualise la page, je me retrouve sur ce qui semble être une version alternative du formulaire, avec des questions différentes (cf. image), et plus qu'une seule étape. Je ne sais pas si c'est un comportement propre à la page de test, mais ce n'est en tout cas pas un comportement souhaitable en production.

<img width="663" alt="Capture d’écran 2021-09-29 à 17 47 56" src="https://user-images.githubusercontent.com/34340568/135304338-35b73b84-bde4-46cf-be70-c5d0065f26ea.png">

**Comment by lucaa** [comment]
Ce n'est pas spécifique au formulaire de test, c'est un problème du formulaire d'avis, déjà décrit dans #772 .
Je ferme cette tache comme doublon et je déplace #772 dans la colonne "blocker".

**Comment by lucaa** [comment]
> et plus qu'une seule étape

juste une note, toutes les étapes sont bien là si la réponse à la question "comment avez-vous fait cette démarche" est "en ligne, jusqu'au bout". 

Pour explication, ce formulaire "alternatif" est un reste fonctionnel du temps ou le formulaire d'avis était disponible à tout moment à partir du site de l'observatoire, pas uniquement par un lien à la fin d'une démarche administrative. Cette fonctionnalité a été supprimée au printemps 2019.

**Comment by lucaa** [comment]
Note: les conséquences de ce bug ont changé avec l'implém de #1063 et #1114, voir https://github.com/DISIC/observatoire/issues/772#issuecomment-1105620898 .
