### ISSUE TITLE
Élimination du h2 du footer du site

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1047]
Aujourd'hui le footer du site contient un titre h2 (caché).

Suite aux changements de structure des titres pour le formulaire d'avis ( #1045), le besoin d'enlever ce h2 a été evoqué.
Dans le passé il y a déjà eu des discussions autour de ce markup.

Cette tâche est ici pour tracer les investigations et décisions liées à cette demande.

**Comment by AnthonyBrunelli** [comment]
Sauf si cela pose un problème particulier ou si le coût en temps est disproportionné, on confirme.

**Comment by lucaa** [comment]
> On enlève le h2 du footer :)

pour la traçabilité de la décision, la justification est que nous sommes (pour l'instant) dans le cas d'un footer simple dsfr, qui n'a pas de heading dans dsfr et donc on suit cette direction sans forcement essayer de clarifier les autres question sur les footers dsfr, car elles n'impactent pas le footer de l'observatoire.

**Comment by lucaa** [comment]
@ugodtn je t'ai dit vendredi que service-public.fr n'avait pas de heading dans le footer. 
Cette affirmation nécessite une explication supplémentaire: _au moment de l'implémentation de #786 service-public.fr n'avait pas de heading dans le footer_. Aujourd'hui il semble y avoir un heading dans le footer de service public (footer qui est aujourd'hui un footer dsfr aussi et ne l'était pas au moment de l'implémentation de #786), et ce heading est un heading de niveau 2 (sans parent autre que le titre de la page), pour les "partenaires" (ceux qui sont marqués comme un heading 4 dans le dsfr).

**Comment by lucaa** [comment]
La suppression est faite.

**Comment by AnthonyBrunelli** [comment]
Vu ok!
