### ISSUE TITLE
Clarification marges des legendes du formulaire d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1059]
Dans le sketch du formulaire d'avis ici: https://www.sketch.com/s/1b3497c0-5207-427a-b01c-d2cef8efabce/a/jgqEDkG il semble y avoir quelques inconsistances des marges des questions du formulaire entre elles mais aussi par rapport au dsfr.

Cette tâche est pour valider ces valeurs et surtout la règle à utiliser.

Il y a 2 cas de telles étiquettes:
1. avec une aide (hint) - pour la première question (de la premiere page), pour les questions des choix "Autre" des 2 listes de checkboxes et pour le champs "Souhaitez-vous nous en dire davantage"
2. sans aide pour les autres

Pour cas 1, les distances sont variables entre la première page et les distances de la deuxième page:
![Selection_235](https://user-images.githubusercontent.com/657716/139069449-61357277-653e-46e0-942e-948a1b86ad31.png)
![Selection_236](https://user-images.githubusercontent.com/657716/139069487-d2d191bd-68be-4743-bac4-383e89dece37.png)

L'implémentation de ces questions a été faite avec des legendes dsfr et des labels de legendes, car le style correspond. Dans DSFR, toutes les legendes ont une marge de 1rem en bas (en dessous de leur aide, s'il y en a une), qui correspond donc à celle de la première page. Dans dsfr, la distance entre l'aide d'une legende et le texte de la legende est de 8 = 0.5rem, donc pour cette partie là tout va bien.

**Ainsi, la question pour le cas 1 est si on doit faire des marges spécifiques pour les legendes avec aide de la deuxième page du formulaire ou on garde les règles d'espacement du dsfr qui seront en plus les mêmes partout.**

Pour le cas 2, la distance entre les questions et les réponses possibles et différente entre les questions avec smiley et les questions avec cases à cocher:

![Selection_237](https://user-images.githubusercontent.com/657716/139115803-50878fcd-89bc-4aff-9893-cd01ee1b18db.png)

**Pour le cas 2, la question est par rapport à la marge standard dsfr de 16 (1rem), si on doit la personnaliser ou si elle reste à 24 partout?**

**Comment by lucaa** [comment]
> Dans le premier cas, on passe les deux marges à 0.5rem (comme pour le DSFR)

Pour le premier cas, #1060 a été implémenté pour les éléments de la deuxième page, donc nous avons désormais les marges suivantes:
* pour la question de la première page: même marges que l'image ci-dessus 0.5rem entre l'aide et l'étiquette, 1rem entre l'aide et les smileys. Ceci sont les valeurs du DSFR et sont conformes à la maquette sur sketch (Page 2, car Page 1 n'a pas tout à fait les mêmes marges :) ).
* pour les 3 questions de la deuxième page (suite à #1060): 0.25rem entre l'aide et l'étiquette, 0.5rem entre l'aide et l'input / textarea. Ceci sont les valeurs standard pour les labels DSFR, mais pas exactement les mêmes marges que sur la maquette sketch. Sur la maquette sketch la distance entre l'aide et l'étiquette est de 0.5rem. Cf. discussion avec @ugodtn vendredi, on garde les distances DSFR.

**Comment by lucaa** [comment]
> Dans le deuxième cas, je n'ai pas bien compris si pour le DSFR la marge normale était de 1rem ou 1.5rem, mais il faut garder 1.5rem et uniformiser (donc tous à 1.5rem)

Cf. discussion à l'oral avec @ugodtn vendredi, pour ce cas on ajuste uniquement les marges des légendes _sans aide_ (c.a.d de la deuxième page du formulaire) à 1.5rem.

**Comment by lucaa** [comment]
Les marges pour le deuxième cas ont été également implémentés.
Résultats finaux.

1/ première page
![image](https://user-images.githubusercontent.com/657716/139657713-f0ae542f-0800-46cc-9d72-27250eb97cd9.png)

2/ deuxième page

![image](https://user-images.githubusercontent.com/657716/139657782-8d619ad9-cc1d-47d0-b49a-9c291370a370.png)

**Comment by AnthonyBrunelli** [comment]
Vu avec Ugo, ok
