### ISSUE TITLE
No option is preselected for the type of demarche when entering the feedback form

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#106]
e.g. the demarche no 12 : "Entreprise de travail temporaire d'insertion (ETTI) -  fiche salarie".

There should be at least one option pre-selected for "Comment avez-vous fait cette démarche ?" when entering the form.

**Comment by slauriere** [comment]
The default value of the mode field was not properly initialized. It has been fixed in 1e046082efe015a6fc5f052ceac0e462b2dff978.
