### ISSUE TITLE
Labels manquants sur le formulaire d'avis pour les champs de type texte

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#1060]
Lors de l'implémentation de #1015 , pour unifier le design des éléments du formulaire, le markup pour le texte libre ("Souhaitez-vous nous en dire davantage") ainsi que pour les 2 champs "autre" des  questions "Avez-vous rencontré des difficultés?" et "De quelle aide avez-vous eu besoin ?" a été changé et des elements ```<fieldset>``` ont été mis en place, avec les etiquettes dans des champs de type ```<legend>```.
En plus de la manque de semantique de l'element fieldset (car aucune liste de champs à réunir), le problème est que les elements de formulaire sont maintenant restés sans des ```<label>```s correspondants.

À ma connaissance ceci est un problème d'accessibilité.

**Comment by lucaa** [comment]
Le même coup homogénéisation du markup avait déjà été essayé et un ticket similaire à celui-ci avait déjà été corrigé dans #259 .

**Comment by lucaa** [comment]
Les légendes utilisées pour le champ verbatim ainsi que pour les 2 champs "autre" ont été remplacés avec des labels.
En plus du style de labels, un texte lg (dsfr) a été ajouté aux 3, pour présenter les questions à la même taille que les autres questions, qui sont des légendes. Une surcouche CSS a été ajoutée pour rendre les labels compatibles avec le texte lg.

**Comment by AnthonyBrunelli** [comment]
Vu avec Ugo, c'est bon.
