### ISSUE TITLE
Modifications sur l'étape 3 du formulaire JDMA (étape de validation)

### ISSUE THREAD

**Issue by ugodtn** [DISIC/wikidemarches#1065]
Ajouter un paragraphe sur la page 3 (étape de validation) du formulaire JDMA. Cf. l'image associée, il s'agit du paragraphe intitulé "Vous souhaitez aller plus loin ?".

Voici le lien vers la maquette : https://www.sketch.com/s/1b3497c0-5207-427a-b01c-d2cef8efabce/a/7y7ZVMw

Les textes sont les suivants :

> Vous souhaitez aller plus loin ?
> Si vous avez des questions ou des difficultés concernant cette démarche, contactez directement le service concerné.
> Si vous souhaitez contribuer d'avantage, vous avez la possibilité de partager votre expérience publiquement.

Le lien, externe (bien l'indiquer dans la balise title), et le suivant : https://www.plus.transformation.gouv.fr/experience/step_1?source=jedonnemonavis

![Page10v2](https://user-images.githubusercontent.com/34340568/141997072-8dca89b4-5ed4-4358-a7a5-ffb79d81e4eb.png)

**Comment by ugodtn** [comment]
@lucaa c'est clairement à la dernière minute, mais est-ce que tu penses que cette modification peut passer avec la 4.9 ? Sinon, il faudrait la faire passer dans la foulée :). Merci !

**Comment by lucaa** [comment]
> Le lien, externe (bien l'indiquer dans la balise title),

@ugodtn tu peux me donner un exemple de ce que la balise title doit contenir exactement?

**Comment by lucaa** [comment]
> Vous souhaitez aller plus loin ?

@ugodtn ceci est un titre ou juste un texte bold?
D'après la maquette c'est juste du texte bold qui est plus est de taille 125% par rapport au reste...

**Comment by lucaa** [comment]
> > Vous souhaitez aller plus loin ?
> 
> @ugodtn ceci est un titre ou juste un texte bold? D'après la maquette c'est juste du texte bold qui est plus est de taille 125% par rapport au reste...

trouvé dans le dsfr, c'est un texte lg et bold.

**Comment by ugodtn** [comment]
@lucaa oui tout à fait, c'est bien un style DSFR, et ce n'est pas un titre.

**Comment by lucaa** [comment]
@ugodtn j'ai mis les modifications de cette tâche en staging, tu peux regarder la-dessus pour voir à quoi ça ressemble pour l'instant.
J'attends encore l'info sur le titre du lien (commentaire ci-dessus), s'il y en a une, et après je mets la 4.9 et en prod.

**Comment by ugodtn** [comment]
@lucaa pardon je n'avais pas vu pour le lien. Voici l'attribut qu'il faut mettre : 

`title="partager votre expérience publiquement - nouvelle fenêtre"`

**Comment by ugodtn** [comment]
@lucaa Ah et donc il faut aussi ajouter un `target="_blank"` pour ouvrir dans une nouvelle fenêtre. Désolé tout ça n'était pas clair.

**Comment by lucaa** [comment]
> pour ouvrir dans une nouvelle fenêtre

@ugodtn juste pour confirmer, sans la décoration dsfr de liens à ouvrir dans une nouvelle fenêtre, correct?

Pour rappel:

dsfr avec la déco par défaut pour liens target blank:

![image](https://user-images.githubusercontent.com/657716/142180311-c7679ce6-2e69-4a28-a089-6fa3f1be39ee.png)

dsfr reset-link (sans la déco):

![image](https://user-images.githubusercontent.com/657716/142180391-d3d8b484-5569-4cd2-a4bb-ed289ac0dcd8.png)

**Comment by lucaa** [comment]
J'ai modifié le lien pour ouvrir dans une nouvelle fenetre et mis à jour le titre, sans la décoration dsfr pour les lien à ouvrir dans une nouvelle fenetre.

**Comment by AnthonyBrunelli** [comment]
@ugodtn ça me semble bon tout ça, je ferme. Si tu veux jeter un coup d'oeil, hésite pas...
