### ISSUE TITLE
Lien vers le design.numerique.gouv.fr KO en pied de page

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1069]
Message reçu:
"L'URL du lien "design.numerique.gouv.fr" situé en pied de page du site https://observatoire.numerique.gouv.fr comporte une erreur :

<a target="_blank" title="design.numerique.gouv.fr (nouvelle fenêtre)" href="https://www.design.numerique.gouv.fr/')">design.numerique.gouv.fr</a>

Ce dernier ne pointe donc pas vers le site désigné."

Je ne sais pas ce que valent les indications techniques mais effectivement le lien ne fonctionne pas. Il devrait rediriger vers : https://design.numerique.gouv.fr/

Idéalement, corriger la prod directement, sauf si cela pose des problèmes/dangers.

**Comment by AnthonyBrunelli** [comment]
![image](https://user-images.githubusercontent.com/35567048/149916443-22ca176e-e145-46a9-bc07-a09ac7af8992.png)

**Comment by lucaa** [comment]
C'est fait, corrigé et mis en production.

**Comment by lucaa** [comment]
@AnthonyBrunelli je te laisse le déplacer dans la colonne "Done & tested"  après validation.

**Comment by AnthonyBrunelli** [comment]
Formidable! C'est tout bon, merci, je déplace :)
