### ISSUE TITLE
Formulaire JDMA - "charactères" au lieu de "caractères" x2

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#1070]
Au dessus des deux champs en saisie libre associés à "Autre", caractère est écrit avec un h qu'il ne devrait pas y avoir.

**Comment by lucaa** [comment]
C'est fait, ça sera en prod lors de la livraison de la 4.10 en production.

**Comment by lucaa** [comment]
Finalement, comme j'ai installé le correctif pour #1071 en production directement, j'ai installé celui-ci aussi.

**Comment by AnthonyBrunelli** [comment]
Contrôlé avec Joffrey, c'est bon!
