### ISSUE TITLE
Facet "Catégories de publics concernés" does not show up correctly

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#109]
It's printed on two lines with the separator line crossing the second line.
![facet](https://user-images.githubusercontent.com/1022195/41852317-04d6713e-788b-11e8-86a2-dbf5809515d2.png)

**Comment by lucaa** [comment]
This was fixed along with other search page improvements, by commit 45f76d8fcae3114bd5761adeac4ff7a4d68386e7 for #105.
