### ISSUE TITLE
Add validation checks to all the radio button properties

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#149]
Currently only the "score" property value gets validated (it has to an integer between 1 and 3). All radio buttons properties have to be validated as well.

**Comment by lucaa** [comment]
à vérifier si c'est toujours nécessaire .

**Comment by slauriere** [comment]
La validation porte à présent sur toutes les propriétés de type 'NumberClass' : leur valeur doit être soit vide, soit un entier compris entre 1 et 3 strictement.
