### ISSUE TITLE
Configure search for wikidemarches

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#15]
Todo:
* search should only search in demarches
* 3 facets configuration: Categories de public, Public, Evenements de vie
* Cleanup of the display of a search result - remove path, last modification & highlights

Do all these customizations in the standard seach of the wiki (not by creating a different search page).

For all pages that are part of the standard distribution, commit first the original version and then the customized version.

**Comment by lucaa** [comment]
In commit 6c10132134895b14215f726da8962050ff8cb810 for the UI setup I moved the global search to the middle of the homepage, so you can use that search for testing this feature.
There are UI glitches of the search suggest, as described by #30.

**Comment by slauriere** [comment]
Solved by commit 3350f19 associated by mistake to #33  (I forgot to commit the original version of the customized pages though, sorry)
