### ISSUE TITLE
Refactor wikidemarches and wikidemat to share the same wiki

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#169]
Currently, the demarches list and its tools are stored in one subwiki, while all public functionalities (user avis and demands of new demarches) are stored in a another subwiki. There is a publication process between the 2, periodically copying demarches data from the wikidemat to the wikidemarches for the users to vote on.

The idea is to have a single wiki and a single list of demarches, which will be built together by the users and the administrators.

Technically, we'd keep the same functionalities from the wikidemarches, we will just add an entry point for the authenticated users to access administration functions.

**Comment by lucaa** [comment]
Functional and UI merging are done, migration of data is handled. The only thing left is audit and re-setup of rights, between logged in users and guest.

**Comment by lucaa** [comment]
The rights table, as analyzed and drawn this afternoon, is here: 
![20180829_151913](https://user-images.githubusercontent.com/657716/44792792-fb114780-aba4-11e8-83c2-b44f2585ba6f.jpg)

**Comment by lucaa** [comment]
The rights, as drawn in the image attached to the issue, were implemented with a single difference:
* For the "Rest of the wiki" column, for Guest, instead of implementing no view right by default, the strategy used on the old wikidemarches was preserved, which gave view rights to guest by default on pages, in order to ensure access to code pages. 
Then, the elements brought on the wiki by the fusion with main wiki and wikidemat wiki were specifically handled from the pov of the guest rights: Demarches, Ministeres, Publics, ... etc (brought from the wikidemat wiki) and Users and groups (brought from the main wiki).

Also, an evaluation of the differences between main wiki and wikidemarches subwiki was done in order to evaluate what other standard XWiki distribution pages will be available to guest as a result of the fusion, and 2 extensions were identified to be uninstalled: Sandbox and Help (Center) Application.

**Comment by lucaa** [comment]
All elements of the migration are done, including script to migrate rights on the XWikiUser profiles. Only thing left are instructions about handling the URL schema, for which a separate task was created (#176).

Closing this issue now.

**Comment by slauriere** [comment]
Rights were updated as defined in #193:
* XWikiAllGroup has delete right on Demarches.WebHome and descendants
* only XWikiAdminGroup has update and delete rights on Demarches.Code and descendants

**Comment by slauriere** [comment]
Rights were updated as defined in #190: restridiction des droits de modification sur les espaces publics, ministères, directions, événements uniquement aux admins
