### ISSUE TITLE
Fix search to index event names and "categories de publics"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#174]
As a result of the merging of the 2 subwikis (#169), the search on the frontend can no longer rely on denormalisation of "eventments de vie" and "categories de publics" to ensure fulltext search in these fields for a demarche.

This task is about fixing this regression, in any possible way.

**Comment by slauriere** [comment]
See also comments in #34 regarding the implementation aspects.

**Comment by slauriere** [comment]
This was implemented by a custom SolrMetadaExtractor.
