### ISSUE TITLE
Testes de charge 

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#181]
In particular for the integration with the service-public.fr server.

**Comment by lucaa** [comment]
Expérimentation à prevoir sur 3 demarches : 
Charge mensuelle
- ~ 150 avis provenant de 47 000 démarches faites par an
- ~ 400 avis provenant de 102 000 démarches faites par an 
- ~ < 150 avis provenant de 15 000 démarches faites par an 

Conversion de ~2% entre les gens qui font la démarche et les gens qui remplissent l'avis.
Nous n'avons pas le nombre de personnes qui ouvrent le formulaire d'avis mais ne le remplissent pas.

Il y a une saisonnalité de ces démarches, mais on ne la connais pas.

**Comment by lucaa** [comment]
Si on considère la répartition des avis uniforme par mois (sans saisonnalité), ces 3 démarches donnent ~600 avis par mois, l'équivalent à ~20 démarches par jour. 
Aujourd'hui les statistiques montrent une frequence de ~7 avis par jour, cette charge va augmenter la charge de ~150%, ce qui devrait être ok.
Au lancement du projet nous avons même eu des jours plus chargés que cette charge estimée, donc il devrait pas y avoir de problème de charge.
Même en considérant une saisonnalité qui doublerait cette charge (~40 avis par jour au lieu de 20), cela reste dans des paramètres "normaux".

À long terme on risque d'avoir un problème de scalabilité de quelques fonctionnalités qui opèrent avec la base des avis, suite au chargement de cette base d'avis. 600 avis par mois = 7200 avis par an, à partir de quelques milliers d'entrées il faut surveiller les fonctionnalités qui opèrent avec les avis pour s'assurer qu'elles soient optimisées. Des solutions existent pour traiter la charge, nous allons devoir les mettre en place une fois la charge confirmée, si elle s'avère problématique.

**Comment by lucaa** [comment]
Un outil de monitoring est installé sur le serveur de production (java melody)  qui nous permettra de surveiller l'évolution de la charge une fois la connexion avec les services externes établie.
