### ISSUE TITLE
Afficher l'indicateur de satisfaction d'une demarche sous forme 0-100%

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#182]
Based on a battery-like display as suggested by XAL.

**Comment by lucaa** [comment]
I implemented a first version of the battery-like display in commit e32a4c75af906e2280ce6dceaff5f0982bece35f but it still needs some improvements. 
Thus, I did not activate it yet, still using the previous ball-based display.
Don't know if I should close this task or not, as the work is not done, but a testable prototype is available.

**Comment by lucaa** [comment]
En attente d'une decision sur la representation graphique de cette synthese, si issue #183 est implementé, il faut également changer l'affichage sur la démarche pour afficher un pourcentage.

**Comment by georges-bayard** [comment]
en complément il faut livrer en production la jauge développée par anca.

**Comment by lucaa** [comment]
L'icône avec lien vers l'explication et la page d'explication sont désormais ajoutées, la tache peut être fermée.
