### ISSUE TITLE
Dashboard implementation

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#183]
Le tableau de bord courant devrait être enrichi avec des informations complementaires, pour arriver à un tableau tel que proposé dans ce mockup, en bas de page:

https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/309952085_Dashboard-Demarches

Le reste des éléments de ce mockup ne font pas partie de cette tache.

**Comment by lucaa** [comment]
Dans le tableau en question il y a le nb d'avis et la moyenne calculée pour chaque démarche.
Ce calcul peut poser un problème de scalabilité, si on veut sortir le fichier .csv "live".

Options: 
* Créer un cache des avis pour une demarche (nb d'avis + moyenne)
* Faire une requête Sql élaborée avec du calcul en direct, à base de group by et fonction aggregate.

**Comment by slauriere** [comment]
En attendant de choisir l'option d'implémentation : 
- ajouter les liens
- ajouter direction
- dématérialisation

**Comment by lucaa** [comment]
Créer un cache des avis pour une demarche (nb d'avis + moyenne)
- Option retenue pour se laisser la liberté de changer l'affichage de cette moyenne dans le futur (comment on l'affiche et ou on l'affiche).

**Comment by lucaa** [comment]
Modifications par rapport à la maquette:
* la colonne dematérialisation doit afficher Oui / Non
* Sans lien vers la démarche, car on n'a rien a afficher sur la démarche

**Comment by lucaa** [comment]
Le tableau doit afficher toutes les demarches actives et les demandes utilisateurs.
Colonne supplementaire à aficher dans le tableau de bord: statut.

**Comment by lucaa** [comment]
Pour la moyenne des avis, il faut afficher un pourcentage, calculé comme :

 (moyenne  - 1) * 100 / 2

**Comment by slauriere** [comment]
Implémentation : 
- Listener Java qui écoute l'ajout et la modification d'avis et qui met à jour le nombre d'avis et la moyenne stockés sur la page de la démarche, mais sans créer d'entrée dans l'historique de la page. Création d'un JAR qui sera déployé directement dans WEB-INF/lib. Attention : cela doit être thread safe.
- À déterminer : stockage ou non des informations des avis dans la classe de la démarche ou dans une classe à côté : de préférence dans une classe séparée même si cela crée un join supplémentaire (mais avec clef indexée, donc ok).

**Comment by lucaa** [comment]
Une tache spécifique pour la création du cache a été créée dans #242. Cette issue reste pour l'implementation du tableau, une fois le cache créé.

**Comment by georges-bayard** [comment]
Info à ajouter dans le tableau de bord : nombre de votes pour la dématérialisation

**Comment by lucaa** [comment]
à noter que dans le contexte ou l'espace horizontal est limité, la colonne à enlever sera la colonne direction.

**Comment by lucaa** [comment]
La première version est implémentée, les améliorations suivantes peuvent être traitées par des taches séparées.
