### ISSUE TITLE
Restreindre les droits de modification sur les espaces publics, ministères, directions, événements uniquement aux admins

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#190]
NB: mettre à jour la spécification de gestion des dtoits telle que écrite dans #169.

**Comment by slauriere** [comment]
Les droits ont été implémentés comme indiqué.

**Comment by lucaa** [comment]
Les droits ont été donné aux admins sans être enlevés aux groupe "All", je rouvre pour corriger.

**Comment by slauriere** [comment]
Le droit d'édition attribué au groupe XWikiAllGroup a été révoqué pour les 4 espaces cibles. Une question @lucaa : j'ai remarqué lors de cette mise à jour que le fait d'attribuer via l'UI des droits à une page ayant des pages descendantes créeait systématiquement un objet "XWiki.XWikiPreferences" qui n'est en fait pas nécessaire ici, sais-tu si c'est un comportement / problème déjà identifié ?
