### ISSUE TITLE
Dans le suggest : ajouter un lien / bouton permettant d'ajouter une nouvelle démarche

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#194]
Questions: 
* on affiche tout le temps ou uniquement quand il n'y a pas de resultats?
* Nous affichons quoi comme etiquette?

**Comment by tetue** [comment]
Dans l’autocomplete, pas besoin d’un bouton : un simple lien suffit, qui renvoie à l’intégralité des résultats (toujours affiché sauf quand la liste exhaustive des résultats est inférieure ou égale au nombre d’items affichés dans le panneau d’autocomplete) :
https://octo.invisionapp.com/share/8XJEA1ZHWK4#/319716828_Search-Autocomplete

**Comment by slauriere** [comment]
Les améliorations suivantes ont été apportées (sur le site de développement) : 
- Utilisation de clefs de traduction
- Echappement XML des caractères dans le formulaire de soumission de nouvelle démarche
- Correction d'un bug qui déclenchait l'insertion de plusieurs boutons d'ajout
