### ISSUE TITLE
Create data model for the wikidemarches wiki

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#2]
Data model creation for the demarches in the wikidemarches public wiki, ready to receive demarches data.

**Comment by lucaa** [comment]
The simplest choice for the public website is to have the same model as the wikidemat, and to fill in only properties that make sense for the public tool.

**Comment by lucaa** [comment]
Already done: 
* added demarches model in the wikidemarches wiki, by separating demarches in an application and including it in both wikidemat and wikidemarches builds

Left to be done:
* copy the model for the metadata that is associated to a demarche (ministries, life events, etc), in the same way it was done for the demarches themselves

**Comment by lucaa** [comment]
We should also prepare installation instructions for creation and setup of the wikidemarches (as we did for wikidemat) as soon as this issue is done, which would instruct how to install this first batch of code (data model) on the wikidemarches.

**Comment by slauriere** [comment]
4 other applications were moved to the wikidemarches wiki:
- Directions
- Evenements
- Ministeres
- Publics

**Comment by slauriere** [comment]
Closing this issue and creating a new one for the wikidemarches setup instructions: #20
