### ISSUE TITLE
La migration 1.x->2.0 des avis remet la date de création des avis à la date de la migration

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#202]
Lors de la migration de la version 1.x a 2.0, telle que prévue aujourd'hui (#169), les dates de création de tous les Avis sont mises à la date de la migration.

Aujourd'hui, cette migration est faite par une copie de l'espace des Avis.

Solutions possibles:
* script de copie custom, pour préserver la date de création
* déplacement des pages (au lieu de copie), pour préserver la date de création - à tester si la date de création des pages dans XWiki est préservée lors d'un renommage.

**Comment by slauriere** [comment]
Le déplacement d'une page ne modifie pas la date de création. En revanche le déplacement d'une page unique modifie le champ parent. Faire le test suivant : déplacer une page avec toutes ses descendantes et regarder si le champ "parent" des descendantes est mis à jour ou non.

**Comment by slauriere** [comment]
Autre solution possible : exporter en XAR et réimporter dans le wiki de destination. Attention toutefois au bug d'export https://jira.xwiki.org/browse/XWIKI-15444. Il faut exporter via l'action "export" dans l'URL. Tester cela.

**Comment by slauriere** [comment]
Attention : il faut importer en cochant l'option "importer en tant

**Comment by slauriere** [comment]
L'export avec "history=true" permet bien d'importer avec conservation de l'historique.

**Comment by slauriere** [comment]
Les instructions de migration de la version 1.x vers la version 2.0 ont été mises à jour : https://github.com/DISIC/wikidemarches/wiki/Migration-instructions-from-1.x-to-2.0
