### ISSUE TITLE
Amélioration de la recherche par URL

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#204]
Je recherche la démarche « admission dans l'enseignement supérieur ». quand je saisis dans le moteur de recherche https://www.parcoursup.fr le moteur de recherche me renvoie plus de 1000 résultats et la démarche admission dans l’enseignement supérieur n’arrive qu’en 3ème position.

**Comment by lucaa** [comment]
à traiter avec #291 .

**Comment by slauriere** [comment]
Le champ URL de la démarche a été boosté dans la configuration de la recherche aussi bien pour la page principale que pour les suggestions de recherche, cela permet de renforcer les URL qui correspondent entièrement à la requête par rapport à celles qui ne matchent que partiellement. @georges-bayard @JeanPerrier nous vous invitons à tester sur le site de développement et à nous dire ce que vous en pensez. Je ferme le ticket pour l'instant, n'hésitez pas à le rouvrir si besoin.
