### ISSUE TITLE
Ajout des champs "modalité" et "organisme" dans le formulaire de soumission de nouvelle démarche

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#205]
Formulaire d’ajout d’une démarche : cf modèle de UX.

Règles de gestion complémentaires :
- Si la valeur « en ligne jusqu’au bout » ou « en ligne pas jusqu’au bout » a été saisie,  la valeur téléprocédure est pré-remplie dans le formulaire démarche - TODO: que remplit-on si on choisit "autre"
- Ajout du champ « auprès de quel organisme vous avez fait votre démarche », qui doit pré-remplire le champ « organisme de traitement » de la démarche
https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/318678870_Ajout

**Comment by lucaa** [comment]
TODO: que remplit-on si on choisit "autre"
Reponse: on ne met rien

**Comment by slauriere** [comment]
Les champs ont été ajoutés. Lors de la soumission d'une nouvelle démarche, une page avis est à présent créée en plus de la page démarche. La question sur la modalité de réalisation de la démarche doit être supprimée du formulaire d'avis lorsque celui-ci s'affiche juste après la soumission d'une nouvelle démarche : #231.

**Comment by lucaa** [comment]
> Lors de la soumission d'une nouvelle démarche, une page avis est à présent créée en plus de la page démarche.

Je ne suis pas

**Comment by slauriere** [comment]
Décision : implémenter le stockage du champ "modalité" uniquement en mémoire jusqu'à soumission effective d'un avis.

**Comment by slauriere** [comment]
Ticket fermé. En suspens par ailleurs : #246

**Comment by georges-bayard** [comment]
dois je comprendre qu'on pourra demander la création d'une nouvelle démarche sans laisser d'avis sans vote ?
