### ISSUE TITLE
Mise à jour du message d'avertissement pour les démarches non validées

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#209]
https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/318688885

"Formulaire de vote sur une démarche non encore validée accessible par les autres utilisateurs :  transformer le message : cf copie d’écran Romy"

**Comment by slauriere** [comment]
Le message a été mis à jour ainsi que le formatage de la date : l'année a été ajoutée.

**Comment by lucaa** [comment]
À verifier s'il faut aussi changer le message en message d'information: l'implementation courante utilise un message d'avertissement mais sur l'écran de Romy c'est un "info".

**Comment by slauriere** [comment]
Réouverture, pour les points suivants : 
- bug d'affichage : le caractère ```'``` a été doublé dans le fichier de traduction pour affichage correct dans la box - vérifier s'il s'agit d'un bug ou d'un mésusage
- faire un cherrypick dans la branche master car la milestone est M3
- dans le doute, c'est une boîte d'information blutôt qu'une boîte d'avertissement qui a été retenue, conformément au mockup

**Comment by slauriere** [comment]
- La disparition des guillements simples semble être un bug, non encore identifié. Il a été référencé à cette adresse : https://jira.xwiki.org/browse/XWIKI-15589
- Le commit a été cherry-pické dans la branche master car la milestone de l'issue est M3: ee47a781ee8998257366950fc2fed88511258588

**Comment by lucaa** [comment]
Le fix me va, j'ai confirmé avec Romy qu'il faut mettre un message d'information, je ferme l'issue.
