### ISSUE TITLE
Sur la page démarches, la vue de recherche a disparu en mode connecté

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#210]
à clarifier

**Comment by lucaa** [comment]
Il s'agit du bouton de recherche disponible dans le menu de haut de page.

La conclusion c'est qu'on va remettre ce bouton pour les utilisateurs connectés, qui va pointer vers la recherche publique nosdemarches.

**Comment by lucaa** [comment]
Implementé tel que décrit dans le commentaire précédent.
