### ISSUE TITLE
Filtrage des démarches sur "active" et "demande utilisateur"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#211]
Page démarches : la vue est filtrée par défaut sur les démarches actives. ll faut par défaut que les utilisateurs ministère voient les démarches « actives » et celles au statut « demande utilisateur » car elles sont visibles des utilisateurs. Les démarches au statut « demande utilisateur » doivent apparaitre en premier dans la liste

NB: quid du pré-filtrage par direction, sachant qu'une démarche nouvellement soumise n'est rattachée à aucune direction.

**Comment by lucaa** [comment]
Après discussion avec Georges autour du besoin, la solution retenue est d'ajouter une nouvelle page, accessible de la page d'accueil (en bas), avec la liste des démarches en état "demande utilisateur", sans pre-filtrage.
Comme le titre de cet issue ne correspond pas, je vais créer une nouvelle issue qui correspond et fermer celle la avec "wontfix".

**Comment by lucaa** [comment]
Nouvelle issue ouverte dans #230.
