### ISSUE TITLE
Amélioration de l'agencement du menu "Plus d'actions"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#213]
gérer les espaces entre les élements de menu, qui à été cassé lors du changement de la taille de police.

**Comment by lucaa** [comment]
Le problème était du aux margins des separateurs des dropdowns ('dividers'), et impactait également les drop-downs du menu du haut de page.

**Comment by lucaa** [comment]
La correction a été aussi mergée dans la branche 2.0 et deployée sur prod.
