### ISSUE TITLE
Absence du bouton "Envoyer par mail"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#214]
"Connecté en tant que Gbayard je ne vois pas le bouton d’envoi du mail de la fonction « envoyer par mail » depuis le formulaire démarches"

**Comment by lucaa** [comment]
Le problème est lié à la visibilité du bouton "Envoyer" dans le dialogue d'envoi d'email, et non pas du bouton "Envoyer par email" dans le menu de page.

La cause est la taille de dialogue de partage par email par rapport à la taille de la fenêtre: si la fenetre du navigateur est trop petite (courte), le bas du dialogue de partage par mail n'est pas visible et, donc, le bouton "Envoyer" n'est pas accessible.
En plus, Georges avait testé avec un écran petit avec un zoom de 130%.

Conclusion: on ne le corrige pas, la probabilité que cette situation arrive est trop basse.
