### ISSUE TITLE
Mise à jour du formulaire d'ajout de nouvelle demarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#217]
Cf. https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/318678870

à changer:
* l'ordre des champs
* les etiquettes des champs

NB: l'ajout des 2 nouveaux champs sur la modalité et l'organisme est couvert par #205 , donc ne fait pas partie de cette tache.

**Comment by slauriere** [comment]
L'ordre des champs et les libellés ont été mis à jour. La position de l'astérisque obligatoire sera peut-être à revoir. Laissons cela à l'appréciation de l'UX et créons une nouvelle issue le cas échéant ?
