### ISSUE TITLE
Libellés des réponses dans le formulaire d'avis

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#219]
- Harmoniser l'usage ou non de majuscules dans les réponses aux questions.
- Choisir si on utilise "autre" ou "autrement" dans la question sur la modalité de réalisation d'une démarche.

**Comment by tetue** [comment]
Pour la première question du formulaire (sorry pour les variantes dans le proto Invision, qui correspondent à des états différents de maquettage) : minuscules + « autre (papier, guichet…) » 

![en-ligne-autre](https://user-images.githubusercontent.com/538106/45560670-0f607000-b846-11e8-9872-0df8638fb58f.png)

**Comment by tetue** [comment]
<img width="405" alt="capture d ecran 2018-10-02 a 11 35 53" src="https://user-images.githubusercontent.com/538106/46340996-64b6c280-c637-11e8-9c2c-2bdf861674b2.png">

Attention au label « autre (papier, guichet, …) » -> « autre (papier, guichet…) » (jamais d’espace avant le point de suspension).

**Comment by slauriere** [comment]
J'ai supprimé l'espace devant les points de suspension.
