### ISSUE TITLE
Add Excel export to the procedure list

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#22]
- also check if we can leave it into the wikidemarches wiki
- make sure the FR version of the livetable excel export macro displays well
- see if we allow exporting a single procedure

**Comment by lucaa** [comment]
Also, a new version of the livetable excel export macro should be released and used on the project.

**Comment by lucaa** [comment]
the livetable excel export needs to export all the columns of the demarches, not only the ones from livetable.

**Comment by lucaa** [comment]
Closing this issue now, as the following have been done:
* configured excel plugin properly (see installation instructions)
* Released livetable excel export version 2.0 and added it as dependency on the project (see installation instructions)
* In the generic application the excel button is not present, so the button is not available on the wikidemarches wiki

Left to be done:
* export of a single procedure , to be done as a separate issue
* verify how the button displays - to me it's acceptable the way it is now
