### ISSUE TITLE
Le lien vers les statistiques des Avis (disponible aux administrateurs en bas de page) a disparu

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#221]
Sur la page d'accueil des avis, il y avait un lien pointant vers Avis.Admin.Statistiques, affiché aux administrateurs IIRC. Ce lien n'est plus présent.

**Comment by slauriere** [comment]
Un bouton "Statistiques" a été ajouté à côté du bouton d'export Excel. Les classes CSS de ce dernier ont été légèrement modifiées pour que les deux boutons s'affichent de la même manière, et comme les boutons de la page d'accueil.

**Comment by lucaa** [comment]
@slauriere  cherrypick, stp, dans le master, l'issue est pour la M3.

**Comment by lucaa** [comment]
Aussi, j'aurais préféré qu'il revienne comme il était avant et non pas qu'on re-code la feature  (c'est le principe d'une regression), mais bon, ça marche aussi.

**Comment by slauriere** [comment]
J'ai cherry-pické le commit dans le master.
