### ISSUE TITLE
Ajout de nouveaux champs dans la deuxième étape du formulaire d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#222]
cf. https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/317832191_Questionnaire-Demarche

3 nouveaux champs à ajouter: 
* la possibilité de specifier une difficulté rencontré dans un champ libre
* un champ libre pour raconter son experience
* un champ pour remplir une addresse email pour être contacté pour plus de détails.

Aucun de ces champs n'est obligatoire.

**Comment by slauriere** [comment]
Champ "Autre difficulté" : bien que sa valeur puisse être stockée dans une StaticList, il est sans doute préférable de la stocker dans un champ dédié. Il est également préférable de stocker la valeur "autre" dans la StaticList.

**Comment by slauriere** [comment]
Les champs de la deuxième étape du formulaire ont été mis à jour conformément à la maquette. Une chose reste à faire : vérifier la conformité RGAA des champs libres associés à "autre difficulté" / "autre aide" (actuellement gérés comme des champs imbriqués), cf #249.

**Comment by slauriere** [comment]
- Modifier le custom displayer plutôt que du JavaScript pour les champs "autreAide" et "autreDifficulté".
- Voir si on garde un custom displayer générique ou pas.

**Comment by slauriere** [comment]
Gestion RGAA :
* Maquette de référence: [étape 2 du formulaire d'avis](https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/317832191_Questionnaire-Demarche)
* Structuration : chacun de ces champs doit être inclus dans le fieldset des listes d'options car il peut être considéré comme un item supplémentaire de la liste. 
* Lien accessibilité : [gestion de champs sans intitulé](https://www.accede-web.com/notices/html-css-javascript/7-formulaires/7-2-title-aria-label-champs-sans-intitule/)
* Deux possibilités pour la gestion des libellés : 
  * Utiliser l'attribut "aria-label" ou "title" dans le champ.
  * Utiliser l'attribut "label" comme pour les autres champs, mais en le faisant sortir de l'écran via une règle CSS comme celle-ci : position: absolute; left: -99999px;

Décision : préférence pour l'attribut "title" plutôt que pour un élément "label" avec une règle CSS dédiée.

**Comment by slauriere** [comment]
L'implémentation de la règle suivante a été effectuée : 
- Si « Aucune » est coché, décocher tous les autres champs.
- Si un des autres champs est coché, décocher « Aucune ».
