### ISSUE TITLE
Homogenisation d'affichage des page d'accueil et de recherche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#225]
cf. https://octo.invisionapp.com/share/8XJEA1ZHWK4#/318748151_Aucun-Resultat

**Comment by tetue** [comment]
https://octo.invisionapp.com/share/8XJEA1ZHWK4#/318748151_Aucun-Resultat

**Comment by tetue** [comment]
Pour éviter le changement de mise en page en cours de parcours, garder le même bandeau de recherche, constant et au même emplacement = à l’identique sur la home et les pages de recherche :
https://octo.invisionapp.com/share/8XJEA1ZHWK4#/299047765_Home
https://octo.invisionapp.com/share/8XJEA1ZHWK4#/319719115_Search-Result
https://octo.invisionapp.com/share/8XJEA1ZHWK4#/318748151_Aucun-Resultat

Exemple :
http://carte-blanche-cahors.fr/home

**Comment by lucaa** [comment]
à traiter avec #308.

**Comment by JeanPerrier** [comment]
et #328

**Comment by lucaa** [comment]
Suite aux modifications de la page d'accueil (#611 puis #658 ) et au changement d'acces à la recherche des démarche des M8/M9, cette issue n'a plus trop de sens.
