### ISSUE TITLE
Remarque XA : le champ description ne devrait pas être obligatoire si l’usager saisit une URL 

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#234]
le champ « description » ne devrait pas être obligatoire si l’usager saisit une URL (quand on met l'URL là de la démarche sur sp.fr, ça devrait dispenser de description)

**Comment by tetue** [comment]
Déjà pris en compte dans la maquette pour l'ité suivante, où ce champ — renommé « Quel est le but de cette démarche ? » n'est pas obligatoire ( https://octo.invisionapp.com/share/8XJEA1ZHWK4#/318678870_Ajout ).

**Comment by lucaa** [comment]
Effectivement, c'est dans la maquette mais on n'avait pas d'issue pour la modification à faire. On va utiliser cette issue.

**Comment by georges-bayard** [comment]
OK

**Comment by georges-bayard** [comment]
on ne rend obligatoire qu'un seul champ : le nom de la démarche

**Comment by slauriere** [comment]
Le caractère obligatoire du champ "but de la démarche" a été supprimé. Un ticket lié : masquage du champ "URL" lorsque la modalité "autre" a été sélectionnée : #262
