### ISSUE TITLE
demande XA : dans le tableau de bord ajouter le nombre de dématérialisations demandées

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#236]
j'appuie à fond cette demande

**Comment by lucaa** [comment]
à décider: comment on affiche ces informations? Un graphique avec les demarches dont la dématerialisation est plus demandée, un tableau avec les démarches qui ont des votes pour la dématerialisation?

**Comment by georges-bayard** [comment]
c'est un point dur pour Xavier qui veut "vendre" le tableau de bord au cabinet. C'est une donnée que nous devons afficher dans le tableau général que nous sommes en train de fabriquer dans l'ité 4. C'est une information supplémentaire à ajouter dans le tableau, Ce tableau répondra de manière synthétique à des questions simples : la démarche est elle dématérialisée ? si non y a t'il beaucoup de demandes de dématérialisation ? comment cette démarche est elle appréciée par les utilisateurs (indicateur de satisfaction) ?

**Comment by lucaa** [comment]
En fait, il s'agit d'afficher, pour chaque demarche, le comptage de nombre d'avis pour lesquels la case "J'aurais prefere faire cette demarche en ligne" a été coché.

**Comment by lucaa** [comment]
La colonne pour afficher le nombre de demandes de dématérialisation a été ajouté pour la tache #183 (Dashboard implementation).

**Comment by georges-bayard** [comment]
quand la valeur est à 0 demandes de dématérialisation afficher un tiret "-"

**Comment by slauriere** [comment]
>quand la valeur est à 0 demandes de dématérialisation afficher un tiret "-"

Oui, bien noté, nous venons de créer un ticket dédié pour cela : #266.

Stéphane
