### ISSUE TITLE
La recherche par nom de ministere ne marche pas en production

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#240]
La reindexation solr n'a pas été lancé en production suite à la dernière mise en prod avec les améliorations de recherche.

Il faut lancer la reindexation, avec une evaluation prealable de l'impact de cette reindexation sur les resultats de recherche (temps, qualité). à lancer la nuit, si l'impact est majeur.

**Comment by lucaa** [comment]
Je viens de  la re-indexation Solr en production.

**Comment by slauriere** [comment]
La recherche par nom de ministère ne fonctionne pas car les noms complets des ministères ne sont pas dénormalisés, donc pas indexés.

**Comment by georges-bayard** [comment]
je ne comprends pas ce point. Est corrigé ?

**Comment by slauriere** [comment]
Ce point n'est pas corrigé car il n'a jamais fonctionné (ce n'est pas une régression en fait, j'enlève le label "régression"), et sauf erreur de ma part il n'a pas fait l'objet d'une validation lors d'une itération. A priori il faudrait en rediscuter lors de la prochaine itération ?

SLA
