### ISSUE TITLE
Nouvelles demarches crées par les utilisateurs ne sont pas créées avec la bonne langue du document

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#241]
e.g. https://nosdemarches.gouv.fr/Demarches/1639 

Apparement, la langue du document est vide (empty). La langue devrait être 'fr', pour assurer le bon fonctionnement de la recherche Solr.

**Comment by slauriere** [comment]
Ce problème est un bug de xwiki-platform : le champ "defaultLanguage" d'un document devrait avoir une valeur attribuée automatiquement (par exemple celle définie au niveau du wiki, ou bien celle définie par les préférences utilisateur).

La ligne suivante a été ajoutée au script de création 'Demarches.Code.NewDemarche' (insérée après un appel à l'API non protégée pour qu'un clone du document soit effectué préalablement, ici après la ligne qui attribue une valeur au champ titre) :

```
#set ($discard = $demarche.getDocument().setDefaultLanguage('fr'))
```

Voir aussi : [XWiki-15159 Add API to set the default language in the Document class](https://jira.xwiki.org/browse/XWIKI-15159)

Je laisse cet ticket ouvert le temps de vérifier si ce bug est référencé sur jira.xwiki.org, et sinon de le référencer.

**Comment by lucaa** [comment]
> Je laisse cet ticket ouvert le temps de vérifier si ce bug est référencé sur jira.xwiki.org, et sinon de le référencer.

Si je me rappelle correctement, la dernière fois que j'ai investigué ce comportement, ce n'était pas un bug, mais un contrat de l'API de création de page. Le problème est plutôt qu'il n'y a pas vraiment d'API pour configurer la langue du document une fois le document créé, comme XWIKI-15159 dit. 
En tout cas, changer le comportement de l'API $xwiki.getDocument() pour y retourner un document avec une defaultLanguage configurée sera une modification de API ("API breakage") donc je doute que cela puisse être considéré comme un bug. Je pense que la solution c'est de corriger XWIKI-15159 et de documenter correctement l'API $xwiki.getDocument() pour expliquer qu'aucune langue ne soit pas mise en place.

> Ce problème est un bug de xwiki-platform : le champ "defaultLanguage" d'un document devrait avoir une valeur attribuée automatiquement 

Dans la lumière de ce que j'ai écrit au dessus, je considère cela comme une API différente de ce que quelqu'un pourrait attendre de cette API, mais pas forcement un bug.

**Comment by slauriere** [comment]
Merci pour ces éclaircissements. J'ai posté [une question sur le forum XWiki](https://forum.xwiki.org/t/default-value-of-the-defaultlanguage-field-for-a-page-that-is-created-programmatically/3617) pour poursuivre la discussion. Je clos ce bug.
