### ISSUE TITLE
Implementer le cache des statistiques des avis, stockés avec la demarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#242]
Pour implementer le dashboard (mais pas que), il faut créer un cache de la moyenne et nombre des avis, stocké sur une demarche et mis à jour à chaque fois que les avis changent.

See #183.

Description des taches a faire (copié de #183):

Implémentation :

- Listener Java qui écoute l'ajout et la modification d'avis et qui met à jour le nombre d'avis et la moyenne stockés sur la page de la démarche, mais sans créer d'entrée dans l'historique de la page. Création d'un JAR qui sera déployé directement dans WEB-INF/lib. Attention : cela doit être thread safe.
- À déterminer : stockage ou non des informations des avis dans la classe de la démarche ou dans une classe à côté : de préférence dans une classe séparée même si cela crée un join supplémentaire (mais avec clef indexée, donc ok).
- Il faut pouvoir déclencher le (re)calcul du cache avec une API / un bouton (e.g. pour le premier déploiement ou lorsqu'on constate un problème dans le calcul), en se donnant la possibilité de pouvoir faire cela aussi pour une démarche spécifique.
- Créer un composant (pour qu'il soit instantiable à partir un d'un Groovy) dédié au calcul des stats d'avis liés à une démarche.
- Il faut s'assurer que les démarches aient une classe Avis.Code.AvisStatsClass lors de l'initialisation / copie / création : soit un listener, soit là où les démarches sont créées (via le template et les scripts de de création).
- Écrire le script d'initialisation des objets AvisStats : calcul pour toutes les démarches via groupBy + fonction aggregate ou bien récupération de chaque démarche individuelle, puis job macro et script Groovy.

**Comment by lucaa** [comment]
pour #236, il faut également ajouter dans le cache le nombre de votes pour dématerialiser la demarche:
combien de personnes ont répondu oui a la question "aurait vu préféré faire cette démarche en ligne".

**Comment by slauriere** [comment]
Une première implémentation a été publiée dans la branche [avis-stats](/DISIC/wikidemarches/tree/avis-stats) sous la forme d'une extension. Elle implémente les fonctions suivantes:
- Listener mettant à jour les statistiques lors de l'ajout d'un avis, de façon synchronized, via un composant, sans nouvelle entrée dans l'historique.
- ScriptService permettant de déclencher le calcul des statistiques pour une démarche ou pour l'ensemble des démarches ayant reçu au moins un avis, et page d'administration permettant d'effectuer ces appels.

Plusieurs opérations restent à être effectuées, en particulier : 
- Listener déclenchant la création d'un objet AvisStatsClass lors de l'initialisation / la copie / la création d'une démarche.
- Gestion de la mise à jour d'un avis existant, de sa suppression, de sa réaffectation à une autre démarche, ou de son renommage.
- Gestion plus rigoureuse des exceptions.
- Vérifier que les opérations de mise à jour ne peuvent pas s'effectuer en parallèle.
- Prise en compte du nouveau champ lié à la question « Auriez-vous préféré faire cette démarche en ligne ? »

**Comment by slauriere** [comment]
Une deuxième version a été implémentée avec les améliorations suivantes : 
- Calcul des statistiques systématiquement par requête, jamais "manuellement"
- Renommage des classes (suppression du terme "Component")
- Exposition de seulement deux méthodes dans le composant : "computeAvisStats" pour une démarche ou n démarches
- Suppression d'un join inutile
- Gestion de l'affectation d'un avis à une autre démarche
- Gestion de la suppression d'un avis
- Ajout du champ 'votes' dans la classe AvisStats et calcul de champ lors de l'ajout d'un avis / lors de l'initialisation des statistiques

**Comment by slauriere** [comment]
Nouvelle version publiée avec les améliorations suivantes : 
- Mise à jour de la méthode "computeAvisStats" pour la prise en compte des démarches n'ayant pas encore reçu d'avis.
- Création d'un listener sur la création de nouvelle démarche : initialisation d'un objet AvisStats.

Il reste en particulier à : 
- Faire davantage de tests, peut-être écrire des tests automatiques.
- Vérifier la thread safety.
- Voir si l'on prend en compte le renommage d'un avis.
- Voir quelle moyenne on attribue à une démarche n'ayant pas reçu d'avis.
- Relire le code.
- Voir si le fait que les votes soient stockés sous forme de StaticList plutôt que sous forme d'entier / booléen ne risque pas de poser à un problème de performance lors du calcul du nombre total de votes positifs (actuellement une fonction d'aggrégation avec "case when" est utilisée, plutôt qu'une simple somme).
- Voir si la contrainte "score.value > 0" est absolument nécessaire dans les requêtes de calculs de statisques.

**Comment by lucaa** [comment]
> Vérifier la thread safety.
ça m'a l'air OK à la première vue, mais il faut étudier un peu plus en détail qu'est-ce qu'il peut se passer en terme d'interleaving de processus
> Voir si l'on prend en compte le renommage d'un avis.
Normalement c'est géré par le listener, qui gère delete et create, et de tt manière on ne peut pas faire bcp mieux car on n'a pas d’événement explicite de rename
> Voir quelle moyenne on attribue à une démarche n'ayant pas reçu d'avis.
On attribue 0, et on gérera à l'affichage.
> Voir si la contrainte "score.value > 0" est absolument nécessaire dans les requêtes de calculs de statisques.
Non, elle n'est pas nécessaire, mais elle ne pose pas de problème particulière aujourd'hui, donc on la laisse
> Voir si le fait que les votes soient stockés sous forme de StaticList plutôt que sous forme d'entier / booléen ne risque pas de poser à un problème de performance lors du calcul du nombre total de votes positifs (actuellement une fonction d'aggrégation avec "case when" est utilisée, plutôt qu'une simple somme).
Sur les votes il faut revoir le calcul du cache, de toute façon, pour vérifier si la valeur peut être null et voir qu'est-ce qu'il se passe avec la moyenne dans ce cas la.

**Comment by lucaa** [comment]
Une version fonctionelle du cache est désormais implémentée, je ferme la tache maintenant. Les améliorations, si nécessaires, peuvent être traitées dans des nouvelles taches.
