### ISSUE TITLE
Implémenter l'export .csv dynamique sur le tableau de bord

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#243]
à trouver le format désiré de ce fichier .csv .

**Comment by lucaa** [comment]
L'export doit prendre en compte les filtres du tableau, comme l'export excel le fait.

**Comment by slauriere** [comment]
Utiliser la librairie opencsv du BatchImport soit via Groovy parseGroovyFromPage, soit on écrit un ScriptService. cf page appelée par la macro Excel. Macro "addExportCsvFromLiveTable"

**Comment by lucaa** [comment]
Pour le format d'export, nous allons viser CSV, comma separated, UTF-8. 
Pour des quantités importantes de données, il est recommandé d'éviter de toujours encadrer les valeurs entre des double quotes, pour ne pas augmenter la taille du document.
Dans notre cas je ne pense pas que cela pose un probleme, au moins pour l'instant.

Je pense que le referentiel qui decrit comment publier ces données de manière conforme a data.gouv.fr est ici: http://references.modernisation.gouv.fr/sites/default/files/Referentiel_General_Interoperabilite_V2.pdf .

**Comment by lucaa** [comment]
Ajouter un lien explicatif vers une page d'explication + modalité d'utilisation du fichier .csv.

**Comment by slauriere** [comment]
La macro "addExcelExportToLivetable" a été modifiée pour supporter l'export au format CSV. Un bouton permettant l'export CSV dynamique a été ajouté au tableau de bord, ainsi qu'une page d'explication sur le format CSV.
