### ISSUE TITLE
Ajouter un méchanisme permettant de pre-remplir la modalité d'un avis, et ne pas poser la question

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#244]
Il s'agit de la question "Comment vous avez fait cette démarche?" .

L'idée est que pour des intégrateurs qui veulent intégrer le formulaire d'avis en fin de démarches en ligne, cette question n'a pas de sens, elle ne devrait pas apparaître mais la réponse enregistrée doit être "en ligne jusqu'au bout" ou configurable.

**Comment by georges-bayard** [comment]
uniquement dans le cas ou l'utilisateur est passé par la fin d'une démarche

**Comment by lucaa** [comment]
La valeur peut-être pre-rempli par un paramètre, nd_mode. Si le paramètre est reçu, la question n'est plus affiché et la valeur du paramètre, si valide, est stocké comme modalité de l'avis.
Les valeurs possibles sont:
* en-ligne-entièrement
* en-ligne-partiellement
* autrement

**Comment by georges-bayard** [comment]
@slauriere  : sur quelle url je peux tester ce fonctionnement ?

**Comment by slauriere** [comment]
Georges,

Tu peux tester ce fonctionnement depuis cette URL sur le site de pré-production : 

https://nosdemarches-staging.devxwiki.com/Demarches/1204?nd_source=service-public.fr&nd_mode=en-ligne-entièrement

Tu verras que, en principe (testé de notre côté) : 
- La question « Comment avez-vous effectué cette démarche » n'apparaît pas sur cette page, alors qu'elle est bien présente sur la page par défaut (i.e. sans paramètres) : https://nosdemarches-staging.devxwiki.com/Demarches/1204
- En mode authentifié, dans la page de la démarche, l'avis stocké a bien la valeur passée en paramètre (ici "en-ligne-entièrement"). D'autres valeurs peuvent être passées en paramètre, cf le commentaire d'Anca ci-dessus.

Stéphane
