### ISSUE TITLE
anomalie : on peut voter pour une démarche qui est au statut "nouvelle démarche"

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#245]
an

**Comment by georges-bayard** [comment]
j'ai cherché la démarche dans le référentiel via la vue de recherche, je l'ai trouvée et je suis entré dans le formulaire de vote sans difficulté. Il faudrait que la démarche soit inaccessible à la recherche

**Comment by slauriere** [comment]
Note technique : commencer par ajouter un filtre Solr qui exclut les démarches au statut "nouvelle démarche" des résultats. Les utilisateurs authentifiés auront un accès via le tableau des démarches.

**Comment by slauriere** [comment]
Les "nouvelles démarches" n'apparaissent plus dans les résultats de recherche (sur le serveur de développement). Par exemple, la démarche ayant le nom "Test demarche #238" qui est une "nouvelle démarche" n'apparaît plus ni dans les suggestions de recherche ni dans les résultats complets de recherche. Elle apparaît bien en revanche dans le tableau des démarches, avec le filtre "nouvelle démarche". NB : les nouvelles démarches restent accessibles aux utilisateurs non authentifiés s'ils connaissent leur URL : il n'y a pas de restriction d'accès à ces démarches actuellement, faut-il en prévoir une ?

**Comment by slauriere** [comment]
Un exemple de démarche ayant le statut « nouvelle démarche » sur le serveur de développement : http://wikidemarches.devxwiki.com/bin/Demarches/2025

**Comment by slauriere** [comment]
Pas de restriction d'accès pour l'instant -> fermeture de cette tâche.
