### ISSUE TITLE
Ajouter une troisième étape dans le formulaire d'avis, pour recueillir l'adresse email des répondants

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#247]
cf. https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/320588849 .

La valeur du champ 'email' ne doit être visible que des administrateurs dans un premier temps.

**Comment by slauriere** [comment]
Un champ "email" a été ajouté, ainsi qu'une troisième étape dans la gestion du formulaire. Ce travail a été l'occasion de faire apparaître plusieurs améliorations possibles dans la gestion de ce formulaire : #255. Je ferme le ticket après avoir testé la plupart des scénarios, mais vu l'importance des changements, davantage de tests sont nécessaires pour validation complète.
