### ISSUE TITLE
Conformité RGAA des champs libres "autre difficulté" et "autre aide" des avis

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#249]
* Maquette de référence: [étape 2 du formulaire d'avis](https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/317832191_Questionnaire-Demarche)
* Structuration : chacun de ces champs doit être inclus dans le fieldset des listes d'options car il peut être considéré comme un item supplémentaire de la liste. 
* Lien accessibilité : [gestion de champs sans intitulé](https://www.accede-web.com/notices/html-css-javascript/7-formulaires/7-2-title-aria-label-champs-sans-intitule/)
* Deux possibilités pour la gestion des libellés : 
  * Utiliser l'attribut "aria-label" ou "title" dans le champ.
  * Utiliser l'attribut "label" comme pour les autres champs, mais en le faisant sortir de l'écran via une règle CSS comme celle-ci : position: absolute; left: -99999px;

Décision : préférence pour l'attribut "title" plutôt que pour un élément "label" avec une règle CSS dédiée.

**Comment by slauriere** [comment]
Si plusieurs options sont possibles, de préférence ne pas utiliser "aria" (cf commentaires sur la maquette).

**Comment by slauriere** [comment]
Structure : un seul fieldset, labels "autre difficulté" et "autre aide" présents mais masqués.

**Comment by slauriere** [comment]
Les tâches liées à ce ticket ont été réincluses dans #222.

**Comment by georges-bayard** [comment]
@tetue , tu peux tester ce point RGAA ?
