### ISSUE TITLE
ajouter un texte sous le champ "souhaitez vous nous en dire davantage ?" du formulaire

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#250]
Ne pas inclure d’informations personnelles (identité, date de naissance, adresse, identifiant administratif, etc.)

**Comment by slauriere** [comment]
Le texte a été ajouté. Il reste à vérifier / corriger la conformité RGAA de ce champ (affichage RGAA d'indications sur champs, et suppression de la balise "fieldset" qui n'a pas de sens ici) : #259.
