### ISSUE TITLE
ETQ administrateur de nosdémarches je ne peux pas faire le lien entre le verbatim d'un champ de saisie libre et l'adresse mail laissée par l'usager

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#252]
nécessite à priori qu'on stocke les adresses de courriel laissées par les usagers dans un espace différent que le reste de l'avis

**Comment by lucaa** [comment]
Les emails doivent: 
* pouvoir être associée à une démarche
* s'ils peuvent être associées au reste de l'avis (les champs de saisie contraints), c'est mieux. à confirmer que c'est OK.

Les champs de saisie libre:
* doivent être associé à tout le reste de l'avis (notes, les autres champs de saisie libre, etc)

En ce qui concerne la correlation qui peut être faite par la date, question à poser au dep. juridique.

**Comment by lucaa** [comment]
à verifier l'impact de cette séparation pour vox-usagers.

**Comment by lucaa** [comment]
GBA: service-public.fr n'a pas besoin d'associer une adresse email avec l'avis.

**Comment by lucaa** [comment]
@georges-bayard à verifier jusuq'a quel point il faut empêcher des corrélations statistiques qui restent possibles.

**Comment by JeanPerrier** [comment]
Solution: Deux fichiers, un ficher avec les réponses, les commentaires et les dates avec horaires, un fichier avec les adresses mails et les dates seulement.

CF réponse de Maud Choquet :

Bonjour,

Il n’y a pas d’interdiction d’avoir un fichier avec l’adresse mail + commentaire, c’est juste que : a) il y a un principe de minimisation des données ; b) si on le fait, il faut le dire. Or, je crois que ce n’est pas trop l’idée.
Il n’y a donc pas de difficulté à conserver à conserver le mail + date.
Bien cordialement,
MC

**Comment by JeanPerrier** [comment]
Mettre en M7

**Comment by georges-bayard** [comment]
perso je ne comprends pas la proposition de Maud. A creuser

**Comment by JeanPerrier** [comment]
Solution: Deux fichiers, un ficher avec les réponses, les commentaires et les dates avec horaires, un fichier avec les adresses mails et les dates seulement. 

D'accord avec GBA et Maud Choquet. 

Mentionner dans les CGU et lors du recueil des adresses mails que les résultats du questionnaires et les adresses mails peuvent être transmis aux agents opérationnels en charge des démarches administratives.

**Comment by lucaa** [comment]
Cette tache n'est plus d'actualité, on ne collecte plus les emails des donneurs des avis, depuis #416.
