### ISSUE TITLE
Auditer l'affichage des champs des avis remplis par les utilisateurs non-identifiés

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#254]

**Comment by slauriere** [comment]
Un appel à "{{html}}$escapetool.html($value){{/html}}" a été ajouté pour échapper 1) la syntaxe wiki, 2) la syntaxe html, en suivant les indications données sur la page [Security](https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/Security) d'XWiki.org.

Cela semble ok, cf cet exemple : http://wikidemarches.devxwiki.com/Avis/2300

WDYT @lucaa ?

**Comment by lucaa** [comment]
> Qu'en penses-tu @lucaa ?

yep, does the job.
