### ISSUE TITLE
Améliorations diverses du formulaire de soumission d'avis

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#255]
Ce ticket référence plusieurs améliorations possibles du formulaire d'avis. Chaque item a vocation a être soit converti en ticket individuel, soit ignoré selon la décision prise. Positionné en M4 pour le moment, à voir.

- La gestion du formulaire utilise des attributs de session (notamment pour stocker l'étape courante, et l'identifiant d'avis courant). Il faut donc sans doute étudier ou prévenir le cas où un utilisateur remplit plusieurs formulaires à la fois ou soumet plusieurs nouvelles démarches à la fois. Le multi-avis en parallèle ne sera pas supporté en M4, à rediscuter ultérieurement éventuellement. Ticket dédié : #257
- Nouvelle démarche, remplie "autrement": propose-t-on à l'utilisateur de voter pour sa dématérialisation ou bien considère-t-on qu'il vote implicitement pour ? Autrement dit : référencer une démarche manquante sur NosDémarches signifie-t-il qu'on veut non seulement la référencer mais aussi voter pour sa dématérialisation, ou pas forcément ? (avec l'écueil que certains usagers se plaignent qu'il n'y ait plus que des démarches en ligne et rien d'autre). Ticket dédié :  #256
- Vérification de la validité de l'e-mail saisi. Pas de nécessiter de vérifier.
- Protection contre l'injection HTML dans les champs texte de l'avis (le display XWiki affiche du HTML, donc possibilité d'injecter du JavaScript). Voir ticket dédié #254
- Vérifier dangerosité de "updateObjectFromRequest", "addObjectFromRequest". La vérification a été effectuée : une validation est effectuée entre ces appels et la sauvegarde elle-même.
- Vérifier tous les libellés du formulaire (en particulier la casse des réponses : première lettre en majuscule ou non). Voir #226

**Comment by lucaa** [comment]
> Protection contre l'injection HTML dans les champs texte de l'avis (le display XWiki affiche du HTML, donc possibilité d'injecter du JavaScript).

Voir #254 .

> Message final : ajouter un line break dans le message localisé.
> Vérifier tous les libellés du formulaire (en particulier la casse des réponses : première lettre en majuscule ou non).

Pour ce genre d'éléments on devrait suivre la maquette à la lettre. Ces informations se trouvent dans la maquette?

**Comment by lucaa** [comment]
> Nouvelle démarche, remplie "autrement": propose-t-on à l'utilisateur de voter pour sa dématérialisation ou bien considère-t-on qu'il vote implicitement pour ? Autrement dit : référencer une démarche manquante sur NosDémarches signifie-t-il qu'on veut non seulement la référencer mais aussi voter pour sa dématérialisation, ou pas forcément ? (avec l'écueil que certains usagers se plaignent qu'il n'y ait plus que des démarches en ligne et rien d'autre).

Pour le fait que la question sur le vote doit être présente dans le formulaire d'avis suite à l'ajout d'une demarche manquante par un utilisateur, voir #256 , c'est un bug, ça doit être corrigé.
Pour le reste, il y a effectivement une discussion possible sur comment cette question est presentée aux utilisateurs qui ajoute des demarches manquantes. Il est peut-etre interessant de mettre la question en avant pour qu'ils retrouvent rapidement une modalité de demander la dematerialisation d'une demarche. Pour l'instant, ce parcours sera identique entre une demarche ajoutée par l'administration dans le référentiel et une démarche ajoutée par un utilisateur.

**Comment by georges-bayard** [comment]
je suis également pour que l'on considère que une personne qui demande l'ajout d'une démarche dans le référentiel puisse explicitement voter pour ou contre sa dématérialisation si il l'a faite au guichet. Il peut très bien avoir fait sa démarche de façon non dématérialisée et souhaiter continuer à la faire de cette manière il me semble.

**Comment by lucaa** [comment]
> Vérifier dangerosité de "updateObjectFromRequest", "addObjectFromRequest".

On les utilise encore? Je croyais qu'on avait déjà blindé ça avec de la vérification des valeurs reçues...

**Comment by slauriere** [comment]
> je suis également pour que l'on considère que une personne qui demande l'ajout d'une démarche dans le référentiel puisse explicitement voter pour ou contre sa dématérialisation si il l'a faite au guichet. Il peut très bien avoir fait sa démarche de façon non dématérialisée et souhaiter continuer à la faire de cette manière il me semble.

C'est à présent possible : le bug #256 a été corrigé (sur la plateforme de développement).

**Comment by slauriere** [comment]
> > Vérifier dangerosité de "updateObjectFromRequest", "addObjectFromRequest".
> 
> On les utilise encore? Je croyais qu'on avait déjà blindé ça avec de la vérification des valeurs reçues...

Ces appels sont utilisés oui. La vérification des valeurs reçues se fait entre ces appels et la sauvegarde elle-même, donc pas de problème.

**Comment by slauriere** [comment]
Tous les items de ce ticket ont été traités : soit directement, soit via la création d'un ticket dédié. Donc je clos.
