### ISSUE TITLE
tableau de bord : revoir la phrase d'introduction sur la fiabilisation du recensement

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#258]
Ancienne phrase : "Le recensement est en cours, il sera complété et fiabilisé dans les prochains mois par les administrations et grâce à vos retours."
Nouvelle phrase : "Le recensement est complété et fiabilisé en continu par les administrations et grâce à vos retours. Vous ne trouvez pas votre démarche ? [bouton "Ajouter une démarche manquante"]

**Comment by lucaa** [comment]
Le message a été changé, et la boite de message transformée en boite d'information plutot que boite d'avertissement.
Le lien vers la création a été mis comme un lien normal, pas un bouton, car le bouton est trop visible (l'emporte sur le reste du message et de la page). Si un bouton est nécessaire, créez une nouvelle tache  pour le transformer en bouton.
