### ISSUE TITLE
Conformité RGAA du champ "Nous en dire davantage"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#259]
Vérifier / corriger la conformité RGAA : affichage RGAA d'indications sur champs, et suppression de la balise "fieldset" qui n'a pas de sens ici.

**Comment by slauriere** [comment]
Utiliser la balise "label" à la place de "legend", et adapter les styles CSS pour uniformiser l'affichage de ce label là avec les autres "legend" (pas forcément les autres labels).

**Comment by slauriere** [comment]
Merci Romy pour tes indications, je les ai appliquées au formulaire, en principe c'est ok à présent (sur le site de développement pour le moment).

**Comment by tetue** [comment]
Vu (après coup), super !
