### ISSUE TITLE
ListDisplayer: prise en compte des listes à valeurs multiples

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#260]
Actuellement le custom displayer "Avis.Code.ListDisplayer" ne prend en compte que les listes mono-valuées. Il faut traiter le cas des listes multi-valuées, e.g. celles des champs "difficultés" et "aides".

**Comment by slauriere** [comment]
Les listes multi-valuées sont à présent traitées (en mode édition, le mode view ne posait pas de problème).

**Comment by georges-bayard** [comment]
Le fait que les multi évaluations soient toutes rassemblées dans un seul champ ne facilite pas le traitement sur Excel des données. Je laisse ouvert pour l'instant

**Comment by slauriere** [comment]
Bien reçu Georges, je te réponds par deux remarques :
- J'ai créé un ticket dédié à ce sujet car celui-ci concernait un problème d'affichage des formulaires, il n'était pas lié à l'export lui-même : #263.
- Pour rouvrir un ticket il faut cliquer sur le bouton "Reopen and comment" (tu as sans doute cliqué à la place sur le bouton "Comment" qui est à côté).

**Comment by slauriere** [comment]
Il est un peu regrettable que les notifications par e-mail de GitHub n'indiquent pas qui est l'auteur du commentaire...

Stéphane

**Comment by georges-bayard** [comment]
il faut que je fasse quelque chose pour que ca s'affiche ?

**Comment by slauriere** [comment]
> il faut que je fasse quelque chose pour que ca s'affiche ?

Non non je crois qu'on ne peut rien faire, c'est le mode de fonctionnement de GitHub lui-même !

Stéphane
