### ISSUE TITLE
 Tableau de bord : supprimer les colonnes "direction" et "statut"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#264]
Attention, "statut" doit rester mais être marqué "hidden" car il y a un filtre par la valeur de cette colonne.

**Comment by slauriere** [comment]
Les deux colonnes n'apparaissent plus, avec un "statut" mis en "hidden" pour préserver le filtre actif sur ce champ.

**Comment by georges-bayard** [comment]
@slauriere  : je ne vois pas la modif sur https://nosdemarches-staging.devxwiki.com/TableauDeBord/ je suppose que tu ne l'as pas encore poussée.
Par aileurs je suppose que je fait de juste masquer la colonne n'a pas d'impact sur l'export Excel qui ramène toujours bien les deux information ?

**Comment by slauriere** [comment]
Georges, J'ai publié à présent la modification sur le site de pré-prod. Cette suppresion de colonnes a actuellement un impact sur l'export Excel, mais nous allons le corriger, cf #268.
Stéphane
