### ISSUE TITLE
Tableau de bord : afficher le libellé long des ministères

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#265]
Privilégier le libellé long dans tous les affichages, même si dans d'autres contextes (e.g. lors de l'édition de démarche) un libellé court est sans doute préférable, car le but est que l'expérience soit avant tout la meilleure possible pour les visiteurs non connectés.

**Comment by slauriere** [comment]
Le custom displayer du champ "ministères" de la classe Demarche a été modifié pour que lorsque l'action est 'get', ce soit le nom complet qui soit affiché. En revanche cela reste le sigle lors d'une action 'view'.

**Comment by georges-bayard** [comment]
le second point de mon commentaire précédent est pris en charge dans une issue particulière. Sur la vue de recherche du champ ministère je vois un autre problème lié aux démarches rattachées à n ministères : quand je cherche un ministère et que je le sélectionne dans la vue de recherche, xwiki ne me ramène que les démarches associées au seul ministère recherché. Il ne me ramène pas les démarches qui sont rattachées à plusieurs ministères DONT celui pour lequel j'ai fait effectué la recherche

**Comment by georges-bayard** [comment]
Je n'arrive plus à reproduire ce comportement. Je maintiens l'issue à non validé sur le point de la recherche sur le sigle et non l'intitulé.

**Comment by lucaa** [comment]
J'ai changé la propriété ministères pour pouvoir chercher par le libellé.
J'ai également vu le cas ou une demarche a plusieurs ministères associés et la recherche par un seul de ces ministères la retrouve correctement (e.g. toutes les démarches avec le ministère "Secrétariat d'Etat chargé des personnes handicapées") - je vais partir du principe qu'il n'y a pas de bug.

J'ai également travaillé un peu l'affichage pour faire passer correctement le tableau dans la largeur de l'écran.
