### ISSUE TITLE
dans le formulaire des démarches le champ direction ne doit être obligatoire que si la démarche est au statut actif

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#269]
Le champ direction ne doit pas être obligatoire si la démarche est au statut inactif, demande utilisateur ou nouvelle démarche

**Comment by slauriere** [comment]
Le script de validation du formulaire de démarche a été mis à jour pour n'imposer de saisir une direction que si la démarche courante est active.

**Comment by georges-bayard** [comment]
ok GBA
