### ISSUE TITLE
formulaire démarche, champ ministère : impossible de sélectionner une valeur qu'on a saisi 

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#271]
exemple : je saisis "services du premier ministre" ; la valeur apparaît bien dans la recerche mais impossible de la sélectionner pour l'enregistrer en tant que valeur

**Comment by slauriere** [comment]
Note technique : le problème semble venir d'une incohérence entre les valeurs retournées par le serveur et les valeurs stockées en JavaScript, liée à ce morceau de code du JSX de DemarcheSheet, qui avait du sens lorsque la recherche se faisait sur les sigles des ministères, mais qui pose problème lorsque cette recherche se fait sur les noms complets des ministères :

```
        } else if (select.attr('data-propertyName')=="ministeres") {
          if (text.indexOf("Ministeres.") < 0)
            text = "Ministeres." + text;
          $('.suggest-propertyValues').clearLoadedSearches();
        }
```

La suppression de l'ajout systématique du préfixe "Ministeres." résout le problème d'édition, mais je ne suis pas encore sûr qu'il n'en introduit pas d'autres -> j'attends que l'on valide cela ensemble Anca @lucaa.

**Comment by slauriere** [comment]
La customization du comportement du widget "selectize" pour le champ "ministères" a été supprimée : elle n'a plus lieu d'être maintenant que la recherche se fait principalement sur les noms complets des ministères (la recherche par sigle fonctionne encore toutefois). Cela résout le problème de sélection d'une valeur qu'on a saisie.
