### ISSUE TITLE
Suivi de la demande d'ajout de demarche manquante

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#273]
L’usager qui fait une demande d’ajout d’une démarche doit être mis au courant des suites de sa démarche. Il faut regarder comment on communique avec l’utilisateur sur la prise en compte ou non de sa demande (rendre visibles les démarches nouvelles proposées par un utilisateur et inactivées à la suite de l’instruction interne de la demande ?)

**Comment by lucaa** [comment]
Une possibilité est d'ajouter une liste de l'ensemble des demandes des utilisateurs , et pas un suivi individuel. Ainsi, les utilisateurs peuvent se raporter à cette liste pour suivre l'avancement.

**Comment by JeanPerrier** [comment]
Réponse
-présent dans l'export csv
- on sait s il est Tjs en du ou actif avec le fond d'écran
