### ISSUE TITLE
Poser une question aux personnes qui declarent avoir fait sur papier une demarche dematerialisée

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#275]
Pour toutes les demarches pour lesquelles la dematerialisation est disponible, si un utilisateur repond avoir fait la demarche autrement (papier, guichet), ajouter une question supplementaire pour essayer de comprendre pourquoi.

**Comment by JeanPerrier** [comment]
Réponse Jean+GBA:

Ajouter : 
- la question "Souhaitez-vous nous dire pourquoi?"
- un champ de saisie libre

Cette question est à poser uniquement pour le cas ou, en plus, l'utilisateur répond **"oui"** à la question "auriez-vous préféré faire cette démarche en ligne" .

**Comment by slauriere** [comment]
Un champ dédié a été ajouté à la classe des avis. Ce champ ne s'affiche que quand l'utilisateur répond "oui" à la question "Auriez-vous préféré faire cette démarche en ligne ?" Lors de l'affichage de la valeur de ce champ, les caractères HTML sont échappés (sécurité).

**Comment by lucaa** [comment]
Question à afficher uniquement pour les demarches qui sont dematerialisées.

**Comment by JeanPerrier** [comment]
@georges-bayard Tu confirmes Georges?

**Comment by JeanPerrier** [comment]
En fait Anca, c'est pour toutes les démarches et pas uniquement les démarches qui sont dématérialisées. J'ai vu ça avec Georges.
