### ISSUE TITLE
Pour les démarches qui ne peuvent pas être faites autre que en ligne (demat obligatoire), ne pas donner la possibilité de voter pour la dématerialisation

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#279]
2 manières de le faire:
* on enleve la réponse "autre" pour la question "Comment avez-vous fait cette démarche ?"
* on enlève la question "Auriez-vous préféré faire cette démarche en ligne ?" dans le formulaire qui s'affiche quand l'utilisateur selectionne "autre"

à decider.

**Comment by lucaa** [comment]
GBA: on enlève la réponse "autre" pour la question "Comment avez-vous fait cette démarche ?"

**Comment by JeanPerrier** [comment]
Cette issue n'a plus de sens
