### ISSUE TITLE
Les ministères n’ont plus de droits en suppression sur les avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#283]

**Comment by slauriere** [comment]
Le droit de suppression des pages de l'espace "Avis" a été donné au groupe XWikiAllGroup (pas d'impact sur le sous-espace "Avis.Code", qui est réservé en modification au groupe XWikiAdminGroup).

**Comment by georges-bayard** [comment]
ok GBA

**Comment by georges-bayard** [comment]
ok GBA
