### ISSUE TITLE
La difference entre le bouton de deconnexion et le lien vers le profil utilisateur n'est pas evidente

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#284]
![image](https://user-images.githubusercontent.com/657716/46349913-b1a89200-c653-11e8-9053-f9d712de7ee0.png)

**Comment by georges-bayard** [comment]
@lucaa : vous avez décidé de prendre le point au titre de la R et D ou on cloture le point ?

**Comment by lucaa** [comment]
@georges-bayard : j'ai crée un ticket dans la plateforme XWiki, mais ce n'est pas encore planifié dans la roadmap.

Il est possible de travailler un affichage spécifique dans le cadre de #466 pour améliorer le parcours utilisateur dans le cadre de ce projet spécifique. 
On peut, donc, cloturer et discuter des améliorations spécifiques dans le cadre de la tache #466 .

**Comment by georges-bayard** [comment]
ok
