### ISSUE TITLE
à vérifier les CGUs sur les cookies

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#286]

**Comment by slauriere** [comment]
Les recommandations CNIL indiquent en effet en particulier que « Les traceurs suivants ne requièrent pas de consentement : les cookies " identifiants de session ", pour la durée d'une session, ou les cookies persistants limités à quelques heures dans certains cas. ». Sur NosDémarches, seul un cookie d'identifiant de session est déposé sur le poste utilisateur. La durée de session définie par XWiki auprès du serveur d'application Tomcat 7.0 est de 30 minutes. Donc aucun consentement n'est requis, juste une information.
