### ISSUE TITLE
votes multiples pour une seule session

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#288]
en tant qu'utilisateur, quand je suis sur la deuxième page ou la troisième page du formulaire d'avis, je peux revenir en arrière sur la première page du formulaire avec le bouton retour en arrière du navigateur. Cela m'autorise à revoter sur la première page. Résultat  : le système prend en compte plusieurs votes.
Intuitivement l'utilisateur pense qu'il a voté une seule fois et qu'il a la possibilité de revenir en arrière pour modifier son vote. En fait son vote peut être prise en compte n fois.
Solution identifiée : ne prendre en compte que le dernier vote effectué au cours de la session, ce qui règlera par contrecoup les votes multiples

**Comment by lucaa** [comment]
* à vérifier les votes 3800 et 3801 sur production, par exemple.

**Comment by lucaa** [comment]
Suite aux discussions, le retour en arrière à traiter (à autoriser) est entre la première étape du vote et la deuxième (et pas les suivantes).

**Comment by lucaa** [comment]
à faire: page d'administration pour identifier les votes provenant de la meme session.

**Comment by lucaa** [comment]
Avec l'aide de Ludovic, j'ai potentiellement trouvé une stratégie pour cette tache, ainsi:
* tant qu'un questionnaire n'a pas été amené jusqu'au bout de la troisième étape, tout renvoi de la première étape du formulaire d'avis pour la même démarche mettra à jour l'avis en cours au lieu de créer un nouvel avis. 
* Par contre, si toutes les étapes du formulaire ont été remplies (jusqu'à la troisième), un envoi de la première étape du formulaire créera un nouvel avis.

@slauriere Techniquement, l'idée est d'implementer cela à base de l'avis de l'ID stocké dans la session, ainsi:
* quand on reçoit une première étape du formulaire, on verifie si nous avons déjà un id d'avis sur la session, si cet avis existe et si la demarche de cet avis est la même que la démarche pour laquelle on reçoit la premiere etape du formulaire:
  * si c'est le cas, on met a jour l'avis existant au lieu de créer un nouveau
  * si c'est pas le cas, on crée un nouvel avis
* à la fin de la troisième étape du formulaire, quand reçoit la dernière etape du formulaire, on nettoie l'id de l'avis de la session.

**Comment by JeanPerrier** [comment]
(y)

**Comment by slauriere** [comment]
Les améliorations suivantes ont été apportées :
- Prise en compte seulement du dernier avis soumis tant que l'utilisateur n'a pas été au bout du formulaire de soumission d'avis.
- Ajout d'une page d'administration permettant d'identifier les avis d'une même session relatifs à une même démarche : page Avis.Admin.AvisSessionManager (cf exemple sur le serveur de développement).
- Écriture d'un [scénario de test](https://github.com/DISIC/wikidemarches/wiki/Sc%C3%A9narios-de-tests) correspondant au cas d'utilisation décrit dans ce ticket.

**Comment by JeanPerrier** [comment]
Très bien. Il faudra vérifier que cette solution empêchera les doublons de vote dont l'un a un référencement (service-public) et l'autre aucun.

**Comment by slauriere** [comment]
Dans la page d'administration des sessions : faire en sorte que le lien sur la session intègre également l'identifiant de la démarche.

**Comment by slauriere** [comment]
Ajout de l'identifiant de la démarche dans le lien de session sur la page d'administration des avis multiples.

**Comment by georges-bayard** [comment]
NOK : j'ai pu voter 3 fois pour une démarche dans la même session en revenant en arrière sur la première page du formulaire à partir de la première page. Numéros de vote générés : 2988 2989 2990

**Comment by slauriere** [comment]
Désolé, un bug a été introduit lors de la résolution de #257 peu après le traitement de ce ticket, et j'ai oublié de retester ce scénario. Le bug a été corrigé, je viens de faire plusieurs tests, peux-tu retester Georges de ton côté stp ?
