### ISSUE TITLE
Transférer le vote/avis d'une démarche à une autre

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#289]
Lorsqu'on sélectionne un avis "n" dans la liste des avis, et qu'on appuie sur l'onglet "modifier", deux problèmes se posent:
(1) il faudrait supprimer la possibilité donnée à un administrateur de modifier les réponses des usagers
(2) il faudrait par contre avec la possibilité de modifier l'attribution de l'avis en question à telle ou telle démarche. ex de la démarche n°60 à la démarche n°953.

**Comment by lucaa** [comment]
> il faudrait par contre avec la possibilité de modifier l'attribution de l'avis en question à telle ou telle démarche. ex de la démarche n°60 à la démarche n°953.

Il est possible de faire ceci, il suffit de choisir une nouvelle demarche dans le formulaire (en choisissant une nouvelle demarche).

**Comment by lucaa** [comment]
> (1) il faudrait supprimer la possibilité donnée à un administrateur de modifier les réponses des usagers

GBA: nous allons miser sur la responsabilité des intervenants de restreindre leurs modifications aux bons champs.
Les modifications étant tracées dans l'historique, nous allons pas traiter ce point maintenant.
