### ISSUE TITLE
Doublons dans les résultats de recherche demarches

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#290]
Comme vous pouvez le voir dans la capture d'écran ci-jointe, certaines démarches se trouvent en doublon sur la page de recherche alors même qu'elles ont le même numéro. 
Dans le cas en question, la demande "déclaration de succession" se trouve deux fois dans la page de recherche. Chacune des versions porte le même numéro 1639.

![succession](https://user-images.githubusercontent.com/44236635/47166600-df046980-d2fc-11e8-836f-9d09c9c612f5.PNG)

**Comment by JeanPerrier** [comment]
Bonjour, 

Je crois comprendre d’où vient l'anomalie. Lorsqu'on modifie le titre ou le nom d'une démarche, le site conserve le nouveau et l'ancien nom. 
ex: j'ai corrigé le nom de la démarche "inscription Pôle emploi" qui était renseigné comme suit "inscription polemploi". Si vous tapez dans la barre de recherche du site "pôlemploi", vous retrouvez dans le champ des résultats l'ancien nom de la démarche "Inscription Pôle emploi" qui était "inscription polemploi".

**Comment by slauriere** [comment]
Note technique : dans le script de vérification des démarches non indexées, ajouter le nombre de résultats même si différents de la démarche recherchée.

**Comment by slauriere** [comment]
Du fait de cette anomalie, nous avons d'une part créé un utilitaire permettant de détecter aussi bien les démarches qui ne seraient pas indexées que celles qui seraient retournées plusieurs fois par l'index, d'autre part réindexé l'ensemble du wiki. À la suite de cette réindexation, le problème des doublons ne se présente plus et l'utilitaire ne retourne aucune démarche problématique du point de vue de la recherche. L'utilitaire se trouve sur la page [Demarches/Admin/](https://nosdemarches.gouv.fr/Demarches/Admin/) et est réservé aux administrateurs. Nous prévoyons de le consulter régulièrement pour détecter d'éventuels problèmes, dans la mesure où nous n'avons pas pour le moment réussi à identifier un scénario clair permettant de reproduire l'anomalie.

**Comment by JeanPerrier** [comment]
![image](https://user-images.githubusercontent.com/44236635/49021785-b5f4b580-f193-11e8-899d-466b4193cd35.png)

Autre exemple de doublon. Je viens de modifier la démarche de demande d'acte de naissance

**Comment by JeanPerrier** [comment]
@slauriere

**Comment by slauriere** [comment]
Effectivement, a priori c'est dû au fait que je n'ai pas réindexé les démarches modifiées suite à la fermeture de #291 (mise à jour de la langue par défaut). Je rouvre le ticket pour vérifier cela et corriger.

**Comment by slauriere** [comment]
Je confirme mon commentaire précédent : le problème venait de ce qu'une vingtaine de démarches n'avaient pas été réindexées correctement suite à la mise à jour de leur langue par défaut (la page [d'administration de l'index](https://nosdemarches.gouv.fr/Demarches/Admin/SolrIndexChecker) signalait bien un problème). La réindexation spécifique de ces démarches a permis de remettre cela en ordre. Je reste vigilant sur le fait de bien positionner ce paramètre de langue lors du prochain import de démarches.
