### ISSUE TITLE
amélioration du moteur de recherche pour être plus discriminant

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#291]
je recherche la démarche suivante : "Demande de bourse nationale d'enseignement supérieur sur critères sociaux (agriculture)". Quand je fais une recherche sur le terme "demande de bourse" le résultat n'arrive qu'en 12ème position, devant "Demande de retraite progressive", "Demande de pension d'invalidité"
ou "Demande d'utilisation des droits à bourse en cas de préparation d'un nouveau diplôme".
Le moteur a l'air de prioriser sur le mot "demande" qui est très utilisé pour les démarches administrative, et ne priorise pas sur "bourse"

**Comment by slauriere** [comment]
Il y avait un problème avec la vingtaine de démarches suivantes, pour lesquelles la langue n'était pas correctement configurée (leur paramètre de langue était vide au lieu de valoir "fr").  Ce problème était lié à un oubli de ma part lors de l'import des démarches du MEAE : j'avais oublié d'exécuter un script effectuant la configuration de la langue, après import. Ce script a été à présent exécuté. Voici les identifiants des démarches concernées : 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753.

Par ailleurs, pour les autres démarches problématiques mentionnées dans ce ticket ("Demande de retraite progressive", "Demande de pension d'invalidité", "Demande d'utilisation des droits à bourse en cas de préparation d'un nouveau diplôme"), une réindexation du wiki à la suite du ticket #290 a résolu le problème.

J'ai ajouté à la page "/Demarches/Admin/" un lien permettant de lister les démarches qui n'auraient pas de paramètre de langue défini.

Je ferme ce ticket pour le moment, n'hésitez pas à le rouvrir ou à en créer un autre si vous identifiez de nouveaux problèmes de classement dans les résultats de recherche.

**Comment by slauriere** [comment]
Cc: @JeanPerrier

**Comment by JeanPerrier** [comment]
@georges-bayard j'ai fait la recherche que tu as indiqué quand tu as ouvert l'issue. ça fonctionne. As-tu d'autres remarques vu que c'est toi qui a mis à jour le problème?
