### ISSUE TITLE
Intégration du référentiel MAEE

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#292]
Nous (Georges surtout) avons intégré les démarches du Ministère des Affaires étrangères dans le modèle donné ci-joint.
Pouvez-vous intégré ce modèle joint dans le site? Merci,
[Copie de Démarches - Modèle de données - 20180423 - intitulés ministères dircetions (002).xlsx](https://github.com/DISIC/wikidemarches/files/2501738/Copie.de.Demarches.-.Modele.de.donnees.-.20180423.-.intitules.ministeres.dircetions.002.xlsx)

**Comment by slauriere** [comment]
J'ai importé ces 21 démarches, elles sont visibles sur le [tableau des démarches ordonné par date de création](https://nosdemarches.gouv.fr/Demarches/?statut=active#|t=demarches&p=1&l=100&s=doc.creationDate&d=desc&statut=active).

Remarques : 
* Avant import, j'ai renseigné la colonne "Ministères" ave la valeur "MAEE"
* Il semble que la démarche [1746](https://nosdemarches.gouv.fr/Demarches/1746) soit rattachée à une direction non déclarée (DRH DGM) - je vous laisse nous indiquer si cette direction et le groupe associé doivent effectivement être créée ou si la démarche doit être rattachée à "DRH MAE" ?

J'ai fait quelques vérifications de mon côté, dites-moi si tout vous semble ok de votre côté, auquel cas nous pourrons clore ce ticket.

**Comment by JeanPerrier** [comment]
Bonjour et merci,

J'ai rattaché la démarche 1746 à "DRH MAE" sur le site. Je ne sais pas si tu dois faire une autre démarche supplémentaire (je me permets de te tutoyer). A priori, tout semble ok de notre coté. 

J'ai deux questions quant à la rubrique "Événement de vie" de ces 21 démarches qui est vide. 
(1) Est-ce que vous remplissez cette rubrique pour toutes ces 21 démarches ou est-ce que je peux le faire directement sur le site? 
(2) Est-ce qu'a l'avenir je peux directement remplir la rubrique "évènement de vie" sur le tableur excel dans le modèle de donnée avant de vous l'envoyer?

**Comment by slauriere** [comment]
OK Jean, vu pour la mise à jour de la démarche 1746. Concernant les événéments de vie : 
- Oui, à l'avenir, tu peux remplir la colonne dédiée directement dans le tableur, sur le même principe que les publics. Il faut juste faire attention à la casse des événements et à leur orthographe car l'appariement se fait sur les termes exacts (mais on a un moyen de détecter les événements qui ne correspondent à aucun événement déjà existant le cas échéant).
- Pour les démarches MEAA déjà importées : le plus simple est peut être que tu les mettes à jour directement sur le site comme il n'y en a pas énormément, si ça te va. Si c'est trop fastidieux dis-moi et on prévoiera un réimport si tu me transmets le fichier avec la colonne complétée.

**Comment by JeanPerrier** [comment]
J'ai modifié la catégorie "événement de vie". Je clôture l'issue.

**Comment by georges-bayard** [comment]
ok GBA
