### ISSUE TITLE
Ajouter un champ de saisie libre quand un usager demande la dématérialisation d’une démarche papier

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#293]
Mettre l'usager en situation de pouvoir préciser sa demande ainsi que le contexte si il le souhaite

**Comment by JeanPerrier** [comment]
Demande des corresponds de l'administration lors des ateliers de fin septembre. A mettre en M8?
Il faudrait assigner têtue à cette tâche.

**Comment by JeanPerrier** [comment]
Lien avec #275

**Comment by lucaa** [comment]
Cette tâche à l'air d'être exactement la même chose que #275.
