### ISSUE TITLE
Changer MAEE en MEAE

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#294]
Le Ministère de l'Europe et des Affaires étrangères nous demande de changer sur le site dans le champ "ministère" le sigle de leur ministère MAEE en MEAE. C'est très important pour eux.

**Comment by slauriere** [comment]
Ok bien noté, j'ai fait la modification en ligne : https://nosdemarches.gouv.fr/Ministeres/MEAE. Je vous laisse vérifier et fermer le ticket si tout vous semble ok.

**Comment by JeanPerrier** [comment]
Merci beaucoup

**Comment by JeanPerrier** [comment]
Bonjour, 

Petite modification à faire encore.  Sur la capture d'écran ci-jointe, le sigle est toujours "MAEE" et non "MEAE". 
![meae](https://user-images.githubusercontent.com/44236635/47487517-dd79fa80-d842-11e8-87b0-8b1762ab161f.png)

**Comment by slauriere** [comment]
Effectivement, j'ai fait la modification. En principe vous pouvez faire ce genre de modification vous-même en tant qu'administrateur. C'est juste sur les opérations "Déplacer / Renommer" (depuis le menu "Plus d'actions") qu'il faut être prudent, car elles ont un impact sur les démarches liées, impact qui n'est pas géré automatiquement dans XWiki actuellement. Je ferme le ticket. À votre écoute,
