### ISSUE TITLE
On peut insérer des valeurs qui ne sont pas dans le référentiel des publics (Backoffice - fiche démarches - champ publics)

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#295]
Illustration sur la démarche "Demande de certificat individuel professionnel produits phytopharmaceutiques" : possibilité d'entrer dans l'information "publics" la valeur "Tous les professionnels exerçant une activité en lien avec les produits phytopharmaceutiques quel que soit leur statut ou leur secteur d’activité"

**Comment by slauriere** [comment]
Commencer par regarder s'il y a une option dans le widget selectize pour empêcher la saisie de valeur absente de la liste.

**Comment by slauriere** [comment]
Le paramétrage du widget de sélection a été modifié pour interdire la saisie de nouvelle valeur.

**Comment by georges-bayard** [comment]
ok GBA
