### ISSUE TITLE
changer l'information ministère par l'information champ ministériel

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#296]
Liste des champs ministériels : 
•Action sociale
•Affaires étrangères, Europe
•Affaires maritimes
•Agriculture, alimentation
•Aménagement, développement du territoire
•Budget, finances
•Collectivités territoriales
•Culture, communication
•Défense, armées
•Écologie
•Économie, entreprises, industrie, artisanat
•Éducation nationale
•Emploi, formation professionnelle
•Enseignement supérieur, recherche
•Fonction publique
•Industrie
•Intérieur
•Jeunesse
•Justice
•Logement
•Outre-mer
•Premier ministre
•Santé
•Sécurité sociale
•Sport
•Transport
•Travail
•Urbanisme, construction
•Vie associative
Point à discuter : affichage de l'information sur la page de vote (suffixer l'information avec "domaine", "champ ministériel", ...)
A réaliser parallèlement : la transformation des données entre l'ancien et le nouveau référentiel

**Comment by lucaa** [comment]
Le champ ministèriel est une propriété à choix multiple.
Il faut laisser le champ précédent, ministère, mais ne pas l'afficher.
L'association des champs ministeriels aux démarches existantes sera faite à base d'un fichier d'associations fourni par @georges-bayard .

**Comment by lucaa** [comment]
à spécifier ou ce nouveau champ doit être affiché et comment.
Idée: afficher un filtre dans la recherche avec ce nouveau champ.

**Comment by JeanPerrier** [comment]
Question: un champ ministériel comporte parfois des virgules ex "Affaires étrangères, Europe" or la virgule est la valeur séparatrice entre deux valeurs. Peut-on supprimer les virgules à l'import (pour éviter les bugs) et les afficher sur le site pour que ce soit compréhensible pour l'utilisateur?

**Comment by JeanPerrier** [comment]
Question: un champ ministériel comporte parfois des virgules ex "Affaires étrangères, Europe" or la virgule est la valeur séparatrice entre deux valeurs. Peut-on supprimer les virgules à l'import (pour éviter les bugs) et les afficher sur le site pour que ce soit compréhensible pour l'utilisateur?

**Comment by JeanPerrier** [comment]
@slauriere

**Comment by slauriere** [comment]
J'ai réalisé les actions techniques suivantes sur le site de développement : 
- Ajout d'une propriété "champs ministériels" à la classe des démarches
- Affichage de cette propriété, sans masquer pour le moment le champ "ministères"
- Ajout d'une classe "champ ministériel"
- Ajout de code pour effectuer la mise à jour en masse des démarches et l'affectation d'un ou plusieurs champ(s) ministériel(s) à chaque démarche
- Ajout d'une configuration d'import pour créer en masse les champs ministériels
- Ajout d'une configuration d'import pour mettre à jour en masse les démarches
- Restriction en édition / suppression des champs ministériels aux administrateurs
- Restriction en édition du code des champs ministériels aux administrateurs

Cela donne les résultats suivants sur le site de développement : 
- Les champs ministériels sont consultables depuis l'espace "CM"
- Les démarches peuvent être mises à jour en masse depuis un fichier contenant deux colonnes : la première contient l'identifiant de la démarche, la deuxième contient la liste de ses champs ministériels, séparés par une barre verticale : "|"

Exemple en CSV : 

```
1733, Affaires étrangères, Europe|Budget, finances|Éducation nationale
1734, Aménagement, développement du territoire|Emploi, formation professionnelle|Économie, entreprises, industrie, artisanat
```

Il reste en particulier à : 
- Remplacer la colonne "Ministère(s)" par une colonne "Champ(s) ministériel(s)" dans toutes les livetables concernées
- Valider et implémenter ce qui doit être fait pour la recherche
- Ecrire les instructions d'installation correspondante (+ mise à jour de la langue par défaut)

**Comment by slauriere** [comment]
Les bases de l'ajout de la propriété 'champsMinisteriels' ont été posées, je ferme ce ticket et en ouvre trois plus spécifiques : exécution des imports associés à cette nouvelle propriété #359 (et mise à jour des instructions d'import de données), mise à jour des interfaces suite à l'ajout de cette nouvelle propriété #361, et vérification du mode de déploiement de l'extension d'import #360.

**Comment by slauriere** [comment]
Ticket lié : #369.
