### ISSUE TITLE
Modification de la base de données des démarches

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#299]
Deux questions:

(1) Est-il possible de mettre en majuscule la première lettre de l’ensemble des démarches pour leur titre et pour leur nom complet? 
(2) J'ai constaté que pour un certain nombre de démarches (exemple ci-dessous), le site ne pouvait pas lire l'apostrophe présent dans les intitulés et le remplaçait par  un point d'interrogation. Est-il possible de résoudre ce problème sans le faire manuellement un à un? 

Exemples:
Demande   d?agrément des opérateurs pour l?aide à la mise en marché et à la   commercialisation des produits interprofessionnels de la viande et du lait
Demande   d?agrément du bénéficiaire unique - Aide à la structuration des filières de   diversification végétale ? POSEI
demande   d?aide exceptionnelle aux éleveurs de bovins à mayotte
demande   d?aide exceptionnelle aux producteurs d'agrumes impactés par la maladie du   citrus greening
demande   d?autorisation d?exportation-expedition
Demande   d?autorisation de type 1 ou de type 2 pour transporter des animaux vivants
demande   d?enregistrement au registre des operateurs
Demande   d?option pour le paiement de la totalite des cotisations d?assurance   vieillesse

**Comment by lucaa** [comment]
Il est possible de faire 2 corrections:
* la majuscule est possible de la corriger
* pour les apostrophes il est possible de: chercher d?[a,e,é,i,o,u] et l?[a,e,é,i,o,u] et remplacer le point d'interrogation avec une apostrophe, dans ces cas là.

**Comment by JeanPerrier** [comment]
Super! Merci.

**Comment by slauriere** [comment]
Jean, La normalisation des noms a été appliquée aux données du serveur de production. Je joins le log des mises à jour. Il concerne toutes les démarches qui soit commencent par une minuscule, soit contiennent un point d'interrogation. Les colonnes "Nouveau nom" et "Nouveau nom complet" contiennent les noms corrigés en utilisant la règle énoncée dans le commentaire d'Anca ci-dessus. Toute autre anomalie reste à être corrigée à la main.

**Comment by JeanPerrier** [comment]
Super Merci!

**Comment by slauriere** [comment]
Et voici le log... [181106-mise-a-jour-demarches.xlsx](https://github.com/DISIC/wikidemarches/files/2554251/181106-mise-a-jour-demarches.xlsx)

**Comment by JeanPerrier** [comment]
le log? ça veut dire? 
Le doc xlsx c'est le référentiel avant modification?

**Comment by slauriere** [comment]
Pardon, voici une explication : le log est la liste des démarches identifiées comme ayant un nom débutant avec une lettre minuscule ou contenant au moins un point d'interrogation. Seules les démarches dont la colonne "Nouveau nom" diffère de la colonne "Nom" ou dont la colonne "Nouveau nom complet" diffère de la colonne "Nom complet" ont été effectivement modifiées. Celles pour lesquelles ces valeurs sont identiques n'ont pas été modifiées.
