### ISSUE TITLE
empecher le croisement entre les champs de commentaire et les courriels

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#300]
les courriels récoltés auprès des utilisateurs ne doivent pas pouvoir être recoupés avec les champs de commentaire en saisie libre. contrainte RGPD cf mails de Maud Choquet

**Comment by lucaa** [comment]
Semble être le meme issue que #252 . @georges-bayard , c'est la même chose ou pas?

**Comment by JeanPerrier** [comment]
Oui!
