### ISSUE TITLE
Lors de l'édition d'un avis, les champs "autreAide" et "autreDifficulté" ne sont pas affichés même s'ils sont non vides

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#301]
Étapes : 
- Saisir un avis depuis la page d'une démarche
- Cocher "autre" à la question "Quelles difficultés avez-vous rencontré ?"
- Saisir une réponse
- Finaliser la saisie de l'avis
- Editer l'avis en tant qu'administrateur
- Le champ "autreDifficulte" est vide en mode édition

Solution : désactiver l'édition des champs autres que "demarche" dans le formulaire d'administration des avis.

**Comment by slauriere** [comment]
À présent dans le formulaire d'administration d'un avis en mode édition, seul le champ "démarche" est éditable (pour rattacher un avis existant à une autre démarche) : les autres champs sont affichés en mode lecture uniquement. 

NB : sur le site de production, seuls 3 avis ont été édités par des non guests à ce stade, donc sans doute pas nécessaire de prévoir un correctif. Cf script "Avis.Admin.AvisEdited".

**Comment by georges-bayard** [comment]
ok GBA
