### ISSUE TITLE
Valider les instructions pour ouvrir le fichier .csv en microsoft office

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#302]
Cette issue est liée à #243, est là pour verifier les instructions pour ouvrir le CSV avec microsoft office. Apparemment, ça ne fonctionne pas comme prévu.

**Comment by lucaa** [comment]
Aussi, il faut ajouter une note sur l'encodage du fichier (écrire clairement CSV).

**Comment by JeanPerrier** [comment]
Pour info notre version d'Excel est Microsoft Office Standard 2013. 
Il n'existe pas de bouton importer.
Ci-joint les informations de l'aide: 

Excel vous permet d’importer des données à partir d’un fichier texte de deux manières : vous pouvez l’ouvrir dans Excel ou l’importer sous forme de plage de données externes. Pour exporter des données à partir d’Excel dans un fichier texte, utilisez la commande Enregistrer sous et modifiez le type de fichier dans le menu déroulant.

Deux formats de fichier texte sont couramment utilisés :

Les fichiers texte délimités (fichiers .txt), dans lesquels les champs de texte sont séparés par des tabulations (caractère ASCII, code 009).
Les fichiers texte CSV (valeurs séparées par une virgule), dans lesquels les champs de texte sont en général séparés par des virgules.


Vous pouvez modifier le caractère séparateur utilisé dans les fichiers délimités et les fichiers texte .csv. Il peut être nécessaire de vérifier que l’opération d’importation ou d’exportation fonctionne de la façon prévue.
 
Importer un fichier texte en l’ouvrant dans Excel

Vous pouvez ouvrir un fichier texte créé dans un autre logiciel sous la forme d’un classeur Excel à l’aide de la commande Ouvrir. Ouvrir un fichier texte dans Excel ne modifie pas le format du fichier ; vous pouvez le voir dans la barre de titre d’Excel où le nom du fichier conserve l’extension du nom du fichier texte (par exemple, .txt ou .csv).

1.Accédez à fichier > Ouvrir.
2.Sélectionnez Fichiers texte dans la boîte de dialogue Ouvrir.
3.Recherchez le fichier texte que vous souhaitez ouvrir et double-cliquez sur son entrée.

S’il s’agit d’un fichier texte (.txt), Excel démarre l’Assistant Importation de texte. Lorsque vous avez effectué toutes les étapes, cliquez sur Terminer pour terminer l’opération d’importation.

Voir : L' Assistant Importation de texte pour plus d’informations sur les délimiteurs et options avancées.

S’il s’agit d’un fichier .csv, Excel ouvre automatiquement le fichier texte et affiche les données dans un nouveau classeur.

Remarque : Lorsqu’Excel ouvre un fichier .csv, il utilise les paramètres de mise en forme des données actifs par défaut pour importer chaque colonne de données. Pour plus de souplesse pour convertir les colonnes en d’autres formats, utilisez l’Assistant Importation de texte. Par exemple, le format d’une colonne de données d’un fichier .csv peut être MJA alors que le format des données par défaut d’Excel est AMJ, ou encore vous souhaitez convertir une colonne qui contient des nombres commençant par des zéros en texte tout en préservant les zéros. Pour forcer Excel à exécuter l’Assistant Importation de texte, vous pouvez modifier l’extension du nom du fichier de .csv en .txt avant de l’ouvrir ou importer un fichier texte en s’y connectant.

**Comment by lucaa** [comment]
Il faut simplifier l'explication, détailler les parametres du format csv (UTF-8 et virgule) et mettre une note generique pour l'ouverture du fichier de type "consulter la doc de votre logiciel".

**Comment by slauriere** [comment]
- "Conforme aux recommandations d'interopérabilité de l'Etat".
- Mentionner que le séparateur est la virgule et que l'encodage est UTF-8.
- Les logiciels qui permettent d'ouvrir des fichiers CSV sont des logiciels de gestion de feuilles de calcul (exemples : LibreOffice, Microsoft Excel, ...). Pour savoir comment ouvrir ce fichier, se reporter aux instructions d'aide des logiciels existantes.

**Comment by slauriere** [comment]
Les instructions ont été mises à jour comme convenu.

**Comment by JeanPerrier** [comment]
@slauriere Il faut mettre le lien vers la page d’explication pour tous les boutons export CSV accessibles aux usagers/ utilisateurs, notamment le bouton export de la page de résultat de démarche détaillé.

**Comment by JeanPerrier** [comment]
j’approuve le texte d'explication! super!

**Comment by slauriere** [comment]
Jean, J'ai ajouté un lien vers la page d'explications sous le bouton d'export des statistiques d'avis, je pense que c'est le seul autre export CSV que nous ayons pour le moment. Cool pour le texte :-)

**Comment by JeanPerrier** [comment]
ça marche merci
