### ISSUE TITLE
Modifier le calcul du taux de satisfaction, pour compter uniquement les avis "satisfait"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#304]
* sur la demarche elle même
* sur le tableau de bord

**Comment by slauriere** [comment]
- L'extension avis-stats a été mise à jour pour implémenter le nouveau mode de calcul.
- Le custom displayer de la propriété "moyenne" d'AvisStatsClass a été mis à jour pour l'affichage du taux de satisfaction dans le tableau de bord.
- DemarcheMacros utilise à présent l'objet AvisStats plutôt que d'effectuer une requête.
- La page Main.Satisfaction reflète le nouveau mode de calcul.

NB : 
- Actuellement la requête de calcul des statistiques suppose que tout Avis a des propriétés "score" et "vote" (éventuellement vides, mais des entrées doivent exister dans la base de données). Il pourrait être pertinent de faire plutôt deux requêtes (une pour chaque propriété) pour éviter d'exclure des statistiques des avis qui n'auraient pas la propriété "vote" (dans le cas où des avis seraient créés non pas via le formulaire du site mais via une API par exemple).
- La propriété "moyenne" d'AvisStatsClass pourrait être renommée.

Lors de la prochaine mise en production, il faudra exécuter le script de la page AvisStatsManager.

**Comment by slauriere** [comment]
Réouverture pour décider si on passe à une requête par propriété ou pas.

**Comment by lucaa** [comment]
> Réouverture pour décider si on passe à une requête par propriété ou pas.

Pour l'instant on laisse le calcul tel quel. Si jamais il y a des problemes de synchronisation entre le cache et les valeurs reeles, on pourra le voir en comparant le nombre d'avis affiche sur l'onglet de statistiques avec le nombre d'avis affiches sur la liste des avis.
