### ISSUE TITLE
Ajouter un onglet pour les détails de votes sur la page de la démarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#306]
* Maquette: https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/322581161_Dashboard-Demarche-2
** La maquette de navigation (qui n'est pas à faire pour cette tache, par contre, se trouve ici: https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/322604713_Parcours )
* L'idée est d'ajouter ces informations dans un onglet supplémentaire sur la page de la démarche, qui n'est pas affiché par défaut, mais activé quand on clique sur la démarche dans le tableau de bord

**Comment by lucaa** [comment]
![image](https://user-images.githubusercontent.com/657716/48077967-d4950b80-e1e8-11e8-8deb-9ce5d25a0e63.png)

En haut a gauche: affichage de la page demarche: on garde le titre, ministere / public et taux de satisfatction tel que courant, on affiche 2 onglets en dessous de cela: Donnez votre avis et plus de détails.

En bas a droite: l'onglet plus de details, avec 4 sections:
- Plus de détails sur la démarche (url, direction, etc.). Pas encore spécifié, voir #237 
- Taux de satisfaction détaillé. Pas encore spécifié non plus. On affichera au moins un bar chart avec les pourcentages de chaque évaluation (satisfait, bof, pas satisfait).
- Détails de l'évaluation de la démarche. Spécifiés dans le mockup de Romy (que je dois trouver)
- Export CSV des données. Voir #307

**Comment by slauriere** [comment]
![qjlbjiajedrdkupnqjugarsd](https://user-images.githubusercontent.com/1022195/48131277-d239bc80-e28f-11e8-97fe-2a1b7afe1882.jpg)

**Comment by slauriere** [comment]
[Maquette InVision](https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/322581161)

**Comment by slauriere** [comment]
Accessibilité : les diagrammes étant contenus dans un canvas, ajouter un fallback affichant le tableau des données. Cf recommandations sur [accede-web](https://www.accede-web.com/) et dans la documentation accessibilité de ChartJS.

**Comment by lucaa** [comment]
Contrainte supplémentaire: il faut avoir un permalien vers l'onglet de statistiques (que l'onglet stats, qui n'est pas l'onglet activé par défault, soit "activable" avec un paramètre d'URL).

**Comment by lucaa** [comment]
* Les smileys sont a afficher en pourcentage, pas en valeur absolue.

**Comment by lucaa** [comment]
Confirmé avec @tetue , pour l'instant on peut laisser les smileys à la couleur du texte (gris-noir), il n'y a pas besoin de les colorer dans la couleur du chart.

**Comment by slauriere** [comment]
- Les diagrammes affichent à présent des pourcentages sur une échelle fixe de 0 à 100.
- Un permalien est disponible pour activer l'onglet des diagrammes soit côté serveur soit côté client : ?tab=details ou #details-tab

**Comment by slauriere** [comment]
- Les valeurs absolues ont été restaurées à la place des pourcentages pour les propriétés "difficultés" et "aide".
- Les histogrammes des smileys contiennent à présent toujours 3 barres.
- Le diagramme "Autre modalité" ne s'affiche que quand il y a eu au moins une réponse dans ce sens.
Fermeture de ce ticket, les autres évolutions feront l'objet de tickets dédiés.
