### ISSUE TITLE
Créer un lien export csv pour chaque fiche statistique des démarches

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#307]
Premiere etape: prototype qui intègre le travail de test fait pour #237 .

**Comment by lucaa** [comment]
à intégrer dans l'onglet defini pour #306

**Comment by slauriere** [comment]
Il faut une page custom. L'export doit contenir la liste des avis relatifs à al démarche en cours, uniquement les champ suivants (ceux utilisés pour les statistiques affichées) : 
- score, facile, compréhensible
- aide (mais pas le détail du champ "autreAide")
- difficultés (idem)
- modalité
- vote pour la dématérialisation

Également : date de création avec l'heure.

Attention : ne pas inclure l'identifiant des avis, l'identifiant de session etc.

S'assurer que le bouton d'export CSV ne soit par défaut pas suivi par les robots.

Le seul paramètre du script doit être l'identifiant de la démarche. Pas la liste des colonnes etc.

**Comment by slauriere** [comment]
La page Avis.Code.LiveTableResults a été modifiée pour prendre en compte le format CSV et pour restreindre l'accès à certains champs aux non-administrateurs d'une part, et aux guests d'autre part. Il reste à faire une vérification de sécurité de Avis.Code.LiveTableResultsMacros dans la mesure où une des macros a dû être modifiée pour un accès aux documents via "getDocumentAsAuthor" puisque les guests n'ont pas accès aux avis.

**Comment by slauriere** [comment]
Séparer le mécanisme d'export de celui de l'export Excel / JSON (pour des questions de sécurité et de maintenance), et résoudre le bug d'export.

**Comment by slauriere** [comment]
Une page dédiée à l'export CSV des avis d'une démarche a été dédiée, avec restriction explicite des propriétés exportables. Cette restriction est définie dans le code et non en paramètres http. Les pages d'export xls des tableaux d'avis ont été restaurées dans leur comportement précédent, à destination des utilisateurs authentifiés uniquement, avec restriction aux administrateurs de l'export de la propriété 'email'.
