### ISSUE TITLE
Amélioration de la page d'accueil du site

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#308]

**Comment by tetue** [comment]
Pour mémoire, la dernière maquette de home en date (à améliorer donc) : 
https://octo.invisionapp.com/share/8XJEA1ZHWK4#/299047765_Home

**Comment by JeanPerrier** [comment]
Plusieurs briques à intégrer dans la page d'accueil:
- les principales démarches par évènement de vie;
- intégration du Cerfa numérique ;
- articulation du design avec vox usager;
- Orientation (message principale du site) du site: celle du cab (tableau de bord) ou celle du directeur (vote/qualité)
=> intelligibilité globale (démarche fortement UX avec maquette et testing)

**Comment by JeanPerrier** [comment]
Cette issue n'a plus de sens
