### ISSUE TITLE
L'etiquette du bouton d'export excel d'une demarche est mal affiché

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#309]
Pour les utilisateurs connectés, sur la page d'une demarche, le bouton d'export Excel s'affiche mal.

![image](https://user-images.githubusercontent.com/657716/48077811-7a944600-e1e8-11e8-9d10-e3fc59c31c1c.png)

**Comment by slauriere** [comment]
Le paramètre 'Excel' a été ajouté à l'appel de la fonction de localisation et le bug lié #310 a été corrigé.
