### ISSUE TITLE
Petite modification d'une virgule sur la page ajout démarche

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#312]
https://nosdemarches.gouv.fr/Demarches/Code/NewDemarche?text=zqd

"Si vous n'avez pas trouvé la démarche que vous avez faite, ajoutez-la ici, afin de pouvoir donner votre avis"

Il faudrait enlever la virgule après "ici"

**Comment by slauriere** [comment]
La modification a été apportée (sur la plate-forme de développement pour le moment uniquement).

**Comment by JeanPerrier** [comment]
Merci
