### ISSUE TITLE
Ajouter le bouton d'export excel pour le tableau des avis d'une demarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#314]
Le tableau d'avis d'une seule démarche devrait être, lui aussi, exportable en Excel (comme le tableau de tous les avis.

**Comment by slauriere** [comment]
Le bouton d'export a été ajouté, et un bug corrigé dans le code d'export custom : le paramètre du nom de fichier a été renommé de 'excelFilename' en 'filename' à la suite de l'évolution de la macro d'export Excel pour le support du format CSV.

**Comment by slauriere** [comment]
PS : est-ce qu'il ne faudrait pas également ajouter sur cette page le bouton permettant d'accéder à la page d'administration des avis ?

**Comment by lucaa** [comment]
> PS : est-ce qu'il ne faudrait pas également ajouter sur cette page le bouton permettant d'accéder à la page d'administration des avis ?

Non, je préfère restreindre l'accès à Avis.Admin qu'aux administrateurs.

**Comment by lucaa** [comment]
@slauriere tu peux verifier le comportement de la colonne "email" dans cet export? 
L'idée étant que cet export n'ouvre pas plus l'accès à cette propriété que l'export de la page Avis.WebHome.

**Comment by slauriere** [comment]
La page Avis.Code.LiveTableResults a été modifiée pour que la colonne 'email' ne soit exportée que si l'utilisateur est un administrateur, cf [ce changement](https://github.com/DISIC/wikidemarches/commit/c3cbaf9894d70ec12f756847a32477ef89f746c9#diff-556f33e8154880436364e3ddcce156d9R68).

**Comment by slauriere** [comment]
Un scénario de test dédié a été ajouté à la [liste des tests](https://github.com/DISIC/wikidemarches/wiki/Scénarios-de-test).

**Comment by JeanPerrier** [comment]
@
![capture](https://user-images.githubusercontent.com/44236635/49070751-b42b0080-f22c-11e8-9cba-636f550717f5.PNG)
slauriere J'ai essayé d'exporter le fichier CSV sur le site de développement  et j'obtiens cette capture d'écran. C'est parce que c'est sur le site de développement?

**Comment by JeanPerrier** [comment]
@slauriere

**Comment by slauriere** [comment]
Il y avait effectivement un problème sur la plateforme de staging, je viens de le corriger. Pour mémo et suivi : le problème concerne plus spécifiquement le ticket #307 -> je clos celui-ci et je te / vous laisse rouvrir le #307 si le problème persiste.

**Comment by JeanPerrier** [comment]
Merci parfait!
