### ISSUE TITLE
Auditer l'accessibilité des graphiques de la page de stats d'une demarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#317]
Il s'agit de vérifier l'accessibilité des graphiques telles que implementés pour #306 , dans 3 catégories.

1/ accessibilité des données pour les lecteurs d'écrans - la presence d'un tableau de fallback
2/ fallback html (dans le canvas) - le markup de ce tableau de fallback
3/ accessibilité des graphiques pour les personnes qui peuvent lire les graphiques mais qui peuvent avoir des difficultés de perception de couleurs.

**Comment by lucaa** [comment]
@tetue contrairement à l'information que j'avais ce matin dans la réunion, le tableau de fallback est en place, il est possible de commencer un audit dessus.

**Comment by lucaa** [comment]
pour 3/ nous avons déjà notés 2 remarques dans la réunion ce matin:
3.a/ il faut essayer de placer les etiquettes des barcharts pour difficultés et aide au dessus de la barre elle-même, pour faciliter la lecture (noir sur blanc)
3.b/ il faut mettre les etiquettes a l'exterieur des pie-charts, affichés tout le temps.

**Comment by tetue** [comment]
Voici ce que j'ai remarqué, en essayant à la synthèse vocale [*] : 

1. Il manque les `<caption>` à chaque tableau : https://www.accede-web.com/notices/html-css-javascript/9-tableaux/9-1-titre-tableau-donnees-caption/ Intitulés, dans l'ordre : _Répartition des avis, Répartition des réponses sur la facilité d'usage, Répartition des réponse sur la compréhension, Difficultés rencontrés, Besoins d'aide, Parcours dématérialisés, Souhaits de dématérialisation_
2. Pour la ligne d'entête (contenant les `<th>`), plutôt que `<tr>` préférer `<thead>`
3. Les intitulés des entêtes de tableau ne sont pas explicites à l'oral. Plutôt que `<th scope="col"> score </th><th scope="col"> Données</th>` préférer `<th scope="col">Satisfaction</th><th scope="col">Réponses</th>`, `<th scope="col">Facilité</th><th scope="col">Réponses</th>`, etc.
4. La colonne contenant les codes couleur est vocalisée et c'est gênant. Essayer [*] en lui appliquant `display:none` ou/et `aria-hidden="true"` (voir : http://a11y-guidelines.orange.com/web/exemples/masquage/index.html ). Sinon appliquer la couleur d'une autre façon. 

[*] Pour essayer avec synthèse vocale, utiliser le logiciel [NVDA](https://www.nvda-fr.org) sinon, a minima, la synthèse vocale intégrée du navigateur Chrome (activable via le menu « Modifier > Voix > Commencer à parler »).

**Comment by slauriere** [comment]
Les améliorations suivantes ont été apportées : 
- Ajout d'une balise "caption" aux tableaux
- Usage de "thead" pour les en-têtes de tableaux
- Utilisation d'en-têtes plus explicites
- Spécification des couleurs ailleurs que dans le tableau des données

Il reste un point à corriger : celui de la colonne des smileys, qui sont actuellement des caractères Font Awesome, donc incompréhensibles lors de la synthèse vocale.

**Comment by slauriere** [comment]
Les smileys ne sont à présent affichés que sur les diagrammes eux-mêmes, les tableaux de données contiennent, eux des libellés lisibles. Je clos cette tâche bien que n'ayant pas encore pu tester avec Chrome / ChromeVox. Têtue : n'hésite pas bien entendu à rouvrir le ticket si tu constates des points à revoir. Merci pour tes indications précises et éclairantes.
