### ISSUE TITLE
Sur les histogrammes placer les libellés au-dessus des barres

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#319]
Eventuellement avec des barres blanches avec libellé. Cf #317.

**Comment by JeanPerrier** [comment]
@slauriere capture d'écran sur mon téléphone 
![screenshot_20181127-094331](https://user-images.githubusercontent.com/44236635/49069643-10405580-f22a-11e8-81da-6fc99c29c0cf.png)
