### ISSUE TITLE
Finir visuellement l'affichage de l'onglet des avis d'une demarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#325]

**Comment by lucaa** [comment]
![image](https://user-images.githubusercontent.com/657716/48765883-77eb2380-ecb3-11e8-962a-8cd683bf89a2.png)

**Comment by slauriere** [comment]
## Compléments

Maquettes InVision de référence : [octo.invision 8XJEA1ZHWK4](https://octo.invisionapp.com/share/8XJEA1ZHWK4#/screens/322581161) (voir aussi les commentaires) – à parcourir depuis la maquette de navigation globale.

* Satisfaction globale : titre "Indice de satisfaction global" à positionner plus bas. Diagramme circulaire à positionner à droite avec les valeurs absolues, et les libellés suivants :  Avis positifs, Avis négatifs, Avis moyens.
* Pour tous tous les histogrammes de la partie "Détail des avis", afficher des valeurs absolues.
* Couleur des barres : une seule couleur pour le moment.
* Diagrammes circulaires : essayer de coller à l'ordre des secteurs sur les maquettes.
* Modalités : 
  * N'afficher les diagrammes que s'il y a eu au moins une réponse.
  * Le diagramme portant sur les autres modalités ne s'affiche que s'il y a des gens qui ont fait la démarche autrement. Il s'affiche même dans le cas où il y a 100% de "dématérialistion non demandée".
* Légende des diagrammes circulaires : dans un premier temps, acceptable d'afficher la légende au-dessus des diagrammes, en petit.
* Voir aussi #319.
* Dans le cas où aucun avis n'a été soumis : afficher l'onglet "Tous les avis" mais avec comme contenu "Aucun avis pour l'instant".

**Comment by slauriere** [comment]
Les améliorations suivantes ont été apportées :
- Mise à jour des éléments d'interface.
- Configuration générique des couleurs de diagrammes.
- Ajout de clefs de traduction.
- Affichage des libellés à l'extérieur des diagrammes circulaires.
- Affichage des diagrammes de modalités uniquement s'il y a au moins une réponse, et des demandes de dématérialisation s'il y a au moins une occurrence de modalité "autre".
- Affichage de "Aucun avis pour l'instant" tant qu'aucun avis n'a été soumis.

Le résultat actuel est visible sur la plateforme de développement.

Il reste à finaliser certains points plus spécifiques, pour lesquels je crée des tickets séparés (en particulier : RGAA dans le cas des tableaux avec smileys : il faut un fallback qui diffère des smileys car non lisibles, packaging des librairies JS).

**Comment by georges-bayard** [comment]
une correction sur le formulaire : quand la démarche est votée par un seul internaute revoir l'intitulé "Données recueillies en ligne sur ce site, depuis le 15 juin 2018, auprès de 1 internautes" ; enlever le "s" si la démarche a été votée par un seul internaute

**Comment by slauriere** [comment]
J'ai mis à jour le libellé en question : usage du singulier quand un seul avis est disponible.
