### ISSUE TITLE
Implémentation de l'affichage des détails de la démarche

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#326]

**Comment by JeanPerrier** [comment]
Créer "voir le détail de la démarche" comme sur la maquette de Romy
https://octo.invisionapp.com/m/share/8XJEA1ZHWK4#/322581161

**Comment by JeanPerrier** [comment]
Suite de l'issue #325

**Comment by lucaa** [comment]
cf. résultat du travail sur #237 .

**Comment by slauriere** [comment]
J'ai publié une première version du bloc affichant les détails d'une démarche, sur le site de développement.

**Comment by JeanPerrier** [comment]
De : slauriere [mailto:notifications@github.com]
Envoyé : jeudi 29 novembre 2018 15:06
À : DISIC/wikidemarches <wikidemarches@noreply.github.com>
Cc : PERRIER Jean <jean.perrier@modernisation.gouv.fr>; Author <author@noreply.github.com>
Objet : Re: [DISIC/wikidemarches] Implémentation de l'affichage des détails de la démarche (#326)


J'ai publié une première version du bloc affichant les détails d'une démarche, sur le site de développement.

**Comment by slauriere** [comment]
J'ai amélioré deux choses sur le site de développement : 
- meilleure fluidité dans l'affichage et le masquage de la zone des détails
- déplacement des libellés affichés dans des pages dédiées pour faciliter leur mise à jour

Je vous laisse regarder ce que vous en pensez, je ferme ce ticket, n'hésitez pas à en créer de nouveaux plus spécifiques pour toute amélioration ou tout bug fixing.
