### ISSUE TITLE
Créer un questionnaire France connect spécifique

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#327]
Il faut :
- une première page avec trois smileys
- supprimer la 2eme et 3eme page
- une quatrième page de remerciement.

**Comment by JeanPerrier** [comment]
Mail de Romy:
1) Pour se faire une idée de ce qui se pratique habituellement, je vous partage ma collection de messages électroniques de demande de satisfaction :

https://extranet.octo.com/oft/viewfile.php?fileid=c38dbf6b50a3fc351a0ef82b91b0f73e&dl=

2) Côté technique, cet article fait le point :
 Peut-on intégrer un formulaire dans un email ?https://www.emailing.biz/creer-un-emailing/integrer-formulaire-emailing/
Réponse : oui et non (ce n'est pas très efficace)

**Comment by slauriere** [comment]
J'ai implémenté le comportement indiqué pour la démarche ayant l'identifiant spécifique 1781 sur la plateforme de développement, et j'ai ajouté le test correspondant à la page de scénarios de tests. J'ai également créé le ticket suivant concernant la mise à jour qu'il faudra effectuer sur le site de production une fois la démarche "France Connect" créée : #357.
