### ISSUE TITLE
Améliorer le contraste des smileys

### ISSUE THREAD

**Issue by tetue** [DISIC/wikidemarches#331]
Pour améliorer le contraste des smileys (au niveau AA du RGAA), utiliser les couleurs suivantes : 

![smileys-color](https://user-images.githubusercontent.com/538106/48772922-226c4200-ecc6-11e8-9ac7-5641cae138ea.png)

- Danger #E62623
- Warning #AE650B
- Success #22891F

**Comment by lucaa** [comment]
les couleurs seront à mettre en place pour tout le site, comme c'est le cas aujourd'hui (danger, warning, succes).

**Comment by slauriere** [comment]
Les couleurs indiquées ont été appliquées au formulaire de vote et à l'onglet des statistiques.

Pour mémo :
- Les couleurs des smileys sont définies dans Avis.Code.RadioVoteDisplayer
- Les couleurs des graphiques statistiques dans Demarches.Code.DemarcheAvisStatisticsTab

Questions : 
- Applique-t-on ces couleurs également aux badges l'observatoire lui-même ? (je suppose que oui)
- Aux panneaux des messages de confirmation / validation ? (je suppose que oui également, mais par précaution)

NB : il reste à appliquer la procédure de validation de contraste pour [conformité au RGAA](http://references.modernisation.gouv.fr/rgaa-accessibilite/glossaire.html#contraste) soit via le calcul indiqué soit via un assistant visuel éventuel.

**Comment by slauriere** [comment]
J'ai également augmenté le contraste des graphiques « Difficultés rencontrées » et « Aides sollicitées » (couleur mauve foncé).

**Comment by slauriere** [comment]
L'outil WCAG signale que le contraste des indications en gris clair est insuffisant (couleur @gray-light: #777) -> j'ai un peu foncé celle-ci, à #666.

**Comment by slauriere** [comment]
Les nouvelles couleurs appliquées permettent de valider le niveau AA dans l'outil WCAG Contrast Checker comme le montre la capture d'écran ci-dessous (pas le niveau AAA toutefois).

![wcag-contrast-checker](https://user-images.githubusercontent.com/1022195/70544361-3d795080-1b6c-11ea-8367-b10b20f94b85.jpg)

Cheers Romy !

**Comment by slauriere** [comment]
Le contraste des infobox vertes est ok également : 

![wcag-contrast-info-box](https://user-images.githubusercontent.com/1022195/70544696-d019ef80-1b6c-11ea-9ee0-bebd6d5e6220.jpg)

**Comment by lucaa** [comment]
> Applique-t-on ces couleurs également aux badges de l'observatoire lui-même ? (je suppose que oui)

non, les couleurs de l'observatoire lui même sont custom et leur accessibilité a été traité par #777 .

**Comment by lucaa** [comment]
Je re-ouvre pour enlever les couleurs custom de la page de vote, rester avec l'approche précédente qui  est d'utiliser les couleurs du thème de couleurs sur la page de vote, et de modifier, pour atteindre le contraste necessaire, le theme de couleurs.

**Comment by lucaa** [comment]
> Aux panneaux des messages de confirmation / validation ? (je suppose que oui également, mais par précaution)

Si je comprends bien cette question et elle parle de ce type de choses https://user-images.githubusercontent.com/1022195/70544696-d019ef80-1b6c-11ea-9ee0-bebd6d5e6220.jpg ,  Comme expliqué dans mon commentaire de re-ouverture, les couleurs de smileys devraient être mis en place dans la color theme et vérifier comment ça impacte ces panneaux. L'idée est d'avoir un color theme qui, si les paires de couleurs foreground / background sont correctement respectés, assure le contraste, plutôt que de le vérifier et corriger pour chaque écran individuellement.

**Comment by slauriere** [comment]
Effectivement, les couleurs sont à présent définies directement dans le thème uniquement, pardon. Les couleurs des panneaux de messages sont ok même si je n'ai pas identifié précisément dans le code où elles sont calculées (e.g. `messages.less`).

**Comment by AnthonyBrunelli** [comment]
Bon, je me suis un peu perdu dans le fil là. Si vous avez contrôlé les boites de message, cool! Du coup, je mets en fait...  si on voit qq part un contraste pas bon, on vous informe dans une nouvelle issue.
