### ISSUE TITLE
Créer un fil d'ariane sur le site

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#335]
Il faudra créer un fil d’Ariane en vu de l'inclusion du projet Cerfa numérique sur NosDémarches.

**Comment by JeanPerrier** [comment]
Demande d'Anthony
@romy : peux tu donner ton avis sur ma manière la plus fluide d'intégrer le fil d'ariane sur les parties publiques ? sur la partie privée l'intégratioin n'est à mon avis pas très naturelle

**Comment by tetue** [comment]
Un fil d'Arianne n'est pas pertinent sur un site qui n'a pas de profondeur (pour rappel, sur la partie publique, il n'y a qu'une page d'accueil et une page de résultats de recherche).

**Comment by georges-bayard** [comment]
Il faut le faire à la suite de l'ajout de la partie cerfa numerique

**Comment by JeanPerrier** [comment]
Depuis l'évolution du modèle cette issue n'a plus de sens
