### ISSUE TITLE
Check that the display value of the dblist properties (evenement de vie, etc) is indexed as text in the demarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#34]
For a demarche that is linked to an evenement de vie, we would want a search for that evenement de vie to return the demarche as result as well.

Afair, in XWiki, the display value of a dblist field is indexed in the document containing the object, as text.
@slauriere says that as far as he tested, this doesn't work.

We need to  investigate and figure it out (make it work, preferably).

**Comment by lucaa** [comment]
So, indeed the values of a dblist are not indexed, only the keys. 
Sometimes it might look like the values are indexed, for the cases when keys (document names) correspond to values (document titles), but it's not the case for the Publics dataset, in our case - keys are numbers and values are texts.

We could modify the metadata extractor - we'd need to intervene about this level https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-search/xwiki-platform-search-solr/xwiki-platform-search-solr-api/src/main/java/org/xwiki/search/solr/internal/metadata/AbstractSolrMetadataExtractor.java#L376 (but in the document metadata extractor, not the abstract one) to add the values as well. 
However, we'd also need to figure out a strategy to reindex all referring documents anytime a possible value of the dblist changes - and this can be more complicated.

In our case, we have the option of denormalizing the data on publication, and copy the displayed value instead of the stored value for all the dblists that we want to index properly. 
Right now the plan is that the frontend data is not used for anything else than search and display to user, so I guess that denormalization is a good enough option. We always have the option to re-normalize (by doing another full publication of data) if we need to add a feature that needs proper foregin keys.

**Comment by slauriere** [comment]
We chose to denormalize indeed and we implemented the feature in the publication application, so I suggest to close this issue.
