### ISSUE TITLE
Accessibilité des diagrammes relatifs aux niveaux de satisfaction

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#340]
Les niveaux de satisfaction sont représentés par des smileys issus de caractères de la police Font Awesome, non lisibles par des lecteurs d'écran. Il faudrait prévoir un texte alternatif à afficher dans les tableaux.

**Comment by lucaa** [comment]
Corrigé par commit bb845519e387b87b98b18ab8c334dc2a8d46be93 pour #317.
