### ISSUE TITLE
Tableau de bord: trier les démarches selon le nombre d'avis par défaut en arrivant sur la page

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#342]

**Comment by slauriere** [comment]
J'ai ajouté un paramètre au lien conduisant au tableau de bord pour que celui-ci soit trié par nombre d'avis décroissant.

**Comment by slauriere** [comment]
J'ai modifié le code pour que le lien par défaut conduisant au tableau de bord fonctionne avec le tri indiqué, sans avoir à utiliser de lien avec paramètres supplémentaires.
