### ISSUE TITLE
Auditer l'affichage de l'onglet des statistiques d'une demarche sur les dispositifs mobiles

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#343]
Chaque section de l'onglet de statistiques d'une demarche contient 2 colonnes. En affichage telephone mobile ou tablette, toutes les sections doivent afficher le meme nombre de colonnes (soit 2 soit 3). Il semble y avoir une différence sur tablette entre la premiere section et les autres.

**Comment by JeanPerrier** [comment]
cf commentaire #319

**Comment by slauriere** [comment]
La règle d'affichage de la première ligne a été ajustée en mode bloc pour correspondre à la même règle que le "md" de bootstrap.
