### ISSUE TITLE
Installer Piwik pour pister les comportements des utilisateurs en fin de démarche et mesure le taux de conversion

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#345]

**Comment by lucaa** [comment]
à la place de piwik, d'autres solutions d'analytics peuvent être envisagées, en synchronisation avec les outils disponibles dans l'administration et partagés par d'autres services.

**Comment by georges-bayard** [comment]
avantage de piwik vs autres produits ?

**Comment by lucaa** [comment]
À faire:
* obtenir les coordonés du serveur pour la config (@georges-bayard )
* configurer l'observatoire pour utiliser ce tracking (@lucaa )

**Comment by lucaa** [comment]
> obtenir les coordonés du serveur pour la config

il faut 2 codes:
* le code à intégrer pour le tracking lui-même (fourni le 21/01/2020 par email)
* le code à intégrer pour permettre aux utilisateurs de desactiver le tracking (pour tache #775 ) - reste à faire.

**Comment by AnthonyBrunelli** [comment]
Pense bête: mettre les CGU à jour.

**Comment by lucaa** [comment]
> mettre les CGU à jour.

c'est le #775

**Comment by lucaa** [comment]
Les instructions ont été ajoutées pour installer l'extension Matomo ici https://github.com/DISIC/wikidemarches/wiki/Installation-instructions-v-4.x#extensions-to-be-installed et la configurer https://github.com/DISIC/wikidemarches/wiki/Installation-instructions-v-4.x#configuration-of-analytics-wheneverif-required .
Les modifications pour le opt-out ont été ajoutés pour la tache #775.

**Comment by lucaa** [comment]
La configuration vient d'être faite en production.

**Comment by AnthonyBrunelli** [comment]
@ugodtn ...ça te parle peut-être plus qu'à nous?

**Comment by AnthonyBrunelli** [comment]
(pour en parler en interne)

**Comment by lucaa** [comment]
@AnthonyBrunelli c'est pas clair pourquoi cette tache a été re-ouverte. Vue que le travail est fait et les modifications décrites dans la tache ont été installées en production, je préfère garder la tache fermée pour avoir un suivi correct de ce qui a été fait et ce qui est "à faire".
S'il y a un aspect de cette tache qui doit être rediscuté (pouvant ensuite avoir comme consequence une nouvelle modification du comportement en production), je préfère créer une tache séparée qui décrit l'aspect à discuter.

**Comment by AnthonyBrunelli** [comment]
Bon je ne sais plus ce que j'avais en tête. Je ferme @ugodtn @georges-bayard. Si on a une problématique sur le sujet on verra.
