### ISSUE TITLE
Regler le problème d'affichage des graphiques sur mobile page résultat		

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#346]
#319

**Comment by slauriere** [comment]
Ce problème a été réglé en imposant une hauteur fixe de 300 pixels aux diagrammes « Difficultés rencontrées » et « Aides sollicitées ». Je ferme le ticket, te laissant le rouvrir si besoin.

**Comment by JeanPerrier** [comment]
C'est bon mais autre bug graphique détecté
