### ISSUE TITLE
Ne pas afficher les graphiques pour les cas ou aucune difficulté n'a été signalé ou aucun aide n'a été utilisé

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#348]
e.g.  (pour demarche 1293): 
![image](https://user-images.githubusercontent.com/657716/49110807-bf167d00-f28e-11e8-8c64-9da297c1eb6e.png)

**Comment by lucaa** [comment]
à définir ce qu'on doit afficher pour ces cas:

- un message disant qu'il n'y a pas de donnée renseigné par les utilisateurs
- ne pas du tout afficher les sections
- autre?

**Comment by georges-bayard** [comment]
je penche pour "il n'y a pas de données renseignée par les utilisateurs"

**Comment by tetue** [comment]
L'option qui a été retenue pour ces pages est d'afficher mais avec l'information qu'il n'y a pas d'info => À la place des graphiques, indiquer « Aucune réponse » (tout simplement).

**Comment by slauriere** [comment]
Les diagrammes vides ont été remplacés par le message « Aucune réponse ». Cf exemple démarche numéro 3010 sur le site de développement.
