### ISSUE TITLE
Setup and create first version of the presentation of a demarche on the public site

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#35]
The displayed data for a demarche is filtered compared to the data displayed on the wikidemat wiki.
It's also supposed to contain the form for the evaluation, but this issue is only for the presentation of the demarches data (which is all we have so far).
see https://octo.invisionapp.com/share/5GJEA21KRSZ#/screens/299056713

**Comment by slauriere** [comment]
See also new version: https://octo.invisionapp.com/share/Q9K04GREAGS#/screens/300343270
