### ISSUE TITLE
Afficher 0 pourcent lorsqu'il y a aucun vote positif sur le tableau de bord de la dématérialisation.

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#354]

**Comment by JeanPerrier** [comment]
Lorsqu'il y a aucun vote positif, le taux affiché est "-".

**Comment by slauriere** [comment]
Tu veux dire qu'on devrait afficher "0" dans la colonne "Nombre d'avis" ? Et également "0" dans la colonne "Demandes de dématérialisation" lorsque la démarche n'est pas déjà disponible en ligne ? Quant au taux de satisfaction, est-ce qu'il ne vaut pas mieux laisser "-" tant qu'aucun avis n'a été soumis ? Sinon, "0 %" signifierait que personne n'est satisfait alors qu'en fait la réalité est que personne n'a voté, non ?

**Comment by JeanPerrier** [comment]
En fait pour expliciter mon propos, il existe des cas ou il y a des avis (négatifs et moyens) mais aucun positif. Dans ces cas, le taux de satisfaction affiché est "-". 
Bien entendu s'il y a 0 votes il faut afficher "-".

**Comment by slauriere** [comment]
Vu, merci pour la clarification. J'ai implémenté cela sur le site de développement, je vous laisse vérifier que cela vous convient, et rouvrir le ticket sinon.

**Comment by georges-bayard** [comment]
testé sur dev : je ne vois pas de correction. quand les avis sont tous négatifs ou neutres on a toujours "-" qui apparaît dans le niveau de satisfaction

**Comment by slauriere** [comment]
Attention je parle du site de dev, pas de celui de staging. Peux-tu me confirmer stp ?
