### ISSUE TITLE
Peut-être ajouter une liste de suggestions au champ "Démarche" du tableau de bord

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#356]
Actuellement le champ "Démarche" du tableau d'avis affiche une liste de suggestions lorsque l'utilisateur met le focus sur ce champ, mais pas le tableau de bord : c'est une aide à la recherche qui peut être utile, cela pourrait peut-être être intéressant de l'ajouter au tableau de bord.

**Comment by JeanPerrier** [comment]
Jean et GBA approuvent cette idée.

**Comment by JeanPerrier** [comment]
Effectivement ce n'est pas une issue importante.

**Comment by slauriere** [comment]
Ok. Je ferme ce ticket.
