### ISSUE TITLE
Le nom de démarche recherché n'est pas repris pour ajouter une démarche manquante

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#358]
Steps to reproduce:
1/ chercher une demarche, e.g. "embarquement pour la lune"
2/ cliquer "ajoutez une demarche" dans le suggest ou dans la liste de tous les résultats

Résultat attendu: 
"embarquement pour la lune" est repris sur "nom de la démarche"

Résultat courant:
le formulaire d'ajout de nouvelle démarche est vide

**Comment by slauriere** [comment]
Le paramètre passé à la page de création de démarche est à présent pris en compte pour pré-remplir le champ "nom de la démarche".

**Comment by lucaa** [comment]
Il semble que ce comportement n'est pas un bug, mais que ça a été demandé comme ça , dans ce commentaire https://github.com/DISIC/wikidemarches/issues/226#issuecomment-433022860 , par @tetue . 
Par contre, j'avoue que je ne comprends pas pourquoi on ne veut pas reprendre le texte recherché dans le nom de la nouvelle démarche créée, au lieu de demander à l'utilisateur de re-taper son nom de démarche. @tetue , tu peux clarifier?

**Comment by tetue** [comment]
Certes :)

Il y avait plusieurs raisons à cela : 
- Les mots que l'on saisit pour une recherche ne sont pas nécessairement le titre exact d'une démarche.
- D'une façon générale, un champ prérempli a plus de chance de passer inaperçu auprès de l'utilisateur (donc moins correctement rempli).
- La qualité des titres récoltés s'en ressentait alors négativement.

Ce peut être rediscuté.

**Comment by lucaa** [comment]
Oui, je comprends. Quand je l'ai vu hier pendant la démo (fait par @georges-bayard ), il m'a semblé vraiment embêtant que l'utilisateur doit re-taper le nom de démarche alors qu'il l'a déjà écrit une fois, dans la boite de recherche, mais j'entends les arguments de @tetue .

@georges-bayard , @JeanPerrier , avez vous des avis à ce sujet?

**Comment by tetue** [comment]
Idem, j'étais temporairement surprise lors de la démo d'hier (la force de l'habitude) mais me suis aussi rappelé que le préremplissage était également surprenant (« pourquoi je retrouve mes mots-clefs dans ce champ ? »). C'est discutable, testable… (mais mineur).
En tout cas, si le titre est prérempli, ne pas préremplir la description (comme c'était auparavant le cas).

**Comment by georges-bayard** [comment]
C est effectivement une régression à corriger

**Comment by slauriere** [comment]
Je ferme donc ce ticket : le champ "nom de la démarche" est de nouveau pré-rempli (site de dév), pas celui concernant la description.
