### ISSUE TITLE
Tableau de bord des démarches : ajouter un bouton d'export sur Excel

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#362]

**Comment by lucaa** [comment]
Il faut exposer le bouton d'export excel à tous les utilisateurs, à coté du bouton d'export csv.

**Comment by slauriere** [comment]
Un bouton d'export Excel a été ajouté. Néanmoins l'export semble poser des problèmes de performance au moins sur le serveur de développement (timeout lors d'un export Excel du tableau de bord complet) - > je crée le ticket #368 au sujet de l'étude de ce problèmes.
