### ISSUE TITLE
export du tableau de bord des démarches : ajouter les informations concernant la volumétrie

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#363]
Ajouter les données suivantes : 
- Volumétrie de la démarche Nombre total de démarches reçues par an
- Volumétrie de la dématérialisation
- Pourcentage de dématérialisation
- Niveau de la volumétrie

**Comment by lucaa** [comment]
@georges-bayard : vous avez fermé cette issue, elle n'est plus à faire?

**Comment by georges-bayard** [comment]
je pense que c'est une faute de frappe. c'est toujours dans le backlog

**Comment by slauriere** [comment]
Les champs indiqués ont été ajoutés à l'export du tableau de bord, formats CSV et Excel.

**Comment by georges-bayard** [comment]
NOK : toutes les données sans distinction sont exportées. Ne laisser que les données de volumétrie (+ éventuellement objet, champ ministériel, catégorie de public, public, évènement de vie, les 3 adresses web, niveau de dématérialisation, dématérialisation obligatoire. L'ajout n'était pas dans l'issue initial donc à n'oujouter que si cela ne prend pas de temps

**Comment by slauriere** [comment]
Le problème a été corrigé et les champs supplémentaires ont été ajoutés sur le site de développement pour le moment.
