### ISSUE TITLE
produire et stocker les informations qui permettent d'avoir une vision historisée des informations : démarche référencée, démarche dématérialisée, taux de satisfaction, nombre d'avis

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#364]

**Comment by lucaa** [comment]
Nous pouvons utiliser les informations suivantes:
* pour la date de referencement de la demarche: date de création du document de la démarche
* evolution du taux de satisfaction et le nombre d'avis: regroupement par la date de création de l'avis

* date de dematerialisation  de la demarche: il faut créer une information dans l'objet de cache sur une demarche pour stocker la date de modification du champ "niveau de dematerialisation" dans la demarche vers une valeur qui represente de la dematerialisation.

**Comment by slauriere** [comment]
En conséquence : 
- Créer un champ "dateDemat" dans la classe démarche pour stocker la date de dématérialisation.
- Cette date pourra être mise à jour soit lorsque la propriété "niveauDemat" est mise à jour, soit manuellement, soit programmatiquement.
- Il faut prévoir de modifier la date aussi bien lorsque la démarche passe du statut "non dématérialisée" au statut "dématérialisée" que dans l'autre sens (qui peut arriver en cas d'erreur de saisie).
- Il faut prévoir un script pour la mise à jour en batch des dates de dématérialisation des démarches existantes déjà dématérialisées, et définir la date de dématérialisation retenue pour celles-ci.
- Remarque technique : renommer l'extension "avis-stats" en "tools" car cette extension est amenée à contenir du code ne portant pas uniquement sur le cache de statistiques mais aussi sur d'autres opérations.

**Comment by slauriere** [comment]
Les actions suivantes ont été effectuées : 
- Ajout d'un champ "dateDemat"
- Mise à jour automatique de cette date quand une démarche est indiquée comme dématérialisée et que la date n'a pas déjà été indiquée par ailleurs
- Effacement de la date de dématérialisation quand une démarche est indiquée comme non dématérialisée

Il reste à : 
- Ecrire un script de mise à jour en masse des dates de dématérialisation des démarches dématérialisées existantes : #374
- Créer des diagrammes : #365

**Comment by georges-bayard** [comment]
une précision : la date de dématérialisation correspond par défaut à celle ou le niveau de dématérialisation passe soit à téléprocédure soit à formulaire en ligne. Même règle que pour l'activation de l'indicateur de dématérialisation oui/non

**Comment by slauriere** [comment]
Concernant les diagrammes : effectivement, ils sont bien en milestone M8, nous pensons juste en faire une première version de base pour s'assurer que nous stockons bien les données nécessaires à leur représentation sans avoir à faire de calculs trop lourds lors de la génération des diagrammes elle-même.

Critère de dématérialisation : nous utilisons le bien les niveaux téléprocédure et formulaire en ligne.

**Comment by JeanPerrier** [comment]
Je sais pas trop comment vérifier cette issue
