### ISSUE TITLE
produire adresses URL contenant des referer pour deux démarches du ministère de l'écologie

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#366]
Ces 2 démarches relatives à l'accessibilité des ERP sont implémentées dans démarches-simplifiées. Voici les lien :
https://nosdemarches.gouv.fr/Demarches/1799
https://nosdemarches.gouv.fr/Demarches/1800
Le nom à insérer dans le referer est "démarches-simplifiées"

**Comment by lucaa** [comment]
J'ai également crée une page de documentation de la fabrication de ces URLs, qui peut être envoyée aux intégrateurs: https://github.com/DISIC/wikidemarches/wiki/URL-de-formulaire-d'avis-(sp%C3%A9cifications) .

**Comment by lucaa** [comment]
Les 2 URLs sont:

https://nosdemarches.gouv.fr/Demarches/1799?nd_mode=en-ligne-enti%C3%A8rement&nd_source=d%C3%A9marches-simplifi%C3%A9es
https://nosdemarches.gouv.fr/Demarches/1800?nd_mode=en-ligne-enti%C3%A8rement&nd_source=d%C3%A9marches-simplifi%C3%A9es

**Comment by georges-bayard** [comment]
c'est normal que l'url soit remplie de signes non reconnus ? (%C3%A8....)
