### ISSUE TITLE
Création d'un script de mise en correspondance des démarches Nos Démarches avec les démarches Service Public

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#367]
Script d'appariement des démarches basé sur une recherche Solr. Je crée ce ticket juste pour suivi de l'historique du script en question et de ses modifications.

**Comment by slauriere** [comment]
Le script a été publié et utilisé pour un appariement.

**Comment by JeanPerrier** [comment]
Il faudra que tu m'expliques ce que c'est.

**Comment by slauriere** [comment]
Ce script est celui qui a permis la création du fichier Excel qui reliait des identifiants de démarches Nos Démarches avec des identifiants SP sur la base de la proximité des termes du titre.
