### ISSUE TITLE
Publication d'une nouvelle version de l'extension d'import en batch pour la mise à jour de la propriété "champs ministériels"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#369]
Une nouvelle version de l'extension BatchImport est nécessaire pour la mise à jour en batch de la propriété "champs ministériels" à partir du fichier qui sera fourni dans le cadre de #359. Ce ticket concerne la publication de cette extension et la mise à jour correspondante des instructions d'installation.

**Comment by slauriere** [comment]
La propriété "champs ministériels" n'étant plus présente (sous la forme définie ici) suite à #558, ce ticket peut être clos.

**Comment by lucaa** [comment]
Pour mon information, de quelle version de l'extension Batch Import parle cet issue? Si je comprends bien, l'import des champs ministeriels est un simple import de valeurs de liste multi-valuée , ce qui est une fonctionnalité du batch import de base. Quelle est la fonctionnalité supplémentaire de batch import qui était nécessaire pour l'import des champs ministeriels?

**Comment by slauriere** [comment]
La tâche est mal intitulée pardon : il s'agissait de publier et d'installer l'extension dblistidentifier-postprocessor car le fichier des champs ministériels qui était à importer contient des titres de documents, pas des identifiants.
