### ISSUE TITLE
Ajouter un onglet présentant le niveau d'évaluation Cerfa numérique

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#370]
Dans le cas d'une démarche dématérialisée, afficher un onglet supplémentaire indiquant le niveau d'évaluation de la démarche du point de vue du Cerfa numérique.

**Comment by slauriere** [comment]
Un onglet a été ajouté. Il est supposé que l'application de Cerfa numérique est installée dans un sous-wiki de la même ferme de wikis que celle de NosDémarches.

**Comment by lucaa** [comment]
L'onglet doit être affiché uniquement s'il y a des informations cerfa numérique pour la démarche.

**Comment by georges-bayard** [comment]
on peut tester cette issue sur quelle démarche ?

**Comment by slauriere** [comment]
L'exemple d'onglet Cerfa numérique est disponible sur le site de développement uniquement, à cette adresse : http://wikidemarches.devxwiki.com/Demarches/1289#cerfa-numerique-tab

L'intégration pour un déploiement en staging puis production nécessite encore 1) une finalisation du packaging des deux applications Nos Démarches et Cerfa ensemble, 2) une validation de tous. Du coup je rouvre ce ticket et je le déplace en M8 sauf si vous y voyez un inconvénient.

**Comment by slauriere** [comment]
Des modifications ont été faites dans les applications Nos Démarches et Cerfa numérique pour pouvoir fonctionner ensemble dans le même wiki avec le moins possible de dépendance. C'est surtout l'application Cerfa numérique qui repose sur l'application Nos Démarches. Cette dernière fait juste une vérification de la présence ou non de l'application Cerfa numérique pour afficher ou non l'onglet correspondant quand une évaluation existe.
