### ISSUE TITLE
Problème d'affichage des info-bulles

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#372]
Pour le cas des smileys dans le paragraphe « Détails des avis », les info-bulles ne s'affichent pas correctement, cf capture d'écran

**Comment by lucaa** [comment]
![selection_108](https://user-images.githubusercontent.com/657716/49729165-fc0e4680-fc74-11e8-8dcb-b516d98ac612.png)
![selection_109](https://user-images.githubusercontent.com/657716/49729169-fe70a080-fc74-11e8-9273-47fac94b7bdf.png)

**Comment by slauriere** [comment]
Le problème était lié à l'usage du plugin "datalabels-plugin" qui gère les polices différemment de la librairie cœur "chartjs". Il a été corrigé en mettant à jour l'extension "application-chartjs" ainsi que la page "DemarcheAvisStatisticsTab".

**Comment by slauriere** [comment]
Les instructions d'installation ont été mises à jour en conséquence, pour pointer vers la nouvelle version de l'extension "application-chartjs" : version 1.1.2.
