### ISSUE TITLE
Ajouter un nouveau role utlisateur , pour administrer un sous-wiki sans modifier les données du wiki nosdemarches

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#376]
Ce rôle est nécessaire pour implémenter des sous-wikis publiques de nosdemarches contenant des données qui ne sont pas publiques.

Ajouter un rôle "ministère" pour que des utilisateurs puissent s'identifier sans avoir le rôle "ministere". Aujourd'hui "ministere"="xwikall". 

Le rôle "xwikiall": 
* Sur Nos Démarches : aucun droit supplémentaire par rapport à guest
* Pourra avoir des rôles sous un sous-wiki (en pratique probablement deux autres sous-wikis)

Implémentation : 
* Créer le groupe "XWikiMinisteresGroup" (le laisser vide)
* Lister tous les droits existants et les mettre à jour en remplaçant "XWikiAllGroup" par "XWikiMinisteresGroup" (possibilité de faire une recherche sur les sources XML, utiliser et mettre à jour le tableau de droits existant ou la spécification). Il peut y avoir quelques différences : par exemple la visualisation des profils des utilisateurs. Le plus important : protéger les démarches, avis, référentiels. Vérifier où on utilise "isGuest".

**Comment by slauriere** [comment]
* Un script pour ajouter les utilisateurs existants au groupe 'Ministeres' a été ajouté.
* Deux tâches liées ont été créées : #394 et #395

**Comment by slauriere** [comment]
NB : les commits liés à cette tâche ont été squashés. Seuls les deux derniers ci-dessus sont pertinents.

**Comment by lucaa** [comment]
Note: Finalement, aprés implementation de #375, le groupe Ministeres ne sera pas rempli des la livraison de cette modification, mais sera synchronisé avec un groupe sur le serveur qui sera l'OpenId provider.
