### ISSUE TITLE
La recherche par ministère sur le tableau de bord ne fonctionne plus

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#378]
Suite à la résolution de #355, la recherche par ministère sur le tableau de bord ne fonctionne plus. La solution est de configurer le nombre de suggestions à la totalité des valeurs disponibles directement dans les sources xwiki (fichier "suggestPropertyValues.js"), à valider ensemble @lucaa et considérer une demande d'amélioration XWiki pour que ce paramètre puisse être calculé dynamiquement en fonction de différents élements de contexte (classe, propriété, nombre d'entrées total effectivement disponible).

NB : vérifier au passage pourquoi la recopie de "suggestPropertyValues.js" dans un JSX désactive le déclenchement du filtre concerné.

**Comment by lucaa** [comment]
Voir le commit log pour l'explication sur la source du problème et la solution choisie.
