### ISSUE TITLE
Supprimer des champs dans le référentiel des démarches

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#384]
Champs à supprimer:

- Identifiants ELI
- Référence BDDFORM
- Nom

Champs à supprimer? 
- Adresse web de documentation de la démarche à fusionner avec Adresse web de la démarche -> Adresse de documentation de la démarche ou adresse web de la démarche. 
- Dématérialisation  obligatoire -> indiquer téléprocédure obligatoire dans Niveau de   dématérialisation prévu
-Caractéristiques prévues de la dématérialisation? 

--

**Comment by georges-bayard** [comment]
Ok pour identifiant ELI et Référence BDDFORM

De : JeanPerrier [mailto:notifications@github.com]
Envoyé : jeudi 20 décembre 2018 15:48
À : DISIC/wikidemarches <wikidemarches@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [DISIC/wikidemarches] Supprimer des champs dans le référentiel des démarches (#384)


Champs à supprimer:

  *   Identifiants ELI
  *   Référence BDDFORM
  *   Nom

Champs à supprimer?

  *   Adresse web de documentation de la démarche à fusionner avec Adresse web de la démarche -> Adresse de documentation de la démarche ou adresse web de la démarche.
  *   Dématérialisation obligatoire -> indiquer téléprocédure obligatoire dans Niveau de dématérialisation prévu
-Caractéristiques prévues de la dématérialisation?

--

**Comment by JeanPerrier** [comment]
GBA: supprimer aussi le champ "titre de la page"

**Comment by JeanPerrier** [comment]
Voici les champs à supprimer:

    Identifiants ELI
    Référence BDDFORM
    Titre de la page
    Niveau de la volumétrie
    Adresse web de documentation de la démarche
    Caractéristiques prévues de la dématérialisation
    Niveau de dématérialisation prévu

**Comment by JeanPerrier** [comment]
De plus le champ "champs ministériel(s)" doit être caché avant suppression éventuelle

**Comment by slauriere** [comment]
Les modifications indiquées dans cette tâche ont été apportées dans le cadre de #549 -> je ferme ce ticket en le marquant comme étant un doublon.
