### ISSUE TITLE
Modification des infos dans téléchargement excel des démarches

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#385]
Supprimer "démarches." avant le numéro de démarches dans la colonne "référence".
Mettre l'ensemble de l'URL dans la colonne URL et pas seulement "/Demarches/830"

**Comment by slauriere** [comment]
L'identifiant de démarche ne contient plus à présent le préfixe "Demarches." sur le site de développement uniquement pour le moment. L'URL reste relative, nous étudions ce point.

**Comment by lucaa** [comment]
La modification de l'affichage de la reference de la démarche a été faite pour l'export des demarches dans le tableau de bord (#389) mais pas dans l'export complet des demarches du backend.
Pour les URLs une nouvelle tache a été crée ( #388 ).

**Comment by JeanPerrier** [comment]
J'avais bien demandé pour le backoffice seulement.

**Comment by slauriere** [comment]
Dans le cadre de #563, la colonne "Référence / identifiant" n'est pas présente à l'export -> cette tâche n'a plus lieu d'être pour l'instant en tout cas, je la clos et vous laisse la rouvrir si besoin.
