### ISSUE TITLE
problème d'affichage des graphiques sur mobile page résultat

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#386]
![image](https://user-images.githubusercontent.com/17125654/50304085-52f2f780-048f-11e9-9564-6060a34991fc.png)

**Comment by georges-bayard** [comment]
non reproductible quand l'image est réduite sur un pc

**Comment by slauriere** [comment]
Je pense que c'est peut-être juste un problème de cache car en principe ce bug avait été résolu en #319 et entre temps les couleurs des barres sont passées de gris à mauve. Peux-tu essayer de rafraîchir la page sur tél pour voir ce que ça donne ?  Cf exemple de rendu petite largeur de mon côté : 

![charts](https://user-images.githubusercontent.com/1022195/50333560-08f92880-0506-11e9-94b2-bd2545070598.jpg)

**Comment by georges-bayard** [comment]
Re testé sur mon mobile et le problème ne se pose plus. Je clôture et valide
