### ISSUE TITLE
Mise en place des droits associés au groupe 'Ministeres' sur le site de production

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#394]
Suite à l'implémentation de #376, les tâches suivantes devront être exécutées sur le site de production : 
* Exécuter le script d'ajout des utilisateurs existants au groupe Ministeres. (cf espace 'Administration')
* Pages XWiki.Groups et descendantes : réaffectation du droit "voir" du groupe XWikiAllGroup au groupe Ministeres.
* Page XWiki.XWikiAdminGroup: "view, edit" pour XWikiAdminGroup, supprimer le droit "view" attribué à XWikiAllGroup (vérifier pourquoi il y avait ce droit)
* NB: les membres de XWikiAllGroup restent autorisés à voir les profils utilisateurs

**Comment by lucaa** [comment]
Des modifications supplémentaires ont été apportées à l'implementation de #376 , ainsi:

- les droits d'accès à XWiki.Groups et XWikiAdminGroup ne changent plus (restent à XWikiAllGroup), donc les point 2 et 3 ne sont plus à faire

Le groupe Ministeres sera peuplé automatiquement à l'authentification avec Open Id (#375), donc il ne sera pas à remplir automatiquement lors du déploiement, donc le premièr point n'est pas à éxecuter non plus.

En consequence, je marque cette tache comme "won't fix" et je la cloture.

**Comment by lucaa** [comment]
Finalement, comme OpenId ne sera plus deployé en production, il faut prévoir la migration des utilisaterus existants dans le groupe AdministrateursMinisteriels (Ministeres).

Voir #411 et #444.

**Comment by lucaa** [comment]
@slauriere tu peux vérifier, s'il te plaît, le fait que le script d'ajout des utilisateurs existants au groupe administrateurs ministeriels

1. a été mis à jour lors du renommage du groupe
1. dans les instructions d'installation de la version 3, il y a une note qui indique l'execution du script lors du deployement.

**Comment by lucaa** [comment]
> a été mis à jour lors du renommage du groupe

Pas besoin, tellement le script est générique :+1: 

> dans les instructions d'installation de la version 3, il y a une note qui indique l'execution du script lors du deployement.

Les instructions ont été ajoutées ici https://github.com/DISIC/wikidemarches/wiki/Installation-instructions-v-3.x#user-content-migration-from-2x-to-3x .
