### ISSUE TITLE
Mise à jour de la spécification complète des droits d'accès

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#395]
L'implémentation de #376 a donné lieu à une vérification des droits sur l'ensemble du wiki. Les droits d'accès avaient été spécifiés dans un premier temps dans le cadre de #169, et cette spécification avait évolué depuis. Une page de synthèse a été créée sur le wiki XWiki SAS interne. Celle-ci reste à être complétée, (re)validée (e.g. droit de suppression des démarches), et implémentée / vérifiée sur le site de production.

NB : il reste à voir sous quelle forme implémenter les restrictions de droits sur certaines extensions qui ne font pas partie de la production, comme les extensions utilisées pour l'import (e.g. BatchImport, FarmTools) : soit elles doivent être désinstallées après chaque utilisation, soit elles doivent être protégées explicitement.

**Comment by georges-bayard** [comment]
@slauriere  : quand doit on planifier l'information des utilisateurs sur le changement des comptes ?

**Comment by lucaa** [comment]
Entre temps la spécification de droits a été clarifié pour #428 et #528. Je marque cette tache comme faite.

Par rapport à:

> quand doit on planifier l'information des utilisateurs sur le changement des comptes ?

Effectivement, cette notification doit être faite lors de la livraison en production du changement, mais ce changement a été annulé depuis, voir #411 . 

Je ferme cette tache comme faite, suite aux précisions des droits d'accès faites pour #428 et #528.
