### ISSUE TITLE
Mise à jour du pied de page

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#400]
Ticket ajouté suite à discussion Cerfa numérique / Nos Démarches  (convergence). 

Dans le pied de page : 
* Ajouter le plan du site.
* Remplacer "Identification" par "Connexion".
* Supprimer "Réseau".
* Ajouter en premier dans la liste des sites "numerique.gouv.fr"

**Comment by lucaa** [comment]
@slauriere : peux-tu vérifier que cette issue est toujours d'actualité suite aux modifications faites lors de la M11?

**Comment by slauriere** [comment]
Les points mentionnés dans la description de cette tâche ont été implémentées -> je clos ce ticket.
