### ISSUE TITLE
Revenir au calcul de taux de satisfaction avec 50% de satisfaction compté pour les avis "moyens"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#404]
Il s'agit de de-faire #304 .

**Comment by slauriere** [comment]
Le taux de satisfaction est à présent de nouveau calculé comme étant la moyenne des avis entre 0 et 2 rapportée à une échelle de 100. Le calcul de la moyenne de toutes les démarches a été relancé sur le site de développement depuis la page AvisStatsManager. Je clos le ticket, je te / vous laisse le rouvrir si vous constatez une erreur.

**Comment by slauriere** [comment]
La page indiquant la façon dont le taux de satisfaction est calculée a été mise à jour en conséquence.

**Comment by slauriere** [comment]
Instructions pour déploiement en production : 
- Compile version deb07d5
- Stop Tomcat
- Remove jar "avis-stats-manager" from WEB-INF/lib (or "tools-api" depending on the exact version in production)
- Deploy "extensions/tools/tools-api/target/tools-api-2.5-SNAPSHOT.jar" to WEB-INF/lib/
- Start Tomcat
- Download the attached zip, rename it to a xar and import it to the main wiki.
- Go the the LoggingAdmin page, set log level to DEBUG for the wikidemarches sub-packages
- Head to AvisStatsManager and launch the recalculation of all AvisStats objects. Refer to the Tomcat log to check the process is over.

[190121-nos-demarches-404.zip](https://github.com/DISIC/wikidemarches/files/2779886/190121-nos-demarches-404.zip)

**Comment by lucaa** [comment]
Les modifications ont été faites en production, telles que décrites par @slauriere , avec une petite modification:
* le zip en pièce jointe n'a pas été deployé tel quel, les pages Avis.Code.AvisStatsClass et Main.Satisfaction ont été importées à partir d'un build de master au deb07d5
* la page Demarches.Code.DemarcheAvissStatisticsTab a été modifiée manuellement
