### ISSUE TITLE
Modifier l'ordonnancement des colonnes dans les exports (surtout excel)

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#405]

**Comment by JeanPerrier** [comment]
**Mettre les colonnes dans l'ordre comme dans l'exemple qui suit:**
- Référence (sans le "Démarches."), Nom, Nom complet, Ministères, champ(s) ministériel (s), Direction ou établissement, Groupe, Organismes de traitement, Objet
- Catégorie de publics concernés, Publics, Événement de vie, Formulaire CERFA, Référence Service Public, Adresse web informations, Adresse web de la démarche, Adresse web de documentation de la démarche
- Niveau de dématérialisation actuel, Démarche dématérialisée Oui/Non, Volumétrie de la démarche, Volumétrie de la dématérialisation, Pourcentage de dématérialisation, Dématérialisation obligatoire, Démarche exclue du SVE, Caractéristiques de la dématérialisation
- Statut du projet de dématérialisation, Niveau de dématérialisation prévu, Caractéristiques prévues de la dématérialisation, Nom du projet de dématérialisation, Date de mise en ligne
- Textes de référence, Statut de la démarche, Remarques, URL de la démarche (uniquement si l'URL est en entier).

**Supprimer de l'export les colonnes suivantes:**
- Date de création si c'est seulement une info technique
- Identifiant ELI


**Modifier les intitulés des noms colonnes suivants:**
- Adresse web de documentation de la démarche -> adresse web téléchargement formulaire
- Demarches.Code.DemarchesClass_niveauDematBoolean -> Démarche dématérialisée Oui/Non

### Question: D'ou vient la colonne "Date de dématérialisation"? il faudrait supprimer cette colonne qui ne comprend pas de données à ce jour.

**Comment by JeanPerrier** [comment]
Supprimer également la colonne titre de la page

**Comment by slauriere** [comment]
Le réordonnancement des colonnes du fichier exporté a été traité dans le cadre de #563 -> je marque cette tâche comme doublon et je la clos.
