### ISSUE TITLE
Phrase incorrecte dans les CGU

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#408]
>Vous ne pouvez en tant qu’usager ou accompagnant évaluer qu’une seule fois la démarche, quand vous l’avez accomplie ou que vous avez essayé de l’accompliren êtes arrivé à son terme [vu qu’on tient compte de cette possibilité]. 

https://nosdemarches.gouv.fr/Main/CGU

**Comment by JeanPerrier** [comment]
Peux-tu expliquer plus précisément ce qui est incorrect? (à part que la phrase est très mal construite grammaticalement)

**Comment by slauriere** [comment]
Bonjour Jean, C'est la fin de la phrase qui me semble assez inattendue – j'imagine qu'il manque peut-être un « ou que vous » entre « accomplir » et « en » et qu'il faut supprimer ce qui est entre crochets ?

>ou que vous avez essayé de l’accompliren êtes arrivé à son terme [vu qu’on tient compte de cette possibilité].

**Comment by JeanPerrier** [comment]
J'ai modifié le texte sur les CGU du staging M8. #511

**Comment by lucaa** [comment]
Je re-ouvre pour ne pas oublier de mettre à jour le fichier dans les sources à partir du staging, sinon il ne sera pas deployé sur la prod.

**Comment by lucaa** [comment]
Fait.
