### ISSUE TITLE
permettre aux utilisateurs de démarches simplifiées de voter pour la démarche sur nosdémarches

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#409]

**Comment by lucaa** [comment]
@georges-bayard il n'est pas clair pour moi si cette tâche est toujours d'actualité (si l'intégration a été faite avec DS ou pas) et qu'est-ce qu'il y a éffectivement à faire du côte de observatoire.numerique pour cette tache...

**Comment by georges-bayard** [comment]
plus d'actualité. c'est DS qui a mis en place une mécanique d'injection du bouton simplifiée à la main des administrateurs fonctions
