### ISSUE TITLE
Utilisation de la macro livetable exporter

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#410]
Ticket technique : ce ticket concerne le remplacement de la macro d'export Excel par la macro plus récente "livetable exporter" : cela facilitera la maintenance du site.

**Comment by slauriere** [comment]
L'usage de la macro d'export a été mis à jour.

**Comment by lucaa** [comment]
@slauriere est-ce que le module https://github.com/DISIC/wikidemarches/tree/master/extensions/macro-livetable-excel-export est toujours nécessaire ? Sinon, est-il possible de reouvrir cette issue et l'enlever ?

**Comment by slauriere** [comment]
J'avais oublié cela effectivement, je rouvre cette issue.

**Comment by slauriere** [comment]
Le module a bien été supprimé, et les installations d'instruction sont à jour, je ferme ce ticket.
