### ISSUE TITLE
Refactoring des onglets de la démarche: création de l'onglet "embed"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#412]
Voir les spécifications sur le wiki dinsic pour qui doit voir cet onglet.

**Comment by slauriere** [comment]
Un onglet a été "Embed" a été créé. Il n'est affiché que pour les propriétaires de la démarche courante. La notion de propriétaire de démarche a été implémentée temporairement comme un groupe de la forme "XWiki.Groups.ProprietairesDeDemarche.1127", en attendant que #434 soit implémenté, en considérant pour le moment que tout propriétaire de démarche est aussi nécessairement un administrateur ministériel. Le fonctionnement par vérification de sous-groupe n'est pas fonctionnel dans cette implémentation : un propriétaire de démarche doit être un membre direct du groupe des administrateurs ministériels. Je clos cette issue en en créant une nouvelle concernant la mise à jour des droits d'accès à l'onglet d'embed une fois que #434 sera implémenté: #440.
