### ISSUE TITLE
Refactoring des onglets de la démarche: cacher les onglets "avis" & "avis stats"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#413]
Sauf pour les utilisateurs qui ont le droit de voir ces onglets. 
Voir les droits dans la spéc du wiki dinsic.

**Comment by slauriere** [comment]
La modification suivante a été apportée dans la page "DemarchesSheet" : "restrict the avis statistics tab to ministeres and admin groups (the tab containing the list of avis was already restricted to those groups)". Les pages contenant le code des onglets eux-mêmes (eg DemarcheAviStatsTab) restent publiques sans que cela ne pose de problème de sécurité puisque pour afficher des données, elles doivent être exécutées avec un paramètre devant être présent dans le contexte Velocity courant.

Des tests ont été effectués avec trois profils : 
- Utilisateur anonyme
- Utilisateur "AdministrateurMinisteriel"
- Utilisateur "AdministrateurDinsic"
