### ISSUE TITLE
Enlever tous les liens de la page de vote

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#415]
Lié au #414, rendra la page de vote "finale" (sans possibilité d'avancer).
Il faut enlever les liens emmenant à la page d'accueil ou d'autres pages du site sauf: déclaration d'accessibilité, contact, CGU (qui sont quasi obligatoires).
Notamment, sur la page de remerciement pour le vote, on avait un lien vers la page d'accueil pour inciter le vote sur d'autres démarches, il faut l'enlever.

**Comment by slauriere** [comment]
Le lien incitant à donner son avis sur d'autres démarches a été supprimé. Dans le pied de page, le lien vers la page d'à propos a été supprimé, celui vers la page d'identification a été conservé, à voir. Il reste à décider ce qu'on fait avec le lien présent dans la bannière du site.

**Comment by slauriere** [comment]
Du point de vue implémentation : il faut que le mode d'affichage soit un paramètre disponible au niveau du contexte, pour que toutes les zones puissent être adaptées (pied de page, bannière etc.). Par ailleurs en mode "formulaire" ou "cerfa-numerique", le lien vers la bannière doit être supprimé.

**Comment by slauriere** [comment]
Actions effectuées : 
- Add two global variables: "displayAvisFormOnly" and "displayCerfaNumeriqueOnly"
- Customize the banner link accordingly
- Hide some links of the footer accordingly

**Comment by JeanPerrier** [comment]
Il faut supprimer aussi le lien de la page de vote

**Comment by lucaa** [comment]
J'ai corrigé le code qui enlevé le lien du logo, et je l'ai amélioré un peu aussi : au lieu de faire un lien vers #, j'ai mis un element <span au lieu du element <a , pour les cas ou il doit pas y avoir de lien.
