### ISSUE TITLE
Eliminer la 3 étape du form de vote: demande d'email

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#416]
Il s'agit de dé-faire #247 .

**Comment by lucaa** [comment]
Il reste une question à répondre (@georges-bayard , @JeanPerrier ): pouvons nous renoncer à cette information (n'est pas nécessaire aux intégrations existantes ?)

**Comment by JeanPerrier** [comment]
Je ne comprends pas ta question, tu m'envoies ton numéro par mail?

**Comment by JeanPerrier** [comment]
Pour l'instant, on l'enlève pour tous les questionnaires. Il faut parcontre garder la page sous la main si jamais on arrive à regagner l'arbitrage.

**Comment by slauriere** [comment]
L'étape de demande d'adresse e-mail a été supprimée, elle pourra être restaurée facilement à partir de l'historique des modifications de code associé à ce ticket.
