### ISSUE TITLE
Vérifier et stocker la clé d'API pour l'ajout d'un avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#419]
Voir #417 et #418.
Cette tache est pour les modifications au formulaire d'avis pour ne pas enregistrer un avis si une clé d'API valide n'est pas fournies dans le formulaire d'avis (ou dans les données envoyées au script de sauvegarde).

Possibilités d'implémentation (à décider entre les 2):
* recherche dans toutes les clés des utilisateurs à chaque sauvegarde d'avis pour valider la clé
* à chaque fois qu'un utilisateur demande le code pour le bouton / embed, on stocke dans la démarche en question le type de bouton / embed qui a été demandé et par quelle clé. Ainsi, on peut faire la vérification de la validité de la clé directement avec les méta données de la démarche (plus rapide) et on peut afficher aux utilisateurs un onglet d'embed contextuel. Par contre, on peut avoir un pb d'accès à l'information (visibilité).

**Comment by slauriere** [comment]
Il me semble que la deuxième option a plutôt des avantages : meilleure performance, et concernant la protection des informations, on pourrait stocker la clef et la modalité d'intégration dans une page d'administration distincte de celle de la démarche, par exemple "administration.demarches.1289", en accès restreint ?

**Comment by slauriere** [comment]
Proposition : 
- Créer une classe Demarches/Code/EmbedClass avec deux propriétés : liste statique "type" pouvant prendre les valeurs "embed" ou "bouton"; champ texte "key" destiné à stocker la clef d'API.
- Stocker ces objets dans des pages de type "Demarches/Admin/Embed/1289" contenant l'identifiant de la démarche concernée.

**Comment by lucaa** [comment]
Oui, la deuxième option a été choisie, mais pas encore implementée, voir le commentaire sur #417 https://github.com/DISIC/wikidemarches/issues/417#issuecomment-466078762 , mais pas encore implémentée.

**Comment by lucaa** [comment]
So, l'implementation du #417 a été faite, en utilisant les suivants:
* API.Code.EmbedClass pour la classe qui stocke les codes générés, sans type d'embed - uniquement la clé est stockée, pour l'instant (dans le futur, l'idée est de pouvoir stocker également des informations sur la configuration de l'embed).
* les documents sont stockés sous Demarches.Embed.<numéro de démarche>, avec acces uniquement aux admins (donc il faut recuperer le document avec getDocumentAsAuthor() - voir EmbedTab pour un bout de code qui manipule ces clés.

**Comment by lucaa** [comment]
Note: pour la performance, il est important de charger la page avec la clé API du cache (av. getDocument()) et ne pas faire une requete à la base de données.
D'ailleurs, toute cette vérification (et en général le code de stockage d'avis) devrait être assez efficace (voir aussi #438).

**Comment by slauriere** [comment]
Une macro de vérification de la validité de la clef d'API fournie par URL a été ajoutée. La validité de cette clef est vérifiée d'une part pour l'affichage du formulaire d'avis, d'autre part pour les stockage d'un nouvel avis.
