### ISSUE TITLE
Fournir le code du bouton monavis aux utilisateurs

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#420]
Sur l'onglet "Embed" (#412) il y aura 2 morceaux de code: le bouton et l'embed. Cette tache est pour l'implémentation du bouton.

Les éléments graphiques restent à spécifier mais le code (l'URL du bouton vers le formulaire d'avis) peut être préparé.

**Comment by lucaa** [comment]
Note: ne pas afficher le code du bouton pour les démarches avec une volumétrie trop importante.

**Comment by lucaa** [comment]
@JeanPerrier nous avons reçu 2 images, une avec un bouton blanc et une avec un bouton bleu. On sait laquelle est l'image qui sera gardée?

**Comment by JeanPerrier** [comment]
Si j'ai bien compris, on laisse la possibilité de choisir l'un des deux boutons en fonction des couleurs d'arrière-plan. Je pensais que Georges t'en avait parlé.

**Comment by lucaa** [comment]
@JeanPerrier non, il m'en avait pas parlé.

**Comment by lucaa** [comment]
aussi, a-t-on une indication de la taille de ce bouton ? Sinon je le mets a 1.5em  ou 2em (ce qui veut dire qu'il sera calculé en fonction de la taille du texte du context dans lequel il est intégré)

**Comment by lucaa** [comment]
J'ai mis le bouton a 3.8 em finalement, ça donne ça (pour un text autour qui est à la taille de 1em):

![image](https://user-images.githubusercontent.com/657716/53431142-396eae80-39f0-11e9-9f75-a098db58b06c.png)

**Comment by JeanPerrier** [comment]
ça m'a l'air bien comme taile

**Comment by lucaa** [comment]
Je ferme cette tache maintenant car le code est disponible, il reste #476 et #485 comme taches liées.

**Comment by JeanPerrier** [comment]
J'ai essayé de copier le code d'un bouton dans un email et je me le suis envoyé à moi-même. Le bouton ne s'affiche pas.
