### ISSUE TITLE
Demander l'authentification sur la page d'accueil

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#422]
Pour les utilisateurs qui ne sont pas connectés, la page d'accueil doit fournir une explication de l'outil et afficher un formulaire de connexion.
Dans le futur, un lien vers la possibilité de s'inscrire sera fourni, pour les utilisateurs n'ayant pas de compte.

Pour les utilisateurs connectés, la page d'accueil reste la même qu'aujourd'hui, donnant accès à la recherche et au tableau de bord (si droits - voir #423).

**Comment by slauriere** [comment]
Serait-ce ok si la page d'accueil est restreinte en visualisation, et que la page d'authentification par défaut affiche le message explicatif ?

**Comment by lucaa** [comment]
effectivement, c'est une idée qui peut marcher tres bien. J'hésite, ça dépend vraiment de ce qu'on veut afficher sur cet écran, et, j'imagine, un peu de #424 aussi, pour la réutilisation de l'écran explicatif. 
Commençons avec une protéction des droits d'accès, makes sense.

**Comment by slauriere** [comment]
L'accès à la page d'accueil a été restreint en lecture à XWikiAllGroup.

**Comment by JeanPerrier** [comment]
#507
