### ISSUE TITLE
Rendre le tableau de bord accessible uniquement aux administrateurs ministériels

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#423]
En attendant sa nouvelle version, le tableau de bord devient privé (accessible uniquement aux utilisateurs ayant le droit de voir les informations sur les avis).
Le lien de la page d'accueil doit également être mis à jour.

**Comment by georges-bayard** [comment]
Nadi Bou Hanna nous demande de remettre en place ce mode de fonctionnement : le tableau de bord ne doit être accessible que pour les administrateurs ministériels

**Comment by lucaa** [comment]
@georges-bayard comme cette tache a été faite (et dé-faite entre temps par #528), je préfère ne pas re-ouvrir la tache si on a besoin de ré-faire les modifications. Je réserve la ré-ouverture d'une tache pour le cas ou la tache n'a pas vraiment être faite, ou a été fermée trop tôt, et l’implémentation est incomplète.
Cela permet également d'encadrer correctement les versions (car maintenant cette tache devrait avoir et M8 et M9 comme version, car elle sera faite 2 fois).
Je vais donc refermer cette tache comme faite dans M8 et ouvrir une autre pour la M9, comme on a fait pour toutes les taches de modification d'accès.

**Comment by lucaa** [comment]
> Je vais donc refermer cette tache comme faite dans M8 et ouvrir une autre pour la M9 .

La tache pour M8.1 + est ici: #570 . La discussion sera continuée sur #570.
