### ISSUE TITLE
Proposer l'authentification aux utilisateurs sur la page de la demarche, s'ils arrivent non-authentifiés

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#424]
Suite aux taches de refactoring des onglets et surtout à la modification pour #414, la page de la démarche ne va rien afficher pour un utilisateur non-identifié.
Elle doit afficher un message proposant l'authentification de l'utilisateur (comme la page d'accueil pour #422 ).

**Comment by slauriere** [comment]
Si la page de la démarche n'affiche rien ou peu de chose, peut-on éventuellement directement rediriger vers la page d'authentification avec des informations explicatives (comme pour la page d'accueil) ? (ou peut-être dans un premier temps ?)

**Comment by lucaa** [comment]
Pour le scénario "Parcours de recherche de référence de démarche pour cerfa numérique" (voir le document de specs), je pense qu'il faut afficher un ecran de login ou un message disant qu'il n'y a pas d'action possible sans se connecter, mais en laissant les détails de la démarche et le nom de la démarche.

Par contre, mets en stand-by, il y a un risque que le scénario "Parcours de recherche de référence de démarche pour cerfa numérique" change un peu demain.

**Comment by slauriere** [comment]
J'ai implémenté quelque chose malgré moi et malgré ton commentaire (désolé), en même temps que l'ajout d'un message d'information sur la nécessité de se connecter. Peut-être que cela pourra malgré tout servir de support à la discussion ? En tout cas ce sera facile à défaire.

**Comment by lucaa** [comment]
It's ok, le scénario "Parcours de recherche de référence de démarche pour cerfa numérique" n'a pas changé. Juste un détail d'affichage de cet écran a changé, voir #450.

**Comment by JeanPerrier** [comment]
Parcours de recherche de référence de démarche pour cerfa numérique 
On ne sait pas retrouver ce parcours . Rappel possibilité de rechercher des démarches et de voir le numéro de référence de ces démarches.

**Comment by JeanPerrier** [comment]
#428
