### ISSUE TITLE
Nouveau formulaire d'ajout de démarche manquante

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#426]
Le formulaire d'ajout de démarche manquante, désormais accessible uniquement aux utilisateurs connectés (#425), doit être completé pour récuperer un peu plus d'informations.

Voir le document de spécifications pour des détails sur ce que la page doit contenir.

**Comment by lucaa** [comment]
Les démarches ajoutées seront toujours en état "demande d'ajout utilisateur", mais sans les marqueurs visuels d'aujourd'hui (voir #453 ).

**Comment by JeanPerrier** [comment]
Vois les champs à remplir lors de l'ajout d'une démarche:
-     Nom de la démarche
·        Ministère(s)
·        Direction ou établissement
·        Catégories de publics concernés
·        Formulaires CERFA associé
·        Commentaire
·        Champ de la démarche (nationale/locale) è à créer à terme
·        Organisme de traitement
·        Adresse web de la démarche
·        Adresse web de documentation de la démarche (sur Service Public)
Identifiant R

**Comment by slauriere** [comment]
NB suite à discussion avec Anca : peut-être également demander la volumétrie ?

**Comment by JeanPerrier** [comment]
On peut ajouter la volumétrie effectivement.
A moyen terme se pose la question de comment "classer" ces informations en terme d'importance et de priorité.

**Comment by slauriere** [comment]
Ok Jean vu, merci. 

Anca : peut-être pourrait-on directement afficher le formulaire par défaut de création de démarche (plutôt qu'une page à part), juste en masquant certains champs, et en en profitant pour créer le nouveau champ "national" / "local" ?

**Comment by JeanPerrier** [comment]
Effectivement à court c'est peut être plus simple pour vous comme cela.

**Comment by slauriere** [comment]
Après réutilisation avec Anca : nous allons réutiliser au maximum le formulaire existant, mais avec un mécanisme de sauvegarde dédié, qui permettra de définir au moment de la sauvegarde des actions particulières éventuelles (positionner l'utilisateur directement comme porteur de démarche, etc.).

**Comment by slauriere** [comment]
Le nouveau formulaire a été implémenté tel que décrit (en principe), avec ajout de l'utilisateur courant comme porteur de démarche. Une nouvelle propriété "Champ de la démarche" a été ajoutée. Les champs soumis ne sont pas validés individuellement, cela fait l'objet d'un autre ticket : #461

**Comment by georges-bayard** [comment]
nok ; cf mes remarques sur le ticket #461

**Comment by lucaa** [comment]
cf. commentaire sur #461 .

> Le champ suivants doit être supprimé : Référence BDD Form

Il y aura aussi #472 à faire.

**Comment by lucaa** [comment]
> Le champ suivants doit être supprimé : Référence BDD Form

Fait!
