### ISSUE TITLE
Bloquer l'indexation du site par les moteurs de recherche 

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#427]
robots.txt qui bloque tout.

à decider: la page d'accueil doit être indexée ou pas?

**Comment by lucaa** [comment]
Le fichier est là : https://github.com/DISIC/wikidemarches/blob/master/web/robots-public.txt , doit être mis à jour.

**Comment by lucaa** [comment]
> à decider: la page d'accueil doit être indexée ou pas?

Tout a été restrictionné, la page d'accueil renvoie un code HTTP 401, donc très probablement elle ne sera pas indexée de toute manière.

**Comment by georges-bayard** [comment]
Je comprends que NosDémarches renverra sur une page http401 ? Il faudrait plutôt renvoyer sur la page MonAvis non ?

**Comment by JeanPerrier** [comment]
@lucaa ?

**Comment by lucaa** [comment]
Les 2 envoient sur la même page, qui est la page d'accueil de monavis .
Cette page d'accueil est envoyé avec un code http 401, car elle demande l'authentification. Ceci n’empêche pas l'affichage de notre formulaire d'authentification personnalisé, avec le texte explicatif et tout. Sauf que le code http qui est envoyé avec ce formulaire d'authentification est un code 401 et non pas un code 200. 

La discussion était lié au fait de laisser ou pas les moteurs de recherche indexer cette page d'accueil. Ça peut être intéressant de permettre l'indexation de la page d'accueil mais de rien d'autre, sauf que, comme elle renvoie un code http 401, elle ne sera probablement pas prise en compte par les moteurs de recherche.
On peut modifier la page pour envoyer un code http 200 tout en gardant le formulaire d'authentification, mais cette modification sera plus longue à faire (pour M8). On peut planifier cela pour la M9.
Pour moi il n'est pas forcement nécessaire que le site monavis.numerique.gouv.fr soit retrouvable par les moteurs de recherche. A-t-on une directive contraire?

**Comment by JeanPerrier** [comment]
Non rien doit être indexé. Faites au plus simple du point de vue technique

**Comment by georges-bayard** [comment]
après réflexion avec Jean si ce n'est pas trop consommateur de ressource ce serait tout de même bien que la page d'accueil MonAvis soit indexée. C'est en effet un réflexe naturel de taper "MonAvis" dans un moteur de recherche plutôt que de taper le nom entier monavis.numerique.gouv.fr

**Comment by lucaa** [comment]
ok, je note (et je crée une issue séparée). 
Par contre, même si la page d'accueil est indexable, ce n'est pas pour autant que ça sera le premier résultat de google pour une recherche du mot clé "MonAvis", car c'est très générique. On va essayer, pour voir.
