### ISSUE TITLE
Re-valider le nouveau schema de droits

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#428]
Voir les spécifications pour le tableau de droits.

Image de la version du 26/02/2019:
![image](https://user-images.githubusercontent.com/657716/53399189-c04d6800-39ab-11e9-8470-81923506c760.png)

**Comment by slauriere** [comment]
Une question : est-ce qu'il le tableau ne gagnerait pas en lisibilité si on plaçait le libellé "Propriétaire de démarche" en tant que rôle (donc en ligne), plutôt qu'en colonne ? Par ailleurs, il pourrait être éventuellement plus clair d'indiquer pour ce rôle que ses droits sur une démarche sont les même que ceux d'un administrateur ministériel, sauf qu'il ne peut pas créer de nouvelle démarche, supprimer de démarche, et que les notifications sont différentes (je veux dire : factoriser ce qui est factorisable, pour répercuter la factorisation dans le code) ?

**Comment by lucaa** [comment]
Par rapport à l'affichage du propriétaire sur une ligne séparée, c'était comme ça au début mais toutes les autres lignes étaient copiés du "utilisateur connecté" (car le propriétaire n'est rien d'autre qu'un utilisateur connecté avec des droits sur _une_ démarche en particulier) et ça posait également quelques soucis de lisibilité.

> Par ailleurs, il pourrait être éventuellement plus clair d'indiquer pour ce rôle que ses droits sur une démarche sont les même que ceux d'un administrateur ministériel,

Justement, lors de la specification nous n'avons pas forcement régardé ceci comme ça, mais on s'est plutot posé des questions par rapport à chaque role individuel (et nous avons fini par avoir les mêmes droits).

Effectivement, tel que dessiné maintenant, ce tableau est moins transformable directement en code que d'autre tableaux de droits, mais il a fallu faire un choix entre une spécification plutôt fonctionnelle et une spécification plutôt proche de l’implémentation. C'est une histoire de preference ou il manque des informations dans le tableau?

**Comment by lucaa** [comment]
L'image a été mise à jour avec une modification mineure (l'affichage du code d'embed), dans la version du 24/02 .

**Comment by JeanPerrier** [comment]
J'ai modifié quelques éléments dans le tableau. @lucaa Tu me diras si tu es d'accord. 
Le tableau des droits me convient à l'heure actuel. @slauriere On peut modifier la façon dont le tableau est construit si c'est plus simple pour vous. Toutefois l'essentiel c'est que vous deux, Georges, Romy et moi-même arrivions à comprendre le tableau pour être sur qu'on est d'accord.

**Comment by slauriere** [comment]
À partir du tableau existant, j'ai créé une page listant un ensemble de scénarios de tests des droits en question, sur le wiki projet. Cette page est intitulée "Scénarios de tests des droits" et est accessible depuis un lien sous le tableau.

La création de ces scénarios de tests a été l'occasion 1) d'ajuster les droits existants, 2) de soulever les questions ci-dessous (je rajoute donc temporairement le label "question") : 

- Restriction des pages utilisateurs et groupe : voir si la restriction doit être "forte" (protection de chaque page utilisateur) ou "faible" (protection seulement des pages contenant la liste des utilisateurs : pages "AllDocs", "UserDirectory", etc.). Les pages de groupes doivent sans doute être protégés individuellement.
- Page de liste des avis : protection faible ou forte des avis (actuellement, la page Avis.WebHome est incluse, en restreignant à une démarche).
- Peut-être re-préciser qui a accès au tableau des démarches de la page "Demarches.WebHome". Les administrateurs ministériels ?
- Un porteur est-il bien autorisé également à supprimer des porteurs, pas seulement à en ajouter ?
- Actuellement les notifications par e-mail portent sur tout changement de porteur, pas seulement un ajout, est-ce ok ?
- Voir ce qui doit se passer du point de vue notification des porteurs quand une démarche est supprimée.
- Vérifier interdiction d'accès aux onglets de démarche avec un paramètre velocity. Il ne faudrait pas qu'un utilisateur authentifié puisse créer une page avec un script d'include qui inclurait une page d'onglet avec une démarche en paramètre dans le contexte Velocity. Actuellement si un utilisateur authentifié crée une démarche (via formulaire simplifié) en insérant du code velocity dans la description, celui-ci est exécuté alors qu'en principe, seul XWikiAdminGroup a le droit de script. Deux façons de résoudre le problème : 1) échapper les scripts (probablement le plus sûr), 2) restreindre les droits d'exécution de scripts.

**Comment by slauriere** [comment]
* Utilisateurs / groupes : créer un mécanisme de protection automatique des pages concernées ("listener") -> création d'un ticket séparé.
* Page d'avis : elle ne doit être accessible qu'aux administrateurs ministériels et niveaux supérieurs (i.e. administrateurs).
* Page "Demarches.WebHome" : elle reste telle quelle.
* Pour l'instant un porteur est autorisé à supprimer des porteurs, pas seulement à en ajouter, les notifications portent sur tout changement de porteur, et aucune notification n'est envoyée en cas de suppression de démarche.
* Concernant la protection des injections de code Velocity : création d'un ticket séparé.

**Comment by JeanPerrier** [comment]
Je ne comprends pas très bien tes commentaires Stéphane, je suppose qu'ils sont surtout adresser à Anca et pour garder une trace écrite de vos réflexions?
Une remarque : Logiquement, un porteur de démarche ne peut pas supprimer le rôle de propriétaire à l’administrateur ministériel. Vous avez prévu comme cela?

"aucune notification n'est envoyée en cas de suppression de démarche." Logiquement un porteur de démarche ne peut qu'inactiver une démarche? on est d'accord?

**Comment by lucaa** [comment]
> Logiquement, un porteur de démarche ne peut pas supprimer le rôle de propriétaire à l’administrateur ministériel. Vous avez prévu comme cela?

Oui, l'administrateur ministériel n'est pas dans la liste de porteurs, ses droits sur la démarche viennent du fait que la démarche appartient à sa direction, il n'est pas un porteur explicit donc il ne peut pas être enlevé par les autres porteurs.

> "aucune notification n'est envoyée en cas de suppression de démarche." Logiquement un porteur de démarche ne peut qu'inactiver une démarche? on est d'accord?

Je ne sais plus si je l'ai mis dans les spécifications explicitement mais oui, la suppression d'une démarche est réservée aux administrateurs.

**Comment by lucaa** [comment]
J'ai crée aussi #460 pour s'assurer qu'un utilisateur identifié ne peut pas supprimer une démarche qu'il a crée (comportement standard XWiki).

**Comment by georges-bayard** [comment]
nok : on n'a pas réussi à accéder à la vue de recherche pour chercher le numéro de la démarche (besoin Anthony)

**Comment by JeanPerrier** [comment]
Le schéma de droit est valide mais pas bien implémenté s'agissant du besoin du cerfa numérique

**Comment by georges-bayard** [comment]
l'url est la suivante : https://nosdemarches-staging.devxwiki.com/Main/Search
