### ISSUE TITLE
Modifier la validation des utilisateurs pour demander une validation manuelle pour tous les comptes non-gouv.fr

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#430]
La validation des comptes des nouveaux utilisateurs (#429) doit être automatique si l'adresse email (validée ) de l'utilisateur est une adresse .gouv.fr et manuelle (par les administrateurs Dinsic) autrement.

**Comment by slauriere** [comment]
Implémentation : 
- Lors de la création d'un compte qui ne correspond pas une adresse .gouv.fr, une fois l'adresse e-mail validée par l'utilisateur lui-même, un e-mail est envoyé aux administrateurs contenant un lien vers la page du nouveau compte utilisateur.
- La page d'un utilisateur permet de passer l'utilisateur du statut inactif au statut actif, pour les personnes autorisées à modifier la page.

**Comment by slauriere** [comment]
NB : sans doute créer un listener, et surcharger la page de validation de compte.

Ticket lié : #456

**Comment by slauriere** [comment]
Cette fonctionnalité a une relative complexité liée au fait que le mécanisme par défaut de validation d'adresse e-mail d'XWiki déclenche immédiatement l'activation du compte. Ici il s'agit dans certains cas de suspendre cette activation, ou éventuellement de désactiver un compte juste après qu'il a été activé, le temps qu'il soit validé par un administrateur (mais cela peut présenter des inconvénients car cela fait passer temporairement un compte dans l'état actif). Il y a plusieurs implémentations possibles : 
* Surcharger XWiki.java pour modifier la procédure de validation
* Écrire un listener qui désactive un compte temporairement après qu'il a été activé
* Introduire un mécanisme générique dans XWiki qui permettrait un workflow de validation plus complexe
* Ou solution plus simple que je ne vois pas.

**Comment by slauriere** [comment]
Implémentation choisie avec Anca concernant les adresses qui ne sont pas du type "gouv.fr" : 
* Les comptes restent à l'état inactif que non validés par un administrateur
* Une fois l'adresse e-mail validée, les administrateurs sont notifiés par e-mail d'un compte à valider, et l'utilisateur lui-même a un message explicatif sur le site
* Le message indiquant qu'un nouveau compte est à valider contient un lien vers une page de script de validation, qui déclenche également l'envoi d'un e-mail à l'utilisateur cible.

**Comment by slauriere** [comment]
Le workflow décrit a été implémenté. Les modèles d'e-mails sont éditables via le wiki.

**Comment by JeanPerrier** [comment]
Modifier le texte explicatif aux mails non @gouv.fr après qu'ils aient validé leur compte en cliquant sur le lien dans le mail reçu:
"Votre adresse e-mail a bien été validée. Votre compte doit maintenant être validé par un administrateur du site avant de pouvoir vous authentifier. Un e-mail de notification vous sera envoyé lorsque votre compte sera validé."

@georges-bayard ça te va?

**Comment by JeanPerrier** [comment]
En fait vu les explications de #488, je préfère laisser tel quel.
