### ISSUE TITLE
Implémenter le propriétaire de démarche: stockage, modification et droits

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#431]
Cette tache est pour l'implémentation du nouveau rôle d'une démarche, le propriétaire de démarche (voir les specs).
Il y a 3 aspects:
* le stockage de la liste des propriétaires
* la possibilité pour tout utilisateur ayant le droit de modifier la démarche, de mettre à jour la liste de propriétaires
* les droits: un propriétaire de démarche doit avoir le droit de modifier la démarche

**Comment by lucaa** [comment]
Plusieurs stratégies sont possibles (à décider):
* utilisation d'un groupe par démarche: pb de performance?
* utilisation d'une propriété de la démarche + un event listener pour mettre à jour un objet de droits sur la page de la démarche à chaque fois que la liste de propriétaires change
* utilisation d'un objet de droits directement sur la page de la démarche, avec un affichage de sa liste d'utilisateurs en mode édition pour ajouter des nouveaux propriétaires

**Comment by lucaa** [comment]
Finalement, on va commencer par gérer les propriétaires dans une prop de la classe Démarche, avec une synchronisation par un listener avec un objet de droits sur la page démarche, donnant le droit de modifier la démarche aux propriétaires.
Ceci est pour éviter, dans une première phase, le risque de performance du module d'authorisation lié au rajout de ~2000 groupes.
Dans une deuxième phase, après une analyse de l'impact de ce nombre de groupes, nous pourrons passer, si nécessaire, à une gestion par groupe.

**Comment by slauriere** [comment]
Le rôle de propriétaire a été implémenté et testé : 
- Ajout d'une propriété dédiée à la classe démarche
- Affichage de cette propriété en visualisation et en édition
- Mise à jour des droits d'édition lors de la modification de cette propriété

**Comment by slauriere** [comment]
PS : une difficulté rencontrée : la mise à jour des propriétés "groups" et "users" de XWikiRights doit se faire via "setLargeStringValue" et non "setStringValue". Cela met en avant l'importance d'avoir un jour une API de plus haut niveau pour manipuler les droits et éviter d'avoir à connaître ces subtilités interne de stockage. Cf [XWIKI-13466](https://jira.xwiki.org/browse/XWIKI-13466).
