### ISSUE TITLE
Notifier tous les propriétaires d'une démarche de la mise à jour des propriétaires

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#433]
Un émail doit être envoyé aux propriétaires d'une démarche quand la liste de propriétaires est mise à jour, mais également aux administrateurs ministériels ayant une direction qui correspond à la direction de la démarche courante (propriétaires "implicits").

**Comment by slauriere** [comment]
Une première version de notification a été implémentée et testée. Il reste des améliorations possibles, je crée un nouveau ticket pour cela.

**Comment by JeanPerrier** [comment]
La notification marche lorsque l'adresse mail est autre que ".gouv.fr" mais semble ne pas fonctionner lorsque l'email est en ".gouv.fr".
