### ISSUE TITLE
Stress test: evaluation de l'evolution du temps d'ajout d'un avis pour une démarche ayant jusqu'a 10 000 avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#438]
Simuler l'ajout de plein d'avis sur une démarche et dessiner l'evolution du temps de stockage d'un avis avec le nombre d'avis de la démarche, dans 2 contextes:
* avec la mise à jour du cache de nombres d'avis et de taux de satisfaction (#242)
* sans cache des avis et taux de satisfaction.

L'objectif est d'aller jusqu'a 10 000 avis.

**Comment by slauriere** [comment]
Implémentation : peut-être avec curl

**Comment by slauriere** [comment]
NB : il est envisageable de désactiver le cache de statistiques d'avis si besoin.

**Comment by lucaa** [comment]
Le test sans le cache des avis a été fait, les résultats sont notés ici: https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/scalabilite/charge/ .

En ce qui concerne le test avec le cache des avis activé, le plan est de le désactiver ( #671 ), donc il ne sera plus necessaire. 
Des tests supplémentaires de scalabilité peuvent être faits, mais l'objectif de 10 000 est atteint avec les tests ci-dessus, donc je ferme cette tâche pour maintenant.
