### ISSUE TITLE
Mettre à jour l'implémentation du contrôle d'accès à l'onglet d'embed une fois que le concept de propriétaire de démarche sera implémenté

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#440]
Une fois que #431 sera implémenté, répercuter cela sur l'implémentation du contrôle d'accès à l'onglet d'embed.

**Comment by lucaa** [comment]
L'onglet d'embed est accessible a tous les utilisateurs connectés, pas uniquement aux proprietaires.

**Comment by lucaa** [comment]
Je laisse ouvert au cas ou il n'y a pas de controle du tout aujourd'hui. Si l'onglet est affiché a tous les utilisateurs connectés, on peut fermer cette tache avec label "wontfix" .

**Comment by lucaa** [comment]
En fait, les spécifications ont changé ce vendredi (22 feb) et effectivement l'onglet avec le code d'embed doit être affiche uniquement aux porteurs de démarche.

**Comment by lucaa** [comment]
J'ai enfin compris ce qu'il s'est passé, et la confusion sur cet issue: #412 avait été mail implémenté, dans le sens d'afficher l'onglet embed uniquement aux propriétaires de démarche, alors qu'au moment de son implémentation la spéc disait d'afficher cet onglet à tout utilisateur connecté. Entre temps, les specs ont changé et l'implementation de #412 est devenue correcte, ainsi que cet issue.
