### ISSUE TITLE
Compatibilité de l'affichage du formulaire d'avis avec la version 2.0

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#441]
- Paramètre "view-mode"
- Si les paramètres "nd_source" et "nd_mode" sont présents et non vides, cela conduit au mode "avis-tab" directement

**Comment by slauriere** [comment]
Les paramètres "nd_source" et "nd_mode" sont à présent pris en compte.

**Comment by lucaa** [comment]
Il y a également la clé d'API qui va manquer aux anciens URLs d'avis, je me demande si ce n'est pas plus simple de demander aux utilisateurs d'URL de re-faire leurs URLs avec le nouvel API?
@JeanPerrier @georges-bayard est-il possible de faire ça?

**Comment by JeanPerrier** [comment]
Oui cela concerne la DILA pour 3 démarches et le MTES pour deux démarches.

**Comment by lucaa** [comment]
Donc on casse la compatibilité, les anciens URLs ne vont plus marcher tant que la clé n'a pas été généré. Je vais créer une tache pour gérer cela lors de la livraison.

**Comment by georges-bayard** [comment]
ok gba
