### ISSUE TITLE
Amélioration des notifications de changement de porteurs de démarche

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#449]
Amémiorations possibles suite à #433:
- Paramétrer l'émetteur via le wiki
- Utiliser un template pour les e-mails envoyés (sujet / contenu)
- Afficher dans le message le nom des porteurs au lieu de leur identifiant XWiki (avec un lien vers leur profil)
- Intégrer une URL vers la démarche mise à jour

**Comment by slauriere** [comment]
Les améliorations suivantes ont été apportées : 
- Le modèle de message de notification est éditable via une page dédiée 
- Les messages générés contiennent l'URL de la démarche, les noms des anciens et nouveaux porteurs et des liens vers leurs profils

Il reste à rendre paramétrable l'émetteur des e-mails, cela fera l'objet d'un ticket dédié.

**Comment by georges-bayard** [comment]
nok : mettre dans le titre des mails le nom de la démarche et non pas seulement l'identifiant

**Comment by lucaa** [comment]
> mettre dans le titre des mails le nom de la démarche et non pas seulement l'identifiant

a été fait. Par contre, il sera impacté par le même problème que décrit dans l'issue #473, dans ce commentaire: https://github.com/DISIC/wikidemarches/issues/473#issuecomment-468963083 , et devra être corrigé en même temps.

**Comment by JeanPerrier** [comment]
Pour moi c'est bon.
