### ISSUE TITLE
Fix suggest for the demarche "groupes" and "organismes de traitement"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#45]
This needs the patch for https://jira.xwiki.org/browse/XWIKI-15307 to be applied.

**Comment by slauriere** [comment]
- the patch was applied and deployed
- the installation instructions were updated with info on how to build the patched jar file xwiki-platform-legacy-oldcore-9.11.3.jar

Pending:
- commit jar file to SVN
- commit corresponding README to SVN

**Comment by slauriere** [comment]
The jar file and the README have been [committed to GitHub](https://github.com/DISIC/wikidemarches/tree/master/bin). Anca: I'll let you check everything is in order indeed and to close the issue if it's ok.

**Comment by slauriere** [comment]
NB: if the field is empty and the user types the first letters quickly, no AJAX request is emitted. Example: type 'cal' in the input field corresponding to 'Organismes de traitement'.
