### ISSUE TITLE
Donner la possibilité à un utilisateur connecté de s'auto-déclarer propriétaire (porteur) de démarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#451]
Un utilisateur connecté (y compris les administrateurs ministériels) doit pouvoir devenir propriétaire d'une démarche en cliquant un bouton affiché sur la page de la démarche.
Nous n'avons pas encore de visuel la-dessus, mais l'idée est d'avoir une explication suffisamment claire sur les conséquences et le fait que si l'utilisateur n'est pas porteur de la démarche, il ne devrait pas se déclarer porteur.

Techniquement, on doit s'assurer que cette modification sur la démarche est tracké correctement dans l'historique comme ayant être faite par l'utilisateur qui clicke le bouton (si possible) et que les notifications de #433 sont envoyées.

**Comment by slauriere** [comment]
Un bouton a été ajouté en mode visualisation pour les utilisateurs authentifiés qui ne sont pas déjà porteurs de la démarche courante. Ce bouton déclenche l'ajout de l'utilisateur courant à la liste des porteurs de la démarche et redirige vers la démarche courante. Une sauvegarde majeure est effectuée sur la démarche, avec un commentaire du type "Ajout du porteur : XWiki.BusterKeaton". L'auteur de la modification est l'auteur du script d'ajout, pas l'utilisateur courant, car cela semble nettement plus compliqué. Qu'en penses-tu Anca ? 

Les notifications de changement de porteurs sont bien envoyées.

**Comment by lucaa** [comment]
> Qu'en penses-tu Anca ?

C'est bon, j'ai fait pareil pour #417 .
