### ISSUE TITLE
Rendre configurables le nom et l'adresse de l'émetteur des messages de notification

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#458]
Actuellement, le nom et l'adresse de l'émetteur des messages de notification sont écrits dans le code directement. Il faudrait les rendre configurables via le site.

Tickets liés  : #449

**Comment by slauriere** [comment]
C'est bien l'adresse déclarée dans la section "Envoi d'e-mails" de l'administration du site qui est utilisée comme adresse émettrice.

**Comment by slauriere** [comment]
La page "Mail.MailConfig" a été mise à jour dans les sources pour contenir une valeur par défaut "info@nosdemarches.gouv.fr" pour le moment.

**Comment by lucaa** [comment]
L'adresse devrait être une adresse de type "no-reply" - la version française -  et devrait être précédé par un nom d'affichage, de type:
monavis.numerique.gouv.fr <ne-pas-repondre@monavis.numerique.gouv.fr>

**Comment by lucaa** [comment]
Alors, après investigations sur ce qu'il "se fait":
* j'ai trouvé dans ma boit mail des mails de nepasrepondre@marches-publics.gouv.fr 
* j'ai trouvé des articles sur internet disant que c'est pas une super idée d'avoir une adresse "no-reply", car ça nuit à la "rélation client ". 

En +, ça peut être une bonne idée d'avoir une adresse qui fonctionne, au cas où les gens ont quand même des choses à dire, de les recevoir. Pour l'instant, toutes les adresses de type <quelquechose>@monavis.numerique.gouv.fr ne fonctionnent pas, donc si quelqu'un envoie quand même une réponse, on ne la reçoit pas.

Donc, j'ai décidé de mettre cette adresse à la même adresse que l'adresse de contact du site, celle du lien "Contact". Le seul risque c'est de recevoir, dans cette boite, trop de:
* réponses automatiques aux mails de notifs de type : suis en vacances de ... jusqu'au ...
* e-mails d'erreur d'adresse email, qui arrivent quand l'envoi de mail à une adresse email invalide est tenté. Cette situation peut arriver notamment pour les inscriptions avec des adresses erronées (ou spam).

Si ces consequences sont "trop", nous pouvons changer vers une adresse inexistante.

**Comment by lucaa** [comment]
En fait, à cause du bug https://jira.xwiki.org/browse/XWIKI-16198 , je ne peux pas encore mettre de nom d'affichage pour cette adresse email.
Je garde cette issue ouverte, en attendant une reponse pour XWIKI-16198 .

**Comment by lucaa** [comment]
Après tests, il semble que  l'adresse nosdemarches@modernisation.gouv.fr ne peut pas être utilisée car le serveur de mail de modernisation.gouv.fr (au moins) bloque les emails envoyés par le serveur d'email de XWiki qui ont comme expediteur une adresse valide de modernisation.gouv.fr. 
Nous avons fait des testes avec nepasrepondre@monavis.numerique.gouv.fr et ça fonctionne tres bien, on va donc devoir configurer cette adresse là.

**Comment by lucaa** [comment]
en fait, il semble que https://jira.xwiki.org/browse/XWIKI-16198 n'est pas réproductible avec un autre serveur smtp, et ceci sera donc un problème lié au serveur qu'on utilisé et sa configuration (voir les commentaires de XWIKI-16198 ).
@slauriere , pourrais-tu essayer de comprendre un peu plus, avec l'aide de l'équipe infra, si on peut changer quelquechose sur notre serveur SMTP pour que ça marche? moi j'ai eu le problème sur le serveur de developpement.

**Comment by lucaa** [comment]
La tache restante pour mettre en place un nom de présentation de l'expéditeur à été isolée dans #521.
Je ferme donc cette issue, car l'adresse a été choisie et le fonctionnement globalement fait.
