### ISSUE TITLE
Vérifier qu'un utilisateur authentifié ne peut pas effacer une démarche qu'il a crée avec le formulaire d'ajout de nouvelle démarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#460]
Lié à #425 et #426 et à la fonctionnalité par défaut de XWiki qui donne le droit au créateur d'un document de supprimer le document qu'il a crée, même si le droit de suppression est restreint à d'autres utilisateurs.

Avant, la création de démarche était accessible aux utilisateurs non-identifiés et le créateur de démarche était XWikiGuest. Par contre, il ne pouvait pas effacer la démarche.

Cette issue est pour vérifier que lors de la création d'une démarche pas un utilisateur autentifié, il ne peut toujours pas supprimer cette démarche. Si c'est le cas, la fonction doc.saveAsAuthor() peut être envisagée pour sauvegarder le document de la démarche avec, comme créateur, l'utilisateur Admin.

**Comment by slauriere** [comment]
Une démarche créée par un utilisateur authentifiée est sauvegardée en son nom, mais elle ne peut pas être supprimée par celui-ci, du fait que le droit de suppression de page dans l'espace "Demarches" est restreint aux administrateurs ministériels.

J'ai ajouté ce test à la page des scénarios de tests de droits sur le wiki projetdemat.

**Comment by slauriere** [comment]
Comprendre pourquoi.

**Comment by slauriere** [comment]
J'avais fait une erreur : toute démarche pouvait effectivement être supprimée par son créateur. La procédure de sauvegarde a été modifiée : c'est à présent "saveAsAuthor" qui est utilisée, et une sauvegarde supplémentaire "save" est effectuée juste après, pour que l'utilisateur courant apparaisse bien comme dernier auteur.
