### ISSUE TITLE
Formulaire de nouvelle démarche : valider les champs requis

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#461]
La sauvegarde d'une nouvelle démarche ne doit être acceptée que si la démarche est conforme, cf formulaire de validation par défaut.

**Comment by slauriere** [comment]
Les champs "nom de la démarche" et "direction" sont à présent bien marqués comme requis s'ils ne sont pas renseignés.

**Comment by georges-bayard** [comment]
Le champ suivants doivent être supprimé : Référence BDD Form
Le champs suivants doit être déplacé : Formulaire cerfa associé (à mettre au dessus de référence Service Public)
Le champ suivant doit être ajouté : Volumétrie de la dématérialisation (en dessous de volumétrie de la démarche)

**Comment by JeanPerrier** [comment]
#472

**Comment by lucaa** [comment]
Le travail a été bougé sur #426.
