### ISSUE TITLE
Mise à jour des textes de la page d'accueil autentifié

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#465]
La page d'accueil pour les utilisateurs identifiés est la même que l'ancienne page d'accueil publique. 
Dans ce contexte, quelques textes n'ont plus de sens.
Il faut décider quels textes - plus parlants pour les utilisateurs connectés - il faut mettre à la place.

![image](https://user-images.githubusercontent.com/657716/53511388-9fc30200-3ac0-11e9-8fba-aabe445c3fd8.png)

**Comment by lucaa** [comment]
Note: le nom du site sera changé par #464 .

**Comment by JeanPerrier** [comment]
A la place d'"Evaluez votre démarche en ligne" -> "Recherchez votre démarche en ligne" 
Supprimer la phrase "votre démarche n'est pas disponible en ligne..."

**Comment by lucaa** [comment]
Finalement, après la discussion de ce soir:
évaluez votre démarche en ligne - à supprimer
votre démarche n'est pas disponible en ligne - à supprimer
Améliorons les services publiques... - reste tel quel

**Comment by lucaa** [comment]
Version sans titre du tout: 

![image](https://user-images.githubusercontent.com/657716/53656880-eb0e1980-3c54-11e9-9a50-91c463b56cba.png)

J'avoue que ça me gène un peu, visuellement, je mettrai bien un titre de type: "Faites évaluer votre démarche par les utilisateurs" , pour inciter les gens à faire la chose pour laquelle ils sont venus.

**Comment by lucaa** [comment]
Fait sans titre. @JeanPerrier @georges-bayard  , reouvrez si vous voulez changer, mais il me faut un texte pour le titre.

**Comment by JeanPerrier** [comment]
Modification du texte en dessous:
" Vous n'êtes actuellement porteur d'aucune démarche. Recherchez votre démarche ci-dessus, puis, cliquez sur le bouton "<...>" pour devenir porteur de la démarche".

Je laisse GBA se prononcer sur la nécessité d'un  titre

**Comment by georges-bayard** [comment]
je pense qu'il faut rester minimaliste pour l'instant. En tant qu'utilisateur du site on peut peut faire n actions : se déclarer porteur, récupérer le bouton ou l'embed, modifier les caractéristiques de la démarche, consulter les résultats de votes. Soit on dit tout soit on dit rien. pour l'instant je pense qu'il faut rester sobres

**Comment by lucaa** [comment]
Je ne suis pas sure de comprendre si la remarque de Georges s'applique à la demande de modification de texte de Jean aussi ou uniquement à l'idée d'avoir un titre.
Pour être sure, je vais faire la modification de texte demandée par Jean et fermer l'issue. Re-ouvrez si j'ai mal compris.

**Comment by JeanPerrier** [comment]
Il faudrait un mettre un point à la fin du texte.

**Comment by JeanPerrier** [comment]
Oui Anca tu as bien compris.

**Comment by lucaa** [comment]
> Il faudrait un mettre un point à la fin du texte.

Fait!
