### ISSUE TITLE
Afficher le bouton pour devenir porteur de démarche en dessus de l'onglet "informations" pour les utilisateurs authentifiés

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#468]
Pour les utilisateurs authentifiés (mais pas porteurs de démarches ni administrateurs ministeriels), le bouton pour devenir porteur d'une démarche devrait être mis en avant avec un message qui exprime le fait que pour avoir accès à la totalité des fonctionnalités d'une démarche, il faut se déclarer porteur de démarche.
Dans l'implémentation courante, le bouton est un peu perdu dans l'onglet d'informations de la démarche et il n'est pas clair que l'étape suivante est de devenir porteur de cette démarche. Dans l'idéal, il devrait être affiche au dessus de l'onglet "informations" mais si techniquement ça rend les choses compliques, alors en haut de l'onglet Informations, dans une boite d'information qui prend toute la largeur de l'écran, comme un entête de l'onglet Informations, va répondre au besoin.

Ce comportement ne devrait pas s'appliquer aux administrateurs ministeriels pour lesquels le comportement courant (modification de la démarche pour mettre à jour les porteurs) devrait suffir.

**Comment by lucaa** [comment]
![image](https://user-images.githubusercontent.com/657716/53525169-74044400-3ae1-11e9-97df-330acc5502fe.png)

**Comment by lucaa** [comment]
@slauriere attends un peu l'implémentation, on va valider demain avec @JeanPerrier .

**Comment by JeanPerrier** [comment]
Whaou c'est trop bien et trop beau! je valide

**Comment by lucaa** [comment]
ok, cool :). 
@slauriere verifie que les 2 textes sont dans des clés de trads, parce-qu'on va devoir surement les changer pour les rendre plus claires.

**Comment by lucaa** [comment]
Fait. Les textes peuvent être changés si nécessaire.

**Comment by JeanPerrier** [comment]
Modifier le texte (rajouter une virgule) : "Pour avoir accès aux fonctionnalités supplémentaires (code d'intégration du formulaire d'avis, résultats des avis, modification des informations sur la démarche, etc), il faut être porteur de cette démarche."

**Comment by lucaa** [comment]
J'ai ajouté la virgule, je referme.
