### ISSUE TITLE
Mettre à jour la page "à propos", si necessaire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#471]
Décider, également, si elle doit être affiché aux utilisateurs pas connectés ou pas.

**Comment by JeanPerrier** [comment]
Comme le site n'est plus public, plus besoin d'avoir d'a propos surtout qu'il n'est pas à jour. 
Il faudra avoir un guide utilisateur pour les utilisateurs connectés par contre.

**Comment by lucaa** [comment]
J'ai bougé la tache vers M9, pour l'instant on ne va pas afficher ce lien (#491).

**Comment by JeanPerrier** [comment]
Il faut mettre à jour le a propos dixit GBA.

**Comment by lucaa** [comment]
Voir une première proposition dans #504.

**Comment by lucaa** [comment]
Note: suite au modifications de #491 , le lien "A propos" n'est plus affiché. Il faut également affiché ce lien une fois que le texte a été mis à jour.

**Comment by lucaa** [comment]
Texte de #504 à re-valider, suite aux dernières mises à jour.

**Comment by lucaa** [comment]
cette tache est remplacée dans la M11 par #696, je ferme.
