### ISSUE TITLE
Préparer les clés d'API + nouveaux URLs de formulaire d'avis pour les utilisateurs d'URLs v2.x

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#481]
Suite à la décision sur #441 de ne pas accepter des avis sans clé d'API, il faut prévoir la migration des URLs existantes:
* la génération des clés en avance, avant la livraison en production
* la génération des nouvelles URLs avec les clés dessus
* l'envoi de ces URLs aux utilisateurs courants des URLs
* ne pas deployer en production tant que la mise en place des nouveaux URLs n'est pas faite ou clairement avertir les utilisateurs qu'à partir de la date de migration en production les avis ne seront plus ajoutés si l'URL n'est pas mise à jour

**Comment by lucaa** [comment]
Un email pour avoir les noms d'utilisateurs a été envoyé, la tache passe désormais "en attente".

**Comment by lucaa** [comment]
Les 5 URLs pour les 2 porteurs ont été générées et envoyées par émail à @georges-bayard . 
Il faut prévoir, pour l'installation production, la copie des clés d'API de ces 2 porteurs (à partir du staging) et d'ajouter les configurations pour rendre ces clés valides pour les 5 démarches.

**Comment by lucaa** [comment]
à confirmer avec @ldubost qu'on peut garder les URLs nosdemarches après la mise en place du nouveau domaine, avec un redirect.

**Comment by lucaa** [comment]
> à confirmer avec @ldubost qu'on peut garder les URLs nosdemarches après la mise en place du nouveau domaine, avec un redirect.

Confirmé.

Il reste juste à prévoir, pour la mise en prod, la copie des clés d'API de ces 2 porteurs (à partir du staging) et d'ajouter les configurations pour rendre ces clés valides pour les 5 démarches.

**Comment by JeanPerrier** [comment]
Lang a transmis l'information aux concernés. Vu la faible volumétrie de ces démarches, ce n'est pas grave si les anciens liens ne fonctionnent pas à partir de demain.

**Comment by lucaa** [comment]
Oui, la tache reste ouverte pour mettre en place les éléments necessaires au fonctionnement des URLs fabriqués il y a 2 semaines sur la production.

**Comment by lucaa** [comment]
> Il reste juste à prévoir, pour la mise en prod, la copie des clés d'API de ces 2 porteurs (à partir du staging) et d'ajouter les configurations pour rendre ces clés valides pour les 5 démarches.

Fait, je ferme la tache.

**Comment by lucaa** [comment]
Comme cette livraison a été dé-faite, je reouvre cette tache pour la ré-faire lors de la nouvelle livraison.

**Comment by lucaa** [comment]
Cette tache a été re-faite lors de la nouvelle livraison en production aujourd'hui, je re-ferme la tache.
