### ISSUE TITLE
Ajouter la nouvelle API de groupes sur le projet et afficher les groupes de l'utilisateur dans son profil

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#482]
https://extensions.xwiki.org/xwiki/bin/view/Extension/User%20membership%20in%20the%20profile/ .

Note: si une autre fonctionnalité a besoin de la vérification de groupes ou membership d'un utilisateur, il faut ajouter et utiliser l'API qui est la dependence de cette extension, meme si l'onglet n'est pas implémenté.

**Comment by lucaa** [comment]
Presque même tâche que #670 .

**Comment by slauriere** [comment]
Je ferme cette tâche qui doublonne avec #668.
