### ISSUE TITLE
Ajouter tous les champs des avis dans l'export CSV des avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#484]
Il s'agit des données fournies en bas de page, dans la page de résultats d'avis.
L'idée est d'ajouter dedans la maximum d'informations possible sur les avis pour fournir l’accès aux avis aux utilisateurs ayant les droits de voir les stats.
Ne pas ajouter l'info "comment avez-vous fait cette démarche", car irrelevante, ni l'email . Le minimum est le champ de saisie libre.

**Comment by lucaa** [comment]
Ne pas oublier les entrées libres des utilisateurs pour les nouvelles difficultés.

**Comment by JeanPerrier** [comment]
Si je ne m'abuse, il y a deux exports CSV différents et un export Excel: 
1/ L'export CSV et Excel de l'onglet "tous les avis"
2/ L'export CSV de l'onglet "synthèse des avis" (sans les commentaires car à l'origine pour le grand public) 

Il faut garder les exports 1/ et les deux mettre sur les deux onglets "tous les avis" et "synthèse de avis". 

Il vaut mieux attendre la refonte du modèle de données avant de modifier ces exports.

**Comment by lucaa** [comment]
Ces 2 fonctionnalités ont changés depuis l'implémentation de cette tache, ainsi:
* les stats sont désormais visibles aux tous les utilisateurs, à partir du tableau de bord. Pour des raisons de performance, les données brutes disponibles en téléchargement ont été enlevés de cet onglet ( #676 ).
* l'onglet Liste des avis a été désormais rendu visible à tous les porteurs de démarches #447 , avec un export, même si limité (#672).

Si je me rapelle correctement, cette tache visait la completude des informations fournies par l'onglet stats pour contourner l'absence de #447. Ainsi, comme #447 est fait, elle n'est plus à faire.
