### ISSUE TITLE
Proposer des noms d'utilisateurs correspondant à la règle existante

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#489]
Aujourd'hui, quand un utilisateur s'inscrit et donne son nom et prénom, on lui propose automatiquement un nom d'utilisateur qui est prenom + nom en CamelCase. L'idée est de proposer un nom d'utilisateur qui correspond à la règle qu'on a utilisé pour les utilisateurs existants.

Par contre, @slauriere @JeanPerrier , c'est quoi cette règle? car là de ce que je vois en production, nous avons un peu de tout...

**Comment by JeanPerrier** [comment]
Voici les règles de rédaction de l'identifiant dans l'xwiki de la DINSIC fixées par Julien:

La règle générale: identifiant= "première lettre du prénom" + "nom" tout en minuscule 
Règles particulières:
- Si nom composé avec tiret, on garde le tiret entre les deux noms dans l'identifiant;
- Si nom composé sans tiret, on met le tiret dans l'identifiant (ex ale-bourdoulous Alain LE BOURDOULOUS)

Questions: 
1/ Est-ce qu'on reprend la règle de julien?
2/ Est-ce qu'on laisse le choix aux utilisateurs de modifier leurs identifiants?

**Comment by JeanPerrier** [comment]
GBA et moi somme partisans du fait de ne pas pouvoir modifier l'identifiant. Qu'en pensez vous?

**Comment by lucaa** [comment]
> GBA et moi somme partisans du fait de ne pas pouvoir modifier l'identifiant. Qu'en pensez vous?

Je n'ai pas d'avis spécifique, ça a du sens, mais en même temps je pense que peu de gens modifient vraiment le nom d'utilisateur proposé, sauf s'ils ont une préférence pour l'abbreviation de leur nom - surtout pour les noms compliqués, composés, avec des accents et des tirés. 
Aujourd'hui le code qui calcule ce nom ne vérifie pas sa disponibilité pour le cas où le nom composé par la régle automatique est déjà pris. C'est la responsabilité de l'utilisateur de remplir un autre nom si effectivement il y a un doublon.
Si on veut ne plus laisser l'utilisateur changer le nom, il faut aussi que ce calcule de nom assure l'unicité du nom proposé, vu que l'utilisateur ne pourra pas le corriger s'il n'est pas unique. Ainsi, la modification du mécanisme existant est plus importante. 
Je propose, donc, de garder cette issue pour changer uniquement la stratégie des propositions de nom automatiques, et de créer une autre issue pour le rendre non-modifiable par l'utilisateur, si on décide pour.

**Comment by lucaa** [comment]
@slauriere , pour l'implementaiton, ceci devra demander uniquement un javascript à modifier, pour changer la regle de composition du nom d'utilisateur pre-rempli.
Si c'est plus compliqué que ça ou si le javascript à modifier est utilisé à d'autres endroits sur le wiki, on peut laisser l'issue pour après la mise en prod, pour ne pas introduire de risques . 
Aussi, assure-toi de nettoyer les accents des noms, s'il te plaît.

**Comment by JeanPerrier** [comment]
Ok pour changer la règle.
On laisse la possibilité aux usagers de changer leur identifiant pour l'instant.

**Comment by slauriere** [comment]
J'ai implémenté cette règle en surchargeant le code JavaScript qui implémente la règle par défaut (fonction "prepareName" de "xwiki.js"). Cela n'a d'incidence que pour la page d'enregistrement des nouveaux utilisateurs « standards » (page "XWiki.Registration", par opposition à la page où s'enregistre l'administrateur du wiki au moment de l'installation, qui est la seule autre page où s'effectue une proposition de nom d'utilisateur, dans notre cas).

**Comment by JeanPerrier** [comment]
@slauriere On peut tester en staging? Pour l'instant, le formulaire propose seulement prénom+nom comme identifiant.

**Comment by slauriere** [comment]
Oui pardon, je viens de mettre en place la règle sur le staging également.

**Comment by JeanPerrier** [comment]
@slauriere C'est donc les mêmes règles que pour l'Xwiki DINSIC de Julien?

**Comment by slauriere** [comment]
Oui, c'est la même règle en effet. Je viens de corriger un bug (y compris en préprod) : dans le cas où le nom comportait déjà un tiret, il n'était pas conservé, c'est corrigé.
