### ISSUE TITLE
Préparer le staging pour les tests - gestion des mails

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#490]
Le serveur de staging a été fraîchement copié de la production, pour faire des tests dans des conditions proches de la prod.

Par contre, comme les comptes utilisateurs contiennent les vraies adresses, il faut eviter l'envoi des emails vers ces utilisateurs:
* désactiver les watchlists (de-planifier les watchlists jobs)
* vider les groupes des directions pour éviter que les utilisateurs soient notifiés de la mise à jour des porteurs des démarches
* pour l'instant j'ai désactivé les emails dans l'administration, il faut les reactiver.

**Comment by lucaa** [comment]
J'ai vidé les groupes de directions et désactiver tous les scheduler jobs (watchlist & notif).
Les administrateurs, qui vont recevoir des mails d'inscription, sont: moi, @slauriere , @georges-bayard , @JeanPerrier et @ldubost .

**Comment by JeanPerrier** [comment]
Je n'ai jamais reçu de mail d'inscription lorsque GBA créait un compte.

**Comment by lucaa** [comment]
> Je n'ai jamais reçu de mail d'inscription lorsque GBA créait un compte.

@JeanPerrier : je me suis mal exprimé. Il s'agit des emails pour _valider_ les comptes avec une adresse non .gouv.fr. T'as pas reçu ceux-là non plus?

**Comment by JeanPerrier** [comment]
Si ceux  là je les ai reçus
