### ISSUE TITLE
Enlever les liens "à propos", "inscription" et "identification" du footer

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#491]
à propos n'est plus d'actualité (voir #471) , identification et inscription seront demandés / proposées aux utilisateurs quand l'authentification est nécessaire, ce qui sera le cas un peu partout maintenant, car les droits ont changé, donc il n'est plus besoin d'avoir cet URL accessible partout.

**Comment by georges-bayard** [comment]
je ne sais pas si c'est une bonne idée d'enlever le à propos qui permettrait d'expliciter à quoi sert le site. Ce serait un bon exercice d'expliquer tout cela clairement. Je propose de maintenir et d'ouvrir une nouvelle issue
