### ISSUE TITLE
Re-dimensionner l'image de l'embed de type bouton cliquable à 160px

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#493]
Il s'agit du bouton implémenté pour #420.

Aujourd'hui, l'image du bouton est très grande, et dimensionnée utilisant du style inline - voir les commentaires de #420.
J'ai vu avec @tetue ce soir, le mieux serait de ne pas avoir du style inline mais de mettre une taille d'image de dimension fixe, de largeur de 160px, sans élément de dimension dans le HTML.
Comme ça, nous pouvons toujours mettre à jour cette image.

**Comment by lucaa** [comment]
Je me suis trompée hier quand j'ai calculé la taille de l'image, dans l'exemple c'etait plutôt 160px, je modifié pour mettre a 160.

**Comment by JeanPerrier** [comment]
La taille du bouton me semble bien

**Comment by JeanPerrier** [comment]
@lucaa Nous avons compris que l'image pouvait être modifié. Est-ce que la taille du bouton peut être modifié aussi a posteriori?

**Comment by lucaa** [comment]
Oui.
