### ISSUE TITLE
Implémenter la maquette pour l'onglet de l'embed

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#494]
La maquette est ici: https://octo.invisionapp.com/share/KBQOR5MU8VY#/349622295_Code-Integration-1 , faite par @tetue .
(passer à la deuxième page de la maquette avec la fleche droite du clavier).

Les textes sont dans les commentaires de la maquette. 
Ne pas oublier de mettre à jour le nom de l'onglet.

Si complétement faite, cette tache contient les correctifs pour: #469, #476, #485 .

**Comment by lucaa** [comment]
Première étape:
![image](https://user-images.githubusercontent.com/657716/53672356-7e117880-3c82-11e9-9ce5-edb5727a6688.png)

Deuxième étape:
![image](https://user-images.githubusercontent.com/657716/53672374-8ec1ee80-3c82-11e9-8dac-ee01eca4c904.png)

**Comment by lucaa** [comment]
Enfin, pour les démarches avec une volumétrie trop importante: 
![image](https://user-images.githubusercontent.com/657716/53672520-43f4a680-3c83-11e9-9357-e74053e904d7.png)

**Comment by JeanPerrier** [comment]
Petite modification :  Remplacé "La volumétrie de cette démarche (348,003 démarches par an) requiert des conditions particulières pour l'activation du formulaire d'avis par URL. Contactez-nous pour avoir plus d'informations, en utilisant le lien en bas de l'écran." par "La volumétrie de cette démarche (348,003 démarches par an) requiert des conditions particulières pour l'activation du code à intégrer. Contactez-nous pour avoir plus d'informations, en utilisant le lien en bas de l'écran.
