### ISSUE TITLE
Le nom de l'utilisateur demandeur d'embed n'est pas correctement enregistré dans l'historique

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#496]
Voir 
![image](https://user-images.githubusercontent.com/657716/53680302-df186b00-3cd9-11e9-86c5-bb319e292c6e.png)

**Comment by JeanPerrier** [comment]
@lucaa J'ai généré un code avec mon compte Testjean5 sur la démarche pré demande de passeport. Lorsque je regarde l'historique des modifications, l'éditeur indiqué est admin user s'agissant de l'ajout d'un porteur des démarches. C'est normal?

**Comment by lucaa** [comment]
Oui, c'est normal. La generation de l'embed ne se trouve pas dans l'historique de la demarche. Cette issue parle d'un autre historique (d'un document technique).
