### ISSUE TITLE
Mise à jour des données de volumétrie pour les démarches du top 200

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#499]
Pour la mise en production de la M8, il faudrait avoir les volumétries des 200 demarches du top200 mises à jour.
Il faut:
* avoir un fichier avec les données de volumétrie associées aux démarches, par leur id. cc @JeanPerrier @georges-bayard 
* importer les données en production cc @slauriere

**Comment by JeanPerrier** [comment]
Voici le fichier d'import des données de volumétrie. L'import est fait a minima. On attendra que notre tableau excel soit stabilisé et que le modèle de donnée sur le site ait évolué pour un faire un import plus complet. 
Il faudrait toutefois vérifier que toutes les directions renseignées sont déjà créées. 
[import volumétrie.xlsx](https://github.com/DISIC/wikidemarches/files/2945800/import.volumetrie.xlsx)

**Comment by slauriere** [comment]
Bonjour Jean, Voici pour info les directions présentes dans ce fichier et qui ne sont pas encore présentes dans le référentiel actuel, je vais donc les y référencer, ainsi que les groupes d'utilisateurs associés : 
- CNED
- CROUS
- DCS
- DGESIP
- DJEPVA
- DSNJ
- ETABLISSEMENT
- SADJAV
- SCAC
- SG ESC
- SG SASFL
- SGA

**Comment by slauriere** [comment]
Dans certains cas, les volumétries (volumétrie totale et volumétrie de la dématérialisation) indiquées dans le fichier diffèrent de celle indiquée sur le site de production, cf par exemple la démarche n°881. 
Est-ce bien la volumétrie indiquée dans le fichier qui prévaut ? Par ailleurs, dans le cas où une volumétrie est présente en production mais pas dans ce fichier, souhaitez-vous que l'on conserve la volumétrie indiquée en production (ce n'est pas forcément facile à faire automatiquement, à voir, mais on peut en tout cas vous fournir les volumétries existantes sur le site de production pour les démarches indiquées), ou qu'on réinitialise celle-ci ?

**Comment by JeanPerrier** [comment]
Bonjour Stéphane,

La volumétrie du fichier prévaut. 
On conserve les volumétries préexistantes en production dans les autres cas. 
Erratum: Peux-tu exclure les démarches MEAE du fichier d'import? Je préférerais que l'on mette à jour les volumétries pour les affaires étrangères plus tard.

**Comment by slauriere** [comment]
Ok Jean merci pour ces infos. J'ai bien exclu les démarches MEAE du fichier d'import.

Question complémentaire : pour les adresses web des démarches, je pensais appliquer la même règle – donner la prévalence au fichier – mais peux-tu me confirmer stp ? Par exemple, pour la démarche [1677](https://nosdemarches.gouv.fr/Demarches/1677), on a ceci, qui pose question, non ?
- Dans le fichier, l'adresse web indiquée est : https://wwwd.caf.fr/wps/portal/caffr/aidesetservices/lesservicesenligne/faireunedemandedeprestation/demanderlaideaulogement
- Sur le site de production : https://wwwd.caf.fr/wps/portal/caffr/aidesetservices/lesservicesenligne/faireunedemandedeprestation/demanderlaprimedactivite/

**Comment by JeanPerrier** [comment]
Bien vu, un décalage d'une ligne s'est mis dans la colonne des URL à partir de la démarche numéro 892 qui devrait avoir l'URL "https://dossiersco.beta.gouv.fr/".
[import volumétrie2.xlsx](https://github.com/DISIC/wikidemarches/files/2953001/import.volumetrie2.xlsx)

Ci-joint un fichier d'import avec la correction et sans les démarches MEAE

**Comment by slauriere** [comment]
Jean, J'ai utilisé les données de ce deuxième fichier et je les importées sur la préprod. Les démarches importées sont visibles [cette adresse](https://nosdemarches-staging.devxwiki.com/Main/AllDocs#|t=alldocs&p=1&l=100&s=doc.date&d=desc&doc.location=demarches.&doc.date=1552345200000-1552431599999&doc.author=XWiki.slauriere), soit 224 démarches (et non 229 comme dans le fichier d'origine car il y a plusieurs doublons : 813,1869,1244,1258,1291). Je n'ai identifié ces doublons qu'au moment de l'import, du coup de je n'ai pas fusionné les données en amont, est-ce que ce serait ok pour toi qu'on mette à jour les données directement sur le site plutôt que de tout retraiter ? Concernant les autres démarches : j'ai vérifié quelques données ponctuelles, est-ce que tu peux y jeter un œil de ton côté aussi peut-être pour me donner ton go pour un import sur le site de production lui-même ?

NB : les nouvelles directions n'ont été créées que sur le site de production.

**Comment by slauriere** [comment]
Il y a un truc curieux avec l'URL de mon dernier commentaire, désolé, je vais regarder. En attendant voici l'URL à copier / coller, cela fonctionne pour moi alors que l'ouverture directe du lien ci-dessus ne fonctionne pas : 

`
https://nosdemarches-staging.devxwiki.com/Main/AllDocs#|t=alldocs&p=1&l=100&s=doc.date&d=desc&doc.location=demarches&doc.date=1552345200000-1552431599999
`

Voici également la procédure manuelle, au cas où : 
- Se rendre sur https://nosdemarches-staging.devxwiki.com/Main/AllDocs
- Filtrer sur la date du jour
- Filtrer éventuellement en plus sur l'auteur : slauriere

**Comment by JeanPerrier** [comment]
La 1244 n'est pas en doublon. Il faudra modifier manuellement les démarches suivantes:
- Demande de certificat de situation administrative (non gage) simple
- Déclaration de cession d'un véhicule
- Faire une demande de changement de titulaire sur son certificat   d’immatriculation de véhicule (demande de nouveau certificat   d’immatriculation suite à cession de véhicule)
- Demander son certificat de situation administrative (non gage )   détaillé
- Changement d'adresse en ligne
- Désignations   de délégué à la protection des données
- Déclaration   d’Échanges de Biens  (DEB)
- Déclaration   d’Échanges de Biens  communautaires

**Comment by slauriere** [comment]
Pardon c'était la démarche 1242 qui était en doublon et non la 1244. Je viens d'effectuer l'import sur le site de production et de vérifier quelques démarches, qui sont bien ok de mon côté.

**Comment by JeanPerrier** [comment]
OK j'ai effectué les modifications des démarches en doublon
On peut fermer l'issue non?

**Comment by slauriere** [comment]
OK. Pour moi c'est ok oui, je clos !

**Comment by JeanPerrier** [comment]
@slauriere @lucaa Bonjour, je suis désolé j'ai fait une erreur importante. Dans le fichier excel, la volumétrie était décalée d'une ligne également. Toutes les volumétries importées sont fausses. 
Deux solutions:
- on refait un import qui écrase l'ancien. 
- on attend de faire l'import du top 250 (car on aura probablement pas des porteurs qui mettront le bouton pour de grosses démarches)

**Comment by lucaa** [comment]
Dans le fichier CSV que j'ai vu (qui a été utilisé pour l'import, je crois), il y avait également d'autre problèmes: quelques démarches apparaissaient plusieurs fois, avec des données differentes (813) et il y avait une démarche avec une volumétrie importante (~240 000 000) pour laquelle je ne comprends pas la source (mais ceci peut être juste une histoire de sources d'informations manquantes de ma part).
@JeanPerrier est-ce possible de préparer un fichier avec les bonnes données, de ton coté, pour discuter autour de ce fichier ou tu préfères discuter avant?

**Comment by JeanPerrier** [comment]
[import volumétrie4.xlsx](https://github.com/DISIC/wikidemarches/files/3029137/import.volumetrie4.xlsx)

**Comment by JeanPerrier** [comment]
@lucaa @slauriere Voici ci dessus le fichier d'import. Qu'en dites vous?

**Comment by lucaa** [comment]
@JeanPerrier j'ai essayé de t’appeler aujourd'hui pour voir la priorité de cette tache aujourd'hui, mais sans résultat positif. Je vais regarder lundi et essayer de préparer le nouvel import asap.

**Comment by JeanPerrier** [comment]
@lucaa le ministère de l'intérieur m'a demandé de corriger les volumétries dans le back office aujourd'hui. Ou bien vous arrivez à le faire aujourd'hui ou bien vous n'y arrivez pas et donc je corrige manuellement les volumétries pour ce ministère.

**Comment by JeanPerrier** [comment]
il faut créer cette direction MI CNAPS pour "conseil national des activités privées de sécurité"

**Comment by JeanPerrier** [comment]
Il faudrait aussi mettre par défaut en actif les démarches importées

**Comment by lucaa** [comment]
@slauriere pourquoi as-tu enlevé la mention de "volumétrie" du titre de cette tache? Le scope a été élargi?

**Comment by slauriere** [comment]
J'ai rétabli la mention "volumétrie" dans le titre de cette tâche. Cette tâche sera traitée dans le cadre plus large de #571 qui concerne l'import des données du top 250, y compris de la volumétrie.

**Comment by lucaa** [comment]
j'ai ajouté l'etiquette "duplicate" pour marquer qu'il n'y aura pas de correctif spécifique à cette tache, mais le travail sera fait dans le cadre d'une autre (#571).
