### ISSUE TITLE
Donner la possibilité de renseigner une date de mise en ligne antérieure à 2009

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#500]
On ne peut pas indiquer une « Date de mise en ligne » antérieur à 2009.

**Comment by slauriere** [comment]
En fait c'est possible de saisir une date antérieure à 2009 : il faut sélectionner 2009, puis rouvrir le widget de sélection : en principe celui-ci s'affiche avec les 10 années antérieures (1999-2008), et ainsi de suite. -> Je clos cette tâche.
