### ISSUE TITLE
ajouter une zone à propos dans le footer

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#504]
texte (première version en validation : 
À propos de MonAvis.numerique.gouv.fr
----------------------------------------------------------------------------
Ce site a pour objet de permettre le suivi de l’avancement de la dématérialisation des services publics, tant pour savoir le reste à faire pour atteindre la promesse du 100% de démarches accessibles en ligne que pour mesures la qualité des outils numériques mis en place du point de vue des utilisateurs.
100% des démarches administratives accessibles en ligne au 1er janvier 2022 : c’est l’une des mesures phares annoncées par le gouvernement pour accélérer la transformation numérique de l’administration française menée dans le cadre du programme Action Publique 2022.
Premier pas vers cet objectif annoncé lors du Comité interministériel de la transformation publique (CITP) du 1er février 2018 : le lancement en mars dernier, de demarches-simplifiees.fr, permettant aux administrations de dématérialiser facilement les démarches encore gérées sur papier. Le site comptabilise aujourd’hui plus de 30 000 démarches dématérialisées.
La direction interministérielle du numérique et du système d’information et de communication de l’Etat (DINSIC) lance le site MonAvis.numérique.gouv.fr, tableau de bord ouvert et contributif des démarches administratives accessibles en ligne. L’outil répond à une double ambition :
•	mesurer la satisfaction des usagers concernant les démarches en ligne existantes afin d’identifier les démarches exemplaires et celles ayant besoin d'être améliorées,
•	présenter un tableau de bord des démarches « iconiques » c’est-à-dire qui représentent les volumétries les plus importantes (200 000 démarches par an)
Grâce à MonAvis.numérique.gouv.fr,
•	Les usagers de l’administration disposeront d’un moyen simple d’exprimer leurs avis sur les démarches administratives, à la fin de démarches en ligne qu’ils auront effectuée.
•	Les ministères et administrations publiques disposeront d’un outil qui leur permettra d’installer à peu de frais d’un outil permettant de mesurer la satisfaction de leurs usagers à la fin de leurs démarches administratives. L’offre se présente sous la forme d’un bouton qui est très simplement installé à la fin des démarches administratives. Ce bouton permet d’accéder à un formulaire d’avis.
•	A l’ensemble des parties prenantes d’accéder aux données essentielles concernant l’avancement du chantier de la dématérialisation et du ressenti des utilisateurs
MonAvis.numerique.gouv.fr sera régulièrement mis à jour grâce aux retours utilisateurs, dans une logique d’amélioration continue. Le gouvernement franchit ainsi une nouvelle étape vers la totalité des démarches administratives accessibles en ligne, et espère ainsi rapprocher les citoyens de leurs administrations et améliorer la qualité des services publics rendus.
« Avec cet outil ouvert et contributif, nous souhaitons associer les usagers et utilisateurs de démarches en ligne à la transformation numérique de la France, car celle-ci ne peut se faire sans ceux qui la vivent au quotidien. Mieux connaître vos besoins, vos attentes et vos irritants pour orienter en conséquence la dématérialisation des services publics : c’est cela que permet cette plateforme. »
Mounir Mahjoubi, secrétaire d’Etat auprès du Premier ministre, chargé du Numérique.

**Comment by JeanPerrier** [comment]
Moi je pense que le a propos n'est pas utile pour le grand public. A la limite, il faut une page explicative pour les agents administratifs

**Comment by JeanPerrier** [comment]
Mais le site doit être suffisamment fluide pour qu'aucun agent public ne trouve le besoin de cliquer sur le a propos.

**Comment by JeanPerrier** [comment]
Je ferme car la #471 existe déja.

**Comment by georges-bayard** [comment]
je propose qu'on ne touche à rien pour l'instant tant que le discours n'est pas définitivement calé. Je rouvre et mets en M10

**Comment by lucaa** [comment]
Je re-ferme cette tache, car elle a été déjà fermée comme un doublon de #471. Je bouge la #471 en M10, pour faire le travail.
