### ISSUE TITLE
ajouter un texte d'explication sur la page de connexion à MonAvis

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#507]
Ce site permet aux administrations publiques de mettre en place des outils de mesure de la satisfaction des usagers sur les démarches administratives. Il permet également de piloter le chantier de la dématérialisation des services publics en recensant les démarches administratives présentées sous forme de tableau de bord

**Comment by JeanPerrier** [comment]
Afficher l'écran de connexion en dessous avec peut-être la mention "réservé à l'administration", qu'en penses tu @georges-bayard ?

**Comment by JeanPerrier** [comment]
Proposition de correction du texte:

Ce site permet aux administrations publiques de mettre en place des outils de mesure de la satisfaction des usagers sur les démarches administratives effectuées par ces derniers. Il permet également de piloter le chantier de la dématérialisation des services publics en recensant les démarches administratives et en les présentant sous la forme de tableau de bord.

**Comment by JeanPerrier** [comment]
validée par GBA

**Comment by lucaa** [comment]
![image](https://user-images.githubusercontent.com/657716/54042161-be647f80-41c9-11e9-9996-70c83d0b3a8f.png)

**Comment by lucaa** [comment]
![image](https://user-images.githubusercontent.com/657716/54042289-0e434680-41ca-11e9-92e6-c4b6eb231a19.png)

**Comment by lucaa** [comment]
![image](https://user-images.githubusercontent.com/657716/54042446-7134dd80-41ca-11e9-9259-9ac76ab22943.png)

**Comment by lucaa** [comment]
![image](https://user-images.githubusercontent.com/657716/54042561-b822d300-41ca-11e9-8bca-022ec280daa8.png)

**Comment by lucaa** [comment]
Visuellement, ça doit ressembler à la 4ème proposition.

**Comment by lucaa** [comment]
Le message a été ajouté, finalement la 3ème proposition a été gardé, car plus simple à mettre en place, mais le texte du message est correctement aligné au formulaire à droite.

**Comment by JeanPerrier** [comment]
Pour moi c'est bon.

**Comment by georges-bayard** [comment]
Nouveau texte plus léger : 
"Ce site permet aux administrations publiques de mettre en place des outils de mesure de la satisfaction des usagers sur les services en ligne. Il permet également de piloter le chantier de la dématérialisation en recensant les démarches administratives et en les restituant sous la forme de tableaux de bord."

**Comment by lucaa** [comment]
La modification a été faite.
