### ISSUE TITLE
Adapter le moteur de recherche en fonction du nouveau public porteur de démarche

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#509]
Faudrait-il que le moteur de recherche propose les mêmes résultats que pour les admins? 
Par exemple afficher les démarches en brouillon également?

**Comment by lucaa** [comment]
Par rapport au filtrage en fonction du statut de démarche le comportement aujourd'hui est le même pour tous les utilisateurs:
* les résultats de recherche ne contiennent pas les démarches marquées inactives ou celles en état "nouvelle demarche" (ajoutées par les administrateurs). Toutes les autres statuts apparaissent dans les résultats, y compris les "demandes utilisateurs" et les "demandes porteurs". 

Pour avoir acces à toutes les démarches, les administrateurs peuvent consulter le listing de démarches sous forme de tableau, la recherche full text est réservée aux démarches actives ou ajoutées par les utilisateurs ou les porteurs.

Faut-il changer cela?

**Comment by georges-bayard** [comment]
1 / L'accès de MonAvis à des votants  va à priori bientôt disparaître
2 / La recherche full text est plutôt faite pour les utilisateurs extérieurs et non pour les administrateurs de démarche
3 / Je pense donc qu'il ne faut rien changer pour l'instant tant que MonAvis reste Open. On fera l'évolution quand on aura fermé MonAvis

**Comment by marineb** [comment]
On peut fermer cette issue @georges-bayard @lucaa ?

**Comment by georges-bayard** [comment]
oui c'est une relique je cloture
