### ISSUE TITLE
Vérifier l'actualité du texte de la page CGU, modifier si necéssaire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#511]

**Comment by lucaa** [comment]
Min: 
- remplacer le nom du directeur de la Dinsic

**Comment by JeanPerrier** [comment]
[cguV2.docx](https://github.com/DISIC/wikidemarches/files/2952305/cguV2.docx)

**Comment by JeanPerrier** [comment]
Voici le texte à remplacer.

**Comment by slauriere** [comment]
J'ai mis à jour le texte. Jean te laisse vérifier que c'est bien ok et clore le ticket si bien ok pour toi ?

https://nosdemarches-staging.devxwiki.com/Main/CGU
