### ISSUE TITLE
Supprimer XWiki.AccountValidation de la liste des pages exclues du paquet d'upgrade

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#513]
Je ne comprends pas exactement pourquoi cette page est exclue des pages upgradables...
Pour rappel, une page est exclue uniquement si c'est prévu qu'elle reçoit des modifications sur le serveur ou elle est deployé (en general manuelles) par rapport à la version du SCM.

**Comment by slauriere** [comment]
Effectivement, confusion de ma part, j'ai supprimé la page du pom d'upgrade.
