### ISSUE TITLE
Mettre la limite de volumétrie pour l'obtention du code de bouton à 5.000.000.

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#514]
Suite de l'issue #470

**Comment by JeanPerrier** [comment]
Pour des raisons de politique interne, on aimerait élever la limite de volumétrie pour l'obtention du code du bouton à 5 millions. Seulement 24 démarches du top 200 seraient ainsi exclus de la "procédure bout en bout du porteur de la démarche pour obtenir le code du bouton". 
5 millions représentent un vote toute les minutes à peu près, 200.000 votes par an.
En sachant que peu de gens vont venir nous voir à partir du 15 mars pour mettre le bouton, est-ce que ce selon vous c'est un risque que l'on peut prendre?

**Comment by lucaa** [comment]
La limite a été bougée a 5000000 .

**Comment by georges-bayard** [comment]
d'après vous pas d'impact performances ?

**Comment by JeanPerrier** [comment]
@lucaa Peux tu répondre à Georges?

**Comment by lucaa** [comment]
> d'après vous pas d'impact performances ?

Si, mais l'idée est d'implémenter #421 suffisamment vite après et remplacer le bouton avec l'embed dès qu'il est prêt, avec la stratégie de collecte d'avis sélective prévue pour cet embed.
Suffisamment vite = avant que le nombre d'avis collectés par le bouton pour les démarches à forte volumétrie pose un problème.

**Comment by JeanPerrier** [comment]
Dans l'étude de scalabilité pour la prochaine milestone, il faudra que l'on sache quelle est la volumétrie max que peut supporter le site.
