### ISSUE TITLE
Supprimer dans la synthèse des avis la partie "modalités"

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#517]

**Comment by lucaa** [comment]
@JeanPerrier tu peux fournir un peu plus de détails (capture écran) pour comprendre de quel élément il s'agit? exprimé comme ça ça me dit rien...

**Comment by JeanPerrier** [comment]
![Capture](https://user-images.githubusercontent.com/44236635/55222450-38f24f00-520c-11e9-8274-ffc87e3a9aa9.PNG)

**Comment by JeanPerrier** [comment]
cette partie de la synthèse n'aura plus d'utilité.

**Comment by lucaa** [comment]
yes. C'est bcp plus clair. Je me permets de mettre à jour le titre de l'issue.

**Comment by lucaa** [comment]
Fait par #666 , je ferme comme doublon.
