### ISSUE TITLE
Changer le nom "demarches locales" en "demarches territoriales"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#518]
Sur l'onglet d'informations de la démarche mais aussi partout ou ce texte apparaît.

**Comment by JeanPerrier** [comment]
Je ne vois pas la modification en staging.

**Comment by lucaa** [comment]
> Je ne vois pas la modification en staging.

C'est normal, j'ai installé en staging à 14:14. Tu peux checker maintenant?
