### ISSUE TITLE
Import démarches ministère des armées

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#519]
Il faut créer une nouvelle direction et des nouveaux évènements de vie. 
[Imports démarches Ministère des Armées V2.xlsx](https://github.com/DISIC/wikidemarches/files/3038027/Imports.demarches.Ministere.des.Armees.V2.xlsx)

**Comment by JeanPerrier** [comment]
Créer aussi une direction pour SPM intitulé "Miviludes"

**Comment by JeanPerrier** [comment]
Direction des Ressources Humaines de l´Armée de Terre (DRHAT)

**Comment by JeanPerrier** [comment]
La Direction des patrimoines, de la mémoire et des archives (DPMA)

**Comment by JeanPerrier** [comment]
Par la même occasion ces directions MI:
- PP pour Préfecture de Police
- OFPRA pour Office français de protection des réfugiés et apatrides
- OFII Office français de l'immigration et de l'intégration

**Comment by slauriere** [comment]
Concernant l'enregistrement de nouvelles directions dans le wiki : le plus simple est de passer par le formulaire dédié à la création de directions, qui sera disponible dans la section "Administration" du wiki lors de la prochaine livraison (cf #557).

**Comment by georges-bayard** [comment]
cela veut dire que l'on n'aura plus besoin de te solliciter pour créer un ministère ?

**Comment by slauriere** [comment]
Oui, pour créer une direction (les ministères vous pouvez déjà en créer de nouveaux directement sur la plateforme en cliquant sur "Créer" puis en sélectionnant "Type de page : Ministère"). Les directions ont la particularité d'avoir un groupe d'utilisateurs associé, c'est ce que permet cet utilitaire : créer en une seule fois la direction et le groupe qui lui est associé, à l'endroit attendu dans l'arborescence (on pourrait si besoin intégrer cette opération à l'interface standard, pour que la procédure soit la même que lorsqu'on crée un ministère, un public, un événement de vie...).

**Comment by slauriere** [comment]
J'ajoute pour mémo que certaines démarches de ce fichier ont été créées entre temps dans le cadre de l'import du top 250 (#571) -> veiller à la cohérence.

**Comment by slauriere** [comment]
Les données du ministère des armées ont été importées sur la plateforme de pré-production, pour validation avant import en production. La procédure d'import a consisté en les étapes suivantes :

- Création des nouveaux publics suivants : "Veuf, veuve", "Parents", "Victimes de guerre / terrorisme"
- Création du nouvel événément de vie "J'effectue mon service national / civique"
- Formatage des dates sous la forme MM/yyyy
- Mise à jour du fichier de configuration d'import en batch pour prendre en compte les entêtes du fichier reçu et initialiser les champs non renseignés à "non renseigné", ainsi que la valeur "top 250" à "non" hormis pour les démarches qui font explicitement partie du top 250.
- Fusion des données relatives aux 8 démarches déjà existantes avant import (notamment suite à l'import du top 250), à savoir les démarches numéros : 1173, 1879 (conflit entre la direction indiquée dans le top 250 et celle indiquée dans le fichier ; c'est celle du top 250 qui a été privilégiée), 1979, 1980, 1981, 1982, 1983, 1984

Statistiques de comparaison des données du fichier avec celles importées : 
- Avant import, 8 démarches rattachées au MA
- Après import, 43 démarches rattachées au MA
- Catégories de publics = particuliers : 43 démarches
- Directions: DPMA : 18 démarches,  SGA : 24 démarches,   DSNJ : 1 démarche. Total : 43 démarches
- Organisme de traitements : Office national des anciens combattants et victimes de guerre : 12 démarches, SHD : 18 démarches, DRH-MD/Sous-direction des Pensions: 9 démarches, DSNJ: 3 démarches, Lycées de défense : 1. Total : 43 démarches

@georges-bayard, je laisse valider si cela te semble ok sur le serveur de pré-production ?

**Comment by georges-bayard** [comment]
c'est ok pour moi sauf que je ne retrouve pas la MIVILUDES et l'OFII

**Comment by slauriere** [comment]
Effectivement, MIVILIUDES et OFII ne sont pas présentes car sauf erreur de ma part, aucune démarche du fichier à importer ne leur est rattachée, c'est pour cela que je ne les ai pas encore créées. Mais elles peuvent l'être directement sur le site de production de même que les autres mentionnées ci-dessus (DRHAT, PP, OFPRA, ...) depuis le lien "Création de direction" dans [la zone d'administration](https://monavis.numerique.gouv.fr/Administration/). À ta dispo GBA si tu souhaites que je le fasse. J'attends ton go sur ce point pour procéder à l'import des démarches elles-mêmes en production, pour être sûrs qu'on est bien en phase sur les directions.

**Comment by georges-bayard** [comment]
c'est quoi cette page ? comment y accède t'on par l'application ? Ca permet à priori de faire plein de choses ! OK pour l'import des démarches par ailleurs

**Comment by slauriere** [comment]
J'ai effectué l'import en production, j'ai vérifié les compteurs ci-dessus et j'ai vérifié tous les champs de trois démarches au hasard : tout est ok de mon côté. Georges je te laisse vérifier et rouvrir la tâche si besoin ?

Concernant la page d'administration : elle mêle actuellement des pages purement techniques et des pages de fonctionnalités liées aux contenus, et des liens vers d'autres pages d'administration plus spécifiques (Demarches.Admin, Avis.Admin) -> on pourrait éventuellement créer un ticket dédié pour réfléchir à l'organisation de ces pages et à leur accès via l'application ? À voir...
