### ISSUE TITLE
les résultats du vote s'affichent mal sur NosDémarches

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#522]
![Capture](https://user-images.githubusercontent.com/17125654/54817353-0211bb80-4c97-11e9-8412-f750758429ae.PNG)

**Comment by georges-bayard** [comment]
exemple pour modification d'une association

**Comment by lucaa** [comment]
C'est corrigé, suite à ma modification en production de vendredi. 
Je dois encore investiguer un peu pour comprendre exactement ce qu'il s'est passé en production pour arriver à cette situation.

**Comment by lucaa** [comment]
> Je dois encore investiguer un peu pour comprendre exactement ce qu'il s'est passé en production pour arriver à cette situation.

Le mystère est résolu: le problème était lié à une restauration ratée d'une ancienne version du script, datant de 12/03. Ainsi, le problème n'a pas impacté la production trop longtemps.
