### ISSUE TITLE
Refonte de la page d'accueil (faire une maquette rapidement à montrer)

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#525]
Présentation de la page d'accueil en trois parties : 

1/ Texte de présentation: 
"Ce site permet aux administrations publiques de mettre en place des outils de mesure de la satisfaction des usagers sur les services en ligne. Il permet également de piloter le chantier de la dématérialisation en recensant les démarches administratives et en les restituant sous la forme d'un tableau de bord."

2/ bouton/lien vers le tableau de bord

3/ Authentification en plus petit.

**Comment by lucaa** [comment]
Même tache que #546, plus d'actualité, comme #546 (voir commentaire de la #546).
