### ISSUE TITLE
Faire évoluer le champ ministère ainsi que les intitulés des "ministères"

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#527]
cf https://dinsic.xwiki.com/xwiki/wiki/projetdemat/edit/main/Sp%C3%A9cifications%20M9/M%C3%A9tadonn%C3%A9es%20des%20d%C3%A9marches/WebHome?section=1

**Comment by JeanPerrier** [comment]
1/ Le champ actuel "ministère" prendra le nom de champ ministériel. 
2/ Dans l'excel ci-joint, les "ministères" obtiennent de nouveaux noms. 
[Nouveaux champs ministériels V1.xlsx](https://github.com/DISIC/wikidemarches/files/3085083/Nouveaux.champs.ministeriels.V1.xlsx)
3/ Les ministères MCT et MTES doivent fusionner pour former une seule entité Environnement/ Cohésion des territoires

**Comment by slauriere** [comment]
Le champ "ministère a été renommé en "Champ minstériel". Concernant les nouveaux noms des ministères : vu le petit nombre de ministères concernés (20), cela sera plutôt plus rapide de faire l'opération directement sur le site de production plutôt que de passer par une procédure d'import. Je peux le faire si tu veux @georges-bayard ? Le troisième point (fusion MCT et MTES en MECT) a été traité dans le cadre de la reprise et fusion de données #551.

**Comment by georges-bayard** [comment]
@slauriere : je peux aussi le faire pour faire un check des intitulés

**Comment by lucaa** [comment]
Nous allons travailler à base d'un fichier excel d'export des ministeres courants, mis à jour.

**Comment by georges-bayard** [comment]
fusion MTES et MCT
Code de la nouvelle entité : MTES/MCT
Nom complet : écologie / cohésion des territoires

**Comment by lucaa** [comment]
Voici le fichier tel que exporté de la production, avec tous les ministeres. La colonne à mettre à jour est la colonne B "Nom du ministère", pour les lignes pour lesquelles il est nécéssaire. Le reste doit rester pareil.
[ministeres_14_05_2019.xlsx](https://github.com/DISIC/wikidemarches/files/3177643/ministeres_14_05_2019.xlsx)

**Comment by lucaa** [comment]
Les noms des ministères ont été mis à jour en production par @georges-bayard , j'ai repris les noms pour les serveurs de dev & staging. L'issue est faite, plus besoin de remplir le fichier excel, je ferme.
