### ISSUE TITLE
Re-ouvrir l'ajout de nouvelle démarche à tous les utilisateurs

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#529]
Défaire #425 + quelques modifications supplémentaires:
* revenir sur l'affichage d'une démarche nouvelle: #453 
* ajouter un nouvel état pour une démarche, "demande ajout porteur". Les démarches dans cet état ne seront pas affichées comme des démarches nouvelles.

Le formulaire d'ajout de nouvelle démarche reste le même pour tout le monde (utilisateur authentifié ou pas), celui implémenté dans #426 .

**Comment by lucaa** [comment]
> Le formulaire d'ajout de nouvelle démarche reste le même pour tout le monde (utilisateur authentifié ou pas), celui implémenté dans #426 .

@JeanPerrier , @georges-bayard : j'ai 2-3 doutes là-dessus, ça peut être compliqué comme formulaire, pour un utilisateur qui n'est pas forcement porteur de démarche...

**Comment by JeanPerrier** [comment]
Cette fonctionnalité d'ajout de démarche pour l'utilisateur non authentifié est une fonctionnalité dépriorisée. On laisse le nouveau formulaire. Par contre il faut vérifier que :
1/ la Direction ne soit pas une information obligatoire pour ajouter une démarche;
2/ La direction ne soit pas affichée comme étant obligatoire.

**Comment by lucaa** [comment]
> 1/ la Direction ne soit pas une information obligatoire pour ajouter une démarche

Pour tous les utilisateurs ou uniquement pour les utilisateurs non-identifiés?

**Comment by JeanPerrier** [comment]
uniquement pour les utilisateurs non identifiés

**Comment by lucaa** [comment]
> uniquement pour les utilisateurs non identifiés

Due à la manière d'implémenter la validation, techniquement ça peut s'averer assez complexe de personnaliser la validation en fonction de l'utilisateur courant. 
Je vais regarder + en détail et proposer une solution.

**Comment by JeanPerrier** [comment]
Georges avait proposé deux statuts de démarches:
-Demande utilisateur
-Demande porteur. 

Il te ne l'avait pas indiqué dans un mail?

**Comment by lucaa** [comment]
> Il te ne l'avait pas indiqué dans un mail?

Si, si, mais cela ne suffit pas pour techniquement implémenter une différence de validation facilement...

**Comment by lucaa** [comment]
> Due à la manière d'implémenter la validation, techniquement ça peut s'averer assez complexe de personnaliser la validation en fonction de l'utilisateur courant.
> Je vais regarder + en détail et proposer une solution.

Finalement, c'était pas si compliqué, c'est fait.

**Comment by lucaa** [comment]
Les deux status ont été également ajoutés, les invités peuvent ajouter des démarches aussi, et l'affichage d'une démarche ajoutée par un utilisateur est à nouveau accompagné d'un message expliquant que c'est une contribution.
