### ISSUE TITLE
Les fiches Cerfa numérique ne doivent pas être visibles des utilisateurs non authentifiés

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#544]
Sauf erreur de ma part, les fiches Cerfa numérique ne doivent pas être visibles des utilisateurs non authentifiés sur monavis.numerique.\*, mais seulement sur cerfa.numerique.\*. Ce ticket vise à corriger cela.

**Comment by slauriere** [comment]
Un test sur la variable "isGuest" a été (ré)ajouté dans le code de DemarchesSheet pour que l'onglet Cerfa numérique ne soit affiché que dans le cas où cette variable est "false".

**Comment by lucaa** [comment]
Ce problème impacte uniquement la version 8.1, qui represente une bifurcation fonctionelle qui n'a pas été continuée.
