### ISSUE TITLE
De-faire les modifications de la M8.1 pour revenir au comportement de la M8

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#545]
Il s'agit de de-faire les modifications suivantes, qui ont été faites pour la M8.1:
* #528
* #529 
* #532 
* #531 
* #530 

À noter que, par dessus de ces modifications, la page d'accueil sera re-faite pour être accessible aux utilisateurs non-identifiés et pareil pour le tableau de bord, dans des taches spécifiques à la version M8.2 .

Note 2:
Nous gardons #533 (car les URLs n'ont pas été mise à jour chez tous les intégrateurs), #537, #408 , etc.

**Comment by lucaa** [comment]
Cette tache n'est plus d'actualité, cette définition de la milestone 8.2 ne sera plus faite.

**Comment by lucaa** [comment]
Finalement ces taches sont a faire, sont planifies dans la M9.

**Comment by lucaa** [comment]
> Finalement ces taches sont a faire, sont planifies dans la M9.

M10.

**Comment by lucaa** [comment]
La page d'accueil est à ne pas toucher, sera traité par #546 .

**Comment by slauriere** [comment]
Les pages impactées par les revert commits ci-dessus sont les suivantes :

* Demarches/Code/DemarcheAvisFormTab.xml
* Demarches/Code/DemarcheTab.xml
* Demarches/Code/DemarchesMacros.xml
* Demarches/Code/DemarchesSheet.xml
* Demarches/Code/NewDemarche.xml
* Demarches/Code/WikiDemarchesTranslations.xml
* TableauDeBord/WebPreferences.xml

Elles ont été importées depuis la branche 545 sur le site de développement et les tests suivant ont été effectués en mode non authentifié :

* Pas de possibilité de créer une nouvelle démarche
* Démarche : affichage uniquement des informations générales d'une démarche, et d'une invitation à s'authentifier
* Interdiction d'accès à TableauDeBord.WebHome
* Accès page d'accueil : ok
* Accès aux fiches Cerfa numérique : ok

**Comment by slauriere** [comment]
## Résumé

* Ajout de nouvelle démarche
  * Protéger la page
  * Le bouton d'ajout de démarche reste présent dans la recherche et dans la suggestion mais il nécessite une authentification
  * Simplfiier le processus de soumission d'avis : il n'est plus possible de donner son avis après avoir ajouté une nouvelle démarche
  * Enlever le fond hachuré
* Onglets
  * Formulaire d'avis : disponible uniquement par lien direct, et possible même sans clef d'API
  * Statistiques d'avis : ne pas inclure l'onglet, et dans l'onglet lui-même et dans l'export CSV #483 faire une vérification des autorisations
  * Idem pour la liste des avis
  * L'utilisateur non authentifié voit un message et un bouton de logins

## Spécifications et tests de référence

* [Spécifications M8](https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M8%20-%20Embed/)
* [Tests v3](https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M8%20-%20Embed/Test%20Scenarios%20v3_0) - NB : deux types d'URLs à tester : celles correspondant au code d'intégration du bouton d'avis, et celles générées avant les clefs d'API, cf exemple sur [Fabriquer une URL de formulaire d'avis](https://github.com/DISIC/wikidemarches/wiki/Comment-fabriquer-une-URL-de-formulaire-d'avis-pour-une-d%C3%A9marche).

## Remarques

Confronter les changements aux commits référencés dans les taches liées.

**Comment by slauriere** [comment]
Les modifications indiquées ont été implémentées et testées -> je ferme ce ticket.
