### ISSUE TITLE
Mentionner dans les CGU Xwiki SAS

### ISSUE THREAD

**Issue by JeanPerrier** [DISIC/wikidemarches#548]

**Comment by lucaa** [comment]
@JeanPerrier est-ce que tu as une idée du texte que tu veux mettre pour exprimer ça?

**Comment by georges-bayard** [comment]
Prestataires d'hébergement
XWiki SAS
RCS Paris n° 477 865 281
Code APE : 6311Z
N°TVA : FR 69 477 865 281
Siège social : XWiki SAS, 35/37 rue Beaubourg
75003 Paris
France

OVH
RCS Roubaix – Tourcoing 424 761 419 00045
Code APE 6202A
N° TVA : FR 22 424 761 419
Siège social : 2 rue Kellermann
59100 Roubaix
France

**Comment by georges-bayard** [comment]
texte ci-dessus à intégrer dans les CGU

**Comment by lucaa** [comment]
La note a été ajoutée.
