### ISSUE TITLE
Reprise de données suite à la modification du modèle de démarche

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#551]
De nouvelles propriétés ont été ajoutées au modèle de données dans le cadre de #550. Cette tâche-ci concerne la reprise de certaines propriétés existantes et leur migration vers les nouvelles. Les migrations à effectuer sont décrites dans le document de spécification "Spécifications M9.Métadonnées des démarches".

**Comment by georges-bayard** [comment]
on peut se voir demain pour faire un point sur le modèle de données et les questions en suspens ?

**Comment by lucaa** [comment]
> on peut se voir demain pour faire un point sur le modèle de données et les questions en suspens ? 

On décale le point pour une date future. Nous allons essayer d’échanger sur des taches "à spécifier" et faire des points téléphoniques pour les éléments plus compliqués.

**Comment by slauriere** [comment]
Georges, Les spécs indiquent de fusionner les données MCT et MTES. On les fusionne dans quel minstères cible : MCT ou MTES ? @georges-bayard

**Comment by georges-bayard** [comment]
regrouper sous un seul ensemble : MECT, pour ministères chargés de l’écologie et de la cohésion des territoires. Question : pourra on revenir en arrière pour retrouver l'affiliation précédente ?

**Comment by slauriere** [comment]
Ok vu pour MECT merci (j'ai mis à jour les spécifications pour refléter cela). L'affiliation précédente restera disponible dans l'historique de chaque démarche donc on pourra la retrouver oui, simplement cela prendra un certain temps processeur (l'information ne sera pas disponible par une simple requête à la base de données contrairement à l'information actuelle).

**Comment by slauriere** [comment]
Dans le document de spécification, sur la ligne "Démarches simplifiées" il est écrit "Reprendre les données", et plus bas sur la ligne "Caractéristiques de la dématérialisation" il est écrit : "on supprime la donnée démarches simplifiées". D'où doit-on donc reprendre la donnée "Démarche simplifiée", si on doit effectivement la reprendre ? @georges-bayard

**Comment by slauriere** [comment]
Au sujet de la récupération des affiliations précédentes (question de Georges ci-dessus) : qu'en penses-tu Anca ? @lucaa

**Comment by georges-bayard** [comment]
@slauriere  on garde la donnée et on reprend l'existant. Aujourd'hui c'est un flag dans une liste. On la supprime et on la remplace par un champ autonome sous forme de case à cocher (avec deux valeurs possibles : non coché ou coché)

**Comment by slauriere** [comment]
L'outil de reprise de données inclut bien à présent une fonction de reprise de la donnée "démarche simplfiée". L'outil est à présent implémenté, merci @georges-bayard @lucaa pour vos indications. Les reprises de données effectuées par l'outil sont décrites propriété par propriété dans la colonne "Statut de l'implémentation des changements" du document de spécifications. 

J'ai ajouté aux [instructions d'installation 3.x](https://projects.xwikisas.com/xwiki/bin/view/Projects/DINSIC/DINSIC-Dematerialisation/Installation%20Log%203_0) un paragraphe sur les opérations à effectuer pour mettre en œuvre cet outil. 

Prochaine étape : dérouler cette reprise de données sur le serveur de préproduction pour valider que tout fonctionne bien comme attendu (j'ai effectué une batterie de tests sur le serveur de développement).

**Comment by georges-bayard** [comment]
Merci beaucoup. A partir de quand pourra t'on tester la reprise de données sur l'environnement de test  ?

**Comment by slauriere** [comment]
J'ajoute ci-dessous quelques comptages concernant la reprise de données testable sur le site de développement – ce ne sont pas les mêmes données que sur la production ni sur la pré-production mais cela donne quelques ordres de grandeur :
- 1939 démarches passées à "démarche nationale" (sur un total de 2004 sur le site de développement)
- 702 démarches réaffectées à "MECT" (auparavant MTC ou MTES)
- 528 démarches mises à jour à "Peut être effectuée en ligne entièrement  = oui"
- 21 démarches mises à jour en "FranceConnect =  oui"
- 43 démarches mises à jour en "Adapté mobile = oui"
- 172 démarches mises à jour en "API entrerpises"
- 4 démarches mises à jour en "Démarche simplifiée = oui"
- 18 démarches mises à jour concernant la date de mise en ligne à partir de la date de dématérialisation

NB : les propriétés obsolètes comme "Caractéristiques de la dématérialisation" sont encore stockées en base le temps de valider que la reprise de données est correcte.

**Comment by lucaa** [comment]
> Au sujet de la récupération des affiliations précédentes (question de Georges ci-dessus) : qu'en penses-tu Anca ? @lucaa

@slauriere Je confirme ta réponse d'ici: https://github.com/DISIC/wikidemarches/issues/551#issuecomment-486164743

**Comment by slauriere** [comment]
L'identifiant du ministère auquel rattacher les démarches actuellement rattachées à MCT ou MTES est à présent configurable via l'interface de migration, pour pouvoir paramétrer cette réaffectation sans avoir à modifier de code (voir aussi #572).
