### ISSUE TITLE
Spécifier les champs du modèle de données liés à la disponibilité

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#552]
Cette tâche concerne la spécification des champs du modèle de données liés à la disponibilité, en particulier : 
- Disponibilité
- Temps de réponse
- Disponibilité / temps de réponse

**Comment by lucaa** [comment]
Pour essayer de comprendre la priorité de cette tache: aucune meta-donnée n'a pas été prévue pour reprendre les données sur la disponibilité qui sont déjà présentes dans le tableau de bord en format Excel?

**Comment by lucaa** [comment]
> aucune meta-donnée n'a pas été prévue pour reprendre les données sur la disponibilité qui sont déjà présentes dans le tableau de bord en format Excel?

réponse: non, rien n'a encore été prévu. 

À determiner: a-t-on besoin de pouvoir exporter ces informations sur les démarches du top250 dans la M9, pour decider si on doit les importer dans le cadre du #571 ou pas. Si on doit les importer dans la M9, on doit faire cette tache dans la M9 (pour avoir les propriétés).

**Comment by georges-bayard** [comment]
c'est une priorité liée à l'affichage des données dans le tableau de bord qui n'est pas dans la M9. On peut se contenter dans cette itération d'intégrer les données hors Pingdom

**Comment by slauriere** [comment]
Plutôt que de disposer juste pour l'instant d'une propriété destinée à recevoir le score final, les propriétés suivantes ont été ajoutées pour pouvoir calculer le score final à partir des données brutes (et la propriété "lwscore" a été supprimée) :
- Temps de réponse (champ numérique de type entier long)
- Disponibilité (champ numérique de type double)
- Disponibilité / temps de réponse (champ calculé à partir des deux précédents, comme indiqué dans le document de spécification des métadonnées)

La fiche d'une démarche affiche à présent la troisième propriété en mode visualisation. Affiche-t-on également les deux autres propriétés en mode visualisation (a priori en tout cas pas en mode édition puisque les données viendront de pulse.numerique / Pingdom), ou se contente-t-on du score total ?

Il reste a priori à spécifier plus précisément comment calculer le score "disponibilité / temps de réponse" car la spécification actuelle pose deux problèmes : le score du temps de réponse peut valoir "0" (quand le temps de réponse est entre 0.8 seconde et 1 seconde), ce qui rend la division impossible, et les scores peuvent prendre des valeurs négatives, qui, divisées entre elles, donneraient un résultat positif, ce qui n'est pas l'intention.

**Comment by slauriere** [comment]
Le score est calculé non pas par division mais via une somme, donc pas de problème de spécification.

**Comment by slauriere** [comment]
La règle de calcul du score a été implémentée en additionnant le score de disponbilité et celui de temps de réponse. Je clos cette tâche.
