### ISSUE TITLE
Spécifier les champs du modèles de données liés à la qualité de la donnée

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#553]
Cette tâche concerne la spécification des champs liés à la qualité de la donnée, en particulier : 
- Anomalie
- Commentaire
- Statut de l'anomalie

**Comment by lucaa** [comment]
Même tache que #383 , il s'agit d'une problématique plus générale lié à la possibilité de traiter les anomalies sur les données des démarches. Je marque comme dupliqué et je ferme, nous allons traiter ça dans #383.
