### ISSUE TITLE
Ajouter dans les CGU un § concernant le stockage des données informations de connexion

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#554]
§ à  insérer dans la partie "vie privée" avant le § cookies
_"Informations de connexion et d'appareil
Lorsque vous donnez votre avis une démarche administrative sur le site, nous recevons des informations relatives à votre ordinateur, téléphone ou autre outil que vous utilisez pour accéder à MonAvis. Nous pouvons par exemple avoir accès à votre adresse IP, ou aux URLs d'entrée ou de sortie. Le volume d'information recueillie dépend de la configuration de votre appareil et de votre navigateur.
Nous stockons votre adresse IP de façon confidentielle."_

**Comment by georges-bayard** [comment]
question : dans le modèle que j'ai pris pour faire cette proposition on ajoute des éléments concernant le fait qu'on peut utiliser ces données "afin de déterminer votre emplacement géographique et le nom de société", à des fins d'analyse afin de mieux personnaliser les contenus et la configuration qui vous sont proposés"
Je ne l'ai pas mis car je pense que ce n'est pas un besoin pour nous. Dans ce cas je ne vois pas le besoin qu'on à stocker ces données. Or on n'a aucun intérêt à stocker des données dont on n'a pas l'utilité.
@lucaa  : partages tu cette analyse ? faut il préciser la raison pour laquelle on stocke ces données, même succinctement ? pour rassurer ne faut il pas dire que ces données ne sont stockées que XX jours ?

**Comment by lucaa** [comment]
> Nous stockons votre adresse IP de façon confidentielle.

Je ne suis pas sure que je comprends ce que ça veut dire. Dans le sens ou on ne publie pas les IPs des gens? Confidentielles par rapport à qui?

> Je ne l'ai pas mis car je pense que ce n'est pas un besoin pour nous

Ce n'est pas le cas et ce n'est pas un besoin.

> Dans ce cas je ne vois pas le besoin qu'on à stocker ces données. Or on n'a aucun intérêt à stocker des données dont on n'a pas l'utilité.

Il y a, effectivement, une distinction à faire entre le fait qu'on reçoit ces données et le fait qu'on les stocke. On ne peut pas ne pas les recevoir (techniquement), mais on peut ne pas les stocker. La raison de ce stockage (limité dans le temps) est la possibilité de faire une analyse plus pertinente en cas de constat de dysfonctionnement ou attaque (notamment l'analyse des logs d'accès peut contribuer à l'identification des IPs malveillants et au blocage de ces IPs).
Dans l'état courant des choses, la phrase peut être: "Nous stockons votre adresse IP de façon temporaire pour des raisons d'analyse technique, et nous (le hébergeur) ne le partageons pas avec aucun partenaire.", ou quelque chose comme ça.

**Comment by georges-bayard** [comment]
sur la phrase "Nous stockons votre adresse IP de façon confidentielle" je trouve ca pas mal mais on l'enlève si tu trouves que ca pose plus de questions que cela rassure. c'est une formulation que j'ai piqué des CGU Xwiki au demeurant
Sur ta proposition d'ajout de § c'est ok. Très bien

**Comment by lucaa** [comment]
Texte final:


> Informations de connexion et d'appareil

> Lorsque vous donnez votre avis sur une démarche administrative sur le site, nous recevons des informations relatives à votre ordinateur, téléphone ou autre outil que vous utilisez pour accéder à MonAvis. Nous pouvons par exemple avoir accès à votre adresse IP, ou aux URLs d'entrée ou de sortie. Le volume d'information recueillie dépend de la configuration de votre appareil et de votre navigateur.
> Nous stockons votre adresse IP de façon temporaire pour des raisons d'analyse technique, et nous ne la partageons avec aucun partenaire autre que les prestataires techniques ayant des engagements de confidentialité.

**Comment by georges-bayard** [comment]
Ok ça me va
