### ISSUE TITLE
Questions diverses au sujet des nouvelles propriétés du modèle de données

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#555]
Je crée ce ticket au sujet de plusieurs questions qui se posent suite à #550.

**Comment by slauriere** [comment]
Georges, La propriété "Pourcentage de dématérialisation" apparaît deux fois dans le document de spécification, dans deux rubriques différentes. Est-ce qu'elle doit bien être rattachée à la rubrique "Catégorisation" uniquement, avec sa nouvelle règle de calcul ? @georges-bayard

**Comment by georges-bayard** [comment]
Les deux doivent être conservées mais il faut changer le nom de la première pour écarter toute confusion.
Le "pourcentage de dématérialisation" sous la rubrique "catégorisation" doit être renommé "Pourcentage recours à la voie dématérialisée". c'est le rapport entre la volumétrie de la démarche et la volumétrie du recours à la voie dématérialisée
Le "pourcentage dématérialisation" sous la rubrique " caractéristique de la dématérialisation" doit être maintenue à l'identique.

**Comment by slauriere** [comment]
Ah oui pardon, bien sûr ! OK j'ai implémenté cela : les deux pourcentages sont présents.

**Comment by slauriere** [comment]
Info / question : dans le document de spécification, la rubrique "Adresses web" est entre les rubriques "Catégorisation" et "Caractéristiques de la dématérialisation". Cela donne visuellement deux colonnes de tailles assez différentes, du coup pour l'instant j'ai placé cette rubrique sous la rubrique "Références".

**Comment by slauriere** [comment]
(visible sur le site de développement)

**Comment by slauriere** [comment]
Georges, Les spécs indiquent, pour la propriété "Date de mise en ligne prévue ou réalisée" de modifier le panneau. J'ai modifié le libellé de cette propriété (qui était auparavant "Date de mise en ligne, prévisionnelle ou réalisée") mais je me demande si c'est bien le sens du commentaire "Modifier le panneau" ?

**Comment by georges-bayard** [comment]
voici mon interprétation : il ne faut pas modifier le nom du champ mais l'explication qui est en dessous. Le nom du champ qui apparaît à l'écran doit à mon sens demeurer "Date de mise en ligne"

**Comment by georges-bayard** [comment]
sur la question du changement de rubrique pour les "Adresses web"  : ok ca me va très bien

**Comment by slauriere** [comment]
OK Georges merci, j'ai modifié l'explication du champ "Date de mise en ligne", et ok pour la position des "Adresses web". Deux autres questions (quasi finales je pense) : 
- Le document de spécification indique d'ajouter une explication claire à la propriété "Peut être réalisée en ligne complètement". J'ai mis ceci pour le moment : "Une démarche est considérée comme pouvant être réalisée en ligne complètement si elle est disponible sous la forme d'un formulaire web ou d'un téléservice." Qu'en penses-tu ?
- Propriété "Date de la dématérialisation" : le document indique "A garder ?" avec un point d'interrogation : gardons-la peut-être pour le moment et avisons plus tard, ou bien est-ce qu'on supprime cette propriété ?
J'ai mis à jour le statut de toutes les modifications apportées au modèle de démarche dans le document de spécifications, dans la colonne "Statut de l'implémentation des changements".

**Comment by georges-bayard** [comment]
Sur le premier point je propose l'explication suivante : une démarche est considérée comme pouvant être réalisée en ligne complètement si l'utilisateur peut effectuer la démarche complètement en ligne, jusqu'au dépôt de la demande"
Sur le second point on supprime la première date, celle qui est sous "Caractéristique de la dématérialisation". On reprend la donnée des 6 valeurs existantes dans le second champ date sauf si la valeur est déjà renseignée

**Comment by slauriere** [comment]
OK j'ai utilisé l'explication que tu indiques pour les démarches pouvant être remplies en ligne entièrement, et j'ai supprimé la première date, en ajoutant au script de reprise de données l'identification des 6 démarches ayant des dates indiquées. À mon sens cela permet de clore ce ticket, quitte à le rouvrir si des nouvelles questions se posent.
