### ISSUE TITLE
Suppression des documents "Champ ministériel"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#558]
Une cinquantaine de pages décrivant des champs ministériels avaient été créées. La propriété associée à ces pages a été supprimée du modèle de démarche dans le cadre de #549. Je crée ce ticket pour validation : @georges-bayard, nous donnes-tu ton go pour la suppression des données champ ministériel ? Il sera toujours possible de les réintégrer plus tard si besoin bien entendu.

**Comment by georges-bayard** [comment]
c'est ok pour la suppression

**Comment by slauriere** [comment]
Ok vu merci, j'ai supprimé le code et les données associées (sur le site de développement), et j'ai ajouté pour mémo une instruction de l'opération à effectuer en préprod puis prod pour cela, dans  [le document de référence des instructions d'installation ou de migration](https://github.com/DISIC/wikidemarches/wiki/Installation-instructions-v-3.x).
