### ISSUE TITLE
Contrôle d’accès des agents administration (mel en .gouv) : vérifier que le code de contrôle d’adresse mel est suffisamment sévère (pour éviter le pb qu’on a eu sur Tchap)

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#559]

**Comment by lucaa** [comment]
Une première réponse à cette question est que monavis utilise le mechanisme de validation des adresses émail standard de la plateforme XWiki, nous n'avons pas codé un mecanisme de validation d'adresses émail spécifique. Par rapport à l'incident Tchap, nous n'utilisons pas le même code, etc.
Pour la vérification de la catégorie d'adresses qui doit passer sans validation manuelle par un admin, une restriction plus forte est planifiée dans l'issue #600 . Je ferme cet issue comme étant "couverte" par #600 et on va devoir s'assurer de la solidité des vérifications lors de l'implementation de #600.
