### ISSUE TITLE
Intégration avec l'API Pingdom

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#560]
Je recopie ici ce qu'a écrit Jean dans le cadre de #407 :

Tableau de bord Pingdom en bêta: http://pulse.numerique.gouv.fr  sur laquelle Jean a activé j’ai activé la supervision de ~170 services

* http://pulse.numerique.gouv.fr/api redirection vers la version stable de l’API
* http://pulse.numerique.gouv.fr/api/v1 description de l’API
* http://pulse.numerique.gouv.fr/api/v1/ids tableau « application/json » JSON des identifiants de toutes les sondes de services
* http://pulse.numerique.gouv.fr/api/v1/csv/ extract CSV « text/plain » de la sonde du service
* http://pulse.numerique.gouv.fr/api/v1/score/ score composite « text/plain » de la sonde du service

**Comment by slauriere** [comment]
Tâche liée : #552

**Comment by slauriere** [comment]
@georges-bayard, En commençant à travailler sur ce sujet ainsi que sur la tâche #552, je remarque que le site http://pulse.numerique.gouv.fr/ semble ne pas être accessible, en tout cas depuis notre réseau. Sais-tu si c'est bien un site public ou sinon s'il est possible que nous y ayons accès ? Nous en aurons besoin pour automatiser l'intégration des données Pingdom (cela n'empêche pas de mettre en place le modèle destiné à recevoir les données toutefois, à savoir #552).

**Comment by georges-bayard** [comment]
il n'est pas accessible pour nous non plus. Il est en rade et la personne de chez nous qui pourrait le mettre d'aplomb est en congé maladie. On doit s'en passer pour l'instant

**Comment by lucaa** [comment]
Une nouvelle issue a été crée pour le même but, #652 .
Je ferme cette tache comme doublon, le travail sera fait dans le cadre de l'autre tache.
