### ISSUE TITLE
Ecran démarches : modifier les informations qui permettent de filtrer les données  

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#562]
ajouter un filtre Top 250
ajouter le filtre "peut être réalisé en ligne complètement"
supprimer le filtre "statut projet"
supprimer le filtre "niveau démat"

**Comment by slauriere** [comment]
J'ai mis à jour le tableau en conséquence, GBA je te laisse regarder et clore le ticket si c'est bien ok pour toi ?

**Comment by slauriere** [comment]
Ce point a été traité dans le cadre de #563 -> je le clos, n'hésitez pas à le rouvrir si besoin.
