### ISSUE TITLE
ajouter un export excel des démarches du Top 250, modifier la liste des propriétés affichées et la liste des propriétés exportées

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#563]
Critère de tri : démarches Topées Top 250
Données ramenées : celles présentes dans l'Excel du Top 250 + champ catégories de publics + champ commentaire
Public destinataire : administrateurs ministériels

**Comment by slauriere** [comment]
Suite à l'ajout du filtre "top 250" au tableau des démarches (#562), l'export des démarches correspondantes est disponible depuis le bouton d'export. Il exporte tous les champs des démarches y compris les catégories de publics et les commentaires, et le tableau est bien restreint aux administrateurs ministériels.

**Comment by georges-bayard** [comment]
wow la rapidité ! l'affichage de "Peut être réalisée en ligne complètement". c'est possible d'optimiser ? mettre sur deux lignes par exemple

**Comment by georges-bayard** [comment]
le bouton d'export vers excel ne fonctionne pas de mon poste : j'ai un message "impossible d'ouvrir le fichier excel"

**Comment by slauriere** [comment]
GBA, Suite à notre discussion j'ai mis à jour le tableau des démarches comme ceci : 

Champs présents dans l'export Excel, dans cet ordre : 
- Nom
- Date de création
- Statut
- Direction
- Ministère(s)
- Groupes
- Adresse web de la démarche
- Catégories de publics concernés
- Niveau de dématérialisation actuel
- Volumétrie de la démarche
- Volumétrie de la dématérialisation
- Pourcentage du recours à la voie dématérialisée
- Top 250
- Peut être réalisée en ligne complètement
- Pourcentage de dématérialisation
- Démarche intégrée avec MonAvis
- FranceConnect
- Adapté mobile
- Support de qualité
- Date de mise en ligne
- Date de mise en ligne approximative
- Remarques
- URL

Champs présents et filtrables dans le tableau web : 
- Nom
- Date de création
- Statut
- Direction
- Catégories de publics
- Niveau de dématérialisation
- Top 250
- Peut être réalisée en ligne complètement

Ce dernier champ s'affiche à présent bien sur deux lignes en mode web (et en une seule ligne dans l'export Excel).

Dis-moi si j'ai oublié quelque chose ou si tu vois des améliorations à apporter?

**Comment by georges-bayard** [comment]
Voici mes retours : je mets des numéros pour marquer les positions de l'information dans l'extraction

-   Nom 3
-     Date de création
-     Statut
-     Direction 4
-     Ministère(s) 1
-     Groupes 2
-     Adresse web de la démarche
-     Catégories de publics concernés
-     Niveau de dématérialisation actuel
-     Volumétrie de la démarche 10
-     Volumétrie de la dématérialisation 11
-     Pourcentage du recours à la voie dématérialisée 12
-     Top 250
-     Peut être réalisée en ligne complètement 5
-     Pourcentage de dématérialisation 5 bis
-     Démarche intégrée avec MonAvis 13 en changeant le nom : « avis nos démarches intégré ? »
-     FranceConnect 14 
-     Adapté mobile 15
-     Support de qualité 16
-     Date de mise en ligne 6
-     Date de mise en ligne approximative 7
-     Remarques
-     URL

Ajouter indice de satisfaction usager en position 8
Ajouter nombre d’avis usager en position 9 
Ajouter Au moins deux moyens de contact différents, dont un formulaire de contact en position et Accompagnement humain personnalisé en position 16 bis et 16 ter

**Comment by slauriere** [comment]
Je réordonne les champs par ordre croissant ci-dessous, pour faciliter le traitement et la validation du ticket, que je clos au passage.

Deux remarques : 
- Il faut éventuellement réordonner les deux 5 bis et les deux 19 (et donc rouvrir le ticket le cas échéant).
- Dans le fonctionnement actuel de l'export de tableaux XWiki, le champ "URL" ne peut être positionné qu'en fin de liste. J'ai créé un ticket dédié au positionnement de ce champ, si nécessaire: #566

Récapitulatif de l'ordre des champs : 
* Ministère(s) 1
* Groupes 2
* Nom 3
* Catégories de publics concernés 3 bis
* Direction 4
* Peut être réalisée en ligne complètement 5
* Niveau de dématérialisation actuel 5 bis
* Pourcentage de dématérialisation 5 bis
* Date de mise en ligne 6
* Date de mise en ligne approximative 7
* Ajouter indice de satisfaction usager en position 8
* Ajouter nombre d’avis usager en position 9
* Volumétrie de la démarche 10
* Volumétrie de la dématérialisation 11
* Pourcentage du recours à la voie dématérialisée 12
* Démarche intégrée avec MonAvis 13 en changeant le nom : « avis nos démarches intégré ? »
* FranceConnect 14
* Adapté mobile 15
* Support de qualité 16
* Au moins deux moyens de contact différents, dont un formulaire de contact 16 bis 
* Accompagnement humain personnalisé en position 16 ter
* Adresse web de la démarche 16 quater
* Remarques 17
* Top 250 19
* Date de création 19
* Statut 20
* URL
