### ISSUE TITLE
redéfinir l'information "peut être réalisé en ligne" de l'écran tableau de bord

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#564]
Mettre à la place pour ce champ la valeur du champ "peut être réalisé en ligne complètement" du modèle de données

**Comment by slauriere** [comment]
J'ai modifié le modèle de données suite à notre discussion : les champs "peut être réalisée en ligne", "expérimentation", "déploiement partiel" sont à présent regroupés en un seul champ, qui peut prendre les valeurs suivantes : 
* oui
* expérimentation
* déploiement partiel
* non
* non renseigné

**Comment by slauriere** [comment]
OK j'ai répercuté ce changement sur le tableau de bord : c'est bien ce nouveau champ qui y est affiché.

**Comment by georges-bayard** [comment]
j'ai revu l'explication pour essayer de la rendre plus claire : "Oui si l'utilisateur peut effectuer la démarche complètement via internet jusqu'au dépôt de la demande sur l’ensemble du territoire ; Non dans le cas contraire ; Expérimentation si la solution est en cours d’expérimentation sur un échantillon restreint d’utilisateurs ou de cas métier ; Déploiement partiel si la solution est en cours de déploiement (l’ensemble des usagers n’y a pas encore accès)."

**Comment by slauriere** [comment]
OK effectivement c'est plus clair, j'ai mis à jour le texte
