### ISSUE TITLE
Dans le formulaire simplifié de création de démarche, initialisation de certains champs à "non renseigné"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#568]
Dans le formulaire simplifié de création de démarche, les champs  ci-dessous, bien qu'absents, doivent être initialisés à la valeur "non renseigné" : 
* FranceConnect
* Adapté mobile
* Avis Nos Démarches intégré ?
* Au moins deux moyens de contact différents
* Accompagnement personnalisé
* Peut être réalisée en ligne complètement
* Démarche simplifiée

**Comment by slauriere** [comment]
Pour répondre à ce besoin, des champs cachés ("input type='hidden'") avec la valeur "nr" (pour "non renseigné") ont été introduits dans le formulaire simplifié de création de démarche pour ces propriétés.

**Comment by georges-bayard** [comment]
@slauriere  : l'initialisation à "non renseigné" répond à quel besoin ?

**Comment by slauriere** [comment]
@georges-bayard Dans le cadre de la reprise de données, tous les champs pouvant prendre la valeur "non renseigné" qui n'avaient aucune valeur, ont été initialisés à "Non renseigné" oui. J'espère que cela répond à ta question ?

**Comment by georges-bayard** [comment]
j'ai regardé ca me va
