### ISSUE TITLE
Rendre le tableau de bord accessible uniquement aux administrateurs ministériels

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#570]
Même spécification que #423 , à re-faire par dessus de la version M8.1 dans laquelle l'accès a été re-ouvert. 
Cette tache est aussi comprise dans la tache plus globale #545 qui parle de de-faire plusieurs modifications d'accès de la M8.1.
Je l'isole (par rapport aux modifications groupées de la #545) pour pouvoir, potentiellement la planifier en avance par rapport à la #545.

**Comment by lucaa** [comment]
@georges-bayard  par rapport au commentaire d'ici: https://github.com/DISIC/wikidemarches/issues/423#issuecomment-489073253 .

Est-ce que ceci veut dire que cette modification d'accès doit être faite même si #545 n'est pas faite (#545 contient toutes les modifications d'accès pour revenir au schéma d'accès de la M8) ?

**Comment by georges-bayard** [comment]
@lucaa  : je confirme que cette issue qui est liée à la #545 n'est pas à faire dans la M9

**Comment by lucaa** [comment]
Les accès au tableau de bord ont été traités par #602 (nouveau tableau de bord) et #545 (accès á l'ancien tableau de bord).
Je clos cette tache comme un doublon de ces 2 là.
