### ISSUE TITLE
Statuer sur l'identifiant MECT

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#572]
Juste une tâche pour ne pas oublier de statuer sur l'identifiant MECT : utilise-t-on "MTES - MCTRCT" comme suggéré lors d'un échange ? Ou bien un numéro éventuellement si le sigle est encore trop instable, quitte à transformer le numéro en sigle ultérieurement ?

**Comment by lucaa** [comment]
Voir la réponse ici: https://github.com/DISIC/wikidemarches/issues/527#issuecomment-492211530 .

**Comment by lucaa** [comment]
Le nom a été mis à jour dans le commit d8f70a9b543a8cd3c8fc1128a70a73bb69a96ec5 , la tâche est faite, je ferme.
