### ISSUE TITLE
Décider quoi faire pour les démarches du top 250 qui ne sont pas présentes sur monavis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#573]
Dans le fichier des démarches phares (#571) il y a 17 démarches qui n'ont pas de référence de démarche sur le site monavis, donc ne peuvent pas encore être importées. 
De ces 17 démarches, 6 sont du ministère des armées, donc seront créées par #519.

Cette tâche est pour décider ce qu'on fait avec les autres 11 démarches.

**Comment by georges-bayard** [comment]
il faut juste les créer à la main dans MonAvis. Je peux m'en occuper demain

**Comment by lucaa** [comment]
> Je peux m'en occuper demain

Je préfère, si possible, car je ne saurais pas comment remplir les méta-données qui ne sont pas présentes dans le fichier top250.

**Comment by lucaa** [comment]
Les démarches ont été créées, je ferme l'issue.
