### ISSUE TITLE
Mise à jour / création de la documentation des méta-données des démarches

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#574]
Historiquement nous avions un fichier excel qui décrivait les méta-données stockés par l'outil sur les démarches, avec les contraintes, valeurs possibles et aide au remplissage.

Cette tache est pour re-mettre à jour cette documentation avec les dernières modifications du modèle de données.
Nous avons 2 options pour cette documentation:
* continuer en excel
* faire des documents wiki, qu'on pourra exporter en pdf.

La deuxième option paraît la meilleure, car cela rendra cette documentation accessible directement en ligne aux administrateurs ministeriels et porteurs de démarches.

**Comment by slauriere** [comment]
Une première version de la documentation est disponible. Elle reprend les infos suivantes : 
- Champs du modèle de démarche avec leurs explicatifs existant dans le modèle, ainsi que le caractère obligatoire ou non. Certains explicatifs restent éventuellement à compléter (e.g "Accompagnement humain personnalisé").
- Valeurs possibles pour chaque champ
- Quelques exemples
- Des informations qui étaient présentes dans le fichier Excel d'origine, comme le fait que les la liste des publics concernés présentée dans l'interface est filtrée dynamiquement en fonction de la ou des catégorie(s) de publics concernés.

Je vous envoie le lien par mail.

**Comment by georges-bayard** [comment]
Mode de déploiement : un lien de la page démarches vers la page de documentation affiché pour tout le monde sauf les administrateurs DINSIC en mode édition
Pas de texte introductif à mart le titre qui pourrait être "description du modèle de données" plutôt que "documentation du modèle de données"

**Comment by slauriere** [comment]
J'ai introduit un lien vers la description du modèle de données qui s'affiche lors de l'édition d'une démarche sauf pour les administrateurs DINSIC. Ce lien est visible sur le site de développement par exemple avec un compte d'administrateur ministériel. Cela donne ceci, avez-vous des remarques ou suggestions ?

![image](https://user-images.githubusercontent.com/1022195/58163214-e8372980-7c83-11e9-90a4-211ad12d199c.png)

La page de documentation se trouve à l'adresse suivante : 
http://wikidemarches.devxwiki.com/Demarches/Description%20du%20mod%C3%A8le%20de%20donn%C3%A9es

Ce lien s'affiche également lors de la création d'une démarche via le formulaire simplfiié (ajout de démarche m²anquante).

J'ai ces questions : 
- Est-ce que l'URL et l'emplacement de la page de description du modèle vous semblent ok ?
- J'ai restreint l'accès à cette page aux utilisateurs ayant un compte sur le site, est-ce bien ok pour vous ainsi ?
- Affichage : compte-tenu de la largeur d'affichage réduite, je propose d'extraire du tableau les intitulés des rubriques et de les afficher sous la forme de titres, cela donnera plus d'espace aux cellules du tableau, qu'en pensez-vous ?
- Sur l'intranet, on peut supprimer la page de documentation pour éviter d'avoir du contenu désynchronisé ?

Note technique : la page de description du modèle est à marquer comme "non upgradable"

**Comment by georges-bayard** [comment]
mes réponses : 

    Est-ce que l'URL et l'emplacement de la page de description du modèle vous semblent ok ? **je n'ai pas repéré l'emplacement sur la page**
    J'ai restreint l'accès à cette page aux utilisateurs ayant un compte sur le site, est-ce bien ok pour vous ainsi ? **oui mais de toute façon la page démarche n'est accessible qu'aux utilisateurs connectés. En revanche l'accès en modif est réservé aux administrateurs Xwiki et DINSIC** 
    Affichage : compte-tenu de la largeur d'affichage réduite, je propose d'extraire du tableau les intitulés des rubriques et de les afficher sous la forme de titres, cela donnera plus d'espace aux cellules du tableau, qu'en pensez-vous ? **oui très bonne idée**
    Sur l'intranet, on peut supprimer la page de documentation pour éviter d'avoir du contenu désynchronisé ? **je ne comprends pas la question**

**Comment by slauriere** [comment]
Ok Georges, merci,

-  J'ai extrait les intitulés des rubriques pour donner plus d'espace, cf [Description du modèle de données](http://wikidemarches.devxwiki.com/Demarches/Description%20du%20mod%C3%A8le%20de%20donn%C3%A9es)

- Concernant l'URL de la page : je me demandais si on utilisait "/Demarches/Description du modèle de données" ou bien "/Main/Description du modèle de données". Sauf contre-ordre de votre part je laisse comme cela.

- Au sujet de la restriction d'accès : les pages démarches et l'accès en modification sont certes déjà restreints, mais ajouter une restriction à la page de documentation elle-même évitera qu'elle soit indexée par des moteurs de recherche, qui pourraient obtenir le lien vers cette page via d'autres pages du site (par exemple la page des dernières modifications apportées au site)

- Page de l'intranet : je rebondirai par mail.

**Comment by georges-bayard** [comment]
OK

**Comment by lucaa** [comment]
Je sais que c'est un peu tard, mais j'aimerais bien isoler tout le contenu de documentation/aide dans un espace dédié, e.g. "Aide". 
On mettra dedans également des contenus comme #598 et #278 .
Cela peut également faciliter la gestion des droits sur la documentation, differents des droits des démarches.
@slauriere je re-ouvre, dis-moi si tu trouves des raisons pour garder ces contenus dans l'arborescence Demarches.

**Comment by slauriere** [comment]
Ok oui bonne idée, pas de raison de garder le contenu dans l'aborescence de l'espace des démarches. J'ai déplacé la page (-> trois changements : la page elle-même, le lien vers cette page depuis le formulaire d'édition, le pom d'upgrade). Je clos.
