### ISSUE TITLE
Mettre toutes les démarches brouillon en état active

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#575]
Aujourd'hui il y a des démarches en production qui sont en état "Brouillon" qui devrait être en état "active". Cette tâche est pour modifier cela automatiquement, principalement pour toutes les taches du top 250 (see #571).

**Comment by lucaa** [comment]
Après testes sur le serveur de staging, j'ai trouvé 3 démarches du top250 qui sont en état "Inactive": 1676, 1678 et 1690. Cette tâche demande de tout passer en état "active" (au moins tu top250) de manière automatique. Est-ce que je dois passer aussi ces 3 démarches en état "active"?

**Comment by georges-bayard** [comment]
J'ai passé les 3 au statut actif en production
