### ISSUE TITLE
Sécurité : à l'inscription des porteurs de projet effectuer le contrôle sur les adresses de domaine (finances.gouv.fr, social.gouv.fr, …) et non plus sur seulement l'extension .gouv.fr 

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#577]
Cf liste ci-jointe de noms de domaine de l’Etat qui seraient autorisés
[Liste NDD autorisés.xlsx](https://github.com/DISIC/wikidemarches/files/3183426/Liste.NDD.autorises.xlsx)

**Comment by slauriere** [comment]
Cette tache doublonne avec #600 -> je la clos.
