### ISSUE TITLE
Amélioration de l'affichage de la valeur du champ "Pourcentage du recours à la voie dématérialisée"

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#582]
Le champ calculé "Pourcentage du recours à la voie dématérialisée" doit pouvoir afficher plusieurs valeurs :

* Un pourcentage calculé à partir des grandeurs "Volumétrie de la démarche" et "Volumétrie du recours à la voie dématérialisée" quand celles-ci sont disponibles
* "Sans objet" quand la démarche n'est pas du tout dématérialisée
* "Non renseigné" dans les autres cas

Actuellement, seul le premier cas est traité. Cette tâche vise à couvrir les trois cas.

**Comment by slauriere** [comment]
L'amélioration a été apportée, je ferme ce ticket.

**Comment by lucaa** [comment]
@slauriere le changement des valeurs en dur vers des appels de la macro {{translation}} casse l'affichage de la valeur dans l'export excel des démarches.
Je pense que c'est parce-que c'est pas le displayer qui evalue l'appel de la macro {{translation}} mais le contexte dans lequel le displayer est appelé, ou la syntaxe XWiki est interpretée...
Sinon, dans le displayer il n'y a aucune raison pour la macro {{translation}} d'être évalue car elle est appelée dans une macro html qui n'a pas le paramètre wiki mis à true.
Si on ne trouve pas mieux, je préfère qu'on revert cette amelioration (le remplacement des textes en dur avec la macro) pour la M9 et qu'on cherche la solution complète plus tard.

**Comment by slauriere** [comment]
Effectivement, il manquait en tout cas "wiki='true'" dans la macro html. Néanmoins je n'ai pas réussi pour l'instant à ne pas générer des balises "div" à l'export autrement qu'en utilisant un appel direct à "services.localization.render" plutôt qu'en utilisant la macro translation.

**Comment by slauriere** [comment]
L'export fonctionne bien comme attendu ainsi (et l'affichage standard) -> je clos cette tâche.
