### ISSUE TITLE
Trouver une solution pour séparer les groupes de démarches d'usage interne des groupes pour le tableau de bord

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#589]
Aujourd'hui la méta-donnée "Groupes" des démarches a été utilisée pour un regroupement de démarches interne (par les administrateurs ministériels) mais est aussi prévue pour stocker les groupes publiques, provenant des démarches phare (voir #571).
Cette tâche est pour trouver une solution qui permettra de faire un regroupement interne, sans que les groupes internes soient publiés. 
Options:
* utiliser les tags de pages pour faire les groupes internes
* renoncer complètement aux groupes internes, car pas utilisés
* ajouter une deuxième méta-donnée pour stocker séparément les 2 types de groupes.

**Comment by lucaa** [comment]
Pour la M9 les 2 types de groupes seront fusionnés: #588.

**Comment by slauriere** [comment]
GBA: « nettoyer les données issues de la reprise de données (intérieur et équipement) »

**Comment by lucaa** [comment]
Suite au fait que la colonne des groupes des démarches a été  caché pour #602, cette issue n'est plus prioritaire , je bouge dans la M11.

**Comment by slauriere** [comment]
Décision : deux champs distincts : 
* Regroupement interne
* Regroupement externe

**Comment by slauriere** [comment]
De ce fait : prévoir une tache de restauration des groupes internes initiaux (avant import des démarches phares).

**Comment by slauriere** [comment]
Une tache dédiée à la restauration des groupes a été créée : #613

**Comment by slauriere** [comment]
Une propriété "Groupe(s) externe(s)" a été ajoutée.
