### ISSUE TITLE
Produire une vue qui permette de visualiser les porteurs de démarche et les démarches qui leurs sont associées

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#591]
La vue doit permettre de visualiser leurs adresse mail, les démarches auxquelles ils sont associés

**Comment by slauriere** [comment]
Une telle page a été créée, elle permet de visualiser les porteurs et leurs démarches respectives, ainsi que les comptes des utilisateurs susceptibles de devenir porteurs mais qui ne le sont pas encore. La page est visible sur le site de développement: http://wikidemarches.devxwiki.com/Demarches/Admin/Porteurs

**Comment by lucaa** [comment]
À faire: mise à jour de la page Demarches.Admin pour y mettre le bon lien vers la validation des comptes.
Aussi, un lien pour l'administrateur pour accéder à ces fonctionnalités.

**Comment by slauriere** [comment]
Un lien vers la page listant les porteurs de démarches a été ajouté à la page Demarches.Admin, et j'ai corrigé le lien vers la page de validation de comptes -> je ferme ce ticket et vous laisse le rouvrir si besoin.
