### ISSUE TITLE
démarches à supprimer

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#593]
quand dans la vue de recherche de l'écran démarches j'initialise toutes les valeurs à "tout" ce qui me permet de tout voir, je vois apparaître des démarches non renseignées qui font penser à un bug de l'application. Puis-je supprimer physiquement cette quinzaine de démarches qui me paraissent inutiles ?

**Comment by georges-bayard** [comment]
![image](https://user-images.githubusercontent.com/17125654/58116258-2983f680-7bfc-11e9-89cf-1b03616b5ca4.png)

**Comment by lucaa** [comment]
@slauriere , tu peux vérifier ces démarches et les enlever, si nécessaire?

**Comment by georges-bayard** [comment]
je peux le faire aussi si vous me dites qu'il n'y a pas d'impact

**Comment by slauriere** [comment]
Effectivement, ce sont bien des démarches qui ont été créées par erreur (par moi, désolé), elles peuvent être supprimées, pas d'impact. Georges je te laisse le faire, ou bien à ta dispo sinon.

**Comment by georges-bayard** [comment]
ca y est j'ai killé le troupeau
