### ISSUE TITLE
Dysfonctionnement du tri du tableau des démarches

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#594]
Depuis le tableau des démarches (page "/Demarches/"), quand on essaie de trier le tableau par les champs "Ministère(s)" ou "Groupes", le tri n'est pas appliqué, alors qu'il l'est bien pour le champ "Direction" par exemple.

**Comment by lucaa** [comment]
Est-ce que les 2 champs sont multivaluées, par hasard?
Si oui, c'est normal que le tri ne fonctionne pas, on ne sait pas comment trier par plusieurs valeurs. Ce qu'on devrait plutôt faire c'est de desactiver le tri pour ces 2 propriétés, pour ne pas afficher une fonctionnalité qui ne marche pas.

**Comment by lucaa** [comment]
ping @slauriere

**Comment by slauriere** [comment]
Effectivement, ces 2 champs sont bien multivalués. J'ai désactivé le tri pour ces deux champs, je clos la tâche.
