### ISSUE TITLE
Chevauchement des titres et des paragraphes en mode authentifié

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#597]
En mode authentifié, l'espacement entre les titres de sections et les paragraphes est insuffisant, il y a même un léger chevauchement, cf capture d'écran ci-dessous de la page "/Main/CGU". En mode non authentifié en revanche, le problème ne se pose pas.

![chevauchement-titres](https://user-images.githubusercontent.com/1022195/58312313-55c19200-7e0b-11e9-8140-1c6081816fca.jpg)

**Comment by lucaa** [comment]
Problème corrigé, je ferme.
