### ISSUE TITLE
rendre accessible en ligne le mode opératoire de récupération du bouton de vote MonAvis

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#598]
[Fiche de récupération du bouton sur MonAvis2.docx](https://github.com/DISIC/wikidemarches/files/3216084/Fiche.de.recuperation.du.bouton.sur.MonAvis2.docx)

Je suggère en attendant la nouvelle home page de rajouter après "Suivez l'avancée de la dématérialisation" l'ajout suivant : "intégrez le bouton de vote "MonAvis" à la fin d’une démarche administrative

**Comment by lucaa** [comment]
Page à créer (en important le fichier office) dans la zone de documentation, à côté de la doc crée pour #574 .
Nous mettrons le lien après, lors de la création de la page d'accueil.

**Comment by slauriere** [comment]
La page a été créée sur le site de développement avec l'URL relative « /Aide/Intégration du bouton MonAvis ». Il me semble qu'il manquait un « cela » dans le dernier paragraphe, je l'ai ajouté, @georges-bayard je te laisse valider et rouvrir le ticket si besoin.
