### ISSUE TITLE
Rattacher les votes effectués sur la démarche n° 1260 à la démarche n°1901 

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#599]
Rattacher les votes effectués sur la démarche n° 1260 : demande de certificat d’immatriculation (carte grise) d’un véhicule d’occasion à la démarche n°1901 : Demande de certificat d'immatriculation d'un véhicule d'occasion immatriculé en France (changement de titulaire carte grise).

Quand ce sera fait il faudra inactiver la démarche 1260 (GBA).

**Comment by slauriere** [comment]
Il faudra également déplacer l'indice de satisfaction et les avis dans le tableau Excel sur la bonne démarche (action GBA).

**Comment by slauriere** [comment]
Les avis ont été réassignés sur le serveur de staging puis sur le serveur de production, et les vérifications suivantes ont été effectuées : 127 avis réassignés, avec une mention dans l'historique de chacun des avis de la réassignation, et le cache d'avis de la démarche cible (1901) et de la démarche d'origine (1260) ont été correctement actualisés.

@georges-bayard je te laisse répercuter les indicateurs dans le fichier de référence (cela n'a pas d'impact sur les données importées, seulement sur le fichier lui-même et son export PDF).

**Comment by lucaa** [comment]
@slauriere commit aussi le script qui permet de re-affecter les avis, dans une zone ou uniquement l'admin a accès.

**Comment by slauriere** [comment]
Le script a été ajouté à la zone d'administration des avis: [AvisReassigner](https://github.com/DISIC/wikidemarches/blob/master/wikis/xwiki/src/main/resources/Avis/Admin/AvisReassigner.xml).
