### ISSUE TITLE
N'autoriser la création de comptes sans validation des administrateurs que pour les noms de domaines de l'Etat

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#600]
[Liste NDD autorisés.xlsx](https://github.com/DISIC/wikidemarches/files/3231739/Liste.NDD.autorises.xlsx)

**Comment by slauriere** [comment]
Une page contenant la liste des domaines autorisés a été créée dans la zone d'administration (qui est restreinte en lecture et en écriture aux administrateurs du site) : /Administration/Domaines autorisés. Cette page pourra être modifiée sur le site de production si besoin, pour ajouter ou supprimer certains domaines (techniquement : page "non-upgradable").

La règle pour la création sans validation a été modifiée : il faut à présent que le domaine de l'e-mail de l'utilisateur soit exactement dans la liste autorisée, à la casse près, alors que précédemment le domaine devait être soit égal à "gouv.fr" soit se terminer par ".gouv.fr". J'ai fait plusieurs tests.

**Comment by slauriere** [comment]
Une page contenant la liste des domaines autorisés a été créée dans la zone d'administration (qui est restreinte en lecture et en écriture aux administrateurs du site) : /Administration/Domaines autorisés. Cette page pourra être modifiée sur le site de production si besoin, pour ajouter ou supprimer certains domaines (techniquement : page "non-upgradable").

La règle pour la création sans validation a été modifiée : il faut à présent que le domaine de l'e-mail de l'utilisateur soit exactement dans la liste autorisée, à la casse près, alors que précédemment le domaine devait être soit égal à "gouv.fr" soit se terminer par ".gouv.fr". J'ai fait plusieurs tests.

**Comment by lucaa** [comment]
Bug: une adresse modernisation.gouv.fr demande toujours de la validation, même si elle est dans la whiteliste du document Administration.Domaines autorisés. Je re-ouvre.

**Comment by slauriere** [comment]
Le séparateur de ligne a été modifié en conséquence, cela résout le problème identifié, je clos ce ticket.

**Comment by georges-bayard** [comment]
en test sur la prod j'ai créé un compte pour georges.bayard@toto.gouv.fr (compte gbayardtest/gbayardtest) ; j'ai eu le message "Votre compte n'est pas encore actif, car votre e-mail n'a pas été confirmé. Vous devriez avoir reçu un e-mail avec un lien vous permettant de confirmer votre inscription." Je n'ai évidemment pas reçu le message en tant que porteur de démarche puisque l'adresse n'existe pas. En tant qu'administrateur je devrais cependant recevoir un message pour éventuellement pouvoir valider manuellement l'inscription

**Comment by lucaa** [comment]
L'utilisateur ainsi crée apparaît, en fait, dans la liste d'utilisateurs à valider disponible aux administrateurs dans /Demarches/Admin/ActivationDeComptes et peut être activé par l'administrateur, même si son adresse email n'est pas valide.
Nous avons évité d'envoyer un email aux administrateurs avant que l'adresse de l'utilisateur ne soit pas validée par l'utilisateur lui même pour minimiser le nombre d'emails reçus par les administrateurs et pour notifier l'administrateur uniquement quand il _doit_ faire une action. Si un utilisateur crée un compte mais ne le valide jamais parce-que c'est un faux compte (n'a pas accès à l'adresse email) ou parce-qu'il abandonne la démarche, il n'y a pas de raison de notifier l'administrateur, car il n'y a aucune action à faire. Pour les situation de teste, l'administrateur à la possibilité de valider le compte (comme expliqué ci-dessus) et on part du principe qu'il n'a pas besoin d'être notifié.
