### ISSUE TITLE
Une direction créée avec l'outil de #557 ne s'affiche pas correctement dans la démarche en mode édition

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#601]
Pour reproduire:
* créer une direction avec l'outil de #557 
* ajouter cette direction à une démarche
* sauvegarder

Re-entrer en mode édition:
* la direction s'affiche sous la forme Directions.<sigle> et pas juste <sigle>

Après investigations, le problème semble lié à l'absence du titre du document de la Direction (qui doit être mis à la sigle de la direction).
Maintenant, il n'est pas clair si le titre est obligatoire (et devrait être mis en place par l'outil de création de directions) ou si la requête de la db list directions utilise le titre alors qu'elle devrait utiliser la propriété sigle ou le nom.

**Comment by slauriere** [comment]
La requête de la DBList aurait effectivement dû utiliser une propriété de l'objet plutôt que le titre du document, sur le même principe que la propriété "ministères". J'ai mis à jour la requête HQL, en utilisant le sigle plutôt que le nom car les noms de directions peuvent être longs, cela pose un problème lors de l'édition (dépassement de la zone allouée au champ de sélection). J'ai également simplifié le custom displayer de cette propriété : il affiche toujours le sigle, au lieu d'afficher tantôt le sigle, tantôt le titre.
