### ISSUE TITLE
Prototype tableau de bord des démarches phare

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#602]

**Comment by slauriere** [comment]
* Intégrer le critère disponibilité/temps de réponse (parmi les critères de qualité)
* Supprimer le critère « … intègre-t-il le questionnaire de satisfaction MonAvis ? » et modifier la règle d’affichage concernant le critère Indice de satisfaction : soit on affiche le résultat si il existe (plus de 100 votes sur une démarche) soit si ce n’est pas le cas afficher la valeur (« bouton de vote MonAvis à intégrer »)
* Date d’ouverture : mettre « ouvert » si la valeur est à « oui » sur la valeur « peut être réalisé en ligne »
* Remplacer « peut être réalisé en ligne » par « peut être réalisé complètement en ligne »
* Remplacer « Groupes » par « Thèmes »
* Groupes : nettoyer les donnes issues de la reprise de données (intérieur et équipement)
* Titre de la page : proposition de renommage : Observatoire de la dématérialisation tableau de bord des démarches phares de l’Etat – Situation à juin 2019
* Insérer des infos bulles sur les titres des colonnes qui pointent sur un page d’explication.
* Spécifier les n/a et les n/c : mail à venir pour préciser la règle de gestion

**Comment by slauriere** [comment]
* Faire en sorte de pouvoir automatiquement générer la pièce jointe contenant les données utilisées par le tableau de bord

**Comment by slauriere** [comment]
J'ajoute ci-dessous pour suivi la liste des points non encore traités parmi ceux ci-dessus : 
- Choix du mode d'affichage du critère "Disponibilité / temps de réponse" : libellé + badge
- Intégation HTML du titre de la page sur deux lignes
- Page d'aide et liens / infobulles
- Nettoyage des groupes : fait l'objet d'une tâche séparée : #589 
- Spécifier les n/a et les n/c : cela fait a priori plutôt partie de #571, à rouvrir le cas échéant, à voir

**Comment by slauriere** [comment]
Les évolutions suivantes ont été apportées : 
* Suppression de l'affichage "Disponibilité / temps de réponse"
* Génération de la valeur "Ouvert" directement au niveau du modèle
* Arrondissement du pourcentage de recours à la voie dématérialisée
* Les n/a et n/c ont été traités dans le cadre de #608 

Il reste à : 
* Intégrer le titre
* Statuter / ajouter des infobulles

**Comment by slauriere** [comment]
... (et la colonne « Thème » a été supprimée, au moins temporairement)

**Comment by lucaa** [comment]
> Suppression de l'affichage "Disponibilité / temps de réponse"

Remettons cette information, apparemment la raison pour l'enlever était un malentendu.

**Comment by slauriere** [comment]
L'information "Disponibilité / temps de réponse" a été restaurée.

**Comment by slauriere** [comment]
Rétablir la colonne "Thème" (groupes) (c'est une demande des ministères)

**Comment by lucaa** [comment]
@slauriere finalement, l'URL du tableau de bord sera "observatoire". monavis.numerique.gouv.fr/observatoire

**Comment by slauriere** [comment]
Les modifications suivantes ont été apportées dans le cadre du commit d3721a8 :
- Masquage de la date de mise en ligne quand le service est ouvert
- Renommage de colonnes : "Indice de satisfaction usager", "Support usager de qualité", "Disponibilité et temps de réponse"

**Comment by slauriere** [comment]
Deux règles de réécriture d'URL ont été ajoutées au fichier "urlrewrite.xml" : règle inbound et règle outbound de /observatoire vers /TableauDeBord/Top250.

**Comment by slauriere** [comment]
Le tri est à présent possible sur les colonnes "Disponibilité" et "Indice de satisfaction usagers". Les "n/a" ont été remplacés par des tirets, et les "n/c" par le libellé "À venir".

**Comment by lucaa** [comment]
Nouvelles améliorations à faire:
* les - affichés pour les cas ou la valeur n'est pas renseignée devraient être affichées sans décoration
* dans les détails de la démarche, pour une démarche qui ne peut pas être realisée en ligne: 
  * date d'ouverture: mettre "À venir"
  * ne pas afficher le pourcentage de recours à la voie dématerialisée

**Comment by slauriere** [comment]
Les améliorations suivantes ont été apportées : 
- Au lieu d'une réécriture d'URL, le tableau de bord a été déplacé dans "observatoire.WebHome". 
- Affichage de tirets sans badge en cas de n/a
- Date d'ouverture : « à venir » au lieu de n/c
- Pas d'affichage du pourcentage de recours à la voie dématérialisée

**Comment by lucaa** [comment]
> Pas d'affichage du pourcentage de recours à la voie dématérialisée

Si je lis bien le code, cette information a toujours été enlevé quand elle n'est pas disponible (n/a ou n/c). La règle que j'avais donné était uniquement pour les démarches qui ne peuvent pas être realisées en ligne. Autrement dit, pour une démarche qui peut être réalisée en ligne (complètement ou partiellement), le pourcentage de recours à la voie dématérialisée nous intéresse, y compris le fait qu'on ne connaît pas ce pourcentage. En même temps, c'est mon intuition, à confirmer avec @georges-bayard .

**Comment by slauriere** [comment]
> La règle que j'avais donnée était uniquement pour les démarches qui ne peuvent pas être realisées en ligne.
Effectivement, à présent le pourcentage du recours à la dématérialisation n'est absent que pour les démarches qui ne sont pas du tout dématérialisées.

**Comment by slauriere** [comment]
L'observatoire est à présent en version 1.0. Les évolutions ultérieures feront l'objet de taches dédiées. Fermeture de ce ticket.
