### ISSUE TITLE
questions de l'ANTS concernant l'utilisation du bouton MonAvis

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#607]
Je viens de sortir d’une réunion avec l’ANTS qui s’occupe des démarches concernant les titres sécurités(carte d’identité, passeport, permis de conduire, …) et le ministère de l’intérieur. La très bonne nouvelle c’est qu’ils se mettent en ordre de bataille pour installer le bouton rapidement. L’impact en terme de scalabilité ne devra pas être négligé car ils ont de fortes volumétries.

Ils me posent des questions concernant la pose du bouton dans le cadre de leurs contexte métier particulier : dans certaines procédures complexes ils souhaitent placer le bouton à plusieurs endroits dans la procédure. Il font la distinction dans le processus métier d’une même procédure entre 
•	les cas où la procédure est « passante » c’est-à-dire que la procédure se conclut positivement sans intervention humaine ni aller-retour entre l’ANTS et l’usager (80% des cas)
•	le cas où la procédure est « non passante » c’est-à-dire qu’elle ne se conclut qu’avec une intervention humaine en backoffice pour instruire la demande (20% des cas)

Ils ont deux préoccupations :

1/ Ils voudraient d’abord pouvoir distinguer finement les votes en fonction du contexte dans lequel ils ont été effectués en fonction du cas métier. Mes questions :
•	peuvent-ils placer le même bouton à plusieurs endroits dans la procédure ? à la fin de la procédure « passante » et à la fin de la procédure « non passante »
•	les résultats des votes sur les différents boutons pourront-ils être distingués afin d’avoir une analyse plus fine des résultats, dans le back office notamment ? cela nécessite-t-il une évolution de l’application ?

2 / ils souhaiterait aussi pouvoir pondérer les résultats des votes qui seront affichés dans le tableau de bord des démarches, en partant de l’hypothèse que les gens qui voteront sur le bouton correspondant à la procédure « non passante » seront forcément plus mécontents et voteront plus en proportion que ceux qui auront fait une procédure « passante »  qui seront forcément beaucoup plus satisfaits (ils sont content, la démarche a été très rapide et ils ont obtenu satisfaction) et moins enclins à voter pour dire leurs satisfaction ;
Ca me parait très compliqué mais il faut qu’on en reparle

**Comment by lucaa** [comment]
réunion prévue pour la semaine prochaine pour répondre à cette question.

**Comment by georges-bayard** [comment]
réponse donnée à l'ANTS

**Comment by georges-bayard** [comment]
j'ouvre en revanche une nouvelle issue sur le fait de leurs générer des boutants passant et non passant
