### ISSUE TITLE
Ajouter un filtre par ministère dans le tableau de bord des démarches phare, à côté de la recherche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#609]
Il s'agit d'une modification à apporter au tableau de bord fait pour #602: 
* à coté de la recherche texte il faut ajouter un filtre pour selectionner un ministere pour afficher uniquement les démarches d'un ministère.

**Comment by slauriere** [comment]
Un filtre de sélection par ministère a été ajouté juste avant le champ de recherche. Il reste à faire un travail d'intégration HTML pour un meilleur affichage, mais peut-être dans la tâche du tableau de bord elle-même#602 @lucaa ? Ou bien dans celle-ci ?

**Comment by lucaa** [comment]
Dans celle ci, ggr. Assigné-moi, stp.

**Comment by slauriere** [comment]
NB : il reste également à trier correctement les initiales accentuées, par exemple Écologie / Economie, je m'en occupe.

**Comment by slauriere** [comment]
La liste des ministères est à présent correctement triée dans le widget de sélection. Je t'assigne le ticket pour l'intégration HTML AL, merci pour ton aide.

**Comment by lucaa** [comment]
Pour implémenter le styling j'ai du changer un peu plus le code de @slauriere : j'ai bougé la création du selecteur de ministères pour l'initialization du tableau, au lieu de l'avoir dans le HTML direct. J'ai du donc mettre à jour la stratégie de prise en compte des valeurs de ce selecteur.
Le markup est le même que celui pour le filtre de datatables, le filtre est affiché à coté du filtre datatables standard.
En mode connecté les filtres chevauchent le contenu précédent qui est un titre, et donc le résultat est impacté par #597 , mais ceci sera corrigé par le nouveau UI.

**Comment by lucaa** [comment]
@slauriere je te laisse fermer si t'as rien contre mes changements.

**Comment by slauriere** [comment]
Super
