### ISSUE TITLE
Preselect the method of the feedback depending on the type of demarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#61]
As described in issue #60, there are 2 paths in the feedback form. They both need to be available to the user at any time, however there will be one of them that will be preselected when entering the feedback form, depending on the demarche itself, as follows:
- if none of the values "teleprocedure" or "online form" is present in the values of the digitalization level of the demarche, then the preselected path would be "other" - non-digitalized
- in all other cases, the preselected path will be "online" - digitalized

**Comment by slauriere** [comment]
The form is now showing up with a preselected value. We'll see if we keep the "Give your opinion" button present or if the form will show up at least partially on page load.
