### ISSUE TITLE
Rédiger la page d'explications pour les colonnes du tableau de demarches phares

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#615]
@georges-bayard : remplissez ici https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M10/Aide%20-%20Explications%20colonnes%20top250/ on intègrera des que c'est prêt.

**Comment by lucaa** [comment]
lors de l'intégration du texte il faut egalement mettre à jour les titres de colonnes du tableau de l'observatoire.

**Comment by georges-bayard** [comment]
Le texte est prêt
https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M10/Aide%20-%20Explications%20colonnes%20top250/

**Comment by slauriere** [comment]
La page d'aide a été mise à jour à partir du texte indiqué, et les colonnes du tableau ont été modifiées en conséquence.

**Comment by lucaa** [comment]
Remplacer la phrase « le site est « vert » si le score total est supérieur à 7 » par « le site est « vert » si le score total est supérieur ou égal à 7 »

**Comment by lucaa** [comment]
La modification a été faite.
