### ISSUE TITLE
Rédiger le texte explicatif du tableau de bord des démarches phares

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#616]
Texte à afficher en dessous du titre de la page.

**Comment by lucaa** [comment]
Voir maquette dans #612.

**Comment by georges-bayard** [comment]
Le texte est prêt
https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M10/Aide%20-%20Explications%20colonnes%20top250/

**Comment by georges-bayard** [comment]
Proposition de texte

Afin que gouvernement, citoyens et administrations puissent suivre l’état d’avancement et la qualité de la dématérialisation, un observatoire de la dématérialisation est mis en place. Celui-ci produit un  tableau de bord consultable par tous en ligne, et mis à jour tous les 3 mois afin de suivre les évolutions. Cet outil qui permet d’alimenter le débat public en données chiffrées et partagées fournit pour les 250 démarches phares des données concernant l’état d’avancement de sa dématérialisation, le respect de critères de qualité précis (qualité du support, accessibilité sur smartphone, disponibilité, temps de réponse, …) ainsi que les retours utilisateurs au travers d’un indice de satisfaction usagers. Cet indice de satisfaction est capté sur les démarche administratives en ligne elles-mêmes, grâce à un bouton « MonAvis » proposé en fin de parcours utilisateur. Ce bouton est en cours de déploiement progressif sur l’ensemble des démarches phares de l’Etat.

**Comment by slauriere** [comment]
Le texte a été appliqué sous le sous-titre, centré.

**Comment by lucaa** [comment]
Je re-ouvre pour intégrer les remarques suivantes:

> La partie texte semble un peu longue… et dans une certaine mesure redondant avec la home… on  ne peut pas élaguer ? Voir supprimer le texte hormi le fait qu’il s’agit de la version de juin 2019 ?

> Je suis pour supprimer ce texte de cet endroit, hormis la date (juin 2019).

@georges-bayard : j'attends votre nouvelle version de texte ou la décision de le supprimer complètement.

**Comment by georges-bayard** [comment]
j'ai proposé à Nadi et Xavier de maintenir le texte mais planqué dans un lien

**Comment by lucaa** [comment]
Proposition à implémenter:
>  on ajoute cette explication dans la page d'explication des critères de qualité, et qu'on mette un seul lien sur la page du tableau de bord, qui contient à la fois cette explication et les explication des colonnes.

**Comment by lucaa** [comment]
Il faut également changer le titre avec: "Observatoire de la dématérialisation de qualité"

**Comment by lucaa** [comment]
Les modifications ci-dessus ont été faites, je ferme.
