### ISSUE TITLE
Créer la page "comment donner son avis pour une démarche" 

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#618]
Il s'agit de la page vers laquelle pointe le dernier bouton "en savoir plus" affiché sur la page d'accueil (voir #611).

**Comment by georges-bayard** [comment]
@lucaa  Voici le texte à insérer

[présentation tableau de bord.docx](https://github.com/DISIC/wikidemarches/files/3286336/presentation.tableau.de.bord.docx)

**Comment by lucaa** [comment]
C'est fait, c'est intégré et lien mis derrière le bouton "En savoir plus" sur la page d'accueil.

**Comment by lucaa** [comment]
Changer la copie d’écran ? l’intitulé de la démarche est trop long. Prendre à la place changement d’adresse en ligne .

**Comment by lucaa** [comment]
Copie d'écran changé. J'ai également utilisé des copies d'ecran de taille similaire, pour un rendu plus propre de la page. Je ferme.
