### ISSUE TITLE
Display the success message for saving the user feedback

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#62]
We need to display a message when the user feedback is saved, but without leaving the user on the page which is the response of the post of the form, to avoid re-posting the data (by browser refresh).
We use PRG for this (https://en.wikipedia.org/wiki/Post/Redirect/Get) and we need a way to display a success message on the last Get.
A transportation of the message on the session is probably the way to go, making sure we destroy it after using it the first time.

**Comment by slauriere** [comment]
Reference to a best practice:
https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/BestPractices/#HHandlingerrorswhenusingxredirectfornon-JavascriptUIs

**Comment by slauriere** [comment]
The message box was updated to a success box with the success macro instead of the info one.
