### ISSUE TITLE
Observatoire : formater le nombre d'avis recueillis

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#626]
Formater le nombre d'avis recueillis (séparateur de milliers).

**Comment by lucaa** [comment]
@slauriere il y a du code dans ce commit qui ne semble pas être lié purement au formatage, mais aussi au tri du tableau. Tu peux mettre un commentaire pour expliquer quelle est le comportement courant?

**Comment by slauriere** [comment]
Un commentaire a été ajouté dans le cadre de #636.
