### ISSUE TITLE
Gestion plus fine de la valeur "n/a" pour la méta-donnée France Connect

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#627]
Il faut ajouter une nouvelle valeur possible pour la méta-donnée France Connect, pour marquer les démarches qui ne nécessitent pas d'authentification / identification.
Cette nouvelle valeur est "Sans identification". À afficher telle quelle sur la page de la démarche en mode connecté.

Des valeurs pour cette donnée seront fournies dans l'import du fichier excel, v2 ( #608 ), il faut mettre à jour l'import pour s'assurer que ces valeurs sont prises en compte.

Il faut également mettre à jour le tableau de l'observatoire de la démat ( #602 ), pour implémenter la gestion suivante pour la colonne France Connect:
* pour toutes les démarches ayant la valeur "sans identification", on affiche "non applicable" (n/a)
* pour les démarches ayant la valeur "non applicable" (n/a):
  * si la démarche peut être realisée en ligne, on affiche "non applicable" (n/a)
  * si la démarche ne peut pas être realisée en ligne, on affiche "-"
* pour les autres valeurs le comportement reste celui d'aujourd'hui.

**Comment by slauriere** [comment]
La nouvelle valeur de propriété a été ajoutée au modèle de données, et la règle d'affichage de la propriété FranceConnect a été mise à jour dans le tableau de bord de l'observatoire.

**Comment by slauriere** [comment]
Et la procédure d'import a été mise à jour pour prendre en compte cette nouvelle valeur possible et la normaliser.

**Comment by slauriere** [comment]
Réouverture pour conserver le maximum de données dans le JSON en déportant au maximum les règles d'affichage dans le JavaScript.

**Comment by slauriere** [comment]
La donnée brute a été ajoutée au fichier JSON généré en plus de la valeur à afficher.
