### ISSUE TITLE
Laisser accessible les statistiques des votes des démarches, uniquement sur lien direct

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#628]
Cette tache est une exception de la #545 , avec un travail supplémentaire pour rendre accessible ces données uniquement par lien direct (comme le formulaire d'avis, comme les informations cerfa numerique).

**Comment by slauriere** [comment]
Les statistiques sont à présent accessibles depuis le tableau de bord de l'observatoire via un clic sur l'indice de satisfaction ou sur le nombre d'avis recueillis. Pour ce faire, les identifiants de démarches ont été ajoutés au fichier JSON généré, et le paramètre "view-mode" a été positionné à "statistics". Dans le cas où l'utilisateur n'est pas authentifié, il ne voit que les informations générales de la démarche et les statistiques. Si le "view-mode" est absent ou invalide, l'utilisateur est invité à s'authentifié. Dans le cas où l'utilisateur est déjà authentifié, il voit les autres onglets auxquels il a accès.
