### ISSUE TITLE
Ajouter un lien vers les détails des votes dans l'observatoire, pour les démarches ayant un indice de satisfaction

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#629]
Ce lien doit pointer vers les pages de statistiques des votes pour une démarche ( #628 ). 
Pour une première version, mettons le lien dans la colonne "indice de satisfaction".

**Comment by slauriere** [comment]
Cette tâche a été implémentée dans le même temps que #628, avec également un lien depuis le nombre d'avis recueillis.

**Comment by slauriere** [comment]
Ré-ouverture de cette tache pour supprimer du tableau de bord de l'observatoire le lien vers la page de statistiques.

**Comment by slauriere** [comment]
Le lien direct a été supprimé.
