### ISSUE TITLE
Améliorations tableau de bord

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#633]
Quelques améliorations supplémentaires du tableau de bord:
* bouger le sous-titre dans le titre, sur 2 lignes supplémentaires - techniquement il va faloir remplacer le titre en syntaxe wiki avec titre en html car, si je me rapelle bien, on ne sait pas faire un retour à la ligne dans la syntaxe wiki dans un h1. Voir image:
![image](https://user-images.githubusercontent.com/657716/59707076-25022c00-9202-11e9-8b21-40684ff3b0de.png)
* Renommer « nombre d’avis recueillis » par « nombre d’avis usagers recueillis »
* implémenter la même stratégie d'affichage des tirets pour "accessibilité smartphone" que pour "france connect" - voir #631 
* sur la page d'accueil, mettre "consulter l'observatoire" tout en majuscules, comme "en savoir plus" 
* reprendre la page Aide/Observatoire du staging (mise à jour par @georges-bayard )
* Modifier la valeur affiché "a venir" par "non disponible"

**Comment by slauriere** [comment]
Ces points ont bien été traités. 

Concernant le remplacement de "à venir" par "non disponible" : 
- J'ai l'impression qu'il faut mettre à jour en conséquence la page d'aide (la version du staging mentionne encore des "à venir") @georges-bayard ?
- Est-ce qu'on remplace bien également le "à venir" de l'indice de satisfaction usagers, alors qu'il est présent dans l'Excel actuel ?

**Comment by georges-bayard** [comment]
premier point je m'en occupe
premier point non on maintient le "a venir" pour l'indice de satisfaction usager. On maintient un ton volontariste la dessus

**Comment by slauriere** [comment]
Les modifications suivantes ont bien été apportées : 
- Mise à jour de l'affichage du titre, de certains libellés et styles
- Même règle d'affichage pour "adapté smartphone" que pour "FranceConnect"
- Mise à jour de l'aide à partir de la version du staging de midi le 19/6
- "à venir" -> "non disponible" sauf pour l'indice de satisfaction
-> Je ferme ce ticket.

**Comment by slauriere** [comment]
La règle d'affichage du critère de disponibilité a été mise à jour ainsi que la page d'aide pour correspondre à la règle utilisée dans le fichier PDF : couleur orange pour des valeurs comprises entre 5 et 7 inclus.
