### ISSUE TITLE
Fixer l'entête de tableau du tableau de bord de l'observatoire au scroll

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#635]
L'objectif est de pouvoir garder l'entête visible quand on scroll pour lire les données.
L'idée est d'explorer les possibilités de faire cela avec du paramétrage de la librairie utilisée.

**Comment by slauriere** [comment]
L'en-tête garde à présent une position fixe lors du défilement. Les actions ci-dessous ont été effectuées :  
- Installation de bundles datatables homogènes ("datatables.net*")
- Installation de datatables.net-fixedheader
- Ajout de l'option "fixedHeader"
- Adaptation des CSS
- Mise à jour des instructions d'installation

**Comment by slauriere** [comment]
Réouverture pour traitement d'un problème de conflit de dépendances lié à l'installation de la librairie "datatables-fixedheader"

**Comment by slauriere** [comment]
Les instructions d'installation ont été mises à jour : utilisation des librairies org.webjar:datatables et org.webjar:datatables-fixedheader à la place des autres webjars disponibles pour ces modules (car les autres posent des problèmes de conflit avec la version de jQuery packagée avec XWiki). Le CSS de datatables-fixedheader est injecté directement dans DashboardSheet pour le moment car problème de chargement dynamique de SCSS for le module CSS de RequireJS.
