### ISSUE TITLE
Implémenter le tri par nombre d'avis recuellis pour le tableau de bord de l'observatoire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#636]
Le tri par défaut du tableau de bord de l'observatoire doit être la suivante:
* nombre d'avis recuellis
* ministere
* groupe
* (volumetrie?)
* alphabetique par démarche

**Comment by slauriere** [comment]
Ce tri par défaut a été implémenté, y compris avec la volumétrie, et un commentaire explicatif a été ajouté.

**Comment by slauriere** [comment]
L'implémentation du tri a été mise à jour pour que les mots commençant par une lettre accentuée apparaissent bien dans l'ordre lexicographique et non en fin de liste.
