### ISSUE TITLE
Bandeau mal proportioné sur IE11

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#641]
Sur IE11, l'image du bandeau du titre du site est mal proportionné:

![image](https://user-images.githubusercontent.com/657716/59782210-c39f9300-92bd-11e9-9a11-c99ec382dd73.png)

La technique utilisée pour implémenter ce bandeau n'est pas supportée par IE11, on doit implémenter un contournement.

**Comment by marineb** [comment]
@georges-bayard : est-ce qu'on peut fermer ça comme ce sera bientôt plus relevant ?

**Comment by lucaa** [comment]
Suite au #658 , cette tache n'est plus d'actualité.
Je ferme avec le label "invalid".
