### ISSUE TITLE
Mise à jour du pied de page

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#643]
Ajouter sous l’url MonAvis :
* « Un service proposé par la DINSIC »
* À la ligne le bloc-marque de la DINSIC cliquable et renvoyant vers numerique.gouv.fr, à préciser en title du lien
* Liens vers le Twitter et LinkedIn de la DINSIC 
* plan du site »
* Préciser « Nos services aux usagers »

![image](https://user-images.githubusercontent.com/1022195/59933276-718b7880-9449-11e9-9c63-b9a0607d527f.png)

**Comment by slauriere** [comment]
Nous avons mis à jour le pied de page, il reste à le déployer en production, je ferme cette tache.

**Comment by lucaa** [comment]
je re-ouvre pour decider ce qu'on met dans le Plan du site.

**Comment by lucaa** [comment]
> je re-ouvre pour decider ce qu'on met dans le Plan du site.

On laisse le plan du site tel quel, par contre:
1/ le logo de la Dinsic n'est pas cliquable
2/ il faut afficher numerique.gouv.fr en dessous des liens sociaux (?)

**Comment by lucaa** [comment]
Après discussion du 28/08/2019:
* on enlève le logo av. la Marianne, on met un lien vers numerique.gouv.fr sur le mot "DINSIC".
* on ajoute une abbreviation qui décrit l'acronyme
* on bouge le CGU , accessiblite, contact, login etc sous les liens medias sociaux à gauche
* plan du site à mettre à jour

**Comment by lucaa** [comment]
Le plan du site n'a pas été mis à jour, je vais créer une tache separée pour, mais le reste du pied de page a été mis à jour.
