### ISSUE TITLE
améliorations à apporter au tableau de bord des démarches phares

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#647]
A alimenter au fur et à mesure des retours utilisateurs : 
- tri par public (démarches entreprises /particuliers)
- accès à la données structurée (lien vers data.gouv)

**Comment by georges-bayard** [comment]
ajouter dans les informations complémentaires l'adresse du site

**Comment by lucaa** [comment]
Fait par: #724 , #738. 
L'affiche de l'URL de la démarche a été fait pour #640 .
Je ferme comme doublon.
