### ISSUE TITLE
Display mandatory fields in the Avis / Rating form

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#65]

**Comment by lucaa** [comment]
See documentation on https://www.accede-web.com/notices/html-css-javascript/7-formulaires/7-4-required-aria-required-champs-obligatoires/

**Comment by lucaa** [comment]
Apparently, for radio button groups, the required marker needs to be added on each input of the radio group.

**Comment by slauriere** [comment]
- "aria-required" was replaced by "required"
- issue #87 was created for the validation aspect
