### ISSUE TITLE
Supprimer du profil gestionnaire de démarche l'accès à la liste des applications via le menu en haut à droite

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#650]
![image](https://user-images.githubusercontent.com/17125654/61366210-6a5d5c00-a889-11e9-9a49-67dacbce2a65.png)

**Comment by georges-bayard** [comment]
idem pour la liste des doc wiki et l'annuaire wiki

**Comment by lucaa** [comment]
La tache #466, un peu plus générique, existe déjà pour traiter ce besoin. Je ferme la tache courante comme un doublon de #466 . L'implementation de #466 devra tenir compte de la spécification faite ici par Georges.
