### ISSUE TITLE
calculer les ratios de disponibilité/temps de réponse à partir de l'API Pingdom

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#652]

**Comment by lucaa** [comment]
Une première version de cette tache, qui permet de récupérer les données pour une période donnée, a été implémenté dans un script d'administration.
Les données sont récupérées dans un tableau dans une page wiki, à partir de laquelle elles peuvent être lues ou copiés dans un excel.
Je ferme cette tache maintenant, parce-qu'elle répond au besoin immediat de récuperation de données pour la mise à jour des démarches dans le nouveau tableau de bord. Pour d'autres usages de cette donnée, des nouvelles taches devraient être crées.
