### ISSUE TITLE
Mise à jour du nom du site

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#657]

**Comment by lucaa** [comment]
Cf. #656 , le nom du site doit être observatoire.numerique.gouv.fr pour tout le site sauf la page de vote.

**Comment by lucaa** [comment]
Attention au:
* nom du site dans les emails (de confirmation, etc)
* nom du site dans le footer

**Comment by lucaa** [comment]
Le nom du site a été mis à jour, il reste des pages d'aide à mettre à jour, pour lesquelles j'ai crée une tache separée: #687 .

**Comment by georges-bayard** [comment]
il faut qu'en interne on change le nom de la BAL de l'adresse de contact. Je crée une issue M12
