### ISSUE TITLE
Display rating editor with the RadioVoteDisplayer

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#66]

**Comment by lucaa** [comment]
After some more reflection and debate, I think the best would be to store the rating as part of the Avis class, as all the benefits of the rating application are not really interesting at this point:
* ratings are not associated to a user 
* for now we don't have a need for computing and storing average (and in any case it looks like the chances for it to be selective are quite high - only include online demarches). In any case, when we'll need this it will be easy to re-code it
  * from what I see on extensions.xwiki.org, recomputing of the average rating does not seem to be happening without impacting the history of the rated document, so there wouldn't be much advantage of using the rating API for setting ratings
* we won't use the standard UI of ratings
* as far as I remember, the separate storage of ratings is not necessarily compatible with the avis document naming that we created.

For all these reasons, I'll get rid of ratings class and use a new field in the avis class.

**Comment by lucaa** [comment]
Added a "score" property as described above in 868c998491ed0a54969c962d7be94fe6f33b9064 .
