### ISSUE TITLE
Observatoire version "en direct" 

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#660]
Il s'agit de pouvoir voir le tableay de bord (observatoire) avec les données "en direct", dans le sens décrit par la tache #640 . 

Cette tache recouvre une partie du travail necessaire pour la #640, elle est crée séparément pour des raisons de decoupage clair de l'objectif fonctionnel.

Vue accessible uniquement aux :
* administrateurs dinsic,
* administrateurs ministeriels

**Comment by slauriere** [comment]
* Installer l'extension user group.
* Créer une tâche de vérification des droits pour éventuellement protéger l'accès aux données agrégées en temps réel.

**Comment by slauriere** [comment]
* La tâche #668 a été créée concernant l'installation de l'extension de l'application membership-
profile.
 * La tâche #669 a été créée concernant la vérification des règles d'accès au fichier JSON contenant les données agrégées.

**Comment by slauriere** [comment]
Un bouton permettant l'affichage des données en temps réel a été ajouté, uniquement pour les administrateurs ministériels ou administrateurs, et un autre pour rebasculer en mode statique. N'hésitez pas à rouvrir cette tâche pour toute amélioration ou correctif.

Note technique :  la vérification d'appartenance au groupe des administrateurs ministériels s'effectue en utilisant le GroupServiceService, disponible suite à la résolution de #668, c'est le seul code qui utilise cette API pour le moment (en dehors de XWikiUserSheet), cf #670.
