### ISSUE TITLE
Ajouter une fonctionnalité de modification d'une ligne de l'observatoire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#661]
L'utilisateur (administrateur ministériel / porteur de démarche) doit pouvoir modifier une ligne du tableau de bord de l'observatoire , à partir d'un bouton affiché sur ce tableau.

Il y a 2 niveaux possibles:
1/ le lien "modifier" amène vers le formulaire de modification de démarche existant
2/ le lien "modifier" affiche un formulaire simplifié par dessus du tableau de bord, permettant la mise à jour rapide de la ligne

**Comment by slauriere** [comment]
Une première version de l'édition des démarches ligne par ligne est disponible sur le site de développement. Seules les propriétés "FranceConnect" et "Accessibilité smartphone" sont rafraîchies en live pour le moment.

Prochaines étapes :
- Rafraîchir toutes les colonnes, pas seulement FranceConnect et Accessibliité smartphone.
- Cela doit marcher pour plusieurs lignes à la suite (actuellement limitation à une seule ligne)
- La boîte de dialogue d'édition doit être plus compacte (positionner les boutons radio sur une seule ligne pour chaque champ).
- Possibilité d'éditer le nom de la démarche.
- Ne fournir le bouton d'édition que sur la version live du tableau de bord, pas sur les version historisées, puisque pour celles-ci les données sont figées.
- ...

**Comment by georges-bayard** [comment]
le temps de chargement de la version live a l'air très long
la cinématique des boutons est troublante. on appuie sur le bouton pour passer du temps réel aà la version figée. Pourquoi ne pas avoir un bouton temps réel qui s'ajoute au bouton version figée ? Il faut aussi avoir en tête qu'on devra avoir accès aux versions précédentes du tableau figé des trimestres précédents

**Comment by slauriere** [comment]
Les deux boutons s'affichent à présent en permanence.  La version live nécessite un certain temps effectivement, pas évident de le réduire mais à étudier. Dites-nous si tu vois d'autres améliorations.

**Comment by slauriere** [comment]
NB : une note pour ne pas oublier de vérifier les permissions nécessaires à l'édition de chacun des champs présents dans le tableau, hormis les champs calculés, qui ne seront pas éditables directement (actuellement les champs relatifs à la qualité de la dématérialisation ne sont éditables que par les administrateurs DINSIC).

**Comment by slauriere** [comment]
Nouvelle version disponible avec les améliorations suivantes :
- Boîte de dialogue plus compacte (cf capture ci-dessous).
- Le bouton d'édition n'est disponible que pour la version live.
- Rafraichissement dynamique de toutes les données de la démarche hormis les champs calculés "pourcentage de recours à la voie dématérialisée" et "support de qualité" à cause d'une limitation de l'API REST d'XWiki, en cours d'investigation : [XWIKI-16663](https://jira.xwiki.org/browse/XWIKI-16663) (un contournement consistant à implémenter une API dédiée reste toujours possible, à évaluer).
- Possibliité d'éditer plusieurs lignes à la suite.

![edition-demarche-via-tableau](https://user-images.githubusercontent.com/1022195/63358592-9b8ae980-c36b-11e9-89b5-6f0e7a677735.jpg)

**Comment by slauriere** [comment]
La version existante est testable et opérationnelle à 80% en principe. Je la déplace dans la colonne « À  tester » et je crée une autre tâche, dédiée à la finalisation : #680.
