### ISSUE TITLE
Repositionnement du lien voxusagers.gouv.fr dans le footer

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#662]
À décider: si on bouge le lien voxusagers.gouv.fr du footer du site, pour le mettre plus en avant.

À noter que le footer final sera celui décrit dans la tache #643 .

**Comment by georges-bayard** [comment]
positionner Voxusagers au niveau de la rubrique "nos univers" en seconde position après numérique

**Comment by lucaa** [comment]
C'est fait!
