### ISSUE TITLE
Mise en place du nouveau bouton de vote (svg)

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#664]
La vieille version png doit toujours marcher.

**Comment by lucaa** [comment]
> La vieille version png doit toujours marcher.

@marineb l'URL courant de l'image doit desormais pointer vers la nouvelle version du bouton? Ou on garde le bouton courant à cette URL et on fabrique des nouvelles URL pour le nouveau bouton?

**Comment by marineb** [comment]
Bonjour @lucaa !
- Pour la version PNG/JPG : elle pointe vers l'URL existante (en gardant les mêmes proportions du bouton)
- Pour la version SVG (qui sera la nouvelle version officielle), nouvelle URL

Est-ce que tu as les assets ?

**Comment by lucaa** [comment]
> Est-ce que tu as les assets ?

Oui, dans un email.

Donc si je comprends bien la réponse:
* les URLs courents des 2 boutons ( https://monavis.numerique.gouv.fr/monavis-static/bouton-blanc.png et https://monavis.numerique.gouv.fr/monavis-static/bouton-bleu.png ) vont désormais pointer vers la version png du nouveau bouton. C'est a dire, tous les intégrateurs qui utilisent le bouton avec une source d'image de monavis.numerique.gouv.fr vont désormais recevoir le nouveau bouton
* la version SVG sera disponible à des nouvelles URLs, et le code généré pour le bouton dans l'onglet "code à intégrer" va utiliser désormais, cette URL.
* les images couramment disponibles à https://monavis.numerique.gouv.fr/monavis-static/bouton-blanc.png et https://monavis.numerique.gouv.fr/monavis-static/bouton-bleu.png ne seront plus disponibles nulle part.

**Comment by georges-bayard** [comment]
j'ai du mal à suivre. ce que je comprends c'est qu'on ne diffuse pas de version png/jpg des nouveaux boutons et que pour les boutons déjà installés on les redirige vers les version svg; c'est ça ?

**Comment by lucaa** [comment]
> pour les boutons déjà installés on les redirige vers les version svg; c'est ça ?

justement, on ne peut pas tout simplement "rediriger" vers la version SVG, dans le sens ou pour tous les boutons déjà installés (donc qui réfèrencent le fichier png ) e ne suis pas sure qu'on peut envoyer tout simplement un svg à la place et ça suffira. Comme ça represente un changement de technologie (negligeable pour les navigateurs modernes, mais significatif pour les clients email et vieux navigateurs), on risque de créer des bugs, donc l'idée serait de garder, pour la retrocompatibilité, un fichier png (le temps que les intégrateurs re-prennent le code avec le SVG et intégrènt ce code). D'ici la question sur ce fichier png: est-ce que c'est la representation png du nouveau bouton? Est-ce que c'est l'ancien bouton et le nouveau bouton est disponible ailleurs? Si c'est la representation png du nouveau bouton, l'ancien bouton doit rester disponible quelque part ou pas? 
Ma proposition ci-dessus est que l'URL png des boutons déjà installés servira désormais la representation png du nouveau bouton, que les anciens boutons ne sont plus disponibles et que les versions SVG seront disponibles à des nouvelles URLs qui seront utilisées dans les bouts de code à intégrer proposés par l'outil.

**Comment by lucaa** [comment]
Je ferme cette tache, elle a été implementée avec la stratégie décrite ci-dessus.
