### ISSUE TITLE
ETQ usager, je peux visualiser le détail des votes sur le tableau de bord (observatoire)

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#666]
2 choses à faire: 
* rendre la page de statistiques de votes pour une démarche propre - enlever les éléments qui n'ont plus de sens (e.g. comment avez vous effectué cette demarche)
* mettre en place le lien dans l'observatoire

Le lien est affiché pour toutes les démarches ayant des votes.

À determiner: comment afficher les statistiques pour une démarche? Onglet ou lien direct?

**Comment by slauriere** [comment]
Pour mémo : dans le cadre de cette tâche, également optimiser le calcul des statistiques représentées sous forme graphique en utilisant un "group by" + post-traitement destiné à réduire le nombre de requêtes effectuées.

**Comment by lucaa** [comment]
> également optimiser le calcul des statistiques représentées sous forme graphique en utilisant un "group by" + post-traitement destiné à réduire le nombre de requêtes effectuées.

Id est  #341 .

**Comment by slauriere** [comment]
- L'optimisation mentionnée a été apportée à la page de calcul et d'affichage des statistiques des avis.
- Les statistiques concernant les modalités de soumission de la démarche ne sont plus affichées.
- Un lien conduisant à la page du détail des avis a été ajouté au tableau de bord, dans la colonne « Indice  de satisfaction usagers » pour les démarches pour lesquelles cet indice est affiché.
- Le détail des avis s'affiche directement, sans onglet -> à trancher. 

Le résultat de cette tâche est prêt à être testé.

**Comment by georges-bayard** [comment]
J'ai testé : vraiment très bien en expérience utilisateur, ça enrichit beaucoup le tdb. 
Problème qu'on n'a peut être pas anticipé : sur le tdb statique grand public on affiche une note figée à la date de la photo. Il faudrait que la vision détaillée de la note reflète également la situation à date de la prise de la photo. A rediscuter ?

**Comment by slauriere** [comment]
Ah oui tout à fait ! Je n'y avais pas pensé, je crée une tâche dédiée pour suivre la discussion.
