### ISSUE TITLE
Mise en place d'un accès rapide aux actions d'administration

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#667]
ETQ administrateur, je veux pouvoir accéder facilement aux outils d'administration (un lien dans le drawer ?).

**Comment by slauriere** [comment]
Un bouton a été ajouté sur la page d'accueil, uniquement pour les administrateurs, permettant d'accéder à la page Administration.WebHome qui contient les liens vers les outils d'administration complémentaires à ceux déjà présents sur cette page pour les administrateurs et administrateurs ministériels. Une page Administration.Tech complète ces liens par ceux pointant sur des pages de gestion technique.  Je ferme ce ticket, je vous laisse le rouvrir si des modifications sont nécessaires.

**Comment by georges-bayard** [comment]
ok ; je n'ai pas de compte de sur l'environnement de dev. Tu peux m'en fournir ?

**Comment by slauriere** [comment]
Georges, Je te l'envoie par mail.

**Comment by georges-bayard** [comment]
Il manque deux lien d'administration que j'utilise couramment :
nom de domaines autorisés : https://monavis.numerique.gouv.fr/Administration/Domaines%20autoris%C3%A9s
tableau de bord votes https://monavis.numerique.gouv.fr/TableauDeBord/
peuvent ils être ajoutés en l'état ?

**Comment by slauriere** [comment]
J'ai ajouté ces deux liens, dis-nous si cela te convient ainsi et si tu souhaites un autre agencement ?

**Comment by georges-bayard** [comment]
très bien
