### ISSUE TITLE
Installation de l'extension application-membership-profile

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#668]
Tâche technique : il s'agit d'installer l'extension [`org.xwiki.contrib.membership:application-membership-profile`](https://extensions.xwiki.org/xwiki/bin/view/Extension/User%20membership%20in%20the%20profile/) pour pouvoir visualiser les groupes auxquels appartient un utilisateur directement depuis la page de son profil, et pour pouvoir vérifier l'appartenance d'un utilisateur à un groupe en tenant compte de l'arborescence de groupes en plus d'une appartenance directe.

**Comment by slauriere** [comment]
[Les instructions d'installation](https://github.com/DISIC/wikidemarches/wiki/Installation-instructions-v-3.x) ont été mises à jour pour mentionner l'installation de cette extension, et la page XWiki.XWikiUserSheet modifiée pour intégrer l'onglet "groupes" a été ajoutée au dépôt de sources.

**Comment by lucaa** [comment]
@slauriere est-ce la même tâche que #432 ? Tu peux fermer #432 comme "duplicate" si c'est le cas, stp? Merci.

**Comment by slauriere** [comment]
@lucaa Ces deux tâches sont liées mais elles n'ont pas le même objectif. Est-ce que tu pensais en fait à une autre tâche que #432 ou est-ce moi peut-être qui ne comprends pas ?

**Comment by lucaa** [comment]
@slauriere biensur :) . #482. Sorry.
