### ISSUE TITLE
Cache des avis pour une démarche: remplacer calcul immediat lors de l'ajout d'un avis avec un calcul décalé

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#671]
Le calcul du cache des avis (nombre + taux de satisfaction) implementé pour #242 entraîne un coût lors de l'ajout d'un avis pour une démarche, car il est recalculé, pour une démarche, à chaque ajout d'avis.

En plus, cette information n'a pas forcement besoin d'être instantanée, on peut decaler le calcul et le faire une fois par jour, par exemple.

**Comment by slauriere** [comment]
Le calcul et le stockage du nombre d'avis et du taux de satisfaction s'effectue à présent de façon planifiée tous les jours à 3h du matin (paramétrable) au lieu d'être mis à jour à chaque ajout d'avis.  Un lien d'administration de cette tâche planifiée (SchedulerJob) a été ajouté à la page Demarches.Admin. La durée de la mise à jour est affichée à la fin de la tâche, elle est de l'ordre de quelques minutes (6 minutes) sur le serveur de développement (1500 démarches, mais peu d'avis). À  tester dans des conditions réelles sur le serveur de staging. Le composant effectuant le calcul a été simplifié techniquement : obtention du contexte d'exécution directement depuis le composant au lieu d'être passé en paramètre (cela posait [un problème d'incohérence](https://matrix.to/#/!ikPtGZaGWtyblizzlR:matrix.xwiki.com/$15663991456126hLKxb:matrix.xwiki.com?via=matrix.org&via=matrix.xwiki.com&via=matrix.wina.be) entre les objets ExecutionContext et XWikiContext).

**Comment by slauriere** [comment]
Vérifier pourquoi la mise à jour prend plusieurs minutes et peut-être n'exécuter la mise à jour que sous le sous ensemble de démarches le nécessitant.

**Comment by slauriere** [comment]
Le délai de plusieurs minutes correspond à une mise à jour des données d'environ 10 démarches par seconde, ce qui est un temps standard de mise à jour de document pour XWiki. Néanmoins le délai a été réduit en limitant le calcul aux seules démarches ayant reçu au moins un avis. Pour les autres, les statistiques sont déjà initialisées à la valeur zéro au moment de la création de démarche. Le délai de quelques minutes ne devrait pas être significativement supérieur en staging ni en production car le facteur limitant principal est la sauvegarde XWiki, pas le calcul statistique lui-même. Passage de ce ticket au statut "à tester".
