### ISSUE TITLE
Limiter l'export Excel des avis à un nombre fixe (2-300?)

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#672]
Dans l'objectif de la scalabilité, un problème important peut être généré par l'export en excel d'une liste d'avis très importante.

Cette tâche est liée à la #439 , c'est un des endroits ou l'accumulation des avis impacte la performance des fonctionnalités.

Il y a 2 exports des listes d'avis:
* dans le tableau de tous les avis
* dans l'onglet "avis" de la page de la démarche

L'objectif est de limiter le nombre de résultats mais de laisser en place la possibilité de filtrer et de trier et exporter les résultats filtrés et triés.
On n'a pas encore de décision pour le nombre de résultats max. - une première piste est 200-300 - il faut faire encore quelques tests sur le serveur de tests de performance.

**Comment by slauriere** [comment]
Procédure : ajouter un paramètre à la macro d'export avec, dans le cas où une limite est spécifiée, une indication pour que l'utilisateur soit informé que les données exportées ne seront que partielles.

**Comment by slauriere** [comment]
Un paramètre d'export a été ajouté à la macro, il reste à voir comment afficher automatiquement un message avertissant de l'existence de cette limite (éventuellement sous le bouton mais cela pose un problème dans le cas où il y a plusieurs boutons juxtaposés pour l'export Excel et CSV par exemple), à publier la nouvelle macro et à ajouter ce paramètre partout où elle est appelée sur le site.

**Comment by lucaa** [comment]
@slauriere est-ce que tu peux aussi vérifier qu'est-ce qu'on pourrait utiliser comme valeur pour cette limite? Quel serait un nombre de résultats qui est raisonnable en terme de temps de chargement, peut-être faire quelques tests pour voir comment le temps d'export evolue avec le nb de resultats?
Tu peux également utiliser le serveur de tests de perf pour cela, si t'as besoin de plus de donnees pour tester.

**Comment by slauriere** [comment]
Sur le serveur de développement, j'obtiens les temps de réponse ci-dessous pour l'export de tous les champs des avis.

- 10 avis : 5 sec
- 20 avis : 8 sec
- 100 avis : 12 sec
- 200 avis : 20 sec
- 500 avis : 40 sec
- 800 avis : 70 sec

Limitons peut-être à 500 ?

**Comment by lucaa** [comment]
J'ai validé le temps de ~35s pour les 500 avis sur le serveur de perf-staging avec un cache vide / rempli d'autres documents. Donc 500 me parait correcte comme limite dans les conditions des ressources du serveur de perf-staging, qu'ont été réproduite sur production suite à #674.

**Comment by slauriere** [comment]
Pour mémo technique : stocker la limite sous la forme d'une variable globale explicite de l'application (dans layoutExtraVars.vm pour le moment)

**Comment by georges-bayard** [comment]
serait il possible de mettre en place un filtre pour n'éditer que les avis avec les champs de verbatim remplis (les deux champs de saisie libre et le champ de commentaire) ?

**Comment by slauriere** [comment]
Une variable globale a été introduite pour l'export, positionnée à 500 pour le moment.

**Comment by slauriere** [comment]
Georges, Concernant les champs de saisie libre, j'ai créé la tâche #684 pour le suivi.

**Comment by lucaa** [comment]
Les dernières modifications dans l'outil pour l'export excel ont été faites et les instructions ont été mises à jour pour utiliser cette dernière version.
