### ISSUE TITLE
Optimiser le tableau d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#673]
Tâche lié à #439.

Le tableau contenant tous les avis prends beaucoup de temps pour s'afficher et impacte la performance du serveur.

Comme les livetables chargent le document pour chaque ligné affichée et qu'aujourd'hui ce tableau affiche 100 lignes par défaut, une première étape est de baisser le nombre de résultats affichés par défaut dans ce tableau.
Toujours dans cette tâche il faut investiguer la consommation de temps pour l'affichage de ce tableau pour potentiellement trouver d'autres sources d'optimisation.

**Comment by slauriere** [comment]
Le nombre de résultats affichés par défaut a été réduit de 100 à 10. Comme cela réduit déjà significativement le temps de chargement de la page, je ferme ce ticket et je vous laisse le rouvrir si un temps de chargement inférieur est nécessaire.

**Comment by slauriere** [comment]
PS : peut-être peut-on appliquer la même limite de 10 démarches par défaut sur la page /Demarches/
