### ISSUE TITLE
Enlever le téléchargement CSV de la page des stats

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#676]
Il s'agit du bouton de téléchargement des résultats de avis utilisateurs de la page qui donne accès aux statistiques des avis utilisateurs, qui seront affichées suite à #666 .

**Comment by slauriere** [comment]
Le bouton de téléchargement CSV a été supprimé. La page du service d'export lui-même reste disponible si besoin de rétablir la foncitonnalité ultérieurement avec une meilleure performance.
