### ISSUE TITLE
Améliorations de l'édition de démarche ligne à ligne depuis l'observatoire 

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#680]
Cette tâche est la suite de #661. Elle consiste à apporter les améliorations suivantes : 
- Rafraîchissement dynamique des champs calculés (pourcentage du recours à la voie dématérialisée et support usager de qualité) en plus de celui des champs non calculés.
- Ajouter la possibilité d'éditer le nom de la démarche.
- Restaurer la ligne éditée en mode déplié une fois la mise à jour effectuée.
- Peut-être ajouter un lien vers le formulaire complet.
- Positionner le focus sur le premier champ du formulaire pour navigation par tabulation.
- Fermeture de la boîte de dialogue avec la touche Échap.
- Vérifier les droits de modification champ par champ.
- ...

**Comment by slauriere** [comment]
Pour le rafraîchissement dynamique des champs calculés, une implémentation a été proposée pour la branche courante d'XWiki, cf [XWIKI-16663](https://jira.xwiki.org/browse/XWIKI-16663). Il reste entre autre à voir si cela est peut être appliqué facilement à la version utilisée par le projet ou s'il est plus efficace de développer un petit service ad'hoc.

**Comment by slauriere** [comment]
Plutôt que d'utiliser l'API REST, qui présente l'inconvénient de ne pas renvoyer les valeurs à afficher mais seulement les valeurs brutes, utiliser le service de génération lui-même, mais appliqué à une seule démarche.

**Comment by slauriere** [comment]
Le service de génération de fichier JSON a été adapté pour retourner les données pour une démarche unique et l'observatoire utilise à présent ce service dans tous les cas. Le champ d'édition de titre est à présent disponible depuis l'éditeur ligne à ligne.

**Comment by georges-bayard** [comment]
@slauriere : précision sur les règles de gestion concernant es restrictions d'accès en modification pour les utilisateurs ministériels :
- Objectif : empêcher que l'intervention des ministères sur des données du top 250 qui sont de la responsabilité de la DINSIC
- Ces restrictions ne s'appliquent donc que si la démarche est flaguée "top 250". Si la démarche n'est pas flaguée les restrictions ne s'appliquent pas (à l'exception toutefois du flag "top 250" qui ne peut en aucun cas être modifié par un autre profil que le profil DINSIC)
- champ concernée par les restrictions : le flag Top 250, tous les critères qualité (smartphone, contact, France connect, ...), indicateur de niveau de dématérialisation ("peut être réalisé complètement en ligne")
- Les données soumises à restriction ne peuvent être modifiées par les profils administrateur ministériel et porteur de démarche
- Les restrictions s'appliquent sur toutes les interfaces de saisie (complète et simplifiée)

Illustration du mode de fonctionnement recherché  : création à l'initiative du ministère d'une démarche qui a vocation à intégrer le top 250. Le ministère complète toutes les données et la soumet à la DINSIC qui valide sur la partie critères qualitatifs et niveau de dématérialisation. Une fois les données validées la DINSIC active le flag "Top 250". A partir de la le ministère perd la main sur les données soumises à restriction

**Comment by slauriere** [comment]
Georges, Ok. J'ai créé une tâche dédiée à la mise en place / la vérification des règles de contrôle d'accès aux démarches : #688.
