### ISSUE TITLE
Mise à jour des conditions generales pour qu'elles soient adaptées aux deux services: voxusagers et observatoire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#682]

**Comment by lucaa** [comment]
Voir aussi #663 .

**Comment by georges-bayard** [comment]
remplacer le premier § par le § suivant : 
"Ce site permet de suivre l’avancée et la qualité de la dématérialisation des 250 démarches phares de l'État. Il met à disposition les données précises sur l’offre de services dématérialisés aux usagers et présente des indicateurs de qualité concrets mis à jour tous les 3 mois.

Il permet également aux usagers de donner leurs avis sur les démarches en ligne qu’ils viennent d’effectuer, et en affiche les résultats de manière transparente. Un bouton/lien situé à la fin de la démarche permet d’accéder à ce service."

Ajouter à la fin de la partie conditions d'utilisation le § suivant : 
"L'adresse URL qui permet d'accéder à l'observatoire de la qualité des démarches en ligne est la suivante : observatoire.numerique.gouv.fr. L'adresse url vers laquelle sont dirigés les usagers qui donnent leurs avis à la fin d'une démarche est la suivante : voxusagers.numerique.gouv.fr."

**Comment by lucaa** [comment]
Le nouveau texte est mis en place.
