### ISSUE TITLE
Proposer une rédaction de la page "en savoir plus" accessible de la homepage

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#683]

**Comment by georges-bayard** [comment]
[Contenu de la page en savoir plus.docx](https://github.com/DISIC/wikidemarches/files/3556518/Contenu.de.la.page.en.savoir.plus.docx)
Voici en pj le contenu de la page modifiée. C'est la même page que celle accessible via le lien "En savoir plus sur le tableau de bord". Je pourrais la mettre à jour en direct après le déploiement en prod. Je créé une tache à réaliser par moi en post déploiement

**Comment by georges-bayard** [comment]
pour que la front page, le tableau de bord et les explications soient raccord, il faut que les intitulés des rubriques et leurs positionnement soient raccord. Je crée une tache pour modifier le tableau de bord en ce sens

**Comment by lucaa** [comment]
Dans le texte proposé il reste quelques références à "MonAvis", par exemple 

> Cet indice de satisfaction est capté sur les démarches administratives en ligne elles-mêmes, grâce à un bouton « MonAvis »

ou 

> Il n’est affiché que lorsque le nombre d'avis recueillis sur MonAvis est supérieur à 100. 

et encore quelques autres.

Ces réferences n'ont désormais plus de sens, le texte devrait être mis à jour pour exprimer cela différement. Voir aussi #687 qui a été crée pour cela.

**Comment by lucaa** [comment]
J'ai mis à jour le texte mais je laisse la tache ouverte pour gérer les mentions de MonAvis.

**Comment by lucaa** [comment]
> je laisse la tache ouverte pour gérer les mentions de MonAvis.

Une tache specifique a été crée: #707.

Je ferme celle ci.
