### ISSUE TITLE
Possibilité de trier les avis par valeur de champs de saisie libre

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#684]
Création de cette tâche suite à la demande ci-dessous de GBA dans le contexte de #672 :

>serait il possible de mettre en place un filtre pour n'éditer que les avis avec les champs de verbatim remplis (les deux champs de saisie libre et le champ de commentaire) ?
Mon sentiment plus général sur cette question est qu'il faut faire basique à court terme car pour répondre plus finement aux besoins on ne coupera pas à l'organisation d'un atelier dédié backoffice avec les utilisateurs

**Comment by slauriere** [comment]
J'ai ajouté les trois champs de saisie libre au tableau d'avis (sur le site de développement). Le tableau peut ainsi être trié sur chacun de ces champs pour faire apparaître en premier les valeurs non vides. J'ai (peut-être temporairement) masqué l'affichage des champs  « identifiant de session »,  et « date de dernière mise à jour » pour maintenir un affichage sans barre de défilement en largeur. Un filtre est je pense plus compliqué à mettre en place car je ne crois pas qu'XWiki dispose par défaut d'option pour n'afficher que des valeurs non vides. Qu'en penses-tu @lucaa ?

Georges, Est-ce que cela répond au besoin que tu exprimais ? Vois-tu des compléments à apporter à ce stade ?

**Comment by georges-bayard** [comment]
C'est OK pour moi. pendant qu'on y est on peut également supprimer le champ "modalité" qui me semble caduque

**Comment by slauriere** [comment]
OK j'ai supprimé ce champ également.

**Comment by lucaa** [comment]
> je ne crois pas qu'XWiki dispose par défaut d'option pour n'afficher que des valeurs non vides

je confirme, j'ai voulu le faire sur une autre issue et ça n'a pas marché. Par contre, il est raisonnablement facile de faire un service de données du tableau custom pour ajouter ce filtre.

> J'ai (peut-être temporairement) masqué l'affichage des champs « identifiant de session »

l'identifiant de session est interessant car il permet d'identifier rapidement les votes multiples, même si on n'a pas besoin de le trier / filtrer avant un export, donc c'est pas necessaire de l'avoir dans le tableau, on pourrait faire l'evaluation des votes multiples dans l'excel.
