### ISSUE TITLE
Affichage des statistiques d'avis correspondant à une date spécifique

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#685]
Suite à #666, les utilisateurs ont accès aux statistiques d'avis détaillées par démarche, depuis le tableau de bord. Actuellement, les statistiques affichées reflètent l'état courant des données, ce qui pose une incohérence dans ce parcours : les utilisateurs s'attendent à voir des statistiques en phase avec celles du tableau de bord, qui reflète une situtation antérieure.

Plusieurs options : 
- Maintenir un calcul des statistiques en direct, mais en ajoutant une contrainte sur la date à laquelle les avis ont été soumis (pas de difficulté a priori, mais à étudier).
- Archiver les statistiques sur le même principe que l'archivage des tableaux de bord (#639).
- Afficher un message temporaire indiquant que les statistiques reflètent l'état courant et pas celui du(des) tableau(x) de bord à date.

**Comment by georges-bayard** [comment]
Pour moi c'est 1 ou 2

**Comment by slauriere** [comment]
Oui tout à fait, je n'avais mentionné l'option 3 qu'en cas de difficulté avec les deux autres options. L'option 1 a été implémentée (calcul en direct) : les statistiques d'avis s'affichent à présent pour une date paramétrable (ou reflètent la situation courante si aucune date n'est indiquée, auquel cas ce sont les statistiques mises à jour chaque nuit pour l'ensemble des démarches qui s'affichent). Pour le tableau de bord existant, c'est la date du 30 juin 2019 qui est utilisée, et qui est affichée en début de page.

**Comment by slauriere** [comment]
Dans le mode 'live', le lien doit pointer vers les statistiques courantes. Cela a été corrigé.

**Comment by georges-bayard** [comment]
question : un administrateur fonctionnel peut il paramétrer lui même la date ?

**Comment by slauriere** [comment]
Actuellement la date peut être paramétrée dans l'URL, nous pouvons prévoir une interface graphique facilement si besoin, notamment dans le cadre de la tâche #640 concernant  le stockage et l'affichage dynamique des données du tableau de bord.

Exemple : http://observatoire.numerique.devxwiki.com/Demarches/975?view-mode=statistics&date=2019-06-30

NB: attention, pour la démarche 1289 sur le site de développement il y a plusieurs avis invalides (vote vide) qui font que les statistiques de cette démarche sont inexactes, ce sera ok pour des tests plus poussés sur le site de staging.
