### ISSUE TITLE
Mise à jour du plan du site dans le pied de page

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#686]
Suite aux modifications de la structure du site, le plan du site devrait être mis à jour dans le pied de page.

**Comment by lucaa** [comment]
Il faut egalement enlever le point après la phrase "Un service proposé par la DINSIC."

**Comment by lucaa** [comment]
@slauriere est-ce que tu peux faire une proposition pour les liens à mettre en pied de page, en fonction également de la nouvelle page d'accueil de la tache #658 ? (les liens qui sont présents sur cette page?)

**Comment by slauriere** [comment]
Voici les changements apportés à la version de développement (proposition) : 
* Plan de site avec trois entrées : Observatoire, En savoir plus, Qui sommes-nous ?
* Ajout d'un lien "Code open source" dans la première colonne (cf maquette Zepelin)
* Ajout d'un lien "Communauté UX design" dans la troisième colonne (cf maquette Zepelin)
* Suppression du point après "DINSIC"
Qu'en pensez-vous ?

**Comment by lucaa** [comment]
Voici le résultat avec ces nouveaux liens, à valider:

![image](https://user-images.githubusercontent.com/657716/64545711-87faef00-d329-11e9-9ecd-d9aea536b8dd.png)

**Comment by georges-bayard** [comment]
le lien code open source pointe sur le Github je suppose. Quid du lien communauté UX design ?

**Comment by slauriere** [comment]
GBA, Oui pour GitHub. L'UX pointe actuellement vers : https://www.modernisation.gouv.fr/le-hub-des-communautes/communaute-ux

**Comment by lucaa** [comment]
Discuté avec @georges-bayard , on va enlever le lien vers communauté UX.

**Comment by lucaa** [comment]
Pied de page validé tel que proposé et implementé par @slauriere , sans le lien vers communauté UX que j'ai enlevé.
