### ISSUE TITLE
revoir le libellé des rubriques du tableau de bord ainsi que l'ordre des colonnes

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#689]
Cette tache est destinée à mettre en cohérence la homepage, le tableau de bord, la page "en savoir plus"
Intitulé et ordre des colonnes : 
- Démarche dématérialisées (au lieu de "peut être réalisé complètement en ligne") 
- Usagers satisfaits (au lieu de "indice de satisfaction usagers")
- Optimisé sur mobile (au lieu de "accessibilité smartphone")
- Support de qualité (au lieu de "support usagers de qualité")
- Disponibilité du service (au lieu de "disponibilité / temps de réponse")
- Intégration FranceConnect (au lieu de "identification France Connect")

**Comment by lucaa** [comment]
Les modifications ont été faites, je ferme cette tache maintenant.
@slauriere tu peux jeter un oeil sur mes modifications et vérifier que j'ai bien modifié tous les endroits ou l'ordre des colonnes est détérminée / utilisée?

**Comment by slauriere** [comment]
J'ai vérifié : ok pour moi.
