### ISSUE TITLE
Améliorations techniques de l'éditeur ligne à ligne

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#693]
Améliorations techniques à apporter : 
- Le code de sécurité du formulaire (csrf) devrait être regénéré à chaque affichage de boîte de dialogue, au lieu d'être comme actuellement associé à la session.
- L'affichage / masquage du lien d'édition pourrait être piloté directement en JavaScript via un paramètre d'URL plutôt que de nécessiter une exécution Velocity systématique (le cache devant alors être désactivé pour cette page).
- Corriger le message s'affichant en cas d'erreur de chargement du formulaire.

Tâches liées : #661 #640

**Comment by slauriere** [comment]
* Le code de sécurité est lié à la session utilisateur et reste identique à chaque chargement de formulaire donc pas de problème spécifique de sécurité, en revanche le code actuel force à ne pas mettre en cache ce JavaScript, il pourrait être intéressant de générer ce code dans le template de génération des éléments de formulaire.
* Si l'option sans cache est maintenue, considérer une désactivation de la minification JavaScript.

**Comment by slauriere** [comment]
Le chargement se fait à présent sans minification du JavaScript, et un message d'erreur s'affiche en cas de problème lors de l'obtention du formulaire (problème de droit d'accès ou autre).

**Comment by slauriere** [comment]
En 2017, le navigateur Microsoft Edge [n'implémentait pas correctement la directive "no-cache"|https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10739540/] actuellement utilisée. Un paramètre temporel a été ajouté pour forcer un rechargement systématique du JavaScript cible, qui a une taille de 18 KB. Qu'en penses-tu @lucaa?

**Comment by lucaa** [comment]
deployé sur staging le 05/09/2019. 

> Qu'en penses-tu @lucaa?

l'interdiction de cacher fait la même chose, non? (quand elle marche)

**Comment by slauriere** [comment]
Oui, du point de vue de la charge du serveur cela revient au même, juste un contournement du bug Microsoft Edge. Merci. Je clos.
