### ISSUE TITLE
Fiche complète de démarche : restaurer l'affichage de la valeur du champ "Top 250" pour les utilisateurs non administrateurs

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#694]
Suite à #688, la propriété "Top 250" ne s'affiche plus en visualisation pour un utilisateur connecté mais non administrateur, alors qu'elle ne devrait être absente qu'en mode édition dans ce cas.

**Comment by slauriere** [comment]
Le problème a été réglé.

**Comment by lucaa** [comment]
deployé sur staging le 05/09/2019.
