### ISSUE TITLE
Texte pour la page "à propos" / nouvelle page "qui sommes nous"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#696]
il s'agit de l'ancienne page "a propos", qui devrait être mise à jour depuis M8 / M9 (voir #471).
L'idée est de transformer cette page dans une page qui répond à la question "qui sommes nous" et d'avoir un lien vers cette page dans un menu en haut de la page (tache #697).

**Comment by georges-bayard** [comment]
le texte à insérer pour la rubrique "à propos" est le suivant : https://pad.etalab.studio/IMQ79Q0XRjSxXC7FGw15bQ#

**Comment by slauriere** [comment]
Le contenu de la page « À propos » a été mis à jour. La nouvelle page est visible sur le site de développement http://observatoire.numerique.devxwiki.com/Main/A%20propos
