### ISSUE TITLE
Mise en place du menu du haut de page 

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#697]
Voir maquette dans #658.
il s'agit de mettre en place les liens "250 demarches"  (qui va vers l'observatoires) et "qui sommes nous" (qui va vers #696 ), en haut de la page.

**Comment by lucaa** [comment]
Les 2 liens ont été ajouté, cf dernière maquette (voir #658 ), mais j'ai un problème de placement de ce menu sur mobile, l'affichage en dessous du tittre n'est pas le plus inspiré:

![image](https://user-images.githubusercontent.com/657716/64695299-11cac980-d49c-11e9-8caa-cb6034cb0403.png)

@marineb as-tu une idée de comment on pourrait faire?

**Comment by marineb** [comment]
@lucaa je regarde ca !

**Comment by marineb** [comment]
@lucaa j'ai ajouté une screen mobile sur Zeplin. Dis-moi si ca te va.

**Comment by lucaa** [comment]
J'ai crée une nouvelle tache pour la gestion de l'affichage sur mobile, pour pouvoir fermer celle-ci parce-qu'elle est globalement faite.
