### ISSUE TITLE
page d'activation des comptes utilisateurs : ETQ administrateur je veux supprimer de la liste des demandes de comptes celles que je ne valide pas

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#702]

**Comment by slauriere** [comment]
Il est à présent possible (sur le site de développement) de supprimer des comptes. Ceux-ci sont alors effacés de la plateforme sans notification automatique. Je clos cette tâche. GBA je te laisse la rouvrir si besoin.

**Comment by georges-bayard** [comment]
ok ca marche !
