### ISSUE TITLE
Rendre accessible le TDB top 250

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#703]
Synthèse des constats faits par Jamshid avec un lecteur braille :

- Les liens twitter, instagram, facebook ne sont pas labellisés
- Lecture de la colonne titre : les 5 premières colonnes sont lues sans que l'utilisateur comprenne qu'il change de colonne ; la lecture s'interrompt au slash avant "temps de réponse pour reprendre ensuite
- Les options de tri sur la colonne de titre ne sont pas labellisées
- Problème d'accessibilité des informations complémentaires : le tableau contient 8 colonnes dont la 1ere est constituée par la croix qui permet d'accéder au détail. Il faut mettre un label sur la croix (le libeller "en savoir plus")
- Ajouter des titres de niveau 2 sur la page pour faciliter la navigation : sur les filtres, le tableau de bord, le bas de page (traité aujourd'hui entitre de niveau 3)

**Comment by georges-bayard** [comment]
1. mettre cette issue en M12
2. prévoir une séance de travail avec jamshid. Soit pour valider les évolutions réalisées avec lui, soit pour spécifier plus précisément le besoin

**Comment by georges-bayard** [comment]
[Évaluation rapide tableau Observatoire.docx](https://github.com/DISIC/wikidemarches/files/3584523/Evaluation.rapide.tableau.Observatoire.docx)
voici l'évaluation rapide faite par Anthony en complément

**Comment by lucaa** [comment]
[190912 Évaluation rapide tableau Observatoire.docx](https://github.com/DISIC/wikidemarches/files/3636018/190912.Evaluation.rapide.tableau.Observatoire.docx)

**Comment by lucaa** [comment]
J'ai transformé les retours du fichier en tâches, à l'excéption de:

* ER-05 Chaque page affiche un fil d'Ariane représentant la position de la page dans l'arborescence du site
  * Doit-on afficher le fil d'Ariane pour une navigation si simple? Si oui, on l'affiche ou?
* ER-06 Aucune information n'est véhiculée que par la couleur
  * Il reste uniquement les liens vers les 2 téléchargements et le lien du tableau vers la page de statistiques des avis de la démarche:
![image](https://user-images.githubusercontent.com/657716/70099831-44fe9e00-1630-11ea-98f7-284d7bfbedb4.png)
Question: pour les liens de téléchargement, doit-on les différentier du reste? Pour le lien du tableau, comment on peut indiquer que la valeur est cliquable (contrairement aux autres valeurs du tableau). @marineb ?
* ER-24 Le pied de page comporte les liens obligatoires des sites publics
  * le plan du site est désormais affiché dans le pied de page, ce n'était pas au moment de la création de ce document, je pense
* le résultat de recherche dans Google montre qu’il manque des informations : 
  * suite aux modifications faites pour #764 , le site est désormais correctement indexé par Google

**Comment by lucaa** [comment]
> Les options de tri sur la colonne de titre ne sont pas labellisées

Le tri sera bougé vers le menu à coté des filtres: #719 .

> Les liens twitter, instagram, facebook ne sont pas labellisés
> Problème d'accessibilité des informations complémentaires : le tableau contient 8 colonnes dont la 1ere est constituée par la croix qui permet d'accéder au détail. Il faut mettre un label sur la croix (le libeller "en savoir plus")

Couverts par #790.

> Ajouter des titres de niveau 2 sur la page pour faciliter la navigation : sur les filtres, le tableau de bord, le bas de page (traité aujourd'hui entitre de niveau 3)

Des liens d'accès rapide seront ajoutés - #787, j'espère que ça sera satisfaisant.

**Comment by lucaa** [comment]
> Pour le lien du tableau, comment on peut indiquer que la valeur est cliquable (contrairement aux autres valeurs du tableau). 

traité par #792 .

**Comment by lucaa** [comment]
> Problème d'accessibilité des informations complémentaires : le tableau contient 8 colonnes dont la 1ere est constituée par la croix qui permet d'accéder au détail. Il faut mettre un label sur la croix (le libeller "en savoir plus")

La colonne avec le bouton "plus de détails" a été bougé en dernière position depuis la création de cette tache, beaucoup plus logique qu'en première position, et l'étiquetage du bouton a été corrigé par @slauriere  dans le cadre de #790 .

**Comment by lucaa** [comment]
Il reste à vérifier le comportement du lecteur d'écran pour la tête de tableau : 
> Lecture de la colonne titre : les 5 premières colonnes sont lues sans que l'utilisateur comprenne qu'il change de colonne ; la lecture s'interrompt au slash avant "temps de réponse pour reprendre ensuite

**Comment by slauriere** [comment]
J'ai fait des tests avec le logiciel JAWS. 
- L'interruption de lecture était probablement due à la présente de la balise `<br/>` dans l'attribut "alt" des images, j'ai fait en sorte que ces balises soient supprimées dynamiquement à cet endroit.
- Concernant l'identification des colonnes : JAWS identifie bien un tableau de 10 colonnes, mais ne mentionne pas de changement de colonne effectivement. J'ai ajouté l'attribut "scope='col'" comme recommandé sur le site [Webaim](https://webaim.org/techniques/tables/data) mais JAWS ne signale pas pour autant de changement de colonnes. Est-ce que Jamshid pourrait peut-être nous indiquer des tableaux pour lesquels ce changement de colonne est bien signalé ? Je continue à chercher de mon côté.

**Comment by lucaa** [comment]
Une tâche separée a été créé pour le lecteur d'écran, #811 . 
Je ferme maintenant cette tache car le reste a été traité.

**Comment by AnthonyBrunelli** [comment]
Vu - il faudrait que je creuse deux-trois points ou que je retrouve mes petits par ailleurs, je fais ça vite.
Sinon, je pense que le texte Google est à revoir: il restitue les entêtes + d'où vient le texte, il est coupé bizarrement par un point au milieu de la phrase...

![image](https://user-images.githubusercontent.com/35567048/72903417-75f47880-3d2d-11ea-8bc4-144479676ec0.png)

**Comment by lucaa** [comment]
@AnthonyBrunelli ok, on peut creuser la partie d'affichage dans les résultats de recherche. Est-il possible de créer une tache dediée à cet aspect, j'aimerais eviter d'ouvrir celle ci car elle est trop large...

**Comment by AnthonyBrunelli** [comment]
Comme on a tout refait les tests, je passe cette issue dans la dernière colonne. On suit les différents points par ailleurs. J'ai fait une issue dédiée pour Google et autre moteur de recherche (texte qui apparaît) #845
