### ISSUE TITLE
Mise à jour de la page d'aide de l'observatoire et de la tête du tableau pour rendre les noms identiques à la section de la page d'accueil

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#708]
Il s'agit de la même tache que #689  , suite aux quelques modifications des intitulés des critères qui ont été apportées dans les dernières versions de la page d'accueil ( #658 ).

@georges-bayard : pouvez vous nous donner un avis sur cette tâche (à faire  / pas à faire), informations supplémentaires?

![image](https://user-images.githubusercontent.com/657716/64717016-c75d4300-d4c3-11e9-8e43-7b33a97ab2c7.png)

![image](https://user-images.githubusercontent.com/657716/64717081-e5c33e80-d4c3-11e9-8f58-9711fa44acc6.png)

![image](https://user-images.githubusercontent.com/657716/64717057-da701300-d4c3-11e9-88fb-8a09299371f1.png)

**Comment by georges-bayard** [comment]
on fera ça en post prod
