### ISSUE TITLE
Importer le tableau de bord Excel dans XWiki pour le T3 2019

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#709]
Tache à réaliser : faire un RAZ sur l'information Top 250 du référentiel, car des démarches ont été supprimées du top 250

**Comment by slauriere** [comment]
Les données ont été importées sur le site de développement et un tableau de bord utilisant ces nouvelles données a été généré puis visualisé. Les actions ci-dessous ont été effectuées : 
- Mise à jour du modèle de démarche : le champ "Dites-le-nous une fois" peut prendre des valeurs multivaluées de type texte pour le moment, aviser.
- Mise à jour des configurations d'import pour 1) inclure le champ "Dites-le-nous une fois", 2) actualiser le nom des colonnes Pingdom
- Ajout d'une page "Administration.DemarchesPharesDiff" pour visualiser les démarches qui entrent parmi les démarches phares et celles qui en sortent entre deux imports. Les démarches sortantes doivent pour le moment être mises à jour manuellement à partir de la liste obtenue.
- Les instructions d'import ont été mises à jour sur la page [dinsic.xwiki.com:Intégration des démarches phares](https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M9/Int%C3%A9gration%20des%20d%C3%A9marches%20du%20top%20250)

NB : lors de l'import, la valeur d'uptime, qui est un nombre réel, est approximé à trois décimales après la virgule, cela pas d'incidence réelle pour les utilsateurs mais c'est inattendu, il faudrait voir pourquoi.

**Comment by slauriere** [comment]
La propriété "Complexité des informations redemandées" a été modifiée (et renommée) pour accepter des valeurs numériques, l'import a été adapté ainsi que l'affichage dans le tableau.

**Comment by slauriere** [comment]
Pour la propriété "Complexité des informations redemandées" : la valeur "n/a" est désormais stockée explicitement sous la forme de la valeur "-1". La valeur "non mesuré" correspond à une absence de valeur en base de données. Le mécanisme d'affichage a été adapté en conséquence, et un nouvel import effectué sur le site de développement.

**Comment by slauriere** [comment]
La structure de donnée et la procédure d'import ont été mises à jour pour intégrer les données du tableau de bord du T3, je ferme ce ticket, je vous laisse le rouvrir si besoin.
