### ISSUE TITLE
Affichage du menu du haut de page sur mobile

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#710]
Reste à faire suite à  #697 . 
Voir la proposition  d'affichage sur #697.

**Comment by AnthonyBrunelli** [comment]
@lucaa Tu peux préciser ce dont il s'agit stp?

**Comment by lucaa** [comment]
Il s'agit de l'affichage des liens du menu en haut à droite (L'observatoire, A propos) sur mobile.

Affichage courant: 
![image](https://user-images.githubusercontent.com/657716/79688386-4da5e880-824e-11ea-8243-538eb37570f0.png)

Affichage souhaité (capturé de zeplin): 
![image](https://user-images.githubusercontent.com/657716/79688359-2222fe00-824e-11ea-9558-16d0c72f5e4e.png)

**Comment by lucaa** [comment]
Dans la maquette le menu semble être aligné à gauche en dessous du logo, pouvez-vous confirmer cette règle d'affichage?

**Comment by lucaa** [comment]
@AnthonyBrunelli : je bouge dans la colonne "à spécifier par Dinum" pour décider si c'est à faire ou pas.

**Comment by AnthonyBrunelli** [comment]
Alors alors, on est un peu perdu sur le sujet. Actuellement, on a A propos et pas Qui sommes nous et un menu Burger (miam) sur mobile... à revoir @lucaa

**Comment by lucaa** [comment]
Oui, c'est une ancienne tâche rendue obsolete par l'implémentation du burger pour #887 (commit  05c884d ).

Je ferme maintenant, avec label "cannot reproduce" pour marquer le fait que le problème n'est plus d'actualité.
