### ISSUE TITLE
améliorer le tableau de bord des votes

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#711]
- le rendre accessible aux administrateurs ministeriels, dans la section "Administrez les données" en bas de la page d'accueil
- supprimer l'information dématérialisée oui/non - fait
- supprimer l'information demandes de dématérialisation - fait
- ajouter démarche nationale / locale
- ajouter top 250 oui / non - fait

**Comment by lucaa** [comment]
à part 
> ajouter démarche nationale / locale 

qui est mineur comme amélioration, cette tache est la même que #801. Je ferme comme doublon, #801 sera planifiée.
