### ISSUE TITLE
Ajout du champ pour stocker l'indicateur de performance dites le nous une fois

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#715]
Dans les données du tableau de bord T3, il y a une colonne avec l'indicateur Dites-le nous une fois.
Il faut ajouter un champ pour pouvoir stocker cet indicateur dans les demarches, pour pouvoir l'importer ( voir #709) et l'afficher .

Pour l'instant cet indicateur est une valeur numérique, avec des décimales (0, 0.5 ou 1), mais ça pourrait changer dans le futur.

**Comment by slauriere** [comment]
Un champ dédié a été ajouté à la classe démarche avec un affichage dynamique, disponible depuis le tableau de bord avec un affichage sous forme d'étoiles, à améliorer.

**Comment by georges-bayard** [comment]
on s'oriente vers un affichage 3 couleurs rouge orange vert avec un score apparent de -14 à + 14. l'autre option est un rouge orange vert représentant 0, 0,5 et 1 (non apparents sur le tableau)

**Comment by lucaa** [comment]
@georges-bayard cette modification sera faite avant le moment de l'import prévu pour #709 ou avant?
Notez, aussi, qu'on ne peut pas montrer une informaton uniquement par des couleurs dans l'observatoire, ce n'est pas une approche compatible RGAA (les gens qui ne distinguent pas les couleurs ne peuvent pas avoir l'information).

**Comment by georges-bayard** [comment]
La modification doit être faite avant le moment de l'import mon objectif est que tout cela soit stabilisé vendredi soir dans l'envoi définitif du tableau
