### ISSUE TITLE
Prévoir une migration du tableau de bord courant vers un tableau de bord nommé et daté au 30 juin

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#717]
Suite à #640, le tableau de bord courant doit devenir un tableau de bord nommé et daté à la date de 30 juin.
Vu que l'affichage des tableaux de bord historiques est prévu dans le même écran que le tableau de bord courant, 
![image](https://user-images.githubusercontent.com/657716/66561450-c9b1cc00-eb59-11e9-8540-4dd75c1daea6.png)
quelques questions restent ouvertes, liées à comment ce tableau de bord du 30 juin doit s'afficher par rapport aux évolutions des données affichés?

* les méta-données des démarches seront celles du 30 juin ou celles d'aujourd'hui (noms, valeurs, etc)? Je pense que le plus indiqué est 30 juin.
* les nouvelles colonnes ajoutées dans le tableau doivent ou pas être affichés pour les données du 30 juin? Si oui, avec quelles valeurs?

**Comment by lucaa** [comment]
@georges-bayard apellez moi si vous voulez discuter de cette stratégie en direct.

**Comment by lucaa** [comment]
conclusion: 
le tableau de bord du 30 juin s'apellera T2 (2eme trimestre) et ne devra pas afficher les nouvelles colonnes.

**Comment by slauriere** [comment]
* Des instructions de migration ont été ajoutées au [document d'installation](https://github.com/DISIC/wikidemarches/wiki/Installation-instructions-v-4.x) dans la section "Upgrade from a previous version". 
* La migration du fichier JSON consiste pour cette version à simplement ajouter une entrée JSON en fin de fichier tel qu'indiqué (peut-être plus simple ainsi que de stocker le fichier quelque part @lucaa ou penses-tu qu'un stockage intermédiaire soit préférable ?)
* NB : le fichier migré fonctionne sur le serveur de staging tel quel avec l'ancien code.
