### ISSUE TITLE
Déplacer le tri des colonnes de l'observatoire dans un menu à côté des filtres, plutôt que dans la tête de tableau

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#719]
Cette tâche est un reste de #714 . 

Il y a, par contre, 2 questions liées à cette tâche: 
* quelles colonnes doivent être triables?
* comment gérer les 2 directions de tri (ascendent / descendent)? Proposition: dans la liste des tris possible on affiche pour chaque colonne 2 entrées, une pour le tri ascendent et une pour le tri descendent.

**Comment by georges-bayard** [comment]
question 1 : le fonctionnement actuel de tri sur les colonnes me paraît très satisfaisant sous une réserve qui a du guider la réalisation de la maquette par @marineb : le tri sur colonnes ne permet pas de trier sur les informations du tableau présentées en deuxième niveau (volumétries, publics cibles, ..). Je propose donc de réserver la fonction de tri en-tête du tablau aux seuls cas ou la fonction filtre sur les colonnes du tableau n'est pas possible, c'est à dire pour la volumétrie totale, le pourcentage de recours à la voie dématérialisée, le nombre d'avis usagers recueillis et le public cible.
Attention pour le tri sur la valeur public : l'information peut être multi évaluée.
Tout cela a quand même un inconvénient majeur : on trie sur une information qui ne sera pas restituée en premier niveau à l'écran
Question 2 : la solution ne me paraît pas très propre. quelles autre solutions sont possibles ?

**Comment by marineb** [comment]
La dessus, en attendant une liste deroulante, je suggere d'enlever les fleches, mais de laisser la fonctionalite. Simplement.

**Comment by lucaa** [comment]
@marineb
la fonctionnalité sera difficilement découvrable si on enlève les fléches complétement...

Même quand un tri est active on enlève la fléche qui marque le tri par une colonne et la direction du tri?

**Comment by marineb** [comment]
@lucaa : oui je sais mais je pense important de prioriser la lisibilité du tableau vs la fonctionnalité de tri.

**Comment by lucaa** [comment]
J'ai enlevé les fléches, je laisse la tache ouverte pour bouger le tri dans un menu séparé (dans quel cas il reste des questions) mais je la de-priorise.

**Comment by lucaa** [comment]
Planifié pour la M13, à spécifier:
* comment on affiche les possibilités de tri
* définir l'ordre des valeurs des colonnes non-numériques

**Comment by lucaa** [comment]
J'ai fini le deplacement commencé par @slauriere ainsi:

![image](https://user-images.githubusercontent.com/657716/72165622-7c4f3000-33d0-11ea-9bc8-8e679b73013f.png)

J'ai ajouté 2 boutons pour chaque tête de colonne, avec les 2 ordres possibles. Il faut cliquer sur chaque bouton pour trier par l'ordre en question.
Lors du tri, le bouton "trier" se colore pour marquer qu'un tri est actif, et dans sa liste la colonne trié est marquée avec une bordure bleue à gauche et l'ordre de tri est colorée.
J'ai désactivé le tri par les têtes de tableau car ce tri ne mettait pas à jour ces marqueurs de tri actif et, si utilisé aprés avoir fait un tri par le bouton, pouvait donc créer des confusions (le tri marqué n'était pas le même que le tri actif).

**Comment by lucaa** [comment]
> définir l'ordre des valeurs des colonnes non-numériques 

j'ai créé #805  pour cela, cette tâche est fermée car le tri est désormais déplacé.

**Comment by lucaa** [comment]
@marineb @georges-bayard j'aurais besoin d'une validation de ce choix d'interface, svp.

**Comment by AnthonyBrunelli** [comment]
Yep, on est dessus. Je vois ça rapidement, et en termes d'accessibilité pour un aveugle aussi (on fait des tests cette semaine).

**Comment by georges-bayard** [comment]
je trouve le résultat final pas très convainquant. Peut on maintenir le mécanisme de filtre par cliquage sur l'objet pour les rétifs au changement de mon espèce ?

**Comment by lucaa** [comment]
@georges-bayard :)
c'était mon plan initial (de garder l'existant). Par contre, comme le nouveau menu presènte également un "feedback" à l'utilisateur par rapport au tri actif (ce qui n'est pas le cas pour la tête de tableau), garder la possibilité de trier par click sur la tête de tableau implique un peu de travail pour rendre visible le choix courant, quelque soit le tri utilisé (tête de tableau ou menu). 
Je regarde si c'est trop compliqué ou pas.

**Comment by AnthonyBrunelli** [comment]
à tester et à décider de notre côté (avec Marine)

**Comment by AnthonyBrunelli** [comment]
Propositions (à valider @marineb @georges-bayard @Hatice2020, contributions techniques bienvenues le cas échéant @lucaa )

![image](https://user-images.githubusercontent.com/35567048/73254752-4a570f80-41bf-11ea-80e7-29d9546ec13c.png)

Avantages: tout est visible directement, un clic en moins, plus intuitif, plus aisé avec lecteur d'écran.

**Comment by AnthonyBrunelli** [comment]
(pour mémoire, actuellement il faut cliquer sur le bouton "Filtres" pour faire apparaître les trois premiers champs).

**Comment by lucaa** [comment]
Il faut laisser que quelques critères de tri:
* Volumétrie: croissant décroissant
* Réalisable en ligne alphabetique: croissant + décroissant
* Usagers satisfaits
* Nombre d'avis

**Comment by lucaa** [comment]
> Réalisable en ligne alphabetique

Aujourd'hui, parce-que la valeur affichée pour l'option "partiel"  est "Deploiement partiel", l'ordre sera la suivante: Oui, Non, Deploiement Partiel, Beta. 
@georges-bayard est-ce que ça vous paraît correct?

**Comment by lucaa** [comment]
Les options discutées ont été implémentées:
![image](https://user-images.githubusercontent.com/657716/73872330-cb617700-484f-11ea-9fae-0b6befd7c59e.png)

![image](https://user-images.githubusercontent.com/657716/73872352-d6b4a280-484f-11ea-89b5-c66a09c9a4f8.png)

![image](https://user-images.githubusercontent.com/657716/73872368-df0cdd80-484f-11ea-93cc-2074a9c6ab17.png)

**Comment by lucaa** [comment]
Il n'est toujours pas possible de revenir au tri initial du tableau, la tâche #859 a été créée pour cela.
Ainsi, je peut marquée cette tâche comme terminée.
