### ISSUE TITLE
Correctifs du selecteur de source du tableau de bord

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#721]
Cette tache est un reste de #714 .

Quand la source courente est le tableau de bord en direct, la source courente n'est pas affichée en bleu, il est donc difficile de savoir quelles données on regarde.

![image](https://user-images.githubusercontent.com/657716/66758614-e70ad100-ee9e-11e9-920a-7d937d126368.png)

En +, l'historique des données est affiché sous forme de liste à derouler, pas tous affichés sur l'écran avec la version courente séléctionnée.

@marineb est-ce qu'on veut afficher tout l'historique sous forme de switcher vue qu'il sera probablement long ou on laisse l'historique sous forme de liste déroulante pour prévoir sa scalabilité?

**Comment by georges-bayard** [comment]
Sous réserve de l'avis de @marineb je pense que l'affichage sous forme de liste est meilleur : scalable, sobre et aucune confusion sur la version sur laquelle on navigue (inconvénient qui disparaîtra certes quand on affichera au moins 3 versions temporelles du tableau

**Comment by lucaa** [comment]
Les corrections sont faites, et la fleche a été ecartée du text.
