### ISSUE TITLE
charger dans l'observatoire les valeurs de l'information "catégories de publics concernés"

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#723]
L'idée est d'améliorer le fonctionnement du filtre du tableau de bord qui point sur l'information "public". Valeurs à charger dans l'excel joint

**Comment by georges-bayard** [comment]
[sécurisation des démarches par public dns le top 250.xlsx](https://github.com/DISIC/wikidemarches/files/3729313/securisation.des.demarches.par.public.dns.le.top.250.xlsx)

**Comment by slauriere** [comment]
Une page d'administration a été ajoutée pour effectuer cet import à partir d'un fichier CSV comportant les deux colonnes "URL" et "Catégories de publics concernés" du [fichier XSLX mentionné en référence](https://github.com/DISIC/wikidemarches/files/3729313/securisation.des.demarches.par.public.dns.le.top.250.xlsx). La [description de cette procédure](https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M9/Int%C3%A9gration%20des%20d%C3%A9marches%20du%20top%20250) a été ajoutée aux instructions d'intégration des données des démarches phares.

**Comment by slauriere** [comment]
La donnée a été ajoutée à la ligne des détails du tableau de bord. Il reste à implémenter un filtre dédié.

**Comment by georges-bayard** [comment]
problème avec le chargement : 
les valeurs des démarches  "Demande de subventions" 1874 (Associations Collectivités locales Particuliers Professionnels) n'ont pas été importées en staging. @slauriere : c'était à moi de le faire ?

**Comment by georges-bayard** [comment]
je réalise qu'il y a quelque chose de pas logique dans l'affichage de la valeur "a venir" et "non mesuré" du tableau de bord pour l'accessibilité et le DLNUF : dans tous les autres critères demandés quand la démarche est "non dématérialisée" on "neutralise" la valeur avec un "-". Il faudrait faire la même chose pour cette colonne en toute logique.
@marineb : qu'en penses tu ? je pense qu'il est un peu tard pour faire la modif sur la version à paraitre. J'ouvre une nouvelle issue pour la prochaine release ?

**Comment by lucaa** [comment]
@georges-bayard le dernier commentaire est plutot pour #740 que pour cette tache, non?
Vous pouvez le bouger s'il vous plaît, pour pouvoir suivre les avancements plus précisement et surtout pour pouvoir re-fermer cette tache dès que votre première question (pour @slauriere ) est répondue?

**Comment by slauriere** [comment]
GBA, concernant les catégories de publics, c'était bien à nous de faire la mise à jour mais suite à une erreur de ma part celle-ci n'avait été que partielle. Le problème est corrigé sur le serveur de staging.

**Comment by lucaa** [comment]
Le commentaire concernant la colonne dlnuf a été bougé vers #740, je ferme cette tache maintenant.

**Comment by georges-bayard** [comment]
Encore un souci : la démarche "Demande d'état civil par les administrations au profit des usagers" qui est dans l'Excel n'est pas créée en staging mais bien présente sur la prod (2162). Vous me confirmez que pour les données vous partez de la prod ?

**Comment by lucaa** [comment]
> Vous me confirmez que pour les données vous partez de la prod ?

Effectivement, le script de mise à jour des catégories de publics des démarches ne crée pas une démarche si elle n'existe pas, il fait que des mises à jour des démarches éxistantes.
Je confirme, lors de l'imprt de la data en production, comme la démarche 2162 sera presente, elle sera correctement mise à jour avec les catégories de publics de l'excel.
