### ISSUE TITLE
Retour avant lancement du 18 octobre 2019

### ISSUE THREAD

**Issue by marineb** [DISIC/wikidemarches#726]
### Fonctionalites
- [x] Ajout lien dans la version expanded de chaque démarche
- [x] Il manque la colonne vide accessibilité
- [x] Il manque le dropdown entreprises / particuliers
- [x] Texte pour le PDF "Version imprimable (PDF...)"

### Design
- [x] Seuls les 2 premiers icônes doivent être colorées et le texte en gras
- [x] Mettre a jour les icons par rapport au design
- [x] nom de la demarche ~1.3em line-height
- [x] ministere de la demarche, rajouter ~ 5px au dessus
- [x] Ajouter les nouvelles couleurs pour le vert rouge et orange
- [x] La ligne de séparation entre les icons et les démarches du tableau doit etre de 1px
- [x] Enlever les flèches qui permettent de "sort" car elles sont pixelisées et seront remplacees par le bouton de tri
- [x] Remonter le tableau plus pres des filtres
- [x] Ouverture des filtres est un peu bizarre, notamment le déroule de gris. Faire qqch de plus simple 
- [x] La haureur du dropdown ministere est tout petit par rapport au champ mot cle
- [x] Enlever le gradient transparent qui apparait sous les icons / tetes de colonne
- [x] Ajouter plus d'espace sous les tetes de colonne (cf design)
- [x] Enlever les "/" dans le partager (c'est de ma faute j'avais fait ca rapidement)

**Comment by georges-bayard** [comment]
• Tableau de bord : je n'aime pas trop la colorisation en rouge orange vert de la notation pourtant conforme à la maquette ; c'est assez stigmatisant surtout au moment où on fait monter les ministères dans le dispositif. @marineb qu'en penses-tu ? par ailleurs si on maintient la couleur je suis d’avis de remplacer le gris par du orange. Le gris fait référence dans le tableau à une donnée non complète
• Tableau de bord : le filtre est trop restrictif il exige qu’on respecte la casse
• Le temps d’affichage du tableau de bord temps réel est trop long. Je n’ai pas réussi à tester cette fonction avec un profil admin ministériel (fonctionne mieux avec un profil admin ministériel
• Liens vers facebook et Linkedin n’ont pas l’air de fonctionner correctement : le renvoi sur la page perconnelle facebook ou linkedin du lecteur du tableau ne fonctionne pas . Est-ce lié à l’environnement ?
• Le lien vers l’adresse url de la démarche n’est disponible qu’en mode connecté admin. Il faut la rendre accessible quels que soient les publics
• Fonctionnalité d’ajout d’un tableau de bord : je comprends que les informations vont chercher dans le référentiel des démarches les données valides à la date du tableau. Est-ce bien cela ? Comment cela fonctionne il aujourd’hui pour l’intégration des données Pingdom ? quelle est la procédure si on nous demande de modifier une information après la date de parution du tableau ?

**Comment by lucaa** [comment]
* Ajout lien dans la version expanded de chaque démarche
* Le lien vers l’adresse url de la démarche n’est disponible qu’en mode connecté admin. Il faut la rendre accessible quels que soient les publics

Le lien de l'adresse URL de la démarche est affiche ainsi: pour tous les _nouveaux_ tableaux de bord, pour tous les utilisateurs, uniquement pour les demarches qui en ont un URL rempli dans les métadonnées de la démarche.

La notion de "nouveau tableau de bord" est liée au fait que le tableau de bord de 30 juin avec la capture des données au 30 juin à déjà été généré et stocké lors de la publication de ce tableau de bord à la livraison M10 (ce sont les données de l'observatoire courant, voir aussi #717 ).
Ainsi, le tableau de bord du 30 juin est un tableau de bord "ancien" et manque cette information (cf. commentaire https://github.com/DISIC/wikidemarches/issues/716#issuecomment-542708250 ), donc l'URL ne sera pas affiché pour le tableau de bord du 30 juin, car nous n'avons pas stocké cette information dans la capture du 30 juin.

Ainsi, pour le tableau de bord du 30 juin cette métadonnée n'est pas affichée, comme toute autre métadonnée qui n'a pas été collectée lors de la création du tableau de bord 30 juin. Le tableau de bord 30 juin est le tableau de bord courant

**Comment by lucaa** [comment]
> Enlever les flèches qui permettent de "sort" car elles sont pixelisées et seront remplacees par le bouton de tri

Sera traité dans #719.

**Comment by lucaa** [comment]
>  La haureur du dropdown ministere est tout petit par rapport au champ mot cle

Sera traité dans #722.

**Comment by lucaa** [comment]
> Enlever les "/" dans le partager (c'est de ma faute j'avais fait ca rapidement)

Sera traité dans #720 .

**Comment by lucaa** [comment]
> Tableau de bord : le filtre est trop restrictif il exige qu’on respecte la casse 

La casse n'impacte pas la recherche, mais les accents oui (j'imagine c'est à ça que vous faites référence) . J'ai crée un bug pour #730 .

**Comment by lucaa** [comment]
> Liens vers facebook et Linkedin n’ont pas l’air de fonctionner correctement : le renvoi sur la page perconnelle facebook ou linkedin du lecteur du tableau ne fonctionne pas . Est-ce lié à l’environnement ?

Vous avez quoi à la place? des ecrans de connexion de ces plateformes demandant de se connecter sur LinkedIn / Facebook? Si oui, c'est probablement normal et lié au fonctionnement des URLs de partage de ces plateformes (qui demandent de se connecter avant d'afficher le formulaire de partage pre-rempli). Vous avez essayé de vous connecter? Il se passe quoi?

**Comment by georges-bayard** [comment]
> 
> 
> > Fonctionnalité d’ajout d’un tableau de bord : je comprends que les informations vont chercher dans le référentiel des démarches les données valides à la date du tableau. Est-ce bien cela ? Comment cela fonctionne il aujourd’hui pour l’intégration des données Pingdom ? quelle est la procédure si on nous demande de modifier une information après la date de parution du tableau ?
> 
> @georges-bayard La donnée affichée dans un tableau de bord daté est une donnée capturée et stocké lors du click sur le bouton "Générer", qui est determinée ainsi:
> 
>     * pour les données liées aux avis (nb d'avis & indice de satisfaction) , les valeurs sont calculées _à la date du tableau de bord_, renseignée lors de la création / configuration du tableau de bord daté
> Ca veut dire que si on veut récupérer les votes le plus tard possible on doit créer le tableau de bord T3 2019 à la date du 15 ou 20 octobre ? ca ne me paraît pas très propre. y a t'il une autre solution ? 
> 
> ![image](https://user-images.githubusercontent.com/657716/66928806-4220fd00-f032-11e9-8f42-15735eb7720f.png)
> 
>     * pour les meta-données des démarches (toutes les autres informations du tableau de bord), les valeurs stockés lors du click sur le bouton "Générer" sont les valeurs stockés dans le referentiel des demarches _au moment ou le bouton est clické_.
> on peut donc regénérer plusieurs fois je suppose en mode brouillon ?
> 
> Aujourd'hui, les données pingdom et DLNUF sont traitées comme des méta-données des démarches, même si ce sont des données pour lesquelles il peut y avoir une source externe pour la donnée.
> C'est à dire, il n'y a pas de récuperation automatique de la donnée pingdom pour remplir les méta-données des démarches (j'ai crée une tache pour cela, #731 ), la mise à jour de cette donnée est basé sur un import de la donnée recupéré sous forme de tableau par le script que j'ai fait pour la tache #652 .
> Ainsi, la donnée pingdom du tableau de bord est celle qui était stocké dans la démarche au moment ou le bouton "Générer" a été clické.
> 
> Pour modifier une information après la date de la parution du tableau, la procedure est de faire la modification dans le référentiel et ensuite re-generer la capture de ce tableau de bord qui utilisera la nouvelle valeur de la méta-donnée. Attention, toutes les modifications faites entre temps seront capturés dans cette capture (si une autre démarche a été modifié dans le référentiel, cette autre modification sera aussi comprise dans la nouvelle capture).
Cela me paraît bien rigide donc. Si mar exemple Xavier nous demande de modifier la note de l'INSEE sur la démarche de recensement OMER une semaine après la parution il faudra pouvoir le faire même en mode pas propre

**Comment by lucaa** [comment]
> Ca veut dire que si on veut récupérer les votes le plus tard possible on doit créer le tableau de bord T3 2019 à la date du 15 ou 20 octobre ? ca ne me paraît pas très propre. y a t'il une autre solution ?

La date du tableau de bord daté n'est affiché nulle part pour le public, uniquement le nom est affiché.

>  on peut donc regénérer plusieurs fois je suppose en mode brouillon ?

oui.

> Cela me paraît bien rigide donc. Si mar exemple Xavier nous demande de modifier la note de l'INSEE sur la démarche de recensement OMER une semaine après la parution il faudra pouvoir le faire même en mode pas propre

on peut intervenir sur le json, si absolument necessaire.

**Comment by marineb** [comment]
Bonjour ! Quelles sont les questions qui nécessitent une réponse ? (Suis sur mobile et pas facile de voir ce qui est traite ou pas).

**Comment by lucaa** [comment]
@marineb ce commentaire:

https://github.com/DISIC/wikidemarches/issues/726#issuecomment-542718248

**Comment by lucaa** [comment]
> Mettre a jour les icons par rapport au design

Après discussions en direct:
il s'agit des icônes des filtres, et les autres éléments de l'écran observatoire, à chercher sur feathericons.

**Comment by lucaa** [comment]
> Mettre a jour les icons par rapport au design

J'ai crée la tache #747 pour ce correctif.

Je ferme maintenant cette tache, tout le feedback a été distribué dans des taches dediées.
