### ISSUE TITLE
Ajouter la colonne "accessibilité" pour les observatoires v 1.1, vide

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#728]
cf. maquette du #714, la colonne "Accessibilité" doit être presente sur le tableau de bord, vide.
Comme pour l'autre nouvelle colonne, DLNUF, elle ne devrait pas être affiché pour les données de l'observatoire version 1.0 (30 juin) car pas présente à ce moment-là.

**Comment by slauriere** [comment]
Il reste à mettre à jour l'icône.

**Comment by slauriere** [comment]
L'icône a été mise à jour.
