### ISSUE TITLE
Couleurs des indicateurs affichés sur l'observatoire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#729]
Il s'agit du nouvel observatoire fait pour #714.
Cette tache centralise et clarifie la question des couleurs, dont la discussion à commencé dans #726.

Remarques:

* "Seuls les 2 premiers icônes doivent être colorées et le texte en gras" (@marineb )
* "Ajouter les nouvelles couleurs pour le vert rouge et orange" (@marineb )
* "je n'aime pas trop la colorisation en rouge orange vert de la notation pourtant conforme à la maquette ; c'est assez stigmatisant surtout au moment où on fait monter les ministères dans le dispositif. @marineb qu'en penses-tu ? par ailleurs si on maintient la couleur je suis d’avis de remplacer le gris par du orange. Le gris fait référence dans le tableau à une donnée non complète" (@georges-bayard )

**Comment by lucaa** [comment]
Sur la maquette, la donnée est presentée avec 2 couleurs uniquement: le vert turqouise et le gris. 
La seule ligne colorée est la ligne de synthèse, qui n'a pas été implementée.
![image](https://user-images.githubusercontent.com/657716/66923786-c1f69980-f029-11e9-8ec5-722aced2dc8c.png)
La coloration de la tête de tableau (icones) semble synchronisée avec le vert / gris des valeurs.

Ainsi, lors de l'implémentation de #714, je n'ai pas changé les couleurs des indicateurs (valeurs) par rapport à l'implémentation précédente (j'ai laissé du vert, orange, rouge, bleu, gris) car ces couleurs portaient du sens (ce qui n'est pas complétement RGAA mais c'est n'est pas le seul moyen de communiquer le sens).

Ainsi, par rapport aux remarques, quelques questions se posent:

1/ Les indicateurs (valeurs) de chaque ligne doivent être colorés en fonction de leur valeur (rouge, orange, vert, bleu, gris) ou uniquement bicolores (vert turqouise + gris) comme sur la maquette?
- si on garde les plusieurs couleurs, les "nouvelles couleurs pour le vert rouge orange" sont celles de la ligne de synthèse?
![image](https://user-images.githubusercontent.com/657716/66923937-03874480-f02a-11e9-9ffb-56cda47cf1db.png)
Si oui, quel gris, quel bleu?

2/ les icones de la tête de tableau doivent être bicolores même si les lignes du tableau sont multicolores, pour mettre en avant les 2 premières colonnes?

3/ "par ailleurs si on maintient la couleur je suis d’avis de remplacer le gris par du orange. ". @georges-bayard , il s'agit des couleurs des lignes du tableau (des valeurs) ou des couleurs de la tête de tableau?

**Comment by marineb** [comment]
1. Oui pardon, mon commentaire était uniquement sur l'ajustement des couleurs (ancien rouge --> nouveau rouge, ancien vert --> nouveau vert). (oublions le gris pour l'instant je suisd'accord avec ta remarque)

2. Il me semble que ca rend plus facile de dinstinguer les 2 criteres les plus important. Mais tu as un bon point. Ca risque de creer un desequilibre si on ajuste pas les couleurs du tableau lui meme (gris). Donc peut-etre rester avec ces couleurs pour les icones pour l'instant. 

3. C'est un commentaire de georges ? Pourquoi pas si pas trop stigmatisant. Ce sera pour tout ce qui est "a venir", ce genre de messages, c'est bien ca ? 👍

**Comment by lucaa** [comment]
Les couleurs ont été mis à jour.
@marineb : les couleurs utilisées pour le tableau étaient les couleurs standard des 3 types de boutons (danger, warning, success) de la plateforme, couleurs qui sont réutilisées à quelques autres endroits, notamment pour les couleurs des smileys dans le formulaire de vote et lors de l'affichage des graphiques des votes pour une démarche. Pour l'instant j'ai changé les couleurs uniquement sur l'observatoire, je devrais changer les couleurs partout?

**Comment by marineb** [comment]
Merci ! Oui ce serait bien de le faire partout mais pas une urgence.

**Comment by lucaa** [comment]
Si on doit le fait partout, il faut s'assurer qu'on a vérifié le contraste de ces couleurs, du pdv RGAA. À l'oeil l'orange et le rouge me paraissent assez proches, mais c'est vraiment une opinion à base d'impression visuelle...
Por les couleurs existents je pense qu'on avait fait un travail dans ce sens.
Si la vérification n'a pas déjà été faite (@marineb ?), je peux me renseigner dans le standard RGAA (si mes souvenirs ne me trompent pas, il y avait une méthode dedans pour vérifier les couleurs...)
