### ISSUE TITLE
Le filtre de l'observatoire (recherche par mot-clé) est sensible aux accents

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#730]
Les recherches "régime" et "regime" donnent des résultats differents, cf captures:

![image](https://user-images.githubusercontent.com/657716/66927330-e786a180-f02f-11e9-90ed-2e459a527b60.png)

![image](https://user-images.githubusercontent.com/657716/66927378-fa00db00-f02f-11e9-8bcf-de41008cfb86.png)

Le mot de recherche doit être identique du point de vue des accents au mot présent dans la ligne de l'observatoire.

L'idéal serait de pouvoir chercher un mot avec ou sans les accents et de retrouver les demarches qui le contiennent, avec ou sans accent.

**Comment by georges-bayard** [comment]
quelles conclusions en tires tu ?

**Comment by lucaa** [comment]
> quelles conclusions en tires tu ?

J'ai complété la description du bug avec le comportement désiré.

**Comment by slauriere** [comment]
Le problème a été corrigé. L'implémentation consiste à maintenir un index des entrées avec et sans accent, cela pourrait être amélioré mais c'est opérationnel.
