### ISSUE TITLE
L'observatoire en direct n'est pas accessible aux administrateurs ministériels

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#732]
Le tableau affiche "chargement..."   a l'infini.

Une inspection du traffic reseau dans le navigateur montre que la requête de récupération de données (/observatoire/en-direct/?action=json&live=1 ... ) revient, avec un résultat qui n'est pas un json des démarches.

Peut-être une réstriction de droits?

**Comment by slauriere** [comment]
Le problème a été réglé : il était dû au fait que, suite à l'ajout de l'onglet des détails du tableau de bord, le bloc de génération dynamique du fichier json n'était plus exécuté que pour les administrateurs (car le bloc était mal placé dès l'origine).
