### ISSUE TITLE
Nom des colonnes du tableau

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#733]
Le nom des colonnes du tableau doit encore être revu su la version en ligne
1 / la colonne score d'effort DLNUF : l'intitulé "complexité des informations re demandées" est encore trop long :
![image](https://user-images.githubusercontent.com/17125654/66938562-ae572d00-f041-11e9-8392-e1d5b9486658.png)
Propositions : "effort de ressaisie"
2 / "support de qualité" remplacé par "support accessible"
3 / "disponibilité du service" remplacé par "temps de réponse"

Impacter cette modification sur la page d'accueil, la page d'explication et l'Excel;

@marineb : valides tu à ton niveau ou faut il poser la question à Xavier ?

**Comment by marineb** [comment]
Top ! :)

**Comment by georges-bayard** [comment]
@lucaa : ce que tu dis est un risque peu être un peu plus élevé que si on parle de disponibilité. Il reste que la couleur est quand même ce que vont regarder les ministères en premier. Je propose donc de maintenir cette proposition

**Comment by lucaa** [comment]
ok... c'est fait.

**Comment by lucaa** [comment]
Nouveaux noms des colonnes:
* réalisable en ligne
* indice de satisfaction
* compatible mobile 
* disponibilité du service
* inclusion des handicaps
* ressaisies demandées

**Comment by lucaa** [comment]
Nouveaux noms:
* Disponibilité et rapidité
* Prise en compte handicaps

**Comment by lucaa** [comment]
C'est fait!  à tester sur le prochain staging.

**Comment by georges-bayard** [comment]
attention : remplacer "indice de satisfaction" par "usagers satisfaits"
