### ISSUE TITLE
question : faut il maintenir les couleurs rouge orange vert pour l'indice de satisfaction usagers

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#734]
@marineb  : je crée cette nouvelle issue car nos discussions via github n'ont pas été claires sur le point de savoir si on maintenait le dispositif tricolore rouge orange vert pour l'indice de satisfaction. Sur la version précédente l'information était présentéesans couleurs. Je propose de maintenir ce mode de présentation pour les raisons suivantes : d'une part effet de rupture et de mise en valeur de l'information qui ressort mieux par rapport aux autres informations du tableau qui sont toutes colorées ; d'autre par on stigmatise inutilement les ministères. Afficher un score par démarche me paraît bien suffisant comme ca.
Qu'en penses tu ?

**Comment by marineb** [comment]
Ok !

**Comment by lucaa** [comment]
Note: les couleurs pour l'affichage des indices de satisfaction ont été mis en place lors des améliorations du tableua de bord (voir https://github.com/DISIC/wikidemarches/issues/640#issuecomment-540060144 ).

On a voulou implémenter les indices de satisfaction sous forme de carré de couleur encadre (car c'est comme ça qu'ils sont sur la maquette) et on a mis des couleurs d'évaluation. On aurait peut-être pas du. La seule couleur "neutre" qu'on a c'est le bleu.

Aussi, à noter que la valeur de cette colonne est cliquable (la seule qui est cliquable de toutes les colonnes) et sous cette forme (carré coloré) il n'est pas evident qu'on peut cliquer dessus pour avoir plus de détails, d'autant plus que les autres colonnes sont affichées pareil sans être cliquable. Il faut peut-être une proposition aussi pour mettre en avant cet aspect.

**Comment by lucaa** [comment]
Décision: revenir à l'affichage de la version précédente, sans "badge", sans couleur.

**Comment by lucaa** [comment]
J'ai enlevé les couleurs, ainsi le score s'affiche en bleu maintenant, car c'est un lien vers les stats.
