### ISSUE TITLE
Mettre une limite d'une année glissante pour les avis inclus dans un tableau de bord

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#736]
(voir la tache #718 )
L'idée est d'inclure dans les tableaux de bord générés uniquement les avis de la dernière année qui précède la date du tableau de bord.
Attention: il faut également mettre à jour l'écran d'affichage des stats d'une démarche pour afficher uniquement les avis de l'année, quand elle affiche pas les données en direct.

**Comment by slauriere** [comment]
Une première implémentation de la date glissante a été effectuée. Il reste à voir ce qui doit être utilisé comme date de début dans la liste des avis d'une démarche (a priori la date glissante également) et ce qui doit être affiché comme date de début dans le cas « temps réel » (qui pour memo n'est pas réellement « temps réel » puisque le calcul utilise le cache d'avis des dernières 24h).

**Comment by georges-bayard** [comment]
pour moi la date de début est pour moi la date du premier avis enregristré (au plus tard juillet 2018 donc)

**Comment by georges-bayard** [comment]
démarche ICPE n°1644 : le vote n'apparaît plus alors qu'il devrait apparaître puisque la démarche a obtenu 144 votes entre novembre 2018 et aujourd'hui

**Comment by slauriere** [comment]
Pardon j'avais interprété de travers le principe d'année glissante, j'ai rectifié l'implémentation : le début de l'année glissante est présent la date du tableau bord diminuée d'un plus un jour, à minuit. Le correctif est visible sur le serveur de staging et la démarche 1644 apparaît bien de nouveau.

**Comment by georges-bayard** [comment]
Le principe de l'année glissante ne s'applique pas uniquement à l'affichage des notes trimestrielles mais également à l'affichage des notes en temps réel. Est ce bien comme ca que c'est implémenté ? à priori non. En temps réel je vois qu'on prend toujours les notes depuis le début. c'est embêtant en particulier quand on regarde le tdb en temps réel ou on a un résultat qui prend en compte les votes depuis le début et le tdb trimestriel qui prend en compte l'année glissante.

**Comment by lucaa** [comment]
@georges-bayard : vos remarques sont justes (les 2), mais il n'y a pas que le tableau de bord en temps réel qui n'utilise pas la limite d'une année glissante pour les avis pris en compte. 
J'ai crée une issue plus generique ici #748 , pour spécifier comment on veut que cette limite soit prise en compte à tous les endroits ou on utilise des avis sur la plateforme, pour definir une implémentation coherente de cette limite (la question avait déjà été posée par @slauriere sur cette issue).
Comme la logique de l'utilisation de cette limite de manière globale est plus complexe, j'avais restreint cette issue au tableau de bord, pour pouvoir avoir une réponse rapide pour #718 .

Est-ce que cette approche vous convient, on peut re-fermer cette issue et transferer la discussion plus globale sur #748 ?

**Comment by georges-bayard** [comment]
yess
