### ISSUE TITLE
 Retours sur version en staging du 17/10 

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#737]
- filtre : les triangles s'affichent mal sur mozzila : 
![image](https://user-images.githubusercontent.com/17125654/67042584-74148b00-f128-11e9-964e-8f598ffbaca2.png)
en revanche pas de souci sur ie
- @marineb : le critère accessibilité apparaît en avant dernier dans la liste des critère conformément à la maquette. Je trouve ca bizarre avec les données chargées. Qu'en penses tu ?

**Comment by lucaa** [comment]
> filtre : les triangles s'affichent mal sur mozzila :

J'ai re-ouvert #722 qui était l'issue dedié à cet affichage.

**Comment by lucaa** [comment]
> @marineb : le critère accessibilité apparaît en avant dernier dans la liste des critère conformément à la maquette. Je trouve ca bizarre avec les données chargées. Qu'en penses tu ?

Après discussions en direct:
il s'afissait de la colonne "Accessiblité" quand elle était vide, désormais il y a la valeur "a venir", en badge, qui s'affiche (cf. #739 ). On laisse tel quel, c'est mieux avec la valeur "a venir".

Je ferme cette tache, les retours sont traités.
