### ISSUE TITLE
Corrections d'affichage de l'observatoire

### ISSUE THREAD

**Issue by marineb** [DISIC/wikidemarches#743]
beau travail globalement. retours tres rapides : 

- [ ] pour moi les urls devraient être completes. souvent je vois service public.fr alors que l'url est plus longue. ca pousse a croire que l'url est généraliste est n'est pas correcte
- [ ] les colonnes ne semblent pas egales en width
- [ ] certains icons (mobile par ex) n'ont pas le bon "poids"
- [ ] manque de padding top/bottom sur les rectangles de donnees

**Comment by marineb** [comment]
@lucaa @georges-bayard je file en reu. mes petits retours rapides sur la derniere version. a tres vite. envoyez-moi un sms plutot si pas clair.

**Comment by lucaa** [comment]
> pour moi les urls devraient être completes. souvent je vois service public.fr alors que l'url est plus longue. ca pousse a croire que l'url est généraliste est n'est pas correcte

On s'occupe. Les URLs complètes sont vraiment peu esthétiques , mais effectivement plus précises. On peut re-aviser après.

**Comment by lucaa** [comment]
> les colonnes ne semblent pas egales en width

Effectivement, les colonnes n'ont pas la même largeur. Voici une image avec les bordures mises en place:

![image](https://user-images.githubusercontent.com/657716/67272781-7c205200-f4bd-11e9-8500-8b19bcfbed90.png)

les raisons:
* les valeurs des colonnes n'ont pas les mêmes tailles. Notamment dans la première colonne (réalisable en ligne) une des valeurs possibles est "Éxperimentation". 
![image](https://user-images.githubusercontent.com/657716/67273291-724b1e80-f4be-11e9-880d-ad4a3a525d94.png)
* pour la colonne "Prise en compte handicaps" j'ai du agrandir la taille de la colonne pour que son titre tient sur 2 lignes (si je laisse la taille par défaut du tableau la tête du tableau s'affiche sur 3 lignes).
* comme il y a beaucoup de colonnes et peu d'espace, j'ai préferé laisser le tableau choisir la taille des colonnes en fonction de leur contenu et ajuster uniquement là ou c'est nécessaire. J'ai peur que si je mets toutes les colonnes à taille égale et égale à la colonne la plus large, il restera peu d'espace pour la colonne titre, surtout sur les petits écrans (<1440px) ou le tableau passe en 100% de l'écran.

Voici le résultat avec des tailles de colonnes égales (à la colonne la plus large), sur un écran de plus de 1440px (donc avec le tableau à la largeur maximale):

![image](https://user-images.githubusercontent.com/657716/67274585-07e7ad80-f4c1-11e9-8c4c-c44708a95823.png)

**Comment by lucaa** [comment]
Après discussions:
> les colonnes ne semblent pas egales en width

on va rendre les colonnes égales, en remplaçant la valeur "Experimentation" avec "Bêta" pour rendre la colonne plus etroite. Il y a aussi "Deploiement partiel" qui est assez long comme valeur. à tester la nouvelle taille de colonne.

> certains icons (mobile par ex) n'ont pas le bon "poids"

Nouvelles icône smartphone à utiliser, de https://feathericons.com/?query=smartphone .

> manque de padding top/bottom sur les rectangles de donnees

Padding top & bottom des badges à mettre à ~8px.

**Comment by lucaa** [comment]
Extra modifictions à faire:
* les valeurs grises devraient utiliser le même gris que la maquette.
* remplacer l'icône de la dispo service avec une l'icone watch de feathericons

**Comment by lucaa** [comment]
Les modifications sont faites.

**Comment by georges-bayard** [comment]
c'est ok pour moi. Par contre la nouvelle version en staging ne reprend pas les modifs de wording sur la page d'accueil et la page d'explication. Elles seront reprises directement en prod ?

**Comment by georges-bayard** [comment]
rectificatif : j'ai retrouvé le wording (je n'étais pas sur la bonne version)
