### ISSUE TITLE
renommer dans le tableau de bord "expérimentation" en "beta"

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#744]

**Comment by lucaa** [comment]
J'ai fait la modification dans le cadre de la tache #743 , ainsi:
* le mot utilisé est modifié partout ou cette valeur est utilisée (dans l'affichage de la démarche, le formulaire d'édition de la démarche)
* la valeur dans l'ancien observatoire (juin 2019) n'a pas été changé et elle ne sera pas changée car stockée avec les données de l'observatoire.

@georges-bayard est-ce que cette approche convient?

**Comment by georges-bayard** [comment]
@lucaa oui ca me paraît bien

**Comment by lucaa** [comment]
ok, je ferme cette tache, le travail a déjà été fait.
