### ISSUE TITLE
Mettre à jour les icônes de l'écran de l'observatoire, cf maquette

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#747]
Reste de #714 :

Les icônes utilisés sur l'écran de l'observatoire, pour les filtres et les 2 liens de téléchargement devraient être ceux de la maquette, à chercher sur https://feathericons.com/ .

**Comment by AnthonyBrunelli** [comment]
@lucaa Désolé, mais nous n'arrivons pas à accéder aux maquettes, peux-tu nous rappeler de quoi il s'agit? (sans y passer trop de temps hein)

**Comment by lucaa** [comment]
J'ai fait une capture avec les 2 écrans côte à côte et des fléches:
![image](https://user-images.githubusercontent.com/657716/79688749-99f22800-8250-11ea-87ef-115bc5e4cead.png)

C'est ce que j'ai observé à une vue rapide, l'idée est de vérifier tous les icônes et s'assurer qu'elles sont les mêmes.

**Comment by lucaa** [comment]
@AnthonyBrunelli je bouge dans "à spécifier par Dinum" pour décider si c'est à faire ou pas.

**Comment by AnthonyBrunelli** [comment]
Alors on a vu avec Georges que c'est fait en prod, ça nous va bien, je ferme.

**Comment by lucaa** [comment]
> on a vu avec Georges que c'est fait en prod

il n'y a rien de spécifique qui a été fait pour cette issue en prod. Les icônes en prod restent différentes de celles de la maquette initiale. Dans ma capture du commentaire précédent, la maquette est à gauche et la production courante à droite, il reste quelques differences (pointées par les flèches).

Si l'implémentation courante convient et les icônes de la maquette ne sont pas nécessaires, rajoutez le label "won't fix" pour marquer que la cloture de la tâche est lié à l'abandon de l'amélioration et pas à sa réalisation.

**Comment by AnthonyBrunelli** [comment]
Bon, c'est pas clair, on en reparle jeudi...

**Comment by lucaa** [comment]
Vu avec @AnthonyBrunelli et @georges-bayard, décidé que la modification n'est plus nécessaire.
