### ISSUE TITLE
générer pour l'ANTS des boutons de vote avec des referer différenciés en fonction du caractère passant ou no de la démarche

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#751]

**Comment by georges-bayard** [comment]
échéance : janvier 2020

**Comment by lucaa** [comment]
@georges-bayard il nous faut la liste des démarches pour lesquelles on veut générer ces boutons.

**Comment by georges-bayard** [comment]
demande de point de situation adressée au ministère de l'intérieur le 07/01

**Comment by AnthonyBrunelli** [comment]
Vu avec Georges, pas de retour, on clôture.
