### ISSUE TITLE
traduire en multilingue l'observatoire

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#752]
Le besoin de traduire en langue étrangère le site a été remonté par le MJ (casier judiciaire) et par le MEAE. Le besoin exprimé porte sur le bouton "je donne mon avis" et sur le formulaire de satisfaction. Les langues demandées : anglais pour le MEAE, Anglais Espagnol Allemand pour le site du casier judiciaire. Sur le bouton nous avons déjà réalisé un bouton en Anglais. Sur la page de vote rien n'a été réalisé.
NB : aucun besoin n'est remonté concernant l'observatoire lui-même mais il serait peut être utile de se poser la question dans une perspective de communication à l'international des bonnes pratiques.

**Comment by lucaa** [comment]
@georges-bayard les taches #704 , #705 et #706 avaient été crée pour décrire ce même besoin.
Devrait-on fermer ces taches ou on les garde pour le découpage du besoin et des taches individuelles?

**Comment by georges-bayard** [comment]
non c'est parfait je n'avais pas vu qu'elles existaient déja. je cloture la 752 et ajoute mon commentaire dans les 3 issues pour ne pas perdre la descripion du contexte
