### ISSUE TITLE
Ajouter un écran de suivi des évolutions des démarches, de l'intégration du bouton et des avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#754]
Sur demande email de @georges-bayard , les colonnes présentes sont les suivantes:

Démarche, Ministère(s), Nb. avis, Taux de satisfaction (comme dans l'ancien Tableau de bord)
Top 250, Bouton (oui/non si le bouton est intégré ou pas), Démarches simplifiées

**Comment by georges-bayard** [comment]
je suis pour la solution 2 en prenant en compte les non vides et en ne prenant en compte les votes avec source au-delà de 10 pour ne pas prendre en compte les tests.
Sur l'affichage des porteurs je ne vois pas trop l'utilité à ce stade. j'ai juste un besoin les concernant  : vérifier qu'un porteur ne se déclare pas porteur d'une démarche d'un champ ministériel auquel il n'appartient pas. mais il y a un tableau de bord spécialisé pour ca.

**Comment by lucaa** [comment]
Finalement, comme l'information sur la presence du bouton est la plus compliqué à ajouter, on va laisser cela pour une tache separé (la #755).
Pour cette tache, j'ai ajouté uniquement la colonne top250. La colonne demarche simplifiée avait été également ajoutée mais enlevée apres feedback de @georges-bayard .
