### ISSUE TITLE
Mise en cohérence des libellés du statut de dématérialisation

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#759]
L'affichage des libellés du statut de dématérialisation n'est pas toujours cohérent : parfois le statut « expérimentation » est affiché comme « bêta » (dans la fiche de démarche complète).

**Comment by slauriere** [comment]
Pardon, c'est le texte explicatif qui semble incohérent avec la valeur « bêta » :  « Expérimentation si la solution est en cours d’expérimentation sur un échantillon restreint d’utilisateurs ou de cas métier  »

**Comment by georges-bayard** [comment]
t'as raison je vais corriger

**Comment by slauriere** [comment]
En fait tu ne peux pas faire la modification directement car ce sont des pages liées aux code. J'ai fait la modification, en mettant les valeurs en italique pour les distinguer du reste du texte, mais dis-moi si tu préféres autrement ? Le changement est visible en staging.

**Comment by georges-bayard** [comment]
j'ai regardé c'est ok
