### ISSUE TITLE
Améliorations de la page "à propos"

### ISSUE THREAD

**Issue by marineb** [DISIC/wikidemarches#763]
- [x] Navigation : remplacer "Qui sommes nous" (qui n'est as écrit correctement) par "À propos" (et mettre a jour le titre de la page aussi). Si trop compliqué, alors au moins corriger à "Qui sommes-nous ?"
- [x] Pour les H2 sur cette page par ex, changer leur line-height à `line-height: 1.3;` https://observatoire.numerique-staging.devxwiki.com/Main/A%20propos

**Comment by marineb** [comment]
@lucaa possible de faire ces mini modif please ?

cc @georges-bayard

**Comment by lucaa** [comment]
C'est fait

**Comment by marineb** [comment]
Bon pour moi. Merci bcp @lucaa
