### ISSUE TITLE
2 problemes sur l'image des reseaux sociaux

### ISSUE THREAD

**Issue by marineb** [DISIC/wikidemarches#764]
- [x] bug sur twitter : https://cards-dev.twitter.com/validator ("ERROR: Fetching the page failed because it's denied by robots.txt.")
- [x] L'image sur FB trop faible qualité et resolution donc en voici une nouvelle en piece jointe 

![meta-observatoire](https://user-images.githubusercontent.com/234208/67709441-3d5b3200-f9be-11e9-8910-b4c52bcd889c.png)

**Comment by marineb** [comment]
@lucaa 
cc @georges-bayard 

Merci

**Comment by lucaa** [comment]
C'est fait et mis en production.
