### ISSUE TITLE
supprimer des avis en masse sur la démarche 321

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#773]
A la suite d'une erreur de manipulation la DILA a installé le même bouton sur deux démarches  :  le bouton démarche 321 « Déclaration d'acquisition, vente, cession ou destruction de certains engins motorisés non soumis à réception » a été installé sur cette même démarche ainsi que sur la démarche 1825 « fraude à la carte bancaire ». Du coup tous les votes des deux démarches apparaissent indistinctement dans le tableau de bord sur la démarche 321.
Solution 1 : réussir à distinguer les votes entre les 2 démarches et réattribuer les votes aux bonnes démarches. Personnellement je ne vois pas comment c’est possible puisque c’est le même bouton qui a été installé sur deux démarches,  mais je pose la question
Solution 2 : supprimer tous les votes et réinstaller le bouton carte bancaire sur la démarche carte bancaire. 
Parallèlement il faudra également faire une extraction des données de vote des 3500 votes pour les adresser à la DILA.

**Comment by georges-bayard** [comment]
la Dila a désactivé le bouton sur la démarche carte bancaire le 0**7 novembre à 9h30**; il convient donc de désactiver tous les votes qui ont eu lieu auparavent

**Comment by lucaa** [comment]
Note: il s'agit très probablement de la démarche 1865 "Signaler une utilisation frauduleuse de sa carte bancaire en ligne" et non pas la démarche 1825 comme annoncé dans la description initiale du problème.

**Comment by lucaa** [comment]
3540 avis ont été effacés, il reste 5 avis sur la démarche 321. Les avis ont été exportés et envoyés par email.

**Comment by AnthonyBrunelli** [comment]
@georges-bayard Tu peux regarder? Je n'ai pas tout compris, la démarche "Signaler une utilisation frauduleuse de sa carte bancaire en ligne" n'affiche par de résultat de satisfaction (ni en prod, ni en pré-prod).

**Comment by georges-bayard** [comment]
@lucaa : tu confirmes que l'action a été faite sur l'environnement de prod directement ?

**Comment by georges-bayard** [comment]
ok vérifié : les votes antérieurs au 07/11 ont été supprimés de la démarche 1865. Vérifié en prod

**Comment by lucaa** [comment]
> @lucaa : tu confirmes que l'action a été faite sur l'environnement de prod directement ? 

oui.
