### ISSUE TITLE
impossible d'accéder au détail des avis depuis le tableau "liste des avis"

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#774]
Il n'y a plus de lien pour accéder au détail des avis depuis le tableau "liste des avis"

**Comment by lucaa** [comment]
Effectivement, il n'est plus disponible car ce tableau est partagé avec les porteurs et, pour une question de droits, les porteurs n'ont pas accès aux détails des avis.

Par contre, le tableau affiche toutes les données d'intêret pour un avis, et les avis individuels sont accessibles aux administrateurs par le tableau des avis de la page d'accueil.

On a décidé avec @georges-bayard que nous allons pas corriger.
