### ISSUE TITLE
Vérifier les couleurs du tableau de bord (observatoire) du point de vue accessibilité

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#777]

**Comment by georges-bayard** [comment]
Anthony confirme que les couleurs du tdb ne sont pas accessibles. cf mail du 13/11

**Comment by marineb** [comment]
Voici les nouvelles couleurs : 
- Vert = #62D2B0
- Rouge = #FF7777
- Orange = #FE8D5E

Le texte par dessus doit etre noir a 65% ou bien utiliser ces couleurs : 
- Sur le vert = #22493D
- Sur le rouge = #592929
- Sur le orange = #583120

Merci ! A faire au plus vite SVP :)

**Comment by lucaa** [comment]
@marineb il y a aussi le bleu de la valeur "Bêta" de la première colonne et le gris des valeurs "a venir", "n/a" et similaire.

**Comment by marineb** [comment]
@lucaa oui tu as raison. Je viens de rajouter et de mettre a jour. Merci !!

**Comment by lucaa** [comment]
J'ai mis à jour les couleurs sur l'observatoire et également mis les modifications sur la production.

**Comment by AnthonyBrunelli** [comment]
Merci on regarde ça vite!

**Comment by AnthonyBrunelli** [comment]
@lucaa C'est ok pour le tableau, mais pas pour les graphes derrières pour les textes en gris: intitulés des graphes et textes dans les graphes. Dans le 1er cas, détecté par l'extension WCag contrôle contraste checker, dans le deuxième c'est à l'oeil parce que l'extension ni accède pas.

![200130 Contraste couleurs Graphes](https://user-images.githubusercontent.com/35567048/73448435-22071680-4361-11ea-8c90-411ad483396d.png)

**Comment by AnthonyBrunelli** [comment]
(ne pas oublié les graphes bâton violet en dessous)

**Comment by lucaa** [comment]
@AnthonyBrunelli j'ai crée une tâche spécifique pour corriger ce problème: #851 .
