### ISSUE TITLE
Corriger les données de disponibilités/temps de réponse de deux démarches du tableau de bord d'octobre

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#781]
A la suite d'une vraisemblable erreur de manipulation dans Pingdom les démarches 871 et 872 ont été interverties sur les données du tableau de bord d'octobre. J'ai fait les corrections sur la version Excel.
871 : remplacer la valeur 8 par la valeur 2
872 : remplacer la valeur 2 par la valeur 8
Il faut corriger dans le tableau de bord en ligne
[TDB démarches phares_20192810_Voctobre2019-2.xlsx](https://github.com/DISIC/wikidemarches/files/3835633/TDB.demarches.phares_20192810_Voctobre2019-2.xlsx)

**Comment by lucaa** [comment]
J'ai inversé manuellement les valeurs des paramètres des mesures de performance pour les 2 démarches et re-genéré le tableau de bord d'octobre 2019.
@georges-bayard confirmez, svp, et fermez la tâche si le résultat convient.

**Comment by georges-bayard** [comment]
ok pour moi
