### ISSUE TITLE
mettre à jour le footer de l'observatoire à la suite de la création de la DINUM

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#782]
![image](https://user-images.githubusercontent.com/17125654/69056507-69436380-0a10-11ea-90a7-eb5f751374b3.png)

- Proposé par la DINUM + dans l’infobulle « Direction interministérielle du numérique »
- Màj lien Twitter https://twitter.com/_DINUM
- Màj lien LinkedIn https://www.linkedin.com/company/direction-interministerielle-du-numerique-dinum/

**Comment by lucaa** [comment]
J'ai également mis à jour la prod avec ce correctif.

**Comment by AnthonyBrunelli** [comment]
Vu okey!
