### ISSUE TITLE
ER-18: Rendre les headings du pied de page coherents

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#786]
Critère d'accessibilité ER-18 de http://pidila.gitlab.io/amoa/evaluation-rapide.html .
Voir analyse dans #703.

Il y a un problème pour les headings du footer qui commencent avec un heading 3, alors qu'il peut ne pas y avoir du heading 2 sur la page (heading incoherent). 
Aussi, le heading 3 peut se retrouver en dessous d'un heading 2 du contenu de la page, ce qui rend les headings incoherents.

Solutions possibles;
* pas du tout de heading dans le footer, comme dans service-public.fr
* heading 2 + headings 3 le footer, comme sur numerique.gouv.fr , car il y a toujours un heading 1 sur la page (le nom du site en logo pour la page d'accueil et le titre de la page pour toutes les autres pages).

**Comment by slauriere** [comment]
J'ajoute quelques liens intéressants sur ce sujet : 
* [La page « Headings » de la Web Accessibility Initiative](https://www.w3.org/WAI/tutorials/page-structure/headings/), qui propose des en-têtes dans le footer : 
* [Des best practices recommandées par la documentation Drupal](https://www.drupal.org/docs/7/creating-accessible-themes/using-headings-to-improve-accessibility), en particulier sur la manière de cacher certains en-têtes inutiles visuellement mais utiles pour une navigation non visuelle.
* Des éléments généraux de structuration sur [CSS-Tricks](https://css-tricks.com/how-to-section-your-html/) qui fournit souvent du contenu de bonne qualité.

**Comment by slauriere** [comment]
J'ai opté pour le moment pour la solution d'un ajout de h2 masqué avec une indentation négative pour qu'il apparaisse bien sur les lecteurs d'écran. Ça donne ceci : 

![pied-de-page](https://user-images.githubusercontent.com/1022195/70524425-63d7c580-1b45-11ea-8b72-7e52a4eb553c.jpg)

**Comment by slauriere** [comment]
Je clos cette tâche pour l'instant, ce sera intéressant d'avoir l'aval de Jamshid si possible cc @georges-bayard ?

**Comment by georges-bayard** [comment]
cf mail : ce serait intéressant de tester toute la partie accessibilité avec jamshid et Anthony

**Comment by AnthonyBrunelli** [comment]
On est dessus. On avait effectivement remarqué le titre en niveau 2 ET on a aussi été voir SP :).
Je creuse et on voit...
