### ISSUE TITLE
ER-04: Ajouter les liens d'evitement ou accès rapide ("bypass blocks")

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#787]
Voir l'analyse dans #703 .

**Comment by lucaa** [comment]
Voir aussi numerique.gouv.fr .

**Comment by slauriere** [comment]
Un menu d'accès rapide a été ajouté dans le header de la page sur le même principe et avec les mêmes styles que sur numerique.gouv.fr et cerfa.numerique.gouv.fr, avec les entrées suivantes :
- Menu
- Contenu
- Recherche (pour les personnes identifiées)
- Pied de page

**Comment by AnthonyBrunelli** [comment]
Oui vu, par contre le lien Menu, je n'ai pas bien compris où il dirige... Dans l'entête (header)?

**Comment by lucaa** [comment]
@AnthonyBrunelli oui, le menu est cette zone ici:
![image](https://user-images.githubusercontent.com/657716/72920301-4bb0b400-3d49-11ea-9fad-a62e1b27f5de.png)

**Comment by AnthonyBrunelli** [comment]
Ok! merci.
