### ISSUE TITLE
ER-17: corriger les couleurs utilisés sur le site pour avoir les bons contrastes

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#789]
Sur le top250 (voir #703) mais pas uniquement.
Une partie des correctifs ont été faits dans #777 , mais il reste quelques problèmes signalés par l'outil "WCAG Color contrast checker"

Page d'accueil:
* le contraste entre les icônes bleues et leur fond bleu n'est pas sufissant  - peut-être pas necessaire car juste une icône
* le texte du bouton "Consulter l'observatoire", blanc sur rouge, n'est pas assez visible

Pour le top250: 
* la couleur du texte en bas du tableau qui annonce le nombre de résultats est trop claire
* les couleurs des icônes dans le header du tableau, bleu foncé sur bleu clair (comme sur la page d'accueil)

Pour la page de vote:
* Les couleurs des boutons smileys vert et orange n'a pas assez de contraste avec le blanc. Par contre, il faut que les 3 couleurs soient assez contrastées entre elles pour que l'usager voit une différence entre les 3 options. IIRC, même à la mise en place initiale de ces couleurs, on a eu des difficultés à trouver les bonnes couleurs pour ces raisons.

**Comment by lucaa** [comment]
> Pour la page de vote:

voir #331, déjà crée pour ce travail.

**Comment by lucaa** [comment]
> le contraste entre les icônes bleues et leur fond bleu n'est pas sufissant - peut-être pas necessaire car juste une icône
> les couleurs des icônes dans le header du tableau, bleu foncé sur bleu clair (comme sur la page d'accueil)

Les couleurs des icônes des criteres a été discuté dans https://github.com/DISIC/wikidemarches/issues/795 , j'ai décidé qu'il n'est pas nécéssaire de le modifier.

**Comment by lucaa** [comment]
Il reste donc:
> le texte du bouton "Consulter l'observatoire", blanc sur rouge, n'est pas assez visible
> la couleur du texte en bas du tableau qui annonce le nombre de résultats est trop claire

**Comment by lucaa** [comment]
J'ai essayé de faire rester dans la même zone chromatique mais avec une couleur à bon contraste pour le bouton "consulter l'observatoire":
Avant:

![image](https://user-images.githubusercontent.com/657716/72289732-6356b100-3654-11ea-9c08-9f05483ced9c.png)

Après:
![image](https://user-images.githubusercontent.com/657716/72289827-95681300-3654-11ea-9ef6-2811b2bb3759.png)

Le contraste est à 4.58, à peine au dessus du seuil minimal de 4.5 donc je pense qu'on on ne peut pas faire plus pastel que ça pour la couleur du bouton.
@marineb , est-ce que tu approuves cette couleur?

**Comment by lucaa** [comment]
> le texte du bouton "Consulter l'observatoire", blanc sur rouge, n'est pas assez visible
> la couleur du texte en bas du tableau qui annonce le nombre de résultats est trop claire

C'est fait, avec la couleur ci-dessus pour le bouton, et une couleur de survol adaptée (aussi corrigée pour le contraste).
En plus, j'ai mis à jour les couleurs d'arrière plan des boutons à liste deroulante de l'observatoire (la séléction de l'historique de l'observatoire et le bouton de tri) pour mettre des gris moins foncés, pour qu'ils restent visibles même quand appuyés.

**Comment by AnthonyBrunelli** [comment]
Vu ok pour nous pour les pictos et le bouton si le contraste est bon.

**Comment by marineb** [comment]
Pardon du retard. Cette couleur plutot : #E6004A. Merci !

**Comment by lucaa** [comment]
Couleur mise à jour, et j'ai également mis à jour la couleur de survol.

**Comment by AnthonyBrunelli** [comment]
Traité dans #777
