### ISSUE TITLE
Create the legal notice page and link it from the wiki footer

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#79]
This page will contain the "mention legales" text.

**Comment by slauriere** [comment]
Done at the URL below and committed to the repository.
http://wikidemarches.devxwiki.com/Main/MentionsLegales

**Comment by lucaa** [comment]
Apparently there is no link in the footer. Reopening to add the link.

**Comment by slauriere** [comment]
A link was added to the footer.
