### ISSUE TITLE
ER-22: Vérifier (et corriger) le comportement des liens sous les icônes sur la page du top250

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#790]
Voir analyse dans #703 .
Les liens de partage du tableau de bord sur les liens sociaux et le lien d'expansion d'une ligne du tableau sont des icônes FontAwesome, il faut vérifier comment les lecteurs d'écran fonctionnent pour ces liens et s'assurer que tout est correctement fait pour que les liens soient correctement signalés.

**Comment by slauriere** [comment]
La documentation Font Awesome mentionne comment procéder, en utilisant les attributs `aria-label` et `aria-hidden` :

https://fontawesome.com/v4.7.0/accessibility/

```
<a href="path/to/shopping/cart" aria-label="View 3 items in your shopping cart">
  <i class="fa fa-shopping-cart" aria-hidden="true"></i>
</a>
```

**Comment by slauriere** [comment]
Le cas des liens de partage sur les résaux sociaux a été traité. Celui du bouton d'affichage / masquage des informations détaillées nécessite probablement de passer d'un affichage basé sur le pseudo-élément `before` à l'nsertion d'un élément dédié, pour pouvoir affecter également à celui-ci l'attribut `aria-hidden', et `aria-label` à l'élément parent.

**Comment by slauriere** [comment]
Un traitement spécifique a été apporté à l'élément td.details-control comme indiqué ci-dessus. J'ai été amené à devoir supprimer la règle CSS "display: block;" qui avait été ajoutée au pseudo-élément `:before` pour Chrome, cela semble bien ok maintenant qu'il n'existe plus.
