### ISSUE TITLE
tableau de bord : rendre plus évident qu'on puisse cliquer sur le lien pour accéder aux détails de l'indicateur de satisfaction

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#792]

**Comment by lucaa** [comment]
Voir aussi le commentaire sur #703 ( https://github.com/DISIC/wikidemarches/issues/703#issuecomment-561411772 ), qui parle de l'affichage de ce lien dans le contexte de l'accessibilité.

**Comment by lucaa** [comment]
@marineb : as-tu une proposition pour améliorer cela?

**Comment by georges-bayard** [comment]
souligner le lien ? info bulle au survol ?

**Comment by lucaa** [comment]
> info bulle au survol ?

C'est compliqué sur mobile.

> souligner le lien ?

On peut _et on doit_ souligner le lien, cf. regles d'accessibilité, mais en fonction de la réponse pour #797, on pourrait devoir chercher d'autres solutions.

Je pense qu'avec les décorations de #797 , on n'a pas beaucoup d'autre options que de mettre un access explicit aux résultats, sous forme d'un lien supplémentaire dans la même case, en dessous ou à côté.
![image](https://user-images.githubusercontent.com/657716/70996030-35706200-20d2-11ea-990f-2f029b9cfeb1.png)
![image](https://user-images.githubusercontent.com/657716/70996234-a3b52480-20d2-11ea-8c26-b95d7492fcf5.png)

**Comment by georges-bayard** [comment]
c'est bien. Je préfère voir les résultats ca pousse plus au clic d'après moi

**Comment by lucaa** [comment]
Voir aussi les écrans de #797 pour une version complète de cet affichage.

**Comment by lucaa** [comment]
J'ai implementé la solution proposée par @marineb pour #793 . Voir le commentaire https://github.com/DISIC/wikidemarches/issues/797#issuecomment-572993682 pour les explications et capture d'écran.

**Comment by AnthonyBrunelli** [comment]
Okey - j'ai une petite réserve sur le fait que ET le pourcentage ET le lien "graphe" soient cliquables pour mener au même endroit pour des problématiques de redondance au niveau du lecteur d'écran. Je rouvrirai une fiche le cas échéant.

**Comment by marineb** [comment]
Je suis d'accord avec Anthony. Mes retours : 
1. Je pense mieux de garder un look and feel consistant sur tous les indicateurs (je n'ai pas du suivre une conversation). Pourquoi le pourcentage est-il dans un encadré ?
2. Le lien "graphes" est ce qui est cliquable, c'est assez à mon sens (ca fonctionne sur mobile + desktop)

**Comment by georges-bayard** [comment]
sur ta question @marineb c'est pour répondre à la demande de nadi de colorier l'indice de satisfaction pour mettre en avant les bons et les mauvais. On a proposé une identification visuelle différrente pour maintenir une spécificité visuelle du ce critère qui est celui qui doit retenir l'oeil

**Comment by lucaa** [comment]
Pour répondre à la re-ouverture de cette issue, je retiens comme modification à faire la suivante:
* enlever le lien du pourcentage de satisfaction lui-même ("badge") et le laisser uniquement sur le texte "graphes".

Pour la question relative à l'encadré de l'indice de satisfaction, j'attends la décision suite aux clarifications de @georges-bayard .

**Comment by AnthonyBrunelli** [comment]
Vu avec Georges: pour l'instant on laisse le contour aux pourcentages et on enlève bien le lien sur le chiffre.

**Comment by lucaa** [comment]
Double lien corrigé, je re-ferme. Reouvrez si d'autre modifications sont necessaires.
