### ISSUE TITLE
Affichage du tableau de l'observatoire sur mobile

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#793]
Voir maquette sur https://app.zeplin.io/project/5d3fdb2bd28ae14c1a004431/screen/5d43d61abccdab2be718da87 .

Cette tâche est liée à la tache #778 et concerne l'affichage du tableau de l'observatoire, sur mobile.
L'idée est de transformer chaque ligne du tableau dans un block, avec les entêtes des colonnes repetées.
Note: cette technique de rendre les tableaux responsive est celle utilisée par le composant Livetable de XWiki. Par contre, ce tabeau est fait avec datatables. Il faut soit trouver un plugin similaire pour datatables, soit coder une solution similaire à celle du livetable XWiki (à base de javascript et CSS? )

**Comment by lucaa** [comment]
Voir aussi en relation avec #788 , quand le texte est trop grand, la vue mobile devait être utilisée, je pense.

**Comment by slauriere** [comment]
Une premier jeu de règles CSS a été ajouté pour un affichage sur mobile sur le même principe que les livetables XWiki sauf que les libellés des premières cellules de chaque ligne sont stockés directement dans le CSS plutôt que dans le HTML. Cf capture d'écran ci-dessous.

Il reste en particulier à :
- Utiliser une pour la taille d'écran
- Voir s'il est possible d'afficher les contenus sur deux colonnes plutôt qu'une (cf design sur zeplin)
- Améliorer les alignements lors de l'affichage des données détaillées
- Ajouter un bouton de tri
- Centrer les boutons d'action (filtrage, tri, etc.)

![mobile](https://user-images.githubusercontent.com/1022195/71360188-37816780-258f-11ea-990a-822df6231c9e.jpg)

**Comment by slauriere** [comment]
Deux modifications apportées : 
* Menu déroulant de tri (mais pas d'inversion d'ordre pour le moment)
* Centrage de la barre d'outils et de liens de partage / téléchargement sur mobile

**Comment by slauriere** [comment]
* Placer les boutons de filtre et de tri juste au-dessus du tableau
* Ajouter les ministères

**Comment by slauriere** [comment]
J'ai rétabli l'affichage des ministères, déplacé l'ordre des barres d'outils sur petits écrans, et aligné les styles avec ceux utilisés dans la ligne des données détaillées. L'affichage sur deux colonnes sur mobile est a priori significativement plus complexe, mais à étudier. Il reste également à voir comment présenter exactement la ligne des données détaillées – sans doute comme les autres avec alignement à droite des valeurs, cela nécessite a priori un changement de structure HTML.

**Comment by slauriere** [comment]
Sur mobile, chaque ligne de propriété s'affiche à présent sur deux colonnes. Les libellés ont été temporairement raccourcis ("Prise en compte handicap" -> "Handicap") pour pouvoir être affichés sans chevauchement à ce stade directement en CSS, il reste à les intégrer plutôt au code HTML pour pouvoir conserver les balises de retour chariot  (<br/>), qui ne peuvent être injectées en CSS.

**Comment by lucaa** [comment]
petit bug: les URLs des démarches sont insécables et agrandissent la taille du tableau sur mobile:

![image](https://user-images.githubusercontent.com/657716/71528401-e7ccd400-28df-11ea-898f-e687271d929c.png)

**Comment by georges-bayard** [comment]
On peut ne pas les afficher en mode mobile si ça fout la grouille

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

-------- Message original --------
De : Anca Luca <notifications@github.com<mailto:notifications@github.com>>
Date : ven. 27 déc. 2019 à 19:36
À : DISIC/wikidemarches <wikidemarches@noreply.github.com<mailto:wikidemarches@noreply.github.com>>
CC : Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Objet : Re: [DISIC/wikidemarches] Affichage du tableau de l'observatoire sur mobile (#793)

petit bug: les URLs des démarches sont insécables et agrandissent la taille du tableau sur mobile:

[image]<https://user-images.githubusercontent.com/657716/71528401-e7ccd400-28df-11ea-898f-e687271d929c.png>

**Comment by lucaa** [comment]
On a également un problème avec les valeurs très longues des colonnes, elles ne rentrent pas à coté des noms des colonnes, si on respecte les proportions du mockup:

![image](https://user-images.githubusercontent.com/657716/71588023-45e7fa00-2b20-11ea-8c9e-021c5c432e57.png)

@marineb des idées sur comment on devrait faire pour les valeurs longues?

**Comment by marineb** [comment]
@lucaa je regarde et je reviens vers toi.

**Comment by marineb** [comment]
Bonsoir @lucaa voici la proposition, disponible sur Zeplin, et bien sur ici pour voir rapidement : https://scene.zeplin.io/project/5d3fdb2bd28ae14c1a004431/screen/5e0a58b15ffbd61bd35eca6e.

**Comment by marineb** [comment]
J'en ai profité pour rajouter un visuel qu'on peut appliquer sur le web pour indiquer sur l'indice de satisfaction que l'usager peut acceder aux graphs et details. Dis moi ce que tu en penses !

**Comment by marineb** [comment]
Et aussi une solution pour les liens.

**Comment by lucaa** [comment]
@marineb thanks!

Quelques remarques:
* il peut être compliqué de déplier automatiquement les détails des démarches sur mobile (vu que sur desktop ils n'étaient pas caché par manque de place mais par choix d'organisation de l'information. Est-il possible de garder l'option de déplier pour avoir des informations supplémentaires?
* J'ai pris du temps pour comprendre que "Voir la démarche" c'est le lien vers la démarche. On avait trouvé une solution pour casser l'URL avec word-break, donc je pense qu'on peut laisser l'URL.
* Pour l'affichage de l'indice de satisfaction ( #797 ), comment cette proposition se decline sur grand écran? Aligné à gauche, centré ou avec "Graphes" en dessous, comme dans les propositions de #797 ?

**Comment by marineb** [comment]
Bonjour @lucaa (et bonne année !). 
1. Ça marche, voyons ce que cela donne !
2. Je pense mieux visuellement d'avoir ce lien, plus concis sur mobile
3. Ah j'avais loupé ces propositions. Si graphes ne passe pas en horinzontal, on peut le mettre en dessous

Merci !

**Comment by lucaa** [comment]
1. et 3. c'est fait, voir le commentaire https://github.com/DISIC/wikidemarches/issues/797#issuecomment-572993682 pour une liste des modifications que j'ai du faire par rapport à la maquette. 
Il manque encore 2. et l'icône du lien Graphes.

**Comment by lucaa** [comment]
> Il manque encore 2. 

J'ai ajouté du traitement du lien pour le cacher sur mobile et le remplacer avec l'étiquette "Voir la démarche" et afficher le lien complet uniquement sur desktop.

> et l'icône du lien Graphes.

j'ai crée une nouvelle tache pour cette icône: #817 .

**Comment by lucaa** [comment]
Je ferme cette tache maintenant, car l'affichage sur mobile est fait, il reste quelques améliorations pour lesquelles des taches séparées ont été crées.
Si des améliorations supplémentaires sont nécessaires ou des nouveaux bugs sont découverts, des nouvelles issues précises devraient être créés, cette tache est trop générique pour la réouvrir.
