### ISSUE TITLE
intégrer au Top 250 des indices de satisfaction sur des démarches générés par autres systèmes d'évaluation

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#794]
La CNAM dispose depuis plusieurs années d'un dispositif qui permet de mesurer la satisfaction des usagers à la fin de ses démarches. les usagers peuvent à la fin des démarches donner leurs niveau de staisfaction en actionnant des smiley : deux smiley un rouge un vert actionnés sur la page à la fin de la démarche. Le système de vte est minimaliste : aucun verbatim; aucune question complémentaire. 
Le résultat des votes  doit pouvoir être affiché tous les trimestres sur le Top 250. Il ne doit pas être affiché sur le tableau de bord temps réel. L'affichage de l'indice de satisfaction sur le top 250 doit être fait sans lien vers dés résultats détaillés car aucune information détaillée n'est disponible

**Comment by lucaa** [comment]
Données à intégrer:
* nb de votes
* indice de satisfaction
* la date à laquelle l'indice correspond
* les données seront ajoutés sur la démarche par un administrateur (dinsic)

Affichage:
* sur l'observatoire
* il est possible d'afficher, sur la page de la démarche, une note qui explique la source externe des votes, avec un lien. On peut donc mettre en place le lien et modifier uniquement la page qui affiche les détails des votes pour afficher cette source externe

Besoin:
* pouvoir analyser / afficher l'evolution de ces indices dans le temps.

**Comment by lucaa** [comment]
>  Il ne doit pas être affiché sur le tableau de bord temps réel. 

@georges-bayard pour des raisons de traitement unifié des données, il peut être plus facile de l'afficher partout sur tous les tableaux de bord, mais j'essaye de remplir cette contrainte aussi.

**Comment by georges-bayard** [comment]
Nous avons un point avec la CNAM sur l'intégration des données. d'ici la il faut leurs proposer une solution et préparer les questions que nous devons leurs poser en complément

**Comment by georges-bayard** [comment]
[Cnam_dématéralisation chiffres pour DINUM_décembre 2019.pptx](https://github.com/DISIC/wikidemarches/files/4031301/Cnam_demateralisation.chiffres.pour.DINUM_decembre.2019.pptx)
[DINUM -TDB démarches phares_Cnam_décembre 2019.xlsx](https://github.com/DISIC/wikidemarches/files/4031302/DINUM.-TDB.demarches.phares_Cnam_decembre.2019.xlsx)
[PDFServletDetailMessage.dopdf.pdf](https://github.com/DISIC/wikidemarches/files/4031303/PDFServletDetailMessage.dopdf.pdf)

**Comment by georges-bayard** [comment]
nous avons eu un point aujourd'hui avec la CNAM (catherine letoy et Eugénie Chevalier) sur l'intégration des données.
- Ils s'engagent à nous envoyer à la fin de chaque trimestre pour publication les indices de satisfaction et le nombre de votes calculés sur une année glissante pour être conformes à notre méthodo
- pour le tdb janvier 2020 nous avons convenu que les chiffres fournis (moyenne de l'ensemble de l'année 2019 sauf décembre) étaient suffisants compte tenu de la grande stabilité des résultats. Ils ne nous fournitont pas le nombre de votants pour cette fois ci

**Comment by georges-bayard** [comment]
Résultats de vote à intégrer : 
- Déclarer une naissance (Ameli) : 90,8%
- Attestation de paiement d'indemnités journalières : 88,2%
- Demander une carte   européenne d'assurance maladie (Ceam) : 95,8%
- Changement d'adresse (Ameli) : 97,4%
- Demander une carte vitale : 96,6%
- Attestation de droits : 92,7%

**Comment by georges-bayard** [comment]
@lucaa : l'objectif est de sortir les chiffres sur le tdb janvier 2020. A discuter : modalités d'intégration. l'urgence pour moi est d'afficher le chiffre brut sur le tableau de bord, sans lien.

**Comment by lucaa** [comment]
@georges-bayard  J'ai préparé une intégration à base d'une déclaration des indices par l'administrateur (dinsic), avec les valeurs et les périodes auxquelles ces indicateurs s'appliquent.

Par contre, aujourd'hui le tri par défaut de l'observatoire est par le nombre d'avis recueillis. Ainsi, pour faire apparaître ces 6 démarches en haut de la liste des démarches de l'observatoire, à coté des autres démarches ayant reçu des avis, nous auront besoin d'un nombre d'avis pour chacune. Mon implémentation prevoit l'ajout du nombre d'avis, il faut juste avoir les valeurs.

**Comment by lucaa** [comment]
Une nouvelle fonctionalité pour définir des indicateurs statiques des sources externes a été ajouté, accessible dans l'écran des "outils d'administration" (section "Tableaux de bord - top 250"), affiché aux utilisateurs qui sont administrateurs Dinum à partir du lien de la page d'accueil.
Elle permet d'ajouter des indicateurs externes datés contenant les informations suivantes:
* la démarche à laquelle l'indicateur s'applique
* l'indice de satisfaction et le nombre d'avis recueillis
* la période à laquelle l'indice s'applique (date de début et date de fin)
* un commentaire (à remplir avec des informations supplémentaires sur l'indicateur, source, métodologie, etc.)

Les indicateurs sont utilisés de la manière suivante:
* à chaque fois que les données pour un tableau de bord nommé (et daté) sont générés, pour chaque démarche pour laquelle il n'y a pas un nombre d'avis suffisant dans le système (<100 avis ou pas d'avis du tout), un indicateur externe est recherche, ainsi:
  * parmi tous les indicateurs remplis pour cette démarche (il peut y en avoir plusieurs), les indicateurs ayant une date de fin de période avant la date du tableau de bord sont séléctionnés. Parmi ces indicateurs, le plus récent est utilisé (autrement dit, l'indicateur utilisé est l'indicateur le plus récent mais précédant la date du tableau de bord nommé).
* i'indice de satisfaction et nombre d'avis utilisateurs de cet indicateur statique sont inclus dans les données du tableau de bord nommé

Lors de l'affichage des statistiques d'une démarche à une date fixée (affichage accessible par le bouton "Graphes" dans le tableau de bord), les indicateurs statiques sont utilisés ainsi:
* s'il n'y a pas d'avis pour cette démarche à la date indiquée, un indicateur statique est recherche en utilisant la même régle que dans le cas de génération des données pour le tableau de bord
* si cet indicateur est trouvé, on affiche la période de l'indicateur , l'indice de satisfaction et le nombre d'avis
* le commentaire rempli lors de la création de l'indicateur statique est également affiché en dessous, ainsi:

![image](https://user-images.githubusercontent.com/657716/73272932-784e4b00-41e3-11ea-9bce-6e6290ca6d63.png)

**Comment by lucaa** [comment]
Le clos cette tâche car la fonctionnalité, telle qu'implémentée répond au besoin.

Il reste un bug, quand même, dans un cas très particulier, ainsi:
* une démarche du top250 a des avis sur l'application, mais pas assez (e.g. 5 avis)
* un indicateur statique est ajouté pour cette démarche
* lors de la génération du tableau de bord , l'indicateur statique est utilisé
* lors du click sur le lien "Graphes" dans le tableau de bord, le résultat affiché est celui pour les 5 avis, alors que ce qu'on attend est l'utilisation de l'indicateur statique - le bug est lié aux vérifications differentes (dans un cas on vérifie le nb d'avis < 100, dans un autre cas on vérifie nb d'avis > 0, on devrait utiliser la même régle partout).
Note: ce bug n'est pas présent si les avis sont ajoutés à la démarche après la date du tableau de bord. Ainsi, la situation ou une démarche n'a pas d'avis du tout pour un tableau de bord , utilise un indicateur statique mais dans le futur elle reçoit des avis car elle intégre le bouton est gerée correctement.

Ce cas ne devrait pas arriver en production. Si le cas arrive, les avis existant qui provoquent cette situation sont plutôt des avis de test qu'on peut effacer pour corriger la situation.

**Comment by lucaa** [comment]
> > Il ne doit pas être affiché sur le tableau de bord temps réel.

> @georges-bayard pour des raisons de traitement unifié des données, il peut être plus facile de l'afficher partout sur tous les tableaux de bord, mais j'essaye de remplir cette contrainte aussi.

Note: la fonctionnalité, tel que décrite ci-dessus, n'utilise pas les indicateurs statiques pour le tableau de bord en temps-réel.
