### ISSUE TITLE
Amélioration du contraste des pastilles représentant les critères

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#795]
L'outil de vérification de niveau de contraste WCAG Contrast Checker indique que le contraste des pastilles représentant les critères, sur la page d'accueil et sur le tableau de bord, est insuffisant : le fond rgba(0,107,230,0.1) doit être éclairci au minium à rgba(0,107,230,0.06) semble-t-il, cf captures ci-dessous indicatives : 

![criteria-badges](https://user-images.githubusercontent.com/1022195/70545841-803c2800-1b6e-11ea-961d-9c907ab5a4fa.jpg)

----

![criteria-badges-1](https://user-images.githubusercontent.com/1022195/70545845-80d4be80-1b6e-11ea-80ef-317b3c836541.jpg)

----

Voir aussi : #331 331

**Comment by slauriere** [comment]
Un fading de 6.4% a été appliqué au lieu du 10% précédent.

**Comment by lucaa** [comment]
Je ne sais pas si je l'ai mis dans un commentaire ou j'y ai juste pensé, mais j'aurais pas touché à ces éléments pour la logique suivante:
* même si d'un point de vue implémentation c'est du texte sur un fond (car c'est comme ça que les icônes FontAwesome marchent), du point de vue de la logique de l'écran ces éléments là sont des icônes (elles ne sont pas le porteur exclusif de l'information, elles accompagnent l'information qui est dans le titre juste en dessous). Dans une autre implémentation, ces éléments auraient été des images (potentiellement vectorielles), ignorés complétément par l'outil de vérification de contraste. 
À ma connaissance, il n'y a pas d'obligativité dans le RGAA pour que toutes les illustrations d'une application aient un contraste 4.5 sinon, pour une vraie image, on ne s'en sortirai jamais.
Ainsi, je crois que l'outil de vérification de contraste devrait être utilisé avec attention à ses limitations. 

Je propose de revenir an arrière sur cette modification, pour essayer de rester sur les visuels validés, tant que possible.

**Comment by slauriere** [comment]
Oui, pas facile de trancher mais effectivement, j'ai rétabli les couleurs précédentes via un revert.
