### ISSUE TITLE
prévoir la possibilité de regrouper sur une même démarche du top 250 les votes effectués sur plusieurs démarches différentes 

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#796]
Le besoin lui même doit être interrogé avant de se lancer.
le cas d'utilisation est celui des démarches de demande de subvention du ministère de la culture
[demarches subventions culture.xlsx](https://github.com/DISIC/wikidemarches/files/3969273/demarches.subventions.culture.xlsx)
sur l'opportunité il faut savoir si il y a un tronc commun très différent ou non entre les démarches

**Comment by georges-bayard** [comment]
il existe au MCC 57 sous démarches de demande de subvention regorupées sur le tableau de bord en une seule démarche. Le besoin est de pouvoir disposer des résultats des votes démarche par démarche mais que ces résultats soient présentés en une seule ligne sur le TDB. Si le besoin est légitime (ce qu'il reste à vérifier) deux solutions sont envisageables
- créer des démarches de type "regroupement" qui agrègent les votes d'autres démarches
- conserver l'unicité du bouton mais pouvoir dans le backoffice distinguer les votes en fonction de la page sur laquelle il a été effectué.

@lucaa : qu'en penses tu ?

**Comment by lucaa** [comment]
> conserver l'unicité du bouton mais pouvoir dans le backoffice distinguer les votes en fonction de la page sur laquelle il a été effectué.

Comme pour #751, on peut ajouter une particule à la "source" du bouton, qui est enregistrée avec l'avis, pour distinguer entre des avis provenant de sous-démarches differentes.
Ainsi, cette solution est déjà faisable, il faut juste modifier le code du bouton que la plateforme observatoire.gouv.fr fournit. On peut le faire de notre côté ou ça peut être fait lors de l'intégration du bouton.

**Comment by lucaa** [comment]
La réponse pour mettre en place la solution à base du paramètre source a été envoyé par email, je ferme cette tache maintenant.
