### ISSUE TITLE
implémenter des couleurs sur la valeur usagers satisfaits de l'observatoire

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#797]
o	>= 80% = vert
o	60-80% = orange
o	< 60% = rouge

**Comment by lucaa** [comment]
@georges-bayard on garde l'affichage courant avec texte coloré mais on colore le lien

![image](https://user-images.githubusercontent.com/657716/70994930-8a5ea900-20cf-11ea-8dd1-1816687ae572.png)

ou on met des pastilles colorées comme pour les autres critères?

![image](https://user-images.githubusercontent.com/657716/70995134-107aef80-20d0-11ea-8c4b-2c9358e51979.png)

à noter que si on veut mettre des pastilles comme pour les autres critères, le problème de decouvrabilité du fait que le pourcentage est un lien ( #792 ) devient encore plus important, car cette information sera désormais affichée comme les autres informations, qui ne sont pas cliquables.

**Comment by georges-bayard** [comment]
je préfère la solution 1 que tu propose pour plusieurs raisons : c'est une info qu'il faut distinger des autres car c'est la plus importante du tableau ; c'est plus facile à comprendre que c'est un lien.
Pourrais tu faire un essai en 
@marineb : qu'en penses tu ?

**Comment by lucaa** [comment]
Quelques versions supplémentaires pour cet affichage (aussi pour #792 ) sans badge, avec valeur colorée et texte explicite:

1/ avec lien "voir les résultats" bleu lien de la valeur soulignée:

![image](https://user-images.githubusercontent.com/657716/71480507-bf6aaa00-27f9-11ea-9aad-dc25f59188b2.png)

2/ la même chose sans souligner la valeur elle même, même si elle reste un lien:

![image](https://user-images.githubusercontent.com/657716/71480620-520b4900-27fa-11ea-8a1a-11016d8edb6a.png)

**Comment by lucaa** [comment]
3/ avec le lien "voir les résultats" coloré dans la couleur de la valeur, valeur soulignée

![image](https://user-images.githubusercontent.com/657716/71480725-e5dd1500-27fa-11ea-95ac-f340968416e6.png)


4/ avec le lien "voir les résultats"  coloré, sans souligner la valeur:

![image](https://user-images.githubusercontent.com/657716/71480683-b9c19400-27fa-11ea-937a-9a8f7cfa8bb1.png)

**Comment by georges-bayard** [comment]
Je préfère la derniere version. @marineb : qu'en penses tu ?

**Comment by georges-bayard** [comment]
ma préférence va toujours vers le 4

**Comment by lucaa** [comment]
J'ai implémenté la solution dessinée par @marineb pour #793 , avec un lien nommé "Graphes", en dessous:

![image](https://user-images.githubusercontent.com/657716/72148694-16e84880-33aa-11ea-91e6-672eddeee184.png)


Quelques modifications par rapport à la maquette de @marineb :
* J'ai du utiliser d'autres couleurs pour les textes (le pourcentage lui-même ) et le lien Graphes, pour respecter les contrastes d'accessiblité. Pour les pourcentages, les couleurs sont les mêmes que celles des textes des autres boîtes, pour le lien Graphes j'ai utilisé le gri #666666 plutôt que le #999999 de la maquette.
* J'ai souligné le lien Graphes, toujours pour respecter des critères d'accessibilité, mais j'ai potentiellement interprété celui-ci trop strictement: la régle dit qu'il faut marquer les liens autre que par leur couleur, qu'il faut souligner ou autre. Par contre, ce lien n'est pas dans un paragraphe de texte, donc il ne s'agit pas de le differentier du texte qui l'entoure, je me demande si on a toujours besoin de le sousligner même s'il est pas dans un paragraphe de texte. Je l'ai fait pour être sure.
* Il manque l'icône du lien Graphes

**Comment by AnthonyBrunelli** [comment]
Premier point: ok :)
Deuxième point: ok, je suis plutôt favorable au soulignement dans ce cas précis, je trouve ça plus clair et plus incitateur.
Troisième point: déso, pas compris... @lucaa

**Comment by lucaa** [comment]
> Troisième point: déso, pas compris... 

@AnthonyBrunelli  : dans sa proposition de design, Marine avait mis une icône pour le lien Graphes, elle n'est pas encore implementée.
Voici la proposition de Marine, découpée de la maquette version mobile: 
![image](https://user-images.githubusercontent.com/657716/72919916-94b43880-3d48-11ea-8140-5458080eda49.png)

**Comment by AnthonyBrunelli** [comment]
Ok compris merci!
