### ISSUE TITLE
Re-mettre la limite d'une année glissante pour les votes à afficher

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#800]
Il s'agit du travail fait pour #736 qui a été enlevé pour #757 .
Voir #748 pour la discussion liée aux endroits ou cette limite doit être active ou pas.

**Comment by lucaa** [comment]
La limite ne dois pas s'appliquer à tous les tableaux de bord, mais uniquement au tableau de bord nouveau.

**Comment by slauriere** [comment]
Créer une nouvelle version du schéma du fichier json (1.2) avec trois dates dans les propriétés : 
- avis-start-date
- avis-end-date
- demarche-date

Ajouter un traitement en JavaScript pour les versions antérieures à 1.2.

**Comment by slauriere** [comment]
La fonctionnalité a été implémentée telle que décrite et testée pour : un nouveau dashboard (json version 1.2), les anciens dashboards (json versions 1.0 et 1.2), les anciennes URLs ("date=" au lieu de "date-fin="), la version live du dashboard, et l'accès depuis une fiche de démarche.
