### ISSUE TITLE
Rendre l'ancien tableau de bord accessible aux administrateurs ministériels

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#801]
Il s'agit du tableau de bord accessible aujourd'hui aux administrateurs DINSIC , qui a été remplacé par l'observatoire, qui a été modifié pour les administrateurs DINSIC pour #754.
L'idée est d'afficher un lien vers ce tableau dans la zone "Administrez les données" en bas de la page d'accueil, avec un nom potentiellement different.
Il faut également verifier que les administrateurs ministeriels ont le droit de voir la page une fois le lien mis, et potentiellement enlever de cette page le message invitant les utilisateurs à ajouter une nouvelle démarche (si elle manque).
Aujourd'hui le but de ce tableau est d'afficher toutes les démarches (top 250 ou pas), leurs nombre de votes et leur indices de satisfaction, quasi en-direct (calculés toutes les nuits). On peut donc mettre un titre dans ce sens là.

**Comment by georges-bayard** [comment]
Titre proposé : "tableau de bord"

**Comment by lucaa** [comment]
Potentiellement la même chose que #711 , à vérifier.

**Comment by AnthonyBrunelli** [comment]
(Note: pour que les ministères aient accès aux infos des démarches avec MonAvis hors top 250)

**Comment by lucaa** [comment]
J'ai ajouté le lien vers le tableau de bord sur la page d'accueil, en bas, sous le nom "Tableau de bord".
Aucune modification n'a été faite sur les droits d'acces à cette page, le seul changement fait du point de vue de l'acces est le fait que le lien est désormais disponible aux utilisateurs ministériels. Par contre, j'ai vérifié rapidement les droits, uniquement les Administrateurs Ministeriels y ont accès.
Aucune modification n'a été faite sur la page, par contre, ni pour le titre ou le message invitant à ajouter une démarche. Reouvrez si une modification dans ce sens est nécessaire.
