### ISSUE TITLE
Ajout des méta données pour "prise en compte des handicaps" dans le modèle de données des démarches

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#810]
L'indicateur à afficher sur le tableau de bord est calculé à base de 2 critères, très similaire à la colonne "support de qualité".
Ainsi, le traitement de cette nouvelle méta-donnée doit être similaire.

**Comment by lucaa** [comment]
Suite à l'analyse des fichiers excel, j'ai les règles de calcul suivantes:

2 nouvelles méta données sont à intégrer au modèle de démarches:
* Déclaration d'accessibilité presente sur le site:
  * valeurs possibles: Oui, Non, Inconnu (vide), n/a
* Pourcentage de conformité au RGAA déclaré:
  * Valeur numérique de 0 à 100% ou _n/a_

Formule pour le calcul de la valeur finale du critère à afficher dans le tableau de bord, telle qu'analysé à base du fichier excel:
* si n/a pour la déclaration -> **"n/a"**
* si la déclaration existe (Oui) et le pourcentage est au dessus de 75% -> **"Oui"**
* si la déclaration existe (Oui) mais le pourcentage n'est pas au dessus de 75% ou _la déclaration n'existe pas (Non ou vide) mais le pourcentage est au dessus de 75%_  -> **"Partiel"**
* si la déclaration n'existe pas (Non) ou sa presence est inconnue (vide) et le pourcentage est en dessous de 75% -> **"Non"**

Notes: 
* la valeur n/a pour le pourcentage de conformité ne semble pas être utilisé dans la formule finale, ainsi nous n'allons pas la stocker. Cela rend les choses un peu plus simple car cela nous permet de stocker le pourcentage comme une valeur numérique de 0 à 100 (qui sera vide en cas de valeur inconnue)
* la situation "la déclaration n'existe pas (Non ou vide) mais le pourcentage est au dessus de 75%" de la formule de calcul pour la valeur finale "Partiel" ne peut pas arriver, en pratique. Ainsi, nous allons probablement implementer la condition pour la valeur "Partiel" sous la forme suivante: "Si la déclaration existe mais le pourcentage déclaré n'est pas au dessus de 75%". Cela aura comme consequence que tous les cas ou la déclaration n'existe pas ou est vide donneront une valeur "Non" pour le critère, quelque soit la valeur du pourcentage.

Ainsi, voici la proposition simplifiée pour la formule finale:
* si n/a pour la presence de la déclaration -> **"n/a"**
* si Oui pour la presence de la déclaration
  * si pourcentage > 75% -> **"Oui"** 
  * autrement -> **"Partiel"** 
* pour tous les autres cas -> **"Non"**

**Comment by georges-bayard** [comment]
Ok ca me va
