### ISSUE TITLE
ajouter dans le tdb un statut particulier pour les démarches pour lesquelles le bouton a été installé mais le seuil de 100 votes n'a pas été atteint

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#812]
L'objectif est de signaler au lecteur du tableau que le bouton a été installé sans que le seuil de 100 votes qui déclenche la visualisation dans le tableau de l'indice de satisfaction ne soit atteinte.
Règles de gestion :
- ajouter une case à cocher (bouton installé) dans le référentiel des démarches
- ce bouton est automatiquement coché (et grisé) si il y a plus de 100 votes sur la démarche
- le bouton peut être coché manuellement (uniquement par l'administrateur DINUM) dans le cas ou la condition précédente n'est pas remplie
- dans le cas ou la case à cocher a été cochée manuellement (cas ou inférieur à 100 votes) alors dans le tableau de bord apparaît le statut "ouvert" (terminologie à challenger)

**Comment by lucaa** [comment]
@georges-bayard est-ce qu'il est prévu que cette information soit presente dans l'excel des démarches phares et qu'on a besoin d'importer cette information lors de l'import de l'excel?

**Comment by lucaa** [comment]
Une méta-donnée pour marquer l'intégration du bouton avait déjà été ajoutée dans le passé et enlevé pour #614 , à cause de sa redondance avec la présence des avis.
Par contre, la métadonnée à ajouter aujourd'hui est plus simple, uniquement une case à cocher est nécessaire (au lieu d'une liste de valeurs possibles).

**Comment by lucaa** [comment]
L'affichage courant est :
![image](https://user-images.githubusercontent.com/657716/73299993-86ff2700-4210-11ea-9f4d-185ae7e518fd.png)

"Collecte des avis en cours" en gris.
@georges-bayard il faut décider le texte final et la couleur.

**Comment by lucaa** [comment]
J'ai implémenté également les régles pour le mode affichage et modification (si 100+ votes, la valeur n'est pas modifiable). Par contre, aujourd'hui le nombre de votes est lu du cache d'avis, donc aura une journée de retard.

**Comment by Hatice2020** [comment]
On propose avec @georges-bayard de mettre "en cours" à la place de "collecte des avis en cours" et on peut garder la couleur gris.

**Comment by lucaa** [comment]
nouvel affichage mis en place:
![image](https://user-images.githubusercontent.com/657716/73366326-11499880-42ae-11ea-80bc-d7f9190b8683.png)

**Comment by georges-bayard** [comment]
@lucaa : sur l'import des données en préparation de la prod on peut soit faire l'import de la case à cocher à partir des données que je vous ai envoyées ce matin dans l'Excel soit on peut aussi le faire en prod entre le moment ou vous aurez importé et le moment ou on génèrera le tableau. Tu préfères quelle solution ?

**Comment by lucaa** [comment]
@georges-bayard : deuxième, en production, c'est plus facile. ça nous permet de ne pas modifier l'import (tools & stratégie).

**Comment by lucaa** [comment]
Etiquette dans le formulaire de démarche à revoir, texte: "Bouton de recueil d'avis intégré".

**Comment by lucaa** [comment]
L'étiquette a été mise à jour, j'ai re-fermé la tache.
