### ISSUE TITLE
Afficher la valeur de l'indicateur "prise en compte des handicaps" sur l'observatoire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#815]
La méta-donnée "prise en compte des handicaps", telle que définie par la tache #810 pour les démarches doit être affichée dans la colonne "Prise en compte handicaps" de l'observatoire, colorée ainsi:
* n/a -> gris ou tiré sur blanc? (@georges-bayard  ?) 
* "Oui" -> vert
* "Partiel" -> orange
* "Non" -> rouge

**Comment by Hatice2020** [comment]
on propose avec @georges-bayard de garder la même forme que les autres critères.
donc n/a en gris convient.
![image](https://user-images.githubusercontent.com/60133783/73350057-a63b9a00-428c-11ea-9124-1c964cd6b599.png)
