### ISSUE TITLE
Import des nouvelles données pour l'observatoire Jan 2020 à partir d'Excel

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#816]
Tâche générique pour toutes les opérations liées aux actions d'import des données à partir du fichier Excel.
Si des modifications de modèle ou code sont nécessaires pour intégrer de la donnée de ce fichier, l'idèal serait de créer une nouvelle tache qui décrit le changement attendu.

Note: même si le label est "prod action", les actions à faire sur staging en vue des tests seront également considère partie de cette tache.

**Comment by slauriere** [comment]
L'import a été effectué sur le site de pré-production (actions notées sur le log de déploiement interne). Un nouveau tableau de bord a été généré.

**Comment by slauriere** [comment]
GBA, Une remarque  au cas où elle cacherait soit un problème d'import soit autre chose: la démarche [1792](https://observatoire.numerique-staging.devxwiki.com/Demarches/1792) semble être pasée du statut « expérimentation » à « non réalisable en ligne », et en même temps, elle a des données Pingdom ? @georges-bayard

**Comment by georges-bayard** [comment]
@slauriere : c'est en effet une dé-dématérialisation ; on a abandonné l'expérimentation sur dossier sco et une autre socultion devrait être mise en place d'ici la fin de l'année. Sur les données Pingdomtu as raison il faut l'inactiver. Je m'en occupe

**Comment by lucaa** [comment]
@slauriere #852 a été fait, à vérifier avant l'import que si ce changement a des consequences sur le fichier, si  c'est necessaire ou pas de mettre à jour les noms de colonnes du mapping lors de l'import. Thanks!
