### ISSUE TITLE
Entête/lecteur d'écran: nom du site lu deux fois

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#818]
[mineur]: le lecteur d'écran lit deux fois le lien dans l'entête, une fois qu'il est sur le logo, et une fois qu'il est sur le nom complet du site à droite du logo. Si possible, faire en sorte qu'il n'y ait qu'une seule lecture.

**Comment by lucaa** [comment]
Un des changements faits pour #887 concerne cet entête qui est maintenant un seul lien (donc URL a lire une seule fois) et le nom du site n'est plus l'URL du site, donc il ne devrait plus y avoir de confusion par rapport à la lecture double. @AnthonyBrunelli est-il possible de re-vérifier si cette tache est toujours d'actualité?

**Comment by AnthonyBrunelli** [comment]
Pas détecté dans l'audit d'accessibilité donc je ferme.
