### ISSUE TITLE
Page d'accueil: structuration (niveau de titre) sur la page

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#819]
![image](https://user-images.githubusercontent.com/35567048/73252310-d4e94000-41ba-11ea-94b1-4c1022251d84.png)

Harmoniser les niveaux de titre: le titre de niveau 1 ne doit pas être l'entête mais le titre de la page (ie, celui de niveau 2). Ajuster le reste en fonction.

Ou y a-t-il des enjeux/contraintes qui m'échappent?

**Comment by lucaa** [comment]
Je ne trouve pas de trace de cette structuration des headings (ça a été fait comme ça pour #29) mais je me rapelle que la régle que j'ai utilisé à ce moment a été fournie par @tetue , sous la forme suivante:
* sur la page d'accueil le h1 est le titre du site (lien vers la homepage et logo)
* sur toutes les autres pages le h1 est le titre de la page, le titre du site (lien homepage & logo est juste un span).

J'ai trouvé une trace qui parle du fait que c'est correct de le faire comme ça https://www.accede-web.com/notices/html-css-javascript/1-structure/1-8-hierarchie-titres-logique-h1-h6/ mais pas de trace de son obligativité.

**Comment by AnthonyBrunelli** [comment]
à revoir...

**Comment by AnthonyBrunelli** [comment]
Vu, corrigé, ok comme aç.

**Comment by lucaa** [comment]
La structure dont parle cette tache a été changée par l'implémentation de #887.
