### ISSUE TITLE
Pour tous les pictogrammes non porteur de sens, mettre des alt vide

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#822]
Sur la page d'accueil et sur les entêtes des colonnes sur la page observatoire, laisser les alt vide (" "): ils sont redondants et nuisent à la lecture d'écran  (règle: si l'image est purement décorative, l'attribut alt doit être présent et vide).

Exemples:

![image](https://user-images.githubusercontent.com/35567048/73253849-930dc900-41bd-11ea-8452-420c62a6e9c0.png)

![image](https://user-images.githubusercontent.com/35567048/73253868-9c973100-41bd-11ea-80a2-a49137e39211.png)

**Comment by lucaa** [comment]
Les éléments des captures ne sont pas des images (HTML), mais des pictos implémentés avec Font Awesome et des spans. @slauriere peux-tu vérifier, s'il te plaît, le comportement des lecteurs d'ecrans pour ces images et faire les modifications necessaires (s'il y en a) pour empecher la lecture?

**Comment by AnthonyBrunelli** [comment]
Issue confirmée à corriger:

1. Dans la section "Comment évaluons nous la qualité des démarches ?", les huit icônes sont décoratives et ont une alternative textuelle non pertinente (ex : "icone.svg"). Pour chaque icône, supprimer la valeur de l'attribut alt. 

2. Dans le tableau, au dessus de chaque titre de colonne, l'icône est décorative car son alternative répète le texte situé en dessous. Pour chaque icône, supprimer la valeur de l'attribut alt.

**Comment by AnthonyBrunelli** [comment]
Critère 1.2: Chaque image de décoration est-elle correctement ignorée par les technologies d’assistance ?

**Comment by slauriere** [comment]
Le commit bb8d2e3 ci-dessus apporte la correction pour la section "Comment évaluons nous la qualité des démarches ?" de la page d'accueil et pour les en-têtes du tableau -> je ferme ce ticket.

**Comment by slauriere** [comment]
Pour ce qui concerne la section "Comment évaluons-nous les démarches", la modification doit être effectuée directement en production car il s'agit d'une page de contenu.

La procédure est la suivante : 
* S'assurer d'être en mode utilisateur avancé
* Depuis la page des [outils d'administration](https://observatoire.numerique.gouv.fr/Administration/), cliquer sur "Explications des critères"
* Modifier la page en mode wiki ("Modifier" > "Wiki")
* Ajouter un attribut `alt` vide à chacune des images en suivant cet exemple : 
```
[[image:Demarches.Code.WikiDemarchesTheme@cloud.svg||alt=""]]
```

**Comment by AnthonyBrunelli** [comment]
Salut @slauriere ! Ok, j'ai dû tâtonner (notamment en passant par "propriété de l'image" pour rien, mes modifs n'étant pas enregistrées) mais j'ai trouvé, ça devrait être bon. Je te laisse gérer l'issue en fonction.

**Comment by lucaa** [comment]
Ces changements font partie aussi des modifications intégrées dans la codebase lors du commit d23bbc7c93a324323f29a5286c68cf2a146bebe0 .

**Comment by lucaa** [comment]
@slauriere il n'est pas clair pour moi s'il reste des choses à faire pour cette tache a part l'intégration dans le codebase. Peux-tu fermer si rien ne reste à faire?

**Comment by slauriere** [comment]
@AnthonyBrunelli @lucaa Je confirme que tout est ok à présent sur ce point ! -> Je clos le ticket.
