### ISSUE TITLE
Tableau observatoire: bouton de retour en haut de tableau

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#823]
Le tableau étant long, est-il possible d'avoir un bouton de retour en haut de tableau qui suit le défilement?

À discuter.

**Comment by lucaa** [comment]
Assez facile à mettre en place, il y a une extension XWiki qui fait ça: des qu'une page scrolle, un bouton est affiché en bas permettant de remonter en haut. Par contre, je ne suis pas sure s'il passe les critères d'accessibilité.

**Comment by AnthonyBrunelli** [comment]
Si c'est assez facile, je suis pour qu'on tente.

**Comment by AnthonyBrunelli** [comment]
Vu avec Georges, nous confirmons.

**Comment by lucaa** [comment]
J'ai ajouté le bouton de retour en haut de cette extension https://extensions.xwiki.org/xwiki/bin/view/Extension/Back%20To%20Top , avec quelques modifications pour la couleur (bleu, pour l'observatoire) ainsi que quelques modifications de position sur mobile.
@AnthonyBrunelli il n'est pas clair pour moi quelles sont les attentes d'accessibilité de ce bouton. Aujourd'hui c'est le dernier élément du body, donc peut-être moins accessible à un lecteur d'écran (sauf si les lecteurs d'écran fonctionnent autrement qu'en ordre).
