### ISSUE TITLE
Tableau observatoire: navigation clavier

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#824]
Manque le focus sur les filtres, trier par et version de tableau ("octobre 2019"). Sens de lecture de droite à gauche (inverser serait plus intuitif) 

Note: il semblerait qu'avec Jaws, les deux menus déroulants ministères et publics ne réagissent pas de la même manière au clavier (ce ne sont pas les mêmes flèches qu'il faut actionner). J'ai refait le test en navigation clavier simple, pas noté de problème.

**Comment by lucaa** [comment]
> Sens de lecture de droite à gauche (inverser serait plus intuitif)

S'il s'agit du fait que dans l'ordre du document le selecteur pour la version du tableau est _avant_ les filtres alors que visuellement ce n'est pas le cas, la raison est l'affichage mobile, pour lequel les 2 éléments s'affichent verticalement, et les filtres doivent rester collés au tableau, pas le selecteur de version. Je pense qu'on pourra garder ce comportement sur mobile tout en corrigeant l'ordre sur desktop, mais je trouve que même si on a la place pour l'écran, semantiquement les filtres sont plus liés au tableau que le selecteur de version.

**Comment by AnthonyBrunelli** [comment]
Okey, mais il faudrait un focus clair et visible.

**Comment by AnthonyBrunelli** [comment]
J'ajoute:

Bouton plier/déplier dans le tableau (chevron en bout de  ligne) ni accessible ni activable au clavier.

**Comment by lucaa** [comment]
> Bouton plier/déplier dans le tableau (chevron en bout de ligne) ni accessible ni activable au clavier.

Similaire au #827 , non?

**Comment by AnthonyBrunelli** [comment]
Oups, ah oui...

**Comment by lucaa** [comment]
Du coup, en plus du #827 et #841 et l'histoire de l'ordre clarifié dans les commentaires, il reste des éléments specifiques pour cette tâche ou on peut fermer ?

**Comment by AnthonyBrunelli** [comment]
Okey je ferme. Il reste l'histoire des menus déroulants avec Jaws, mais je referai une fiche dédiée le cas échéant...
