### ISSUE TITLE
Tableau Observatoire: navigation tableau

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#826]
Test avec Jaws: la navigation clavier dans le tableau est compliquée par le fait qu'il n'est pas possible d'aller vers le bas ou vers le haut: il faut aller au bout de chaque ligne pour passer à la suivante.

Il manque le focus sur pour la navigation clavier 'simple'.

**Comment by AnthonyBrunelli** [comment]
...en complément: structurer la page avec des titres entre les différentes parties (par exemple "Filtre et recherche", "Tableau"...). Cela manque pour un non-voyant. Pas forcément besoin que ce soient des titres visibles.

@marineb @georges-bayard @Hatice2020 avis?

**Comment by AnthonyBrunelli** [comment]
Revoir avec Boutié...

**Comment by AnthonyBrunelli** [comment]
Caduc, des actions ont été faites depuis.

**Comment by lucaa** [comment]
> Caduc, des actions ont été faites depuis.

Je pense que la question de la navigation clavier dans le tableau (surtout l'accès à la flèche pour déplier les détails) reste d'actualité mais je pense qu'il y a aussi une autre tâche qui parle de cela.

En tout cas, j'imagine que s'il y aura du travail planifié autour de cela, ça sera suite à un nouvel audit, qui re-decrira les problèmes restants.
