### ISSUE TITLE
Page 404 - Contenu à revoir

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#832]
[en interne Dinum à ce stade] Revoir le contenu de la page 404

![image](https://user-images.githubusercontent.com/35567048/73346900-f3b50880-4286-11ea-96fb-05eb6b8956c8.png)

@georges-bayard @marineb @Hatice2020

**Comment by boutiecamara** [comment]
Exemple de la page de l'erreur 404 sur le site Service Public @AnthonyBrunelli 

Proposition 
"Nous vous invitons à : 
> Retourner sur la page d'accueil
> Consulter l'observatoire du numérique 
> En savoir plus sur nos critères d'évaluation

![Erreur 404 service public](https://user-images.githubusercontent.com/60467340/73645141-02c8fb80-4677-11ea-8843-a081a49fdfc2.PNG)

**Comment by AnthonyBrunelli** [comment]
Sur la page 404:
- Remplacer "Note" par "Erreur 404"
- Remplacer le texte par: "La page n'existe pas ou n'est pas disponible. Nous vous invitions à [retourner sur la page d'accueil](https://observatoire.numerique.gouv.fr/)."
@georges-bayard Ok pour toi? Si oui, à déplacer dans To Do.

**Comment by AnthonyBrunelli** [comment]
@georges-bayard ok pour toi? ça serait bien qu'on embarque ça rapidement...

**Comment by georges-bayard** [comment]
Oui ca me va. @AnthonyBrunelli : c'est nous qui avons la main en paramétrage ?

**Comment by AnthonyBrunelli** [comment]
Ah tiens, j'aurais préféré que non, mais oui @georges-bayard , on a la main.

@lucaa 'lut, on peut modifier la page 404 sans faire sauter le bouzin?

**Comment by AnthonyBrunelli** [comment]
Salut @lucaa J'ai regardé pour modifier la page 404 mais je ne crois pas que je puisse faire quoi que ce soit. Je peux ajouter du contenu mais a priori pas modifier "Note" et ce qu'il y a en dessou...

**Comment by AnthonyBrunelli** [comment]
@lucaa point assez important.

**Comment by lucaa** [comment]
> J'ai regardé pour modifier la page 404 mais je ne crois pas que je puisse faire quoi que ce soit. Je peux ajouter du contenu mais a priori pas modifier "Note" et ce qu'il y a en dessou...

Oui, c'est à moi de le faire.

**Comment by lucaa** [comment]
Sur l'écran 404, en fonction de l'entité qui n'a pas été trouvé, il est possible que des suggestions soient affichées - ce n'est pas le cas dans l'exemple initial de cette issue car il n'y avait aucune suggestion pour l'URL en question:
![image](https://user-images.githubusercontent.com/657716/83780476-7d3d7280-a68d-11ea-8009-7405a6fcb640.png)

Est-ce que ces suggestions doivent rester ou pas?

**Comment by lucaa** [comment]
> Remplacer le texte par: "La page n'existe pas ou n'est pas disponible. Nous vous invitions à retourner sur la page d'accueil."

À noter que, pour le cas ou le document n'est pas disponible (car pas de droits d'accès) il y a un autre écran et un autre code HTTP (403, de mémoire).

**Comment by lucaa** [comment]
J'ai mis à jour le titre et le message, sans toucher aux suggestions de pages pour l'instant. À reprendre s'il faut changer d'autres messages.

**Comment by AnthonyBrunelli** [comment]
Ok pour tout @lucaa sauf que si je prends cet exemple, je ne comprends pas les suggestions:

https://observatoire.numerique-staging.devxwiki.com/fef

Ce ne sont pas des pages privées? En tout cas, il me semble mieux de supprimer les suggestions. @ugodtn @georges-bayard un avis? (et désolé de ne pas avoir répondu avant)

**Comment by AnthonyBrunelli** [comment]
Résidu traité dans #924.
