### ISSUE TITLE
Page Graphique - Alternative vocale pour "?"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#833]
Le lecteur vocal ne lit que "lien" lorsqu'il passe sur le "?"

![image](https://user-images.githubusercontent.com/35567048/73348107-16482100-4289-11ea-9b9e-6f82b17d297f.png)

**Comment by slauriere** [comment]
Le titre du lien est également présent dans le contenu du lien en sr-only, cela dévrait résoudre le problème.
