### ISSUE TITLE
Page d'accueil - Titre de la page dans l'onglet

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#834]
[En interne Dinum à ce stade @marineb @georges-bayard @Hatice2020 ]

Le titre de la page d'accueil - celui qui apparaît dans l'onglet - n'indique que le nom du site:

![image](https://user-images.githubusercontent.com/35567048/73348516-dafa2200-4289-11ea-81be-8d0778be3e98.png)

Il faudrait rajouter un truc du style "Accueil" non? 

J'ai regarder ce que font les autres, voici quelques exemples:

![image](https://user-images.githubusercontent.com/35567048/73348612-f9f8b400-4289-11ea-9467-798c709b7208.png)

![image](https://user-images.githubusercontent.com/35567048/73348631-00872b80-428a-11ea-837b-b649139ec0d2.png)

![image](https://user-images.githubusercontent.com/35567048/73348644-067d0c80-428a-11ea-9b35-d992f9eb5031.png)

![image](https://user-images.githubusercontent.com/35567048/73348656-0da41a80-428a-11ea-9846-6588577e5013.png)

Une préférence?

**Comment by lucaa** [comment]
@AnthonyBrunelli l'implémentation courante est censée être celle décrite par #51 et #63 .
S'il y a des pages sur lesquelles la régle n'est pas respectée (e.g. observatoire?), c'est un bug.

Après, cette situation (bug ou pas bug) n'empeche pas un changement de stratégie (cf. ta question ci-dessus).

**Comment by AnthonyBrunelli** [comment]
Vu avec @georges-bayard : on construit bien le titre/onglet comme les autres, et donc on ajoute "Accueil - " avec le nom du site après (comme sur les autres pages).
@lucaa

**Comment by lucaa** [comment]
Suite à #887 le titre du site à changé, et en consequence le titre de la page d'accueil.
Ainsi, aujourd'hui mon navigateur indique "L’observatoire de la qualité des démarches en ligne" comme titre de l'onglet. Le fait que l'URL s'affiche ou pas après semble être une histoire de navigateur: chrome semble afficher l'URL après sans que l'URL soit écrit explicitement dans le titre du site, alors que Firefox ne l'affiche pas .
Avant on affichait l'URL du site car l'URL était également le nom du site.

Chrome: 
![image](https://user-images.githubusercontent.com/657716/82264471-42d19700-9965-11ea-8dd1-133528e6f96c.png)

Firefox: 
![image](https://user-images.githubusercontent.com/657716/82264516-541aa380-9965-11ea-8730-97522da8d24e.png)

Doit-on encore changer quelque chose pour cette tache?

**Comment by AnthonyBrunelli** [comment]
Doublon #956 je ferme
