### ISSUE TITLE
Page Accessibilité - Revoir le contenu de la page

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#837]
[en interne Dinum à ce stade @marineb @georges-bayard @Hatice2020 ]

Revoir le contenu de la page, notamment supprimer "Pour cette première version, nos efforts ont porté sur l'utilisabilité des formulaires."

**Comment by AnthonyBrunelli** [comment]
@georges-bayard @marineb @Hatice2020 @boutiecamara 

Pour faire vite, on pourrait copier-coller ce qui est écrit sur la page "Accessibilité" de numerique.gouv.fr : https://www.numerique.gouv.fr/accessibilite/

On remplace juste RGAA 3 par 4.

**Comment by AnthonyBrunelli** [comment]
@lucaa 'lut! On a revu ça avec @georges-bayard : on est ok pour la reprise du contenu de la page https://www.numerique.gouv.fr/accessibilite/ en remplaçant RGAA 3.0 par RGAA 4.0.

On a contrôlé: Georges n'a pas les droits pour procéder aux modifs. Tu peux ou les lui donner, ou faire les modifs, stp?

**Comment by lucaa** [comment]
S'il s'agit de la page https://observatoire.numerique.gouv.fr/Main/Accessibilite , il n'y a aucune raison pour laquelle l'utilisateur de @georges-bayard n'aie pas de droits de modification dessus... Il ne voit pas le bouton "Modifier" sur cette page ou il se passe quelque chose inattendu quand il clicke dessus?
Peux-tu ajouter des captures d'écran?

**Comment by AnthonyBrunelli** [comment]
@georges-bayard C'est pour toi...

**Comment by georges-bayard** [comment]
oui je m'aperçois que je peux le faire en fait. Mais toit aussi avec tes droits tu peux le faire @AnthonyBrunelli . Tu t'en occupes ?

**Comment by AnthonyBrunelli** [comment]
@georges-bayard Je ne crois pas avoir les droits. En tout cas pas de bouton "Modifier"...

![image](https://user-images.githubusercontent.com/35567048/74459931-6380e100-4e8c-11ea-884b-a764083174cf.png)

**Comment by georges-bayard** [comment]
Ok je viens de te donner des droits d'administrateur groupe

**Comment by AnthonyBrunelli** [comment]
Grazie. Fatto. Chiudo.
