### ISSUE TITLE
Page CGU - Remplacer Dinsic par Dinum

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#838]
Sur la page, remplacer DINSIC par DINUM et Direction interministérielle du numérique et du système d'information et de communication de l'État par Direction interministérielle du numérique.

**Comment by lucaa** [comment]
@AnthonyBrunelli la page peur être modifiée directement en production, j'ai assigné à Georges.

**Comment by lucaa** [comment]
en même temps, je peux le faire aussi, le remplacement est simple, il n'y a pas de textes à valider.

**Comment by AnthonyBrunelli** [comment]
C'est corrigé
