### ISSUE TITLE
Page "Comment donner votre avis sur une démarche ?"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#839]
XWiki: visiblement ce n'est plus la même version sur le staging et en prod... Une MAJ à effectuer?
https://observatoire.numerique-staging.devxwiki.com/Aide/Donner%20son%20avis

Interne Dinum @marineb @Hatice2020 @georges-bayard  : Ne faut-il pas rendre cette page plus visible?

**Comment by AnthonyBrunelli** [comment]
(il n'y a qu'un lien dans un texte dans un encadré en page d'accueil)

**Comment by lucaa** [comment]
@AnthonyBrunelli j'ai mis à jour tous les pages du staging avec leur versions de production

**Comment by AnthonyBrunelli** [comment]
Vu avec Georges: on ferme.
