### ISSUE TITLE
Page "Comment donner son avis" - Manque les alt aux images

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#843]
Il manque les alternatives textuelles aux images. J'imagine que les textes sont à fournir... On voit ça. @Hatice2020 @georges-bayard @marineb

**Comment by AnthonyBrunelli** [comment]
Vu dans le cadre de l'audit accessibilité.

"Les deux captures d'écran n'ont pas une alternative pertinente. 
1) Pour la première, la valeur de l'attribut alt doit être : ""Dans la première étape du formulaire, l'utilisateur peut donner son avis sur la démarche via trois boutons : pas bien, moyen, très bien."" 
2) Pour la deuxième : ""Dans la seconde étape, l'utilisateur peut donner plus de détails via des questions plus précises sur l'utilisation de la démarche."""

**Comment by lucaa** [comment]
@AnthonyBrunelli tu peux faire les modifications directement en production aussi, comme pour https://github.com/DISIC/wikidemarches/issues/981#issuecomment-875126627 .

**Comment by AnthonyBrunelli** [comment]
Ok, c'est fait aussi. @amezyane tu peux contrôler en prod si tu veux et mettre à jour le fichier de suivi si c'est bon poru toi!

**Comment by amezyane** [comment]
@AnthonyBrunelli Attention, dans la 2e image, il manque un mot dans l'alternative : "Dans la seconde étape, l'utilisateur peut répondre **à** **questions** plus précises sur son utilisation de la démarche."

**Comment by AnthonyBrunelli** [comment]
Corrigé merci!

**Comment by amezyane** [comment]
Validé en prod et audit MAJ
