### ISSUE TITLE
Page secrète: Comment intégrer le bouton MonAvis

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#844]
https://observatoire.numerique-staging.devxwiki.com/Aide/Int%C3%A9gration%20du%20bouton%20MonAvis

[En interne Dinum à ce stade @georges-bayard @Hatice2020 @marineb ]

Comment accède-t-on à cette page en navigation, dans l'arbo? Je l'ai trouvée à partir d'une page 404, Boutié a réussi autrement mais compliqué...

NB: il manque les alt aux images.

**Comment by AnthonyBrunelli** [comment]
NB bis: structuration à revoir: on a un 2b sans 2a...

**Comment by georges-bayard** [comment]
[Fiche de récupération du bouton sur MonAvis3.docx](https://github.com/DISIC/wikidemarches/files/4133534/Fiche.de.recuperation.du.bouton.sur.MonAvis3.docx)

**Comment by boutiecamara** [comment]
[Critères Cerfa Numérique_V2.docx](https://github.com/DISIC/wikidemarches/files/4147220/Criteres.Cerfa.Numerique_V2.docx)

Les remarques sont sur le document  @AnthonyBrunelli

**Comment by AnthonyBrunelli** [comment]
[Page comment intégrer le bouton mon avis.pdf](https://github.com/DISIC/wikidemarches/files/4413420/Page.comment.integrer.le.bouton.mon.avis.pdf)

**Comment by AnthonyBrunelli** [comment]
@georges-bayard ça ne serait pas intéressant que refasse vite cette page et qu'on la mette quelque part pour que ça soit plus facile pour toi à communiquer? + on pourra la mettre à jour au fil de l'eau en fonction des évol... Enfin, ne faut-il pas la voir aussi avec Ugo? PI, dans le dernier commentaire de Boutié, des suggestions de corrections...

**Comment by AnthonyBrunelli** [comment]
(note pour moi-même: on pourrait travailler sur une version partagée sur Zoho)

**Comment by georges-bayard** [comment]
oui on peut s'en reparler dans la journée. Le sujet à mon avis c'est ou la mettre visible des porteurs de démarche seulement

**Comment by georges-bayard** [comment]
ca m'intéresserait de voir comment ugo voit l'intégration parceque je ne vois pas du tout perso. le sujet c'est de présenter l'info quand le porteur de démarche en a besoin

**Comment by AnthonyBrunelli** [comment]
L'idée ici c'est de faire les modifs rapides (c'est fait je crois par Boutié), et de placer ça qq part pour que tu n'aies plus qu'à communiquer l'URL. À toi @georges-bayard de voir ton cas d'usage: veux-tu élargir le message ou pas? T'adresses tu à des personnes ayant déjà le profil porteur de démarche ou non? si non, ne faut-il pas intégrer cette aspect? à mon avis, à ce stade, faut voir la victoire rapide ou laisser tomber pour l'instant...

**Comment by georges-bayard** [comment]
on pourrait mettre le lien dans le mail de notification pour la création du compte mais je ne suis pas convaincu. Faudrait plutôt une entrée sur la homepage à mon sens

**Comment by AnthonyBrunelli** [comment]
@ugodtn on aimerait échanger sur ça - a priori à mettre après authentification. Voir où et voir s'il faut encore revoir la page.

**Comment by AnthonyBrunelli** [comment]
@lucaa L'idée ce serait pour faire simple de garder cette page 'secrète' mais de l'afficher dans le menu Admin comme ça Georges peut la retrouver (et la modifier le cas échéant) facilement ET envoyer l'URL à ces interlocuteurs. Plus le mettre le menu Admin ministériel, menu Administrer les données, sous Démarches avis (pas de modif pour tout profil autre que Admin Dinum). 
ça te semble facile?
