### ISSUE TITLE
Observatoire - Vocalisation des entêtes de lignes

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#846]
[NB: Retour Alain:
"Au niveau des entêtes du tableau, le problème est structurel. Avec NVDA, seuls la liaison entêtes de colonne /cellule est vocalisée. 
Le problème, c’est la liaison entêtes de ligne /cellule. L’utilisateur, tel que le tableau est structuré, ne sait pas à quelles démarches est liée la valeur de la cellule.  C’est très pénalisant."]

Effectivement, les entêtes de ligne ne sont pas vocalisés. L'utilisateur aveugle ne peut donc pas savoir à quelle démarche renvoie le contenu de la cellule, sauf à naviguer horizontalement à chaque fois.

**Comment by lucaa** [comment]
à priori ça marchera d'implementer le tableau comme ça: https://www.w3.org/WAI/tutorials/tables/two-headers/ , non?

Il faut juste que je trouve comment faire cela avec datatables...

**Comment by AnthonyBrunelli** [comment]
La source me semble fiable :)
Au-delà de ça... On est looooin de mon domaine de compétence. Tu as besoin que je demande une confirmation?

**Comment by lucaa** [comment]
@AnthonyBrunelli si pas trop embêtant.
Le mieux c'est un exemple de bon tableau, comme ça je pourrai comparer le comportement du lecteur d'écran.

**Comment by AnthonyBrunelli** [comment]
On  m'a conseillé de t'envoyer ça:
voir scampi http://pidila.gitlab.io/scampi/documentation/tables.html

ça conviendrait?

**Comment by lucaa** [comment]
L'exemple qui est lu correctement par le lecteur est celui de la section "Effet au survol", j'imagine?

**Comment by lucaa** [comment]
@slauriere peux-tu étudier la possibilité d'avoir une structure avec des éléments th pour les noms des démarches pour le tableau de l'observatoire?

**Comment by AnthonyBrunelli** [comment]
Promemoria au cas où: Les intitulés d’activation du tri sur chaque colonne sont en anglais

**Comment by slauriere** [comment]
D'après les indications du W3C WAI et de Pidila ci-dessus (section "Effet au survol"), les entêtes de ligne doivent utiliser la balise `th` avec l'attribut `scope="row"`, par exemple : 

```
<tr>
      <th scope="row">2</th>
      <td>Marseille</td>
      <td>Bouches-du-Rhône</td>
      <td>Provence-Alpes-Côte-d'Azur</td>
      <td>862 211</td>
</tr>
```
Les entêtes de ligne ont à présent bien cette structure, je vous laisse vérifier et rouvrir le ticket si besoin !

J'ai créé #992 pour le problème des intitulés d'activation du tri.
