### ISSUE TITLE
Changer le nom de l'onglet "tous les avis" qui prète à conffusion

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#847]
c'est en fait une synthèse des avis sur un an

**Comment by lucaa** [comment]
@georges-bayard quel nom devrait-on donner à cet onglet?
"Détails des avis"
"Indicateurs des avis"
"Statistiques des avis"
?

**Comment by georges-bayard** [comment]
Je propose "Synthèse des avis"

**Comment by lucaa** [comment]
le nom de l'onglet est utilisé aux 2 endroits:
* pour l'utilisateur connecté, sur la page de la démarche comme nom d'onglet: 
![image](https://user-images.githubusercontent.com/657716/82928652-c3eee680-9f82-11ea-921a-787a3f6119a2.png)
* pour un utilisateur invité, sur l'ecran qui affiche les détails des votes pour une démarche (à partir du lien Graphes de l'observatoire):
![image](https://user-images.githubusercontent.com/657716/82928485-9ace5600-9f82-11ea-8386-9c8dd8c9b4ad.png)

Les 2 endroits ont été mises à jour.
