### ISSUE TITLE
Cleanup html structure of the feedback form

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#85]
1: The fields structure should roughly be the same for all fields - either all in individual "div"s or neither
2: all radio questions need to be in a fieldset element, with the question as legend, the other fields need to have only label + input (or textarea)
3: all headings markup needs to be removed (including the role=heading) part

**Comment by slauriere** [comment]
1. Fields structure
All fields have now the following structure:
```
<div class='[container-class-name]'>
  <div[class="field"]>
     [fieldset]
       [legend or label]
         input items
```

I'm wondering where the top `<div>` element of the RadioVoteDisplayer comes from though.

2. Radio questions are all in a fieldset element witht the question as legend. Other fields have only label + input item.
3. All headings markup were removed: both `role="heading"` and `aria-level="2"`

I guess we may consider to include all this markup policy to the standard XWiki form generation process?
