### ISSUE TITLE
Contraste des couleurs de la page de statistiques d'une démarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#851]
Analyse faite par @AnthonyBrunelli , je réprends son commentaire de https://github.com/DISIC/wikidemarches/issues/777#issuecomment-580222123 .

> [...] ok pour le tableau, mais pas pour les graphes derrières pour les textes en gris: intitulés des graphes et textes dans les graphes. Dans le 1er cas, détecté par l'extension WCag contrôle contraste checker, dans le deuxième c'est à l'oeil parce que l'extension ni accède pas.

![Capture de page de stats](https://user-images.githubusercontent.com/35567048/73448435-22071680-4361-11ea-8c90-411ad483396d.png)

> (ne pas oublier les graphes bâton violet en dessous)

**Comment by lucaa** [comment]
@slauriere partout ou j'ai eu besoin de gris sur l'appli j'ai utilisé #666 pour remplacer quasi toute autre nuance, tu peux réutiliser la même.
Si la couleur vient d'un élément de theme de couleurs, discutons pour voir si on change toute la theme de couleurs ou on personnalise sur cette page.

**Comment by slauriere** [comment]
>Si la couleur vient d'un élément de theme de couleurs, discutons pour voir si on change toute la theme de couleurs ou on personnalise sur cette page.

Pour ce qui concerne les libellés hors graphiques, le problème a été réglé dans le cadre de #974 en utilisant la variable de thème existante `@gray-light`. Est-ce bien ok pour toi que nous utilisions cette variable @lucaa ?

Le contraste de l'icône d'aide sera réglé dans le cadre de #975.

Il reste à foncer légèrement les libellés dans les graphiques eux-mêmes (canvas).

**Comment by slauriere** [comment]
Dans les graphiques, la couleur utilisée est `#666` (il s'agit de la couleur par défaut de la librairie ChartJS pour le texte, cf [documentation 2.8.0](https://www.chartjs.org/docs/2.8.0/general/fonts.html)) donc le niveau de contraste avec le fond est correct également -> je clos ce ticket.
