### ISSUE TITLE
Transférer les votes de la démarches 1265 vers la démarche 1946 

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#853]
Rappel contexte : 
La démarche 1946 "Demande de renouvellement du certificat d'immatriculation (carte grise) suite à perte, vol ou détérioration du titre" a été équipé par erreur du bouton généré pour la démarche 1265 « Déclaration de perte ou de vol de certificat d'immatriculation (carte grise) ».
Pour rectifier son erreur l'ANTS a fait le choix de renommer les démarches, la 1946 s'appelant aujourd'hui dans le paramétrage « NE PLUS UTILISER - Demande de renouvellement du certificat d'immatriculation (carte grise) suite à perte, vol ou détérioration du titre » et la 1265 étant renommée en « Demande de renouvellement du certificat d'immatriculation (carte grise) suite à perte, vol ou détérioration du titre ». Ainsi les utilisateurs votants pour la démarche de demande de renouvellement de carte grise voteraient pour la bonne démarche.
Cette méthode n'est pas du tout la bonne car elle a des impacts lourds sur paramétrage et le tableau de bord (versions Excel à modifier, Pingdom à modifier avec des impacts en terme de traçabilité. Une démarche = un numéro d'identifiant qui ne doivent pas changer.
Il convient donc pour corriger réaliser cet ensemble d'opérations dans l'ordre indiqué :
1. Corriger l'intitulé de la démarche 1946 pour qu'elle s'appelle à nouveau "Demande de renouvellement du certificat d'immatriculation (carte grise) suite à perte, vol ou détérioration du titre"  : action DINUM
2. Installer le bouton généré sur la démarche 1946 sur la bonne démarche : action ANTS
3. Transférer les votes de la démarches 1265 vers la démarche 1946 : action XWIKI
4. Corriger l'intitulé de la démarche 1265 pour le faire revenir à son état initial : action DINUM
5. Inactiver la démarche 1265 : DINUM

**Comment by georges-bayard** [comment]
attendre réalisation des actions 1 et 2 pour avancer

**Comment by AnthonyBrunelli** [comment]
Vu avec Georges: on la repasse chez nous.

**Comment by georges-bayard** [comment]
cette action n'est plus nécessaire. J'ai inversé le nom des deux démarches

**Comment by georges-bayard** [comment]
ce n'est plus à faire j'ai fait autrement (interversion des numéros de démarche). A annuler donc

**Comment by lucaa** [comment]
Marquée comme "wontfix" et fermée.
