### ISSUE TITLE
Page secrète : deuxième page d'accueil Obsevatoire

### ISSUE THREAD

**Issue by boutiecamara** [DISIC/wikidemarches#854]
https://observatoire.numerique-staging.devxwiki.com/Home-2/

Est-ce que quelqu'un sait de quoi il s'agit ? (Vu avec @AnthonyBrunelli ) 
@georges-bayard @lucaa

**Comment by lucaa** [comment]
Uniquement sur le staging, n'a pas été et ne sera pas livré en production.
Version de test de l'ancienne page d'accueil de l'observatoire (version avant 4.0).

**Comment by AnthonyBrunelli** [comment]
Okey merci!

**Comment by georges-bayard** [comment]
On peut maintenir en staging ce serait une excellente de mettre cette page en ligne. Je m'oblige perso à envoyer le pas à pas à chaque personne à qui j'ouvre un compte. ca me simplifierait la vie. La seule question à trancher pour moi c'est ou on porrait mettre ce lien

**Comment by AnthonyBrunelli** [comment]
@georges-bayard Chuis pas sûr qu'on parle de la même page...
