### ISSUE TITLE
Observatoire: label pour "Filtres" et "Trier par"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#858]
Associer un label/étiquette à "Filtres" et "Trier par" en haut du tableau de l'Observatoire - pour les lecteurs d'écran et éventuellement sous forme d'info-bulle.

**Comment by lucaa** [comment]
@slauriere tu peux vérifier, stp, s'il est simple de mettre en place ces éléments ou c'est du datatables qui doit être modifié (et donc compliqué)?

**Comment by slauriere** [comment]
Nous avons le contrôle complet sur ces boutons donc pas de problème. 

J'ai ajouté un attribut `title` à ces deux boutons, cela permet d'avoir une infobulle (cf capture ci-dessous). Avec les textes suivants : 
* Filtrer les démarches par ministère, public ou mot clé
* Trier les démarches par indicateur

Également ajouté un attribut `aria-labelledby` au contenu du menu déroulant de tri. 

@AnthonyBrunelli Est-ce que cela répond bien au besoin ? A priori pas nécessaire d'ajouter un `aria-label` puisque les boutons contiennent déjà du texte n'est-ce pas ?

Peut-être faudra-t-il du coup faire de même sur le sélecteur de date et le bouton "En temps réel" pour uniformiser ?

![infobulle](https://user-images.githubusercontent.com/1022195/125926274-2a030112-ed3a-4bb5-a8e8-aca1040644d6.jpg)

**Comment by amezyane** [comment]
@slauriere "Également ajouté un attribut `aria-labelledby` au contenu du menu déroulant de tri." => Ce n'est pas sur le bouton qu'il faut le mettre ?

**Comment by amezyane** [comment]
@slauriere  "Également ajouté un attribut `aria-labelledby` au contenu du menu déroulant de tri." => Normalement il devrait être sur le bouton dans ce cas, et non sur le contenu du menu, à part si un élément m'a échappé

"Peut-être faudra-t-il du coup faire de même sur le sélecteur de date et le bouton "En temps réel" pour uniformiser ?" => Oui il est pertinent de faire la même chose sur le bouton "Avril 2021" pour lui donner un intitulé plus explicite (`aria-label` ou `title`). Tu en penses quoi @lucaa ?

**Comment by slauriere** [comment]
Salut @amezyane, Au sujet du `aria-labelledby` : ma compréhension était que le titre du menu déroulant est celui du bouton, donc que le `aria-labelledby` doit pointer vers le bouton, est-ce que ce n'est pas ça l'idée – comme sur [cet exemple](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html) ?

**Comment by amezyane** [comment]
@slauriere au temps pour moi, c'est effectivement ce qu'il faut faire dans ce cas

**Comment by slauriere** [comment]
Merci @amezyane pour ta confirmation, j'ai aligné le comportement du bouton de sélection de date avec lui des autres, j'espère que c'est ok ainsi sinon dites-moi et j'annulerai.

**Comment by amezyane** [comment]
Validé en prod
