### ISSUE TITLE
Mise à jour des pages explicatives

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#860]
Suite aux différentes modifications, il faut mettre à jour les pages de documentation après la livraison en production de M13.

à modifier:
* mise à jour du nom du critère ressaisie demandée, suite à #852 . Voir les endroits à modifier ici https://github.com/DISIC/wikidemarches/issues/852#issuecomment-580777044 .
* [à compléter avec les autres mises à jour nécessaires]

**Comment by georges-bayard** [comment]
fait
