### ISSUE TITLE
rétabli les tris sur les les colonnes du tableau de bord

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#864]

**Comment by lucaa** [comment]
Le tri par la tête de tableau a été ajouté, avec le comportement suivat:
* dès qu'un tri est effectué par un click sur la tête de tableau, le menu de tri prend la forme suivante (marqué actif, avec un indicateur sur le fait que le critère de tri courant n'est pas dans la liste prédefinie): 
![image](https://user-images.githubusercontent.com/657716/74054821-0645e500-49df-11ea-82ba-3a7ea057ff91.png)

Note: même si le tri par la tête du tableau correspond à une option de tri prédefinie (e.g. usagers satisfait decroissant), le bouton affiche "autre".
