### ISSUE TITLE
Dans l'affichage des statistiques d'une démarche, l'année glissante s'applique pour tous les tableaux de bord, pas uniquement pour le tableau de bord janvier 2020

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#865]
Par exemple, pour la démarche "Déclaration impôt sur le revenu" du tableau de bord octobre 2019.
Dans l'observatoire:
![image](https://user-images.githubusercontent.com/657716/74105357-61054b00-4b5d-11ea-86f1-3c353ba5246e.png)

En cliquant sur le lien Graphes:
![image](https://user-images.githubusercontent.com/657716/74105372-6febfd80-4b5d-11ea-9e69-b7d785d8494b.png)

La différence (de pourcentage et de nombre d'avis) vient du fait que dans l'écran des statistiques, la période pour laquelle les stats sont caculés c'est l'année glissante jusqu'a la date de l'observatoire.

**Comment by lucaa** [comment]
Problème résolu et correctif installé en production.

**Comment by georges-bayard** [comment]
@lucaa  : peut tu nous rafaraichir la mémoire ? l'année glissante a t'elle été implémentée oui ou non ?

**Comment by lucaa** [comment]
> @lucaa : peut tu nous rafaraichir la mémoire ? l'année glissante a t'elle été implémentée oui ou non ?

Oui, elle a été implémentée (voir #800) , au moins pour les liens vers les statistiques provenant des tableaux de bord. 
La tâche encore ouverte #748 est pour auditer les parcours utilisateurs et vérifier que l'année glissante est prise en compte partout, mais sur l'observatoire l'année est prise en compte.
