### ISSUE TITLE
Question : Format des données à charger

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#868]
'lut @lucaa !

Il faut que **de notre côté** on s'organise mieux et on s'outille pour le suivi, l'ajout et la modification des démarches, etc. En gros, il nous faut trouver un système de base de données partageable, facile à mettre à jour, intuitive, exhaustive, et incluant des infos qui n'apparaissent pas dans l'Observatoire...

Est-ce que **de ton côté** tu peux me préciser quel doit être le *format* des données pour qu'elles puissent être chargées dans l'appli? Quelles *données* doivent être présentes précisément?

PI @georges-bayard @Hatice2020 @marineb @boutiecamara

**Comment by AnthonyBrunelli** [comment]
...et au passage, une 2ème question: as-tu un plan du site, notamment lorsqu'on est connecté en tant qu'administration?

**Comment by lucaa** [comment]
@AnthonyBrunelli je pense que le mieux c'est de se parler pour répondre à ça ?
Aujourd'hui l'appli peut charger des données à partir des fichiers de type spreadsheet (CSV, excel), et aucune donnée n'est obligatoire. Par contre, si des données sont importées, elles doivent potentiellement respecter certains formats (par exemple pour les propriété à choix parmi une liste, les valeurs du fichier à importer doivent respecter certains formats pour que lors de l'import la valeur de la liste est correctement importée).
Une documentation des méta-données et de leurs formats a été faite ici https://observatoire.numerique.gouv.fr/Aide/Description%20du%20mod%C3%A8le%20de%20donn%C3%A9es , mise à jour la dernière fois pour la tache #574 (Juin 2019). Il y eu quelques modifications depuis, mais pas majeures.

**Comment by lucaa** [comment]
> ...et au passage, une 2ème question: as-tu un plan du site, notamment lorsqu'on est connecté en tant qu'administration?

As a logged in user (admin dinsic or admin ministerial) there is a list of sections on the bottom of the homepage, "Administrez les données".

**Comment by AnthonyBrunelli** [comment]
> 
> 
> @AnthonyBrunelli je pense que le mieux c'est de se parler pour répondre à ça ?
> Aujourd'hui l'appli peut charger des données à partir des fichiers de type spreadsheet (CSV, excel), et aucune donnée n'est obligatoire. Par contre, si des données sont importées, elles doivent potentiellement respecter certains formats (par exemple pour les propriété à choix parmi une liste, les valeurs du fichier à importer doivent respecter certains formats pour que lors de l'import la valeur de la liste est correctement importée).
> Une documentation des méta-données et de leurs formats a été faite ici https://observatoire.numerique.gouv.fr/Aide/Description%20du%20mod%C3%A8le%20de%20donn%C3%A9es , mise à jour la dernière fois pour la tache #574 (Juin 2019). Il y eu quelques modifications depuis, mais pas majeures.

Okey, on se parle quand? Tu es dispo demain?

**Comment by lucaa** [comment]
@AnthonyBrunelli j'ai mis à jour la page https://observatoire.numerique.gouv.fr/Aide/Description%20du%20mod%C3%A8le%20de%20donn%C3%A9es avec ce qu'on a vu ce matin.
J'ai mis en jaune les méta-données utilisées pour le critères de l'observatoire, et indiqué clairement le critère pour lequel la méta-donnée est utilisée.

**Comment by AnthonyBrunelli** [comment]
Ok merci :)

**Comment by AnthonyBrunelli** [comment]
Comme il y a eu changement d'outil (passage de Zoho à AirTable), ce point est à revoir. En attente de stabilisation de AirTable de notre côté. Pour info @lucaa

**Comment by lucaa** [comment]
Suite à la discussion, ce besoin a été exprimé et discuté, le travail qui reste faire est exprimé sous la forme de la tache #871 .
Je vais donc fermer celle ci comme un doublon, le reste du travail qui est a faire (c'est à dire s'assurer que l'import fonctionne avec le nouvel outil) est couvert par #871 .
