### ISSUE TITLE
Avis form validation

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#87]
We should implement some sort of validation (don't save without the mandatory fields filled in).

**Comment by lucaa** [comment]
The validation will be implemented in 2 ways: 
* actual prevention of save without full data
* disabling the save button as long as the mandatory fields are not filled in

**Comment by lucaa** [comment]
> disabling the save button as long as the mandatory fields are not filled in
was done. 

The rest remains to be done. However, if it occurs, we can easily find the Avis that are missing method or notation.
