### ISSUE TITLE
Typo dans le message de confirmation d'activation de compte

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#870]
Le texte dit:
"Votre compte sur le site [...] a été activé avec succès. Vous pouvez **à présenter** vous identifier à l'adresse ci-dessous"

**Comment by lucaa** [comment]
C'est corrigé, mais pas encore en production.

**Comment by lucaa** [comment]
C'est fait en staging et production également.

**Comment by AnthonyBrunelli** [comment]
@georges-bayard une idée de comment recetter ça?

**Comment by georges-bayard** [comment]
ben inscris toi en prod avec une adresse mail perso je te valide et tu regardes le mail de confirmation
