### ISSUE TITLE
Mise à jour de la configuration d'import suite au transfer du fichier Excel sur une platforme collaborative en ligne

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#871]
Le fichier Excel à partir duquel l'import de donnée est réalisé à été transféré vers une plateforme collaborative en ligne.
Suite à ce transfer, quelques paramètres de l'import peuvent changer. Cette tache est pour le mise à jour de l'import pour le rendre compatible.

**Comment by AnthonyBrunelli** [comment]
'lut @lucaa 
PI, ça a avancé, j'ai mis les colonnes manquantes, j'attends une validation de Georges mais on y est presque. Je vais t'envoyer une nouvelle copie du document pour en rediscuter...

**Comment by AnthonyBrunelli** [comment]
(si tu ne reçois pas le lien vers la nouvelle version, tu me dis...)

**Comment by AnthonyBrunelli** [comment]
...et je viens de voir ça https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M14/Import%20Zoho/ que je n'ai pas encore pris en compte. Je vois pour les modifs...

**Comment by georges-bayard** [comment]
Je regarde aujourd'hui

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

-------- Message original --------
De : Anthony Brunelli <notifications@github.com<mailto:notifications@github.com>>
Date : ven. 27 mars 2020 à 08:53
À : DISIC/wikidemarches <wikidemarches@noreply.github.com<mailto:wikidemarches@noreply.github.com>>
CC : Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Objet : Re: [DISIC/wikidemarches] Mise à jour de la configuration d'import suite au transfer du fichier Excel sur une platforme collaborative en ligne (#871)

'lut @lucaa<https://github.com/lucaa>
PI, ça a avancé, j'ai mis les colonnes manquantes, j'attends une validation de Georges mais on y est presque. Je vais t'envoyer une nouvelle copie du document pour en rediscuter...

**Comment by AnthonyBrunelli** [comment]
@lucaa J'ai fait une nouvelle version avec les infos dont tu as besoin pour l'export sur l'onglet 'démarche'. J'ai partagé une copie (la n°3 donc) avec toi, que tu peux martyriser si tu veux.

**Comment by AnthonyBrunelli** [comment]
@lucaa ...pause jusqu'à lundi, Zoho nous semble instable, on va étudier autre chose...

**Comment by lucaa** [comment]
@AnthonyBrunelli j'ai reçu le lien Zoho, je vais regarder ça lundi (ou dès que Zoho reprend des forces).

**Comment by lucaa** [comment]
> ...et je viens de voir ça https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M14/Import%20Zoho/ que je n'ai pas encore pris en compte. Je vois pour les modifs...

Ce document contient ce qu'on s'était dit la dernière fois au téléphone, il devrait pas y avoir des nouveautés.

**Comment by AnthonyBrunelli** [comment]
> 
> 
> > ...et je viens de voir ça https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M14/Import%20Zoho/ que je n'ai pas encore pris en compte. Je vois pour les modifs...
> 
> Ce document contient ce qu'on s'était dit la dernière fois au téléphone, il devrait pas y avoir des nouveautés.

Oui, c'est vu et pris en compte (on verra si pour rien ou pas si on change de solution)

**Comment by AnthonyBrunelli** [comment]
@lucaa Comme indiqué par ailleurs, la solution Zoho n'a pas été retenue. Je laisse ouvert car la problématique reste d'actualité avec une autre tentative avec un autre outil.

**Comment by lucaa** [comment]
Les modifications de la configuration d'import et du traitement des données lors de l'import ont été faites, le reste du travail necessaire (lié à la gestion de l'affichage), sera fait dans #886.

**Comment by lucaa** [comment]
TODO: ajouter une liste des modifications qui ont été faites.
