### ISSUE TITLE
Augmenter l'utilisabilité de  l'écran de lecture des avis 

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#876]
- Faciliter l'usage des filtres, avec des listes déroulantes (si possible à choix multiples)
- Pouvoir appliquer des tris sur plusieurs colonnes simultanément
- Ne plus contraindre la largeur du tableau à la largeur de la page, permettre le scroll horizontal
- Augmenter les largeurs des colonnes de texte libre (x4)
- Déplacer la colonne verbatim entre les colonnes "satisfaction" et "facilité"

**Comment by AnthonyBrunelli** [comment]
(pour l'avoir vu par ailleurs: il ne faut pas que le scroll horizontal ne soit possible qu'en ayant fait un scroll vertical jusqu'en bas... :) )

**Comment by AnthonyBrunelli** [comment]
Vu avec @georges-bayard : @ugodtn va faire une maquette (comme c'est chez nous, je déplace la fiche).

**Comment by AnthonyBrunelli** [comment]
Vu avec @ugodtn Pas de maquette mais traitable en l'état.

**Comment by lucaa** [comment]
Note pour moi-même: il faut découper cette tache en plusieurs taches individuelles pour chaque amélioration.

**Comment by lucaa** [comment]
Priorités: 
* Déplacer la colonne verbatim entre les colonnes "satisfaction" et "facilité"
** Colonnes de taille fixe, non-adaptées au contenu
* Ne plus contraindre la largeur du tableau à la largeur de la page, permettre le scroll horizontal

**Comment by lucaa** [comment]
Après discussions, l'item 

> Faciliter l'usage des filtres, avec des listes déroulantes (si possible à choix multiples)

rentre aussi dans les priorités.

Donc, la tache entière reste à faire,  sauf 
> Pouvoir appliquer des tris sur plusieurs colonnes simultanément .

**Comment by lucaa** [comment]
Une première couche d'améliorations a été faite, ainsi:
* la police du tableau a été baissé à 81.25% de la police de la page pour faire un peu plus de place dans la page: ~13px pour une police de la page à 16px. Pour moi ça reste lisible, mais je prends du feedback.
  * les têtes des colonnes sont encore plus petites, à 11.7px , car très longues par rapport à leur contenu
* le tableau lui même a été agrandi à 1404px largeur minimale, avec un scroll horizontal en bas du tableau, et les colonnes ont été proportionnées ainsi, de manière fixe (même s'il n'y a pas le contenu pour remplir ces tailles, les tailles sont gardées):

|Colonne(s)|Taille|Taille en em
Date, Id, Satisfaction | 5.9% chacune | 7em
Verbatim | 17% | 20em
Facilité, Simplicité | 5.1% | 6em
Difficulté, Autre difficulté, Aide, Autre aide | 12.7% chacune | 15em
Source | 4.3% | 5em

* Les proportions des colonnes ont été choisies pour donner aux colonnes avec des valeurs de longueur fixe la place minimale nécessaire pour accueillir leurs contenus et laisser tout le reste de place disponible pour les colonnes contenant du texte.
* La taille de 1404px a été choisie pour pouvoir agrandir la largeur horizontale de cette page à la même largeur que celle de l'observatoire (si on décide de le faire) et d'avoir comme résultat, dans ce  cas, un tableau sans scroll (l'observatoire est a 1410px).

**Comment by lucaa** [comment]
> (pour l'avoir vu par ailleurs: il ne faut pas que le scroll horizontal ne soit possible qu'en ayant fait un scroll vertical jusqu'en bas... :) )

@AnthonyBrunelli c'est pas très très clair pour moi ce que ça veut dire: est-ce que tu parles de la possibilité d'avoir la barre de scroll en haut du tableau ou du fait que le scroll devrait coller au bas du tableau, et pas être repoussé tout en bas de la page entière?
Ce que j'ai fait là c'est de coller le scroll du tableau au tableau strictement, ainsi:
![image](https://user-images.githubusercontent.com/657716/83399581-bfeb1a80-a401-11ea-8dca-dd266f3ff5a3.png)
mais bouger la barre de scroll en haut du tableau est assez complexe à faire, je préfère plutôt agrandir la taille de la page à 100% de l'écran pour éviter le scroll.

**Comment by lucaa** [comment]
Les filtres des colonnes "Satisfaction", "Facilité" et "Simplicité" ont été également mis à jour pour utiliser des listes deroulantes à la place des champs de filtre libre. Le visuel de tous les filtres de type liste déroulante a été amélioré pour ressembler aux filtres de l'observatoire.
Fonctionnellement, une seule valeur peut être choisie à la fois pour une colonne filtrée, mais plusieurs colonnes peuvent être filtrées en même temps (dans quel cas les lignes affichées sont celles qui satisfont les filtres de tous les colonnes filtrées). S'il est nécessaire de pouvoir choisir plusieurs valeurs pour un filtre pour la même colonne, une nouvelle tâche devrait être ouverte.

Visuellement, la tête de ce tableau peut être améliorée de manière significative, à créer une nouvelle tâche si on veut explorer cette possibilité.

**Comment by lucaa** [comment]
Les besoins de la liste initiale ont été faits (à part "Pouvoir appliquer des tris sur plusieurs colonnes simultanément" qui a été abandonné), donc la tâche peut être fermée.

**Comment by AnthonyBrunelli** [comment]
@georges-bayard Je ne trouve plus comment accéder aux avis. Me faut-il être un porteur de démarche?

**Comment by AnthonyBrunelli** [comment]
Merci Georges pour les droits.

@lucaa 'lut! Voilà ce que j'essayais d'expliquer: le tableau s'adapte à la largeur de l'écran dans une certaine limite; si toutes les colonnes sont renseignées, le tableau finit par dépasser la largeur de l'écran et on n'accède plus à la dernière colonne ET on n'a pas la barre de défilement horizontale (il faut descendre, pas très ergonomique):

![image](https://user-images.githubusercontent.com/35567048/84015916-d56dc080-a97c-11ea-8bb1-be535c7d4a3d.png)

**Comment by AnthonyBrunelli** [comment]
en complément: je ne sais pas à quoi sert la colonne "ID de session" concrètement, mais en masquant cette info ça devrait résoudre le problème.

**Comment by georges-bayard** [comment]
j'ai une nouvelle page qui ressemble à ce qui a été commandé : 
![image](https://user-images.githubusercontent.com/17125654/84029825-5041d600-a993-11ea-9a78-fce26489d193.png)

**Comment by georges-bayard** [comment]
sur l'id de session je pense que c'est important de le garder. C'est un id généré pour distinguer le vote d'un utilisateur au cours d'une session de navigation. Ca permet de repérer les usagers qui votent plusieurs fois au cours d'une même session. Je pense que c'est très importat de la garder à disposition dans la page pour effectuer des contrôles sur le sujet du multi vote. @lucaa qu'en penses tu ? 
je suis pour qu'on le remette même en mode discret c'est à dire tout à droite

**Comment by lucaa** [comment]
Il faut clarifier ce qui semble être une confusion assez importante.
Il y a 2 modalités d'accès aux avis de la plateforme:
1/ par le bouton "Avis" qui s'affiche sur la page d'accueil, accessible uniquement aux administrateurs Dinum, à l'adresse https://observatoire.numerique-staging.devxwiki.com/Avis/ . Ce tableau affiche les avis de _toutes les démarches_, aux administrateurs Dinum qui ont accès aux avis de toutes les démarches.
2/ par l'onglet "Liste des avis" d'une démarche, accessible aux utilisateurs ayant le droit de voir les avis de la démarche en question: le porteur et les administrateurs ministeriels de la même direction que la démarche (cf. #901). Bien évidemment, cet accès est également disponible aux administrateurs Dinum.

L'écran identifié par @AnthonyBrunelli correspond à l'accès no. 1, l'écran envoyé par Georges correspond à l'accès no. 2. Dans le cadre de cette tache et itération, des modifications ont été faites uniquement pour l'accès no 2., car c'est le seul accessible aux porteurs / administrateurs min. hors Dinum et ma comprehension est que c'est l'accès de ces profiles d'utilisateurs qu'on essaye d'améliorer.

Maintenant, l'accès no. 1 est beaucoup plus technique et complet que l'accès no. 2. Notamment, il affiche l'id de session, un lien direct vers la fiche complète de l'avis, un filtre par démarche, des actions pour un avis, et d'autres détails qui ne sont pas forcement comprehensible pour un utilisateur "normal".
L'accès no. 2 est plus contrôlé, on vérifie plus les informations qu'on affiche dessus, on ne donne pas accès direct à la fiche complète de l'avis (contenant tous les informations techniques, etc).

**Comment by lucaa** [comment]
> Je pense que c'est très importat de la garder à disposition dans la page pour effectuer des contrôles sur le sujet du multi vote. @lucaa qu'en penses tu ?
> je suis pour qu'on le remette même en mode discret c'est à dire tout à droite

Du coup, avec ma clarification ci-dessus, il faut mentionner de quel "page" il s'agit? L'accès aux avis no. 1 ou no. 2 ?

**Comment by lucaa** [comment]
> si toutes les colonnes sont renseignées, le tableau finit par dépasser la largeur de l'écran et on n'accède plus à la dernière colonne ET on n'a pas la barre de défilement horizontale (il faut descendre, pas très ergonomique):

Ok, je vois (et même si ce commentaire est pour le tableau de l'écran de l'accès admin dinum, le problème de scroll est exactement le même pour le tableau de l'accès porteur de démarche).
Par contre, je ne comprends pas vraiment si tu as une proposition d'alternative? As-tu un exemple de défilement (pour un tableau ou autre element) plus ergonomique ou plus proche de ce que tu t'attends à avoir pour ce tableau? (j'ai cherché si c'est possible de mettre la barre de défilement en haut d'un conteneur, cela ne semble pas exister). Je pense que le plus facile est de s'appeler, je suis dispo toute la journée demain.

**Comment by georges-bayard** [comment]
@lucaa j'ai effectivement fait une confusion entre les deux écrans je retire ma proposition sur l'ajout de l'identifiant

**Comment by AnthonyBrunelli** [comment]
@lucaa Ok merci pour l'explication, il y avait effectivement une confusion de mon côté entre les deux pages. 
Pour le scroll, on ne peut pas l'avoir figé en bas d'écran?
Possibilité d'avoir un filtre pour les verbatims et sortir les avis sans verbatim par exemple?
@ugodtn On revoit ça ensemble?

**Comment by AnthonyBrunelli** [comment]
@lucaa 
Nos retours:
- Pour le scroll, on ne peut pas l'avoir figé en bas d'écran (sauf si le tableau est plus haut que le bas de l'écran). 
- Filtres: S'il est nécessaire de pouvoir choisir plusieurs valeurs pour un filtre pour la même colonne, une nouvelle tâche devrait être ouverte: ok on va faire ça.
- Ça rame, ça bloque, pas recettable sur staging

**Comment by lucaa** [comment]
> Filtres: S'il est nécessaire de pouvoir choisir plusieurs valeurs pour un filtre pour la même colonne, une nouvelle tâche devrait être ouverte: ok on va faire ça.

La tâche #912 a été créée pour cette amélioration.

**Comment by lucaa** [comment]
> pouvoir filtrer les avis avec verbatim rempli pour éliminer de l'extraction les avis sans verbatim. NB : on doit pouvoir continuer à faire des recherches textuelles dans les verbatim

tâche #917 créée pour cette fonctionnalité.

**Comment by lucaa** [comment]
j'ai créé #918 pour le defilement en bas de l'écran, avec des captures de ce à quoi doit rassembler.

**Comment by lucaa** [comment]
> élargir les champ verbatim, difficultés et autres difficultés (x1,5)
tache #919 .

Tous les retours de cette tâche ont été dirigées vers des tâches indépendantes. Il reste à mettre une ordre des priorités entre ces améliorations.

**Comment by AnthonyBrunelli** [comment]
Okey
