### ISSUE TITLE
Ouvrir l'extraction des avis aux administrations (niveau ministériel)

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#878]
@georges-bayard Tu confirmes? (suite à l'échange avec NBA).

**Comment by georges-bayard** [comment]
je confirme

**Comment by lucaa** [comment]
@AnthonyBrunelli il s'agit de quelle fonctionalité ? l'export des avis d'une démarche?

**Comment by lucaa** [comment]
Pour une démarche donnée l'administrateur ministeriel de la même direction que la démarche doit avoir accès à la liste de tous les avis (et les fonctions associées).

**Comment by lucaa** [comment]
Effectivement, il y avait un bug de verification de droits à ce niveau, qui empechait les résultats du tableau d'avis de charger pour un administrateur ministeriel, même s'il voyait l'onglet:
![image](https://user-images.githubusercontent.com/657716/81850885-e6cbd480-9558-11ea-8108-89d958cfa803.png)

J'ai corrigé ce bug de vérification des droits dans l'esprit de l'implémentation initiale: c'est à dire permettre à tout administrateur ministériel de voir les avis de toute démarche.

Pour changer la règle et mettre en place une règle plus restrictive où un administrateur ministeriel  a accès à ces informations uniquement pour les démarches qui font partie de sa direction, il faut créer un nouveau ticket, je dirais, qui décrit le comportement souhaité pour chaque onglet de la démarche (@AnthonyBrunelli).

**Comment by lucaa** [comment]
à faire: changer la condition d'accès aux avis pour ajouter la vérification de la direction de l'utilisateur: on affiche la liste des avis uniquement pour les administrateurs ministeriels de la même direction que la démarche.

**Comment by lucaa** [comment]
J'ai enlevé l'etiquette "bug" car finalement, comme cette tache comporte aussi un changement de comportement par rapport à l'existant, c'est un peu plus qu'un bug.

**Comment by lucaa** [comment]
> à faire: changer la condition d'accès aux avis pour ajouter la vérification de la direction de l'utilisateur: on affiche la liste des avis uniquement pour les administrateurs ministeriels de la même direction que la démarche.

Une nouvelle tache a été crée pour ce changement de spécification d'accès, #901.
Je ferme ce bug comme "fait" car le correctif pour le tableau des avis d'une démarche a été apporté, mais la tâche #901 va re-changer tout de suite l'accès à cette data.

**Comment by AnthonyBrunelli** [comment]
@georges-bayard à voir ensemble...

**Comment by georges-bayard** [comment]
@AnthonyBrunelli  faut deja tester que ca marche. Il faut que je te mette admin ministériel  et que je te rattache a une direction et que tu vois si tu vois les avis de cette direction, et exclusivement ceux la. Tu as pu regarder la synthèse qu'elle a mise à jour sur les droits ?
