### ISSUE TITLE
Tableau observatoire: flèches des filtres non cliquables

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#879]
![image](https://user-images.githubusercontent.com/35567048/78681172-ad1a0500-78ec-11ea-920b-e9956f051326.png)

Tableau observatoire: flèches des filtres non cliquables: il faut aller dans le champ pour voir le menu déroulant.

**Comment by lucaa** [comment]
> flèches des filtres non cliquables: il faut aller dans le champ pour voir le menu déroulant.

les flèches sont, effectivement pas cliquables, par contre pour activer le select il suffit de cliquer n'importe ou dans le champ, par exemple sur le nom de l'option selectionnée.
Plus précisément, la zone entourée dans cette capture n'est pas cliquable, mais tout le reste l'est:
![image](https://user-images.githubusercontent.com/657716/82155650-c19bd680-9876-11ea-92a3-2fb76511439a.png)

**Comment by lucaa** [comment]
@AnthonyBrunelli tu peux me confirmer que cliquer sur le reste de la zone active la liste déroulante sur ton navigateur aussi?

**Comment by lucaa** [comment]
Corrigé, avec un setting CSS assez obscure: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events qui permet de ne pas intercepter les clicks sur la flèche: ainsi, les clicks seront pris en compte par l'élément "en dessous" qui est la liste deroulante.
