### ISSUE TITLE
Fix search suggest to not display "no results" when there are no results

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#88]
It's bothering, for the user experience, that the search suggest displays "no results" when 3 letters are typed, for example, and there are no results yet for these 3 letters.
One way to handle results for the 3 letters search is to always search with a wildcard, see #42 , but an improvement is already to not display "no results" anymore, so that the user continues typing until they get some results.

**Comment by lucaa** [comment]
I completely removed the first line of the suggest results, the one displaying "Afficher tous les resultats" and "no results" when there are no results.
I assume that if users want to see all results they'd hit enter or click "Trouver ma demarche".

**Comment by slauriere** [comment]
Great. I'm adding here a minor comment for the record: I noticed that both JIRA and Google propose an action at the bottom of the suggestion list, allowing to view all the matching results. This might be viewed as a common UX pattern which we may consider as well I guess at some point, what do you think?
