### ISSUE TITLE
Implémentation de l'année glissante pour les résultats du tableau de bord administration pour les avis 

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#880]
![image](https://user-images.githubusercontent.com/35567048/78686217-100e9a80-78f3-11ea-8561-dc1802185e3b.png)

le % correspond à une année glissante alors que le nombre d'avis correspond au total depuis la nuit des temps.

**Comment by AnthonyBrunelli** [comment]
https://observatoire.numerique.gouv.fr/TableauDeBord/

à revoir ensemble...

**Comment by georges-bayard** [comment]
@lucaa : pourquoi est ce à spécifier de notre côté ?

**Comment by georges-bayard** [comment]
Règle de gestion : afficher sur cet écran les données en année glissante, que ce soit le % de votes que le nombre de votes

**Comment by lucaa** [comment]
> le % correspond à une année glissante alors que le nombre d'avis correspond au total depuis la nuit des temps

Je ne pense pas que le % correspond vraiment à l'année glissante, je pense que c'est pour tous les avis depuis le début, mais il se trouve que assez souvent, l'indice peut facilement être le même car à partir de quelques milliers d'avis, il ne change plus beaucoup.

La règle va être changée pour les 2, cf. commentaire de @georges-bayard .

**Comment by lucaa** [comment]
@slauriere à modifier:
* service Java qui calcule les cache d'avis (AvisStatsClass) pour ajouter la limite d'une année précédente à la date courante
  * pour toutes les démarches
  * pour une démarche donnée
* sans modification d'API de ce service
  * tous les appels restent exactement les mêmes qu'aujourd'hui

**Comment by slauriere** [comment]
Le service `AvisStatsManager` calculant les statistiques d'avis (nombre d'avis émis, moyenne des notes attribuées et nombre de votes pour une dématérialisation le cas échéant) a été modifié pour ne porter que sur les 365 derniers jours (pris au moment où le service est exécuté), qu'il soit appliqué à l'ensemble des démarches ou à une seule. L'API du service reste inchangée. 

J'ai effectué des tests de sur le serveur de développement depuis la page `/Avis/Admin/AvisStatsManager` d'une part sur des démarches individuelles (`Demarches.1288` et `Demarches.1743` ayant des avis générés automatiquement dont certains ayant plus d'un an), d'autre part sur l'ensemble des démarches : les statistiques obtenues correspondent bien au résultat attendu (avis émis au cours de l'année passée au lieu de l'intégralité des avis précédemment).
