### ISSUE TITLE
Ajouter l'historique des votes dans la vue de synthèse des votes d'une démarche

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#883]
Il s'agit de la fonctionnalité mentionnée dans la tache #875:

![image](https://user-images.githubusercontent.com/657716/79695653-57dcdc80-8278-11ea-993e-2c2c44c6ed6a.png)

. les données doivent pouvoir être affichées avec une précision journalière, mensuelle (par défaut) ou trimestrielle;
. durée d'historique d'affichage : 12 barres si la précision choisie est mensuelle ou trimestrielle (1 ans de données ou 3 ans de données) ou 30 barres si elle est journalière (1 mois de données);
. afficher les valeurs sur les abscisses et les ordonnées (dates, intervalles de %, intervalles de nombres);
. reprendre les couleurs des smiley.

Ces graphiques doivent être accessibles à tous les profils, dans l'onglet statistique de la démarche. Attention les graphiques sont dynamiques, et pas statiques comme actuellement. Il faut choisir une vue par défaut. Attention à l'aspect accessibilité.

**Comment by ugodtn** [comment]
<img width="994" alt="Capture d’écran 2020-04-21 à 16 32 40" src="https://user-images.githubusercontent.com/34340568/79880545-75cd4d00-83f0-11ea-83bc-0e016d323bc0.png">

**Comment by georges-bayard** [comment]
sur les graphiques à l'information mois rajouter la donnée année (20, 21, ...)

**Comment by lucaa** [comment]
> les données doivent pouvoir être affichées avec une précision journalière, mensuelle (par défaut) ou trimestrielle;
> durée d'historique d'affichage : 12 barres si la précision choisie est mensuelle ou trimestrielle (1 ans de données ou 3 ans de données) ou 30 barres si elle est journalière (1 mois de données);

ce n'est plus à faire, les graphiques affichent toujours la dernière année (glissante).

**Comment by lucaa** [comment]
Pour le deuxième graphique l'idée est que les rectangles au dessus du graphique soient cliquable et que lors du click le graphique presente uniquement les données du type choisi.

**Comment by lucaa** [comment]
Le calcul des données à afficher est fait, et une première version de l'affichage. 
La gestion de la donnée (tableau vs affiché) est la même que pour les autres charts, il y a un tableau html qui contient la data et qui remplace le graphique pour les lecteurs d'écrans.

Pour l'affichage, il reste à faire: l'affichage du nombre total de votes au dessus du graphique pour le deuxième graphique, et quelques améliorations de l'affichage (tailles, etc).

**Comment by lucaa** [comment]
J'ai créé tâche #905 pour gérer le nombre total de votes, je ferme cette tâche maintenant, car la fonctionnalité principale est implémentée. 
D'autres tâches liées peuvent être créées, pour différentes améliorations.

**Comment by lucaa** [comment]
Une conséquence de l'implémentation de la distribution des avis dans les mois de l'historique a été ouverte dans la tache #906 , à répondre.

**Comment by AnthonyBrunelli** [comment]
Mes points sur le sujet:
- Est-il possible d'avoir les mois en français?
- Les chiffres sur les tronçons de colonnes sont illisibles: n'y a t il pas une couleur qui permet un contraste suffisant? (sinon, mieux vaut ne rien mettre vu que l'info apparait au survol et donc, j'imagine, au lecteur d'écran)

![image](https://user-images.githubusercontent.com/35567048/83884462-33b05e80-a745-11ea-8bcf-3a7f3279a36e.png)

@lucaa Tu veux que j'ouvre d'autres fiches pour déclarer ça, c'est ça?

@ugodtn @georges-bayard Vous voyez autre chose?

**Comment by lucaa** [comment]
> Les chiffres sur les tronçons de colonnes sont illisibles: n'y a t il pas une couleur qui permet un contraste suffisant? (sinon, mieux vaut ne rien mettre vu que l'info apparait au survol et donc, j'imagine, au lecteur d'écran)

Ces chiffres ne sont pas censés rester là, voir  #905 qui a été ouvert pour ça.

> Est-il possible d'avoir les mois en français?

Ok pour les mois, j'ouvre un ticket.

**Comment by AnthonyBrunelli** [comment]
Pour mémoire, à voir avec Ugo, mais:
- Quid de l'explication du calcul de l'"Indice de satisfaction global"?
- Quid d'avoir les deux schémas visibles en même temps?
- Renommer "Répartition des avis" en "Nombre d'avis" ou les deux? Inclure le terme de répartition?

**Comment by lucaa** [comment]
> mettre la facilité d'usage et la compréhension sous forme de camembert en ajoutant les non exprimés
> dans tous les camemberts ajouter le nombre de réponses

Tache séparée #914  .

**Comment by lucaa** [comment]
> adapter les couleurs en les calant sur les couleurs de l'observatoire

@georges-bayard : de quelles couleurs s'agit-il? Les couleurs des 2 graphiques ajoutées pour cette tache ou toutes les couleurs de l'écran de graphiques d'une démarche?
Les couleurs de ces 2 graphiques sont ainsi: 
* le bleu est le même bleu que la bannière de l'observatoire
* les rouges / orange / vert sont les mêmes rouge / orange / vert que les autres graphes de l'écran de graphes qui sont les couleurs des smileys du formulaire d'avis, choisies pour leurs contrastes. Lors de l'implémentation des couleurs des indicateurs sur l'observatoire il y a eu une discussion sur le fait d'utiliser des nouvelles couleurs vs les couleurs des smileys vs mettre à jour les couleurs des smileys pour être synchronisées avec les couleurs de l'observatoire, voir ce commentaire https://github.com/DISIC/wikidemarches/issues/729#issuecomment-543314778 et ceux qui suivent. Entre temps, #777 a été fait aussi (pour les contrastes), donc je pense que ça serait intéressant de prévoir ce calage de couleurs dans le contexte de cette harmonisation globale des indicateurs rouge, orange, vert.

**Comment by lucaa** [comment]
@georges-bayard 

> Réduire la largeur et la hauteur des deux schémas de 50% sauf les textes et tout ce qui comporte du texte
> Mettre les deux schémas côte à côte sauf sur mobile
> Passer les deux schémas juste avant l'avis global

à faire dans cette itération?

**Comment by lucaa** [comment]
> Réduire la largeur et la hauteur des deux schémas de 50% sauf les textes et tout ce qui comporte du texte
> Mettre les deux schémas côte à côte sauf sur mobile

dans la tache #920 , va peut-être demandé du travail supplémentaire en terme de taille et agencement.

**Comment by AnthonyBrunelli** [comment]
@lucaa du coup, que faut-il valider ici? 
Il me semble qu'il faut déplacer les schémas au-dessus du "Détails des avis", c'est ça @georges-bayard ?
Pour les couleurs, moi ça me va mais @georges-bayard @ugodtn ?
Reste :
Renommer le tableau d'historique mensuel "répartition des avis" en "nombre de votes"
mettre la facilité d'usage et la compréhension sous forme de camembert en ajoutant les non exprimés
dans tous les camemberts ajouter le nombre de réponses

**Comment by AnthonyBrunelli** [comment]
(hey @lucaa je t'ai même pas dit salut!)

**Comment by AnthonyBrunelli** [comment]
Résidu traité dans #925

**Comment by lucaa** [comment]
j'ai enlevé la partie "mettre la facilité d'usage et la compréhension sous forme de camembert en ajoutant les non exprimés
dans tous les camemberts ajouter le nombre de réponses" de #925 car elle est couverte par #914
