### ISSUE TITLE
Critères notation à revoir

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#886]
Lié à #871, il s'agit de la mise à jour des indicateurs et des valeurs affichées pour les critéres des démarches sur l'observatoire (textes affichés, couleurs, etc.)

**Comment by AnthonyBrunelli** [comment]
[Critres_et_notes_Observatoire.pdf](https://github.com/DISIC/wikidemarches/files/4517106/Critres_et_notes_Observatoire.pdf)

@lucaa 'lut! v'la notre doc... On en reparle s'tu veux.

**Comment by lucaa** [comment]
Après analyse de l'état existant et du pdf, des modifications d'affichage ont été faites en utilisant les principes suivants:
1 / Dans la mesure du possible, les valeurs existantes ont été utilisées et seules les valeurs affichées ont été modifiées. Pour toutes les propriétés avec des valeurs "na" et "nr" pour gérer des valeurs non spécifiées, le "na" a été conservé pour n/a et "nr" a conservé et utilisé pour En attente (correspondait à n/c, non renseigné, non disponible, etc.)
2 / L'affichage de "-" pour une propriété n'est pas traité avec une valeur spécifique stockée, mais sera traité lors du rendu des données dans l'observatoire. Autant que possible, pour ces cas, j'ai essayé de ne pas avoir de valeur du tout stockée dans la propriété (mais il y aura quand même des propriétés qui auront une valeur qui sera ignorée lors de la génération de l'observatoire selon le statutDemat)
3 / une valeur vide stockée peut également apparaître pour une propriété non renseignée, auquel cas la valeur vide doit être interprétée comme "En attente" plutôt que "-".

Cette modification simplifie également (partiellement) le traitement des valeurs à afficher pour les elements de liste (l'intention est de passer le plus possible par les traductions et de ne pas utiliser d'autres sources).

**Comment by lucaa** [comment]
Plusieurs autres modifications ont été faites pour finaliser la mise en place des nouvelles valeurs et nouvel affichage.
Je ferme cette tâche car le travail est fait et satisfaisant, mais il y a une explication plus longue potentiellement à écrire sur les modifications faites.
