### ISSUE TITLE
Implémenter la nouvelle charte de l'état dans le header et page d'accueil

### ISSUE THREAD

**Issue by ugodtn** [DISIC/wikidemarches#887]
Mettre en place le nouveau bloc Marianne dans le header, et ajuster la page pour respecter les contraintes (liés à la charte) suivantes :

Desktop : 
- 30px de padding top et bottom dans le header (il y a 20px aujourd'hui)
- 115px de haut pour le bloc Marianne
- 60px entre le bloc Marianne et le logo de l'observatoire
- 44px de haut pour le logo Observatoire
- 29px de padding-top pour le logo Observatoire

Mobile : 
- 16px de padding dans le header (de toute part)
- 64px de haut pour le bloc Marianne
- 24px entre le bloc Marianne et le logo de l'observatoire
- 25px de haut pour le logo Observatoire
- 15px de padding-top pour le logo Observatoire
- placer les éléments de navigation dans un menu hamburger (ce n'est pas grave si le comportement en mode connecté sur mobile n'est pas parfait pour le moment)

Commun : 
- Le alt name pour le bloc Marianne est : "Logo République française"
- Le alt name pour le logo observatoire est : "Logo Observatoire de la qualité des démarches en ligne"
- Le title pour le lien qui inclus ces deux logos (même comportement qu'aujourd'hui) est : "Accueil - Observatoire de la qualité des démarches en ligne"
- Réduire le padding-top du premier bloc suivant le header (bloc titre) à 2em
- Remplacer la font pour les éléments de navigation par Marianne Regular 1.125em
- Transformer le h2 et h1 et les h3 en h2
- Remplacer le texte du titre par le sous-titre, supprimer le sous-titre
- Remplacer la font du h1 par Marianne ExtraBold 3em
- Remplacer la font des h2 par Marianne ExtraBold 2em
- Remplacer la font-family du body par Inter
- Modifier le title (meta) de la page pour : "L’observatoire de la qualité des démarches en ligne"

Ci-joint les maquettes desktop et mobile, le nouveau bloc Marianne au format svg et le logo Observatoire au format svg, la font Marianne. La font Inter est ici : https://rsms.me/inter/.

**Comment by ugodtn** [comment]
[LogoRF.svg.zip](https://github.com/DISIC/wikidemarches/files/4511437/LogoRF.svg.zip)

**Comment by ugodtn** [comment]
<img width="1051" alt="Capture d’écran 2020-04-21 à 18 32 08" src="https://user-images.githubusercontent.com/34340568/79892249-8b4b7280-8402-11ea-89b2-b7a75aa003ef.png">

**Comment by ugodtn** [comment]
<img width="1280" alt="Capture d’écran 2020-04-21 à 19 14 04" src="https://user-images.githubusercontent.com/34340568/79893531-825ba080-8404-11ea-8272-004fad0ec9d1.png">

**Comment by lucaa** [comment]
@ugodtn les contraintes ci-dessus sont les mêmes sur mobile?

**Comment by lucaa** [comment]
@ugodtn bouge la tache dans la colonne "To do (blocker)"  dès que la maquette est stabilisé et validé coté Dinum, pour la mettre au bon endroit dans la liste des choses à faire, stp.

**Comment by ugodtn** [comment]
@lucaa oui, c'est encore en discussion, ça va changer ;). Je mets à jour la maquette demain matin, et j'ajoute les infos pour le mobile.

**Comment by ugodtn** [comment]
<img width="1296" alt="Desktop" src="https://user-images.githubusercontent.com/34340568/80108016-1dc35180-857c-11ea-92c4-26f7c7e70b34.png">

<img width="418" alt="Mobile" src="https://user-images.githubusercontent.com/34340568/80108034-261b8c80-857c-11ea-82dc-5b0da3ab1012.png">

**Comment by ugodtn** [comment]
<img width="1296" alt="Desktop" src="https://user-images.githubusercontent.com/34340568/80108076-2f0c5e00-857c-11ea-9a73-50e86a1c1738.png">

**Comment by ugodtn** [comment]
<img width="418" alt="Mobile" src="https://user-images.githubusercontent.com/34340568/80108103-36cc0280-857c-11ea-87fb-4ce2ec6196e5.png">

**Comment by ugodtn** [comment]
[marianne_font.zip](https://github.com/DISIC/wikidemarches/files/4523197/marianne_font.zip)

**Comment by ugodtn** [comment]
[LogoObservatoire.svg.zip](https://github.com/DISIC/wikidemarches/files/4523202/LogoObservatoire.svg.zip)

**Comment by ugodtn** [comment]
@lucaa c'est à jour. Si tu veux on peut échanger rapidement, car ça s'est un peu étoffé.

**Comment by lucaa** [comment]
à faire également: déclinaison de ces régles d'affichage pour la age d'avis: voxusagers.numerique.gouv.fr .

**Comment by lucaa** [comment]
Quelques commentaires pour les directives sur mobile:

> 15px de padding-top pour le logo Observatoire

Si je suis les autres dimensions (Logo Marianne + logo Observatoire), il me faut 10px de padding (top) pour aligner les 2 lignes du logo Observatoire avec Republique Francaise. Peux-tu confirmer, @ugodtn que c'est cet objectif la qu'il faut atteindre?

> 16px de padding dans le header (de toute part)

Je comprends que ces 16px sont censé remplacer les 30 px du desktop.
Sachant que le logo Marianne sera écarté du bord gauche par 15px toujours (et ces 15px sont alignés avec le padding du reste de la page en dessous), le padding de 16px donnerait un cadre presque symmetrique au logo Marianne pour son coin haut gauche, ainsi: 
![image](https://user-images.githubusercontent.com/657716/80287333-4b053080-8731-11ea-81fb-fc5813862a77.png)

Ceci n'est pas le cas dans l'image de la maquette sur mobile que tu as uploadé, @ugodtn . Peux-tu clarifier les 16px?

**Comment by ugodtn** [comment]
@lucaa concernant ta première question, ok si c'est 10px, le but est effectivement l’alignement des 2 lignes.

Pour ta seconde question, si la marge à gauche est à 15px (comme pour le reste de la page), pas de soucis, alors on met 15px de marge au-dessus aussi. La maquette n'est pas très précise à cause de la manière dont je l'ai exportée. Mais le but c'est bien d'avoir la même marge à gauche et au-dessus du bloc Marianne.

**Comment by lucaa** [comment]
@ugodtn ok, thanks!

**Comment by lucaa** [comment]
Les modifications demandées dans la description et commentaires ont été faites, avec quelques amendements:

> Le alt name pour le logo observatoire est : "Logo Observatoire de la qualité des démarches en ligne"
> Le title pour le lien qui inclus ces deux logos (même comportement qu'aujourd'hui) est : "Accueil - Observatoire de la qualité des démarches en ligne"
> Modifier le title (meta) de la page pour : "L’observatoire de la qualité des démarches en ligne"

Tous les usages du nom du site sont articulés, sous la forme "L'observatoire [...]", car ils utilisent une variable dans le code qui peut être mise à jour facilement. Si cela pose un problème grave de langue française, on peut re-travailler.
Aussi, le nom du site dans le footer a change également, pour la même raison:
![image](https://user-images.githubusercontent.com/657716/80514215-7f226080-8980-11ea-9851-f3d04a92786c.png)

J'ai mis en place les polices et les tailles demandées mais le résultat (les proportions) ne sont pas tout-à-fait identiques aux proportions des maquettes fournies dans cette tâche. Il y aura potentielemment des modifcations supplémentaires à faire, je propose d'attendre l'installation du code sur le serveur de test et d'aviser suite aux testes plus "real-life".

**Comment by ugodtn** [comment]
@lucaa Parfait c'est top ! Est-ce qu'on peut faire 3 petits changements, puis passer en prod : 
- Modifier le h1 pour : Pour des services publics numériques de qualité
- Modifier le texte sous le h1 pour : 66% des français estiment que les services publics numériques sont trop complexes. Afin de suivre leur qualité et l'avancement de leur amélioration, nous publions chaque trimestre une analyse fine des 250 démarches en ligne les plus utilisées.
- Dans le footer, passer le nom du site en bold
Merci !

**Comment by lucaa** [comment]
Le modifications demandées ont été faites, je re-ferme.
