### ISSUE TITLE
La police du titre de la page de l'observatoire doit être Marianne

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#890]
![image](https://user-images.githubusercontent.com/657716/80717419-34782400-8af9-11ea-87ed-92a657678f17.png)

La police des titres de la page d'accueil a été mise à jour pour #887 , mais pas la police du titre de la page observatoire.

**Comment by ugodtn** [comment]
@lucaa oui tout à fait, comme pour la page d'accueil. Au passage, j'ai trouvé les fonts au format ttf, woff et woff2, les voici : 

[fontes web.zip](https://github.com/DISIC/wikidemarches/files/4585375/fontes.web.zip)

**Comment by lucaa** [comment]
> @lucaa oui tout à fait, comme pour la page d'accueil. Au passage, j'ai trouvé les fonts au format ttf, woff et woff2, les voici :
> 
> [fontes web.zip](https://github.com/DISIC/wikidemarches/files/4585375/fontes.web.zip)

Une nouvelle tâche a été créée pour ajouter les formats: #893 .

**Comment by lucaa** [comment]
J'ai mis à jour la police et l’épaisseur à 800, mais je n'ai pas changé la taille. Il n'était pas clair pour moi si "comme pour la page d'accueil" voulait dire aussi la même taille que la page d'accueil ou pas. à ouvrir une nouvelle tache si la taille doit également être changé.
