### ISSUE TITLE
Revoir / redéfinir / corriger les tris des colonnes de l'observatoire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#892]
Suite aux changements faits pour #886, les valeurs des colonnes de l'observatoire ont changé (pour certaines colonnes), et une partie de ces colonnes avaient des règles spécifiques pour les tris (car valeurs mixtes texte / numéro).  Ainsi, le résultat des tris sur les colonnes est a revoir car il a changé suite à #886.

**Comment by lucaa** [comment]
La règle pour les tris a été donnée dans https://github.com/DISIC/wikidemarches/issues/805#issuecomment-575239663 .

**Comment by AnthonyBrunelli** [comment]
S'il n'y a pas de valeur ajoutée par rapport à #805 ne faut-il pas fermer?
