### ISSUE TITLE
Réduire la taille du logo dans le formulaire d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#899]
Le logo de la page d'avis, tel que défini par https://github.com/DISIC/wikidemarches/issues/887#issuecomment-618514808 , est à remplacer avec une version réduite, en pièce jointe.
[LogoVoxusagers.zip](https://github.com/DISIC/wikidemarches/files/4647192/LogoVoxusagers.zip)

**Comment by lucaa** [comment]
C'est fait, en production aussi.
Ça donne ça:
Avant: 
![image](https://user-images.githubusercontent.com/657716/82348749-9097df00-99f9-11ea-818e-120ffc486cb9.png)


Après: 
![image](https://user-images.githubusercontent.com/657716/82348716-87a70d80-99f9-11ea-85a0-60026b6ab604.png)

**Comment by AnthonyBrunelli** [comment]
@georges-bayard C'est une demande à toi à l'origine?

**Comment by georges-bayard** [comment]
@AnthonyBrunelli  : oui c'est de moi on peut fermer c'est ok en prod. Que penses tu de la solution ? je trouve que c'est encore très voyant. Voir avec @ugodtn pour la solution définitive
