### ISSUE TITLE
Restaurer la bonne version de l'icône mobile.svg

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#900]
Pendant le travail pour #887  , une modification a été faite par erreur sur l'icône mobile.svg, ici : https://github.com/DISIC/wikidemarches/commit/2e99601756a627038a97ea3b4846536627b2a078#diff-c79666f5a8825918a712c863469334cbL104 .
L'icone en question avait été mise en place précédemment dans commit 80f22246205fa77a538c57ec704bacb3608b17de pour #743. 

Il n'est pas clair pourquoi ce changement est survenu, mais comme on n'a jamais validé ou planifié un changement à ce niveau, il fait revenir en arrière.

**Comment by lucaa** [comment]
La modification a été faite, en production aussi.

**Comment by AnthonyBrunelli** [comment]
@georges-bayard tu sais de quoi il s'agit? où contrôler ça? l'icone sur la version mobile, mais quel icone?

**Comment by georges-bayard** [comment]
@AnthonyBrunelli je comprends que c'est une ano repérée par Anca elle même qu'elle a réparé. Je propose de clôturer

**Comment by lucaa** [comment]
@AnthonyBrunelli effectivement, c'est une anomalie que j'ai repéré, qui a été introduite lors de la dernière livraison, donc j'ai mis le correctif directement en production sans attendre la validation.

Ce n'est pas une icône sur mobile mais l'icône du téléphone mobile qui est utilisé pour le critère "Compatible mobile", dans la tête de tableau de l'observatoire mais aussi sur la page d'accueil, celle ci: 

![image](https://user-images.githubusercontent.com/657716/84085692-6c229780-a9e6-11ea-86e0-9d4f807fbc8a.png)

L'anomalie est vraiment très difficilement visible à l'oeil libre:

![image](https://user-images.githubusercontent.com/657716/84085912-ea7f3980-a9e6-11ea-8706-921615072046.png)
mais je l'ai détecté en regardant les ressources dans le code, et je l'ai réparé.

**Comment by AnthonyBrunelli** [comment]
Aahhh
