### ISSUE TITLE
Configurer le formulaire d'avis sur la démarche "France Connect" sur le modèle courant

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#902]
issue #327 : on a configuré un parcours spécifique pour les démarches France Connect. Il faut revenir sur cette évolution et revenir sur le droit commun (2 étapes de vote)

**Comment by lucaa** [comment]
@georges-bayard : j'ai fait la modification. On veut installer en production asap ou on installe avec les autres modifications?

**Comment by georges-bayard** [comment]
j'ai appelé FC qui n'est pas au jour près. on peut donc attendre la mise en prod globale

**Comment by AnthonyBrunelli** [comment]
@georges-bayard à voir ensemble non?

**Comment by georges-bayard** [comment]
@lucaa : je ne trouve pas la démarche France connect sur le staging. C'est normal ?

**Comment by lucaa** [comment]
@georges-bayard c'est la 1650. ll faut la chercher avec la syntaxe "FranceConnect" (sans éspace), celui-ci est le branding correct du nom du projet.
Effectivement la recherche Solr ne trouve pas la démarche si on cherche par "France Connect" (avec espace), et je pense que c'est normal (au moins partiellement), car lors de l'indexation c'est considéré un seul mot. 
La seule qui aurait une chance de la trouver c'est la recherche par prefix (car c'est la seule recherche qui cherche lettre par lettre sans analyser le texte écrit) mais, comme le mot "France" est prefix du mot "FranceConnect", dès qu'on commence à écrire les premières lettres de F, R, A, N, etc. , les démarches qui contiennent les mots "France, français, française" seront  identifiées d'abord, et il y en a beaucoup.

**Comment by georges-bayard** [comment]
je ne sais plus comment tester le bouton du code : 
<a href="https://voxusagers.numerique-staging.devxwiki.com/Demarches/1650?&view-mode=formulaire-avis&nd_mode=en-ligne-enti%C3%A8rement&nd_source=button&key=d209f7b2be0fca3de1df21eaeff49a97">
  <img src="https://voxusagers.numerique-staging.devxwiki.com/static/bouton-bleu.svg" alt="Je donne mon avis" title="Je donne mon avis sur cette démarche" />
</a>

**Comment by lucaa** [comment]
@georges-bayard ici https://dinsic.xwiki.com/xwiki/wiki/projetdemat/view/main/Sp%C3%A9cifications%20M8%20-%20Embed/TestBoutonNosdemarches (j'ai re-lu et mis à jour la page pour correspondre aux versions recentes).

**Comment by lucaa** [comment]
Je viens d'installer cette modification en production,  à la demande de @georges-bayard .
