### ISSUE TITLE
Ajouter le nombre total d'avis sur le graphique des avis par type dans l'historique des avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#905]
Il s'agit d'un reste de fonctionnalité de la tache #883 : l'affichage du nombre total des votes au dessus des barres:
![image](https://user-images.githubusercontent.com/657716/83630427-168c5c00-a59c-11ea-890e-a17c816514f1.png)

**Comment by lucaa** [comment]
Une amélioration a été apportée au l'extension XWiki utilisée pour faire les graphes https://jira.xwiki.org/browse/CHARTJS-28 pour rendre possible le calcul des totaux, les instructions d'installation ont été mises à jour pour utiliser cette nouvelle version et la configuration du graphe d'historique d'avis a été mise à jour pour utiliser cette option.

Aussi, j'ai réduit l'espace blanc entre les segments de la barre, pour rendre ce graphe plus cohérent visuellement avec le camembert en haut de l'écran.
Résultat:
![image](https://user-images.githubusercontent.com/657716/84537397-ed806f80-acef-11ea-90c3-8ec1a4e8c4b1.png)

Reste à faire: configurer l'affichage de la legende en haut du graph pour laisser de la place aux étiquettes affichées en haut des barres.

**Comment by lucaa** [comment]
Une nouvelle amélioration a été apportée au l'extension XWiki utilisée pour faire les graphes https://jira.xwiki.org/browse/CHARTJS-29 , pour permettre d'ajouter une distance entre la legende et le graph (l'option n'existe pas dans chartjs par défaut, demande une configuration de plugin bizarre). 
Les instructions d'installation ont été mises à jour pour utiliser cette nouvelle version et la configuration du graphe d'historique d'avis a été mise à jour pour utiliser cette option.
![image](https://user-images.githubusercontent.com/657716/84648633-95bb5180-af05-11ea-8110-3ae6934e81e3.png)

**Comment by AnthonyBrunelli** [comment]
Ok pour moi (en staging la version est plus petite mais ça correspond aussi à notre demande). @georges-bayard @ugodtn sauf remarque de votre part, je mets ça dans 'terminé'.
