### ISSUE TITLE
Test & Amélioration de performance de l'export illimité d'avis

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#908]
Sur le serveur de staging, l'export des avis illimité (implémenté pour #882 ) bloque pour un problème de mémoire vers 5000 avis.

**Comment by lucaa** [comment]
Une première piste d'optimisation a été exploré et validé avec de très bons résultats sur 15 000 avis à exporter, il faut juste finaliser l'implémentation (l'optimisation au niveau de l'affichage des valeurs de chaque colonne, qui peut être géré au niveau global plutôt que traité individuellement pour chaque ligne en isolation).

**Comment by lucaa** [comment]
La solution décrite ci-dessus a été implémentée et installée en staging.

**Comment by lucaa** [comment]
Testé sur staging sur 15 000 avis, ça passe, assez rapidement, et la courbe mémoire semble re-descendre au niveau initial après la finalisation de l'export.
Je ferme cette issue pour l'instant, mais des tests supplémentaires devraient être faits, et re-ouvrir s'il y a toujours des problèmes.

**Comment by AnthonyBrunelli** [comment]
Moins de deux minutes pour 7500 avis.
Je mets en terminé sur le principe de "Je ferme cette issue pour l'instant, mais des tests supplémentaires devraient être faits, et re-ouvrir s'il y a toujours des problèmes."
