### ISSUE TITLE
placer le logo VoxUsagers en haut à droite de la page de vote

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#913]
La solution actuelle n'est pas compréhensible par l'usager car le logo placé la ou il est laisse à penser que c'est le nom du servivce. ce qui n'est pas le cas

**Comment by lucaa** [comment]
@georges-bayard , @ugodtn : il y aura une proposition ou je fais une proposition moi-même?

**Comment by georges-bayard** [comment]
La aussi prochaine iteration.

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

-------- Message original --------
De : Anca Luca <notifications@github.com<mailto:notifications@github.com>>
Date : jeu. 11 juin 2020 à 22:27
À : DISIC/wikidemarches <wikidemarches@noreply.github.com<mailto:wikidemarches@noreply.github.com>>
CC : BAYARD Georges <georges.bayard@modernisation.gouv.fr<mailto:georges.bayard@modernisation.gouv.fr>>,Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Objet : Re: [DISIC/wikidemarches] placer le logo VoxUsagers en haut à droite de la page de vote (#913)

@georges-bayard<https://github.com/georges-bayard> , @ugodtn<https://github.com/ugodtn> : il y aura une proposition ou je fais une proposition moi-même?

**Comment by lucaa** [comment]
Le besoin décrit par cette tâche n'est plus d'actualité suite à l'implémentation du nouveau design du formulaire décrit dans la tâches #1008 et les tâches associés, dans la même version.
Je ferme cette tâche comme invalide, dans la même version que #1008 .
