### ISSUE TITLE
revoir la question "comment s'est passée cette démarche pour vous" dans la première page du formulaire de vote

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#915]
"comment s'est passée cette expérience pour vous" au lieu de "comment s'est passée cette démarche pour vous" dans

**Comment by lucaa** [comment]
@georges-bayard c'est quoi le niveau de priorité sur cette tâche? C'est prêt à faire ou il y a encore des discussions?

**Comment by georges-bayard** [comment]
On doit encore en discuter en interne pour voir si il y a des alternatives

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

-------- Message original --------
De : Anca Luca <notifications@github.com<mailto:notifications@github.com>>
Date : jeu. 11 juin 2020 à 22:38
À : DISIC/wikidemarches <wikidemarches@noreply.github.com<mailto:wikidemarches@noreply.github.com>>
CC : BAYARD Georges <georges.bayard@modernisation.gouv.fr<mailto:georges.bayard@modernisation.gouv.fr>>,Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Objet : Re: [DISIC/wikidemarches] revoir la question "comment s'est passée cette démarche pour vous" dans la première page du formulaire de vote (#915)

@georges-bayard<https://github.com/georges-bayard> c'est quoi le niveau de priorité sur cette tâche? C'est prêt à faire ou il y a encore des discussions?

**Comment by AnthonyBrunelli** [comment]
ça reste d'actualité dans la mesure où ce pourrait être autre chose que des démarches, notamment si on pense à l'embed qu'on pourrait mettre où on veut. Donc à penser. A revoir dans le cadre de la réflexion 'Embed' #872
