### ISSUE TITLE
Liste des avis: augmenter (x1.5) la taille des colonnes verbatim, difficultés et autres difficultés

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#919]
Commentaire initial de #876 , par @georges-bayard:

> élargir les champ verbatim, difficultés et autres difficultés (x1,5)

**Comment by lucaa** [comment]
|Colonne(s)|Taille|Taille en em
|-- | -- | --
|Date, Id, Satisfaction | 4.9% chacune | 7em
|Verbatim | 21% | 30em
|Facilité, Simplicité | 4.4% | 6em
|Difficulté, Autre difficulté| 15.5% | 22em
|Aide, Autre aide | 10.5% | 15em
|Source | 3.5% | 5em

**Comment by AnthonyBrunelli** [comment]
C'est bon pour moi, même si je n'ai pas le moyen de comparer avec avant. @ugodtn @georges-bayard, sauf remarques de votre part, je mets ça dans 'terminé'.
