### ISSUE TITLE
Passer les graphs de l'historique des avis sur la même ligne

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#920]
Initialement un commentaire sur https://github.com/DISIC/wikidemarches/issues/883#issuecomment-642131442 : 
> Réduire la largeur et la hauteur des deux schémas de 50% sauf les textes et tout ce qui comporte du texte
> Mettre les deux schémas côte à côte sauf sur mobile

**Comment by lucaa** [comment]
Résultat: 

![image](https://user-images.githubusercontent.com/657716/84654373-572a9480-af0f-11ea-8540-b72cdfadb224.png)

**Comment by AnthonyBrunelli** [comment]
Vu ok !
