### ISSUE TITLE
adresser aux porteurs de démarche et administrateurs ministériels des mails leurs présentant les derniers votes concernant leurs démarches

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#922]
fréquence : mensuelle
si un porteur de démarche est porteur de n démarches lui lui envoyer q'un seul mail
n'envoyer un message que si il y a eu 20 votes supplémentaires depuis le dernier envoi
contenu du mail : 

- note globale + évolution de la note au cours du dernier mois par rapport aux mois précédents => ca pourrait être une copie d'écran de la page de synthèse, à voir

- un lien d'accès vers la page d'avis détaillés

**Comment by lucaa** [comment]
lié à la fonctionnalité proposée dans #898 (notification par email des évolutions).

**Comment by AnthonyBrunelli** [comment]
Doublon.
