### ISSUE TITLE
Changer l'emplacement et nom des graphes d'historique des avis

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#925]
Prolongement de #883 

Reste à traiter:

- Déplacer les schémas au-dessus du "Détails des avis", 

- Renommer le tableau d'historique mensuel "répartition des avis" en "nombre de votes"

**Comment by lucaa** [comment]
> Renommer le tableau d'historique mensuel "répartition des avis" en "nombre de votes" 

@AnthonyBrunelli @georges-bayard : l'utilisation du mot "vote" me paraît dangereuse, on utilise "avis" partout sur cet écran pour nommer les opinions des utilisateurs. Plutôt "nombre d'avis" ?

**Comment by lucaa** [comment]
C'est fait, aussi mis en staging prêt à tester.

![image](https://user-images.githubusercontent.com/657716/85877862-187ebf00-b7d8-11ea-9b62-46b296a2b96a.png)

**Comment by AnthonyBrunelli** [comment]
Okey super! Merci pour la note sur "vote" et "avis" :)
