### ISSUE TITLE
URGENT - Bug je donne mon avis

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#927]
@lucaa Salut!

Bug sur un champ je donne mon avis - on a deux cas (tout est en fichier joint). A priori, pb rencontré par ceux qui écrivent beaucoup de texte (c'est mon analyse, à voir)... Tu peux regarder? On en discute si besoin...

**Comment by lucaa** [comment]
même problème que #921 .

**Comment by lucaa** [comment]
Il y a 3 champs de texte libre dans le formulaire d'avis:
* autre difficulté
* autre aide
* verbatim

L'erreur en question peut survenir pour un des cas suivants:
* autre difficulté ou autre aide sont plus longs que 255 caractères
* verbatim est plus long que 60 000 caractères. 

Il n'y à pas de détails dans le pdf qui parle du bug, mais pour avoir une estimation des choses, j'ai généré 60 000 caractères de Lorem ipsum, c'est approx ce montant là: [60000.pdf](https://github.com/DISIC/wikidemarches/files/4878186/60000.pdf) . Je pense que c'est assez compliqué de dépasser cette limite si on écrit du texte à la main, mais si on copie-colle des choses j'imagine qu'on peut atteindre cette limite assez facilement.
Ainsi, le plus probable est que le problème est survenu sur un des premiers champs, autre difficulté ou autre aide.

Du coup, qu'est-ce qu'on vise comme comportement attendu?
A. un meilleur traitement de l'erreur dans le cas ou le texte rempli dépasse 255 caractères - troncation automatique ou validation du formulaire avant envoi ou autre chose
B. accepter plus que 255 caractères dans ces champs

@AnthonyBrunelli , tu peux m'appeler pour décider vite.

**Comment by AnthonyBrunelli** [comment]
Merci Anca! Comme on disait: solution B., utilisateur averti dans l'intitulé (255 caractères maximum) et blocage (troncation pour les anciens navigateurs)

**Comment by lucaa** [comment]
Les 2 champs ont été limités à 250 signes max, avec l'affichage suivant:
![image](https://user-images.githubusercontent.com/657716/86623934-bafe2580-bfc2-11ea-864b-1c188a57a0e9.png)

La solution choisie rend impossible pour l'utilisateur de remplir plus de 250 caractères dans le formulaire dans le navigateur, et marche correctement sur tous les navigateurs et IE à partir de la version 10 (cf. https://caniuse.com/#search=maxlength ).
Finalement, comme le support des navigateurs est assez étendu, je n'ai pas mis en place de troncation. Ainsi, pour tout envoi d'avis qui contourne l'implementation de la limitation par les formulaires HTML, il y aura toujours une erreur, mais je ne vois pas de possibilité pour un utilisateur normal de faire un tel envoi.

Le correctif a également été ajouté en production.

**Comment by AnthonyBrunelli** [comment]
Testé en prod merci :)
