### ISSUE TITLE
ajouter l'information "directions" dans le tableau de bord interne des démarches

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#928]
aide les EP à retrouver facilement leurs démarches. Ex : ASP

**Comment by lucaa** [comment]
C'est fait, et installé en production.
En plus, une amélioration a été apportée au filtre par ministères pour pouvoir filtrer par plusieurs ministères et avoir toutes les démarches qui correspondent à ces ministères.
