### ISSUE TITLE
supprimer les votes antérieures au 14 aout sur la démarche 1472 « Déclaration de ressources pour la détermination des droits à prestations pour les assurés du régime agricole »

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#932]
Il faut supprimer des votes sur la démarche 1472 « Déclaration de ressources pour la détermination des droits à prestations pour les assurés du régime agricole ». Plus précisément ceux exprimés avant le 14 aout. En effet avant cette date le bouton correspondant à cette démarche était installé sur deux démarches ce qui fait que ces votes ne veulent rien dire (cf échange de mail ci-dessous).

**Comment by lucaa** [comment]
C'est fait, 240 avis utilisateurs ont exportés et supprimés de la plateforme, de la démarche 1472.
