### ISSUE TITLE
Amélioration de la vue des porteurs et leurs démarches

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#934]
Il s'agit d'une amélioration de la vue crée pour #591 , pour ajouter des informations supplémentaires (besoin exprimé par email par  @gbayard ) : 
* Nom, Prénom du porteur
* Démarche dans top 250 ou pas
* si possible, direction et ministère du porteur

**Comment by lucaa** [comment]
> si possible, direction et ministère du porteur

Le ministère du porteur ne peut pas être affiché car cette association n'existe pas vraiment pour un utilisateur. Un utilisateur peut être membre dans un groupe associée à une direction mais il ne peut pas être directement associé à un ministère. Ainsi, je peux essayer de vérifier l’appartenance à un groupe direction et afficher cette information mais pas plus.

**Comment by lucaa** [comment]
J'ai enrichie la vue créée pour #591 (disponible dans les outils d'administration lien "Démarches par porteur") pour:
* afficher une ligne du tableau pour chaque démarche (avant c'était une ligne par porteur), en répétant les informations du porteur à chaque fois
* afficher le statut top250 ou pas pour chaque démarche, ainsi que son ID (pour pouvoir l'utiliser dans un excel avec du lookup, si nécessaire )
* afficher le nom et prénom séparé pour chaque porteur (l’adresse email y était déjà)
* afficher groupes directions desquelles l'utilisateur est membre (ainsi que le groupe AdministrateurMinisteriel)

**Comment by georges-bayard** [comment]
Ca me va parfaitement ! j'ajoute que pas la peine d'export excel un simple copier coller permet de faire l'interface avec excel. Tu as fait l'évol en prod à priori ?

**Comment by lucaa** [comment]
@georges-bayard  Oui, oui, c'est en prod.
