### ISSUE TITLE
Affichage de la satisfaction utilisateur sur 10 au lieu de pourcentage

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#936]
* Dans le tableau de l'Observatoire, ajouter "(sur 10)" dans l'intitulé de l'entête de colonne et mettre au format "9,7" (et pas "9,7/10") sur chaque ligne.
* Sur la page démarche/graphe: mettre au format "9,7/10"
* Attention: sur la même page, dans "Historique des avis", "Indice de satisfaction global", mettre aussi les notes sur 10 (en mettant "sur 10" uniquement dans titre : "Indice de satisfaction global (sur 10)")

La modification au niveau de l'observatoire sera faite pour **tous** les observatoires, également ceux du passé.

**Comment by lucaa** [comment]
Note: du point de vue technique, l'idée est de ne pas modifier le format des données dans le json de l'observatoire mais uniquement ajouter une règle lors de l'affichage sur l'écran.

**Comment by slauriere** [comment]
L'indice de satisfaction s'affiche à présent sur un plafond de 10 au lieu de 100 auparavant, aussi bien dans la section donnant sa valeur globale que dans celle affichant son historique, avec au plus un chiffre après le séparateur décimal (contre juste un chiffre entier lorsque nous avions des pourcentages) et l'utilisation de la virgule comme séparateur (et non le point, séparateur en langue anglaise utilisé par défaut dans l'application de diagramme ChartJS).
