### ISSUE TITLE
Affichage d'un observatoire sous forme de tableau HTML

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#937]
Le besoin a été remonté dans le contexte de l'export des données d'un observatoire (telles qu'affichées sur l'observatoire), sans les décorations de l'observatoire.
Un tableau HTML permet à la fois un affichage web plus utilisable, mais aussi la transformation en feuille de calcul par une copie (avec copier-coller) sous forme de feuille de calcul dans les logiciels qui ont cette fonctionnalité.

**Comment by lucaa** [comment]
Le code a été fait en production et utilisé pour sortir des données récemment, mais pas committé dans la codebase. 
Cette tache est pour committer le code.

**Comment by slauriere** [comment]
Le code de la page `Demarches.Dashboard.Code.DashboardTableSheet` du serveur de production a été committé dans la codebase.
