### ISSUE TITLE
Affichage de l'indice de satisfaction en format "sur 10" également sur le tableau de bord "interne"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#938]
Il s'agit de la propagation de la modification d'affichage décrite dans #936 pour le tableau de bord interne qui affiche toutes les démarches.

**Comment by slauriere** [comment]
Le tableau de bord interne (page `/TableauDeBord/`) affiche à présent l'indice de satisfaction sur une échelle de 0 à 10 au lieu d'un pourcentage précédemment (l'info de l'échelle se trouve dans le libellé de la colonne correspondante, comme sur l'observatoire public).
