### ISSUE TITLE
Remplacer le ministère dans l'observatoire avec l'information du thème (regroupement externe)

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#939]
Dans l'observatoire (json et affichage), l'information utilisée pour le ministère doit être désormais le regroupement externe.

Ainsi, le regroupement externe (thème) n'est plus utilisé du tout (dans le json le champ doit être vide).
En consequence, il n'y aura plus de thème affiché sur l'observatoire.
Le comportement de cette information doit être le même que celui d'avant, pour le ministère (e.g. pour le filtre),

**Comment by lucaa** [comment]
Note: cette modification sera faite dans le json généré, pas uniquement à l'affichage.

**Comment by slauriere** [comment]
Le champ "ministère" tel qu'affiché utilise à présent la valeur du champ "regroupement externe" aussi bien dans les lignes du tableau que dans les filtres. Ce changement n'a un impact que sur les nouveaux tableaux de bord générés et sur celui en temps réel, pas sur les anciens JSON.

**Comment by slauriere** [comment]
PS : j'ai bien testé et validé cette fonctionnalité en dev, sur deux tableaux de bord : celui en temps réel, et sur un nouveau tableau de bord généré à la date du 4 février. Par ailleurs j'ai vérifié que les tableaux de bord anciennement générés fonctionnent toujours comme attendu (néanmoins j'ai regénéré par erreur un JSON pour celui de mai 2020).
