### ISSUE TITLE
Changer l'ordre de tri par défaut de l'observatoire

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#940]
Les démarches doivent être triées selon l’ordre suivant : ministère politique, administration, ordre alpha des démarches.

**Comment by lucaa** [comment]
Comme l'administration ne fait pas partie des données affichées sur l'observatoire, je vais implémenter une première version avec les 2 autres ordres.

**Comment by lucaa** [comment]
C'est fait, et mis en production, sans l'administration.

**Comment by georges-bayard** [comment]
C'est parfait. Mais retour en arrière possible. On discute pour savoir si on ne peut pas trier par indice de sat ou par volumétrie totale

**Comment by lucaa** [comment]
> C'est parfait. Mais retour en arrière possible. On discute pour savoir si on ne peut pas trier par indice de sat ou par volumétrie totale

Je rouvre alors pour tracer le fait que c'est pas fait.

**Comment by lucaa** [comment]
Aucune mise à jour pour la spécification de cette fonctionnalité depuis 05/02/2021. Je re-ferme pour correctement tracer l'état du ticket.
