### ISSUE TITLE
Mise à jour de la page expliquant le mode de calcul du taux de satisfaction (échelle de 0 à 10)

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#941]
Suite au passage, pour le taux de satisfaction, d'une échelle sur cent à une échelle sur 10 (#936), la page documentant le mode de calcul de ce taux doit être mise à jour pour indiquer cette nouvelle échelle. La nouvelle formulation sera intégrée à l'arbre de fichiers sources (développement) une fois qu'elle aura été mise à jour par la DINUM sur le serveur de production.

**Comment by lucaa** [comment]
Les modifications ont été faites en production en fevrier, par @georges-bayard  .

**Comment by lucaa** [comment]
La page a été integrée aussi sur dans les sources dans le commit d23bbc7c93a324323f29a5286c68cf2a146bebe0 . Je ferme.
