### ISSUE TITLE
Ajout d'outil de suppression d'avis par date pour les administrateurs Dinum

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#942]
L'outil a déjà été ajouté, dès le début du projet et perfectionné pour la tache #773, mais pas rendu disponible aux admins.

**Comment by lucaa** [comment]
Fait, et installé en prod.

**Comment by georges-bayard** [comment]
Merci Anca. peux tu rendre le champ démarche obligatoire ? je trouve ça dangereux de pouvoir supprimer tous les avis sur une période pour toutes les démarches. Je ne vois pas le besoin fonctionnel non plus.

**Comment by lucaa** [comment]
> Merci Anca. peux tu rendre le champ démarche obligatoire ? je trouve ça dangereux de pouvoir supprimer tous les avis sur une période pour toutes les démarches. Je ne vois pas le besoin fonctionnel non plus.

Discuté par email: suite à la présence d'une étape de validation dans laquelle les avis doivent être sélectionnés pour être supprimés, ceci n'est plus nécessaire.
