### ISSUE TITLE
Ajout d'une nouvelle valeur possible pour la colonne "Réalisable en ligne"

### ISSUE THREAD

**Issue by lucaa** [DISIC/wikidemarches#944]
Dans les méta-données des démarches (et à afficher sur l'observatoire), une nouvelle valeur est désormais possible pour l'information "Réalisable en ligne":  En déploiement local.

Besoins de gestion / affichage:
* aucun impacte sur les autres colonnes ou pré-conditionnement des autres méta-données en fonction de cette valeur (doit se comporter comme "Partiel" ou "Bêta"
* affichée dans l'observatoire avec le fond vert clair (#d1f7c4) et une couleur de texte foncé (noir?)

**Comment by lucaa** [comment]
Dans le formulaire de mise à jour d'une démarche, on affiche un mini-guide pour renseigner cette information:

![image](https://user-images.githubusercontent.com/657716/116705115-7f5a9f00-a9cc-11eb-9198-9863d318f7a7.png)

Idéalement, la nouvelle valeur devrait également être brièvement expliquée dans le texte d'aide. @georges-bayard : pouvez me fournir ce texte, s'il vous plaît?

**Comment by georges-bayard** [comment]
En déploiement local si la responsabilité du déploiement effectif d’une démarche en ligne auprès des usagers sur l’ensemble du territoire est assurée par les collectivités territoriales

**Comment by lucaa** [comment]
Affichage après implémentation dans l'observatoire:

![image](https://user-images.githubusercontent.com/657716/116729125-16cceb80-a9e7-11eb-981b-2b61fd4da80d.png)

La couleur #d1f7c4 a été utilisée avec la couleur de texte de la valeur "Oui" de la même colonne (vert très foncé). Le contraste entre les 2 est suffisant du pdv de la RGAA.

Le contraste entre #d1f7c4 et le blanc qui est le fond de la page ne passe pas le seuil de contraste de la RGAA mais c'est déjà le cas pour toutes les autres couleurs de fond des autres valeurs (vert, orange, rouge, gris, bleu), et il n'y a pas de contrainte (de ce que j'ai compris) pour ce contraste, les seuls contrastes à respecter sont pour les textes sur leurs fonds, donc aucun besoin d'agir.

**Comment by lucaa** [comment]
Les autres usages de l'information Réalisable en ligne ont été audités et un seul endroit cette nouvelle valeur pourrait avoir un impacte (même si peu probable):

Dans l'observatoire, dans les détails d'une démarche (suite au click sur la flèche de la fin de la ligne), une Date d'ouverture du service dématerialisée est affichée pour toutes les démarches dont le statut de dématérialisation est autre que "Oui" (Non, Bêta, Partiel):

![image](https://user-images.githubusercontent.com/657716/116730112-5e07ac00-a9e8-11eb-98ca-f5bbf64c192a.png)

@georges-bayard confirmez-vous que pour ce nouveau statut le comportement doit être le même? (c.a.d que la date d'ouverture doit être affichée pour les démarches en déploiement local)

**Comment by lucaa** [comment]
Je ferme le ticket pour marquer le travail comme fini. S'il n'y a pas de confirmation pour la réponse ci-dessus, il faudra re-ouvrir le ticket car il y aura des modifications à faire.

**Comment by lucaa** [comment]
> @georges-bayard confirmez-vous que pour ce nouveau statut le comportement doit être le même? 

Réponse validée par téléphone, il faut garder une date affichée à ce niveau.

**Comment by lucaa** [comment]
Il faut également:
* changer la couleur (afficher au même vert que "oui"
* changer le texte affiché pour dire "En cours de déploiement local"
