### ISSUE TITLE
supprimer du footer de la page de vote le lien vers contact

### ISSUE THREAD

**Issue by georges-bayard** [DISIC/wikidemarches#948]
Les usagers qui votent sur "je donne mon avis" ont accès à la page de contact "nosdemarches@modernisation.gouv.fr". résultat : nous recevons beaucoup de messages de demande d''aide sur les démarches elle-même. Il faut donc supprimer du footer visible du formulaire de vote le lien vers le contact

**Comment by AnthonyBrunelli** [comment]
Vu. Tout ok pour toi Anca ou besoin que je vois quelque chose sur le sujet?

**Comment by lucaa** [comment]
@AnthonyBrunelli @georges-bayard : pas besoin d'autres informations, j'ai tout ce qu'il faut.
L'idée est d'installer la modification en production dès qu'elle est prête?

**Comment by AnthonyBrunelli** [comment]
Sauf indication contraire de @georges-bayard , oui :)

**Comment by georges-bayard** [comment]
pas de souci pour moi

**Comment by lucaa** [comment]
C'est fait et installé en production.

**Comment by georges-bayard** [comment]
pour moi c'est ok  ; vérifié en prod
