### ISSUE TITLE
Changement de l'intitulé "Accessibilité" en pied de page

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#950]
Mettre "Accessibilité : non conforme" à la place (lien en pied de page).

**Comment by slauriere** [comment]
Modification effectuée !

**Comment by AnthonyBrunelli** [comment]
J'annonce la couleur: si on passe la barre des 50% de conformité avec le RGAA (on est à 36%), il faudra mettre "partiellement conforme"... Mais on verra.

**Comment by AnthonyBrunelli** [comment]
Désolé, vous avez trop bien bossé, avec ce qui a été contrôlé par @amezyane en staging, on passé à partiellement conforme. Il faut donc indiquer "Accessibilité : partiellement conforme" à la place (intitulé du lien en pied de page).

**Comment by slauriere** [comment]
Cool, bonne nouvelle :-) – J'ai la modif.

**Comment by AnthonyBrunelli** [comment]
Vu en staging, super!
