### ISSUE TITLE
Dans le header, pour le logo "République française", supprimer la mention "Logo" de l'alternative textuell

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#951]
Tout est dans le titre

**Comment by AnthonyBrunelli** [comment]
Critère 1.3: Pour chaque image porteuse d'information ayant une alternative textuelle, cette alternative est-elle pertinente (hors cas particuliers) ?

**Comment by slauriere** [comment]
Mention "Logo" supprimée, également pour l'image "Observatoire de la qualité des démarches en ligne" juste à côté du coup (même logique je suppose)

**Comment by amezyane** [comment]
@slauriere oui effectivement, mais comme la 2e image doit être remplacé par du texte stylé en CSS, je ne l'avais comptée dans la correction
