### ISSUE TITLE
Footer: alternatives liens Twitter et Linkedin

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#954]
Dans le footer, les liens Twitter et Linkedin sont vides. Pour chacun, rajouter un texte caché avec pour valeur respective "La DINUM sur Twitter" et "La DINUM sur Linkedin". 

Exemple pour le lien Twitter : <a href="https://twitter.com/_DINUM" class="twitter" target="_blank"><span class="fa fa-twitter"></span><span class="sr-only">La DINUM sur Twitter</span></a>

**Comment by AnthonyBrunelli** [comment]
Critère 6.2: Dans chaque page web, chaque lien a-t-il un intitulé ?

**Comment by AnthonyBrunelli** [comment]
Critère 10.2 également: Dans chaque page web, le contenu visible porteur d’information reste-t-il présent lorsque les feuilles de styles sont désactivées ?
--> Les liens "Twitter" et "Linkedin" ne sont plus visibles, étant vides

**Comment by slauriere** [comment]
J'ai bien ajouté un texte caché pour ces deux liens.
