### ISSUE TITLE
Sur mobile, le bouton ouvrant le menu (<button [...] data-target="#xwikimainmenu">) doit avoir un attribut aria-controls="xwikimainmenu", pour faire le lien entre les deux.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#955]
Tout est dans le titre.

Critère 7.1: Chaque script est-il, si nécessaire, compatible avec les technologies d’assistance ?

**Comment by slauriere** [comment]
Changement effectué. (et répercuté comme amélioration possible pour le drawer standard XWiki : [XWIKI-18843](https://jira.xwiki.org/browse/XWIKI-18843))

**Comment by AnthonyBrunelli** [comment]
Pas pu recetter, à voir par Améziane, mais rien de bloquant.

**Comment by amezyane** [comment]
Attribut aria-controls bien implémenté, validé en prod
