### ISSUE TITLE
Page d'accueil: (balise <title>), préciser le nom de la page "Accueil"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#956]
Dans le titre de la page (balise <title>), préciser le nom de la page "Accueil" : "Accueil - L’observatoire de la qualité des démarches en ligne" (comme sur les autres pages).

Critère 8.6: Pour chaque page web ayant un titre de page, ce titre est-il pertinent ?

**Comment by slauriere** [comment]
Le titre de la page d'accueil a été mis à jour et uniformisé.
