### ISSUE TITLE
La balise <nav> doit regrouper les liens du menu principal seulement et non le logo

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#958]
Remplacer la balise ```<nav class="navbar navbar-default actionmenu">``` par une ```<div>```. 

Remplacer la balise ```<div id="xwikimainmenu">``` par une balise ```<nav role="navigation" id="xwikimainmenu">```.

Critère 9.2: Dans chaque page web, la structure du document est-elle cohérente (hors cas particuliers) ?

**Comment by lucaa** [comment]
Finalement, la modification est plutôt sans effet de bord, je l'ai faite pour l'avoir dans 4.9.

**Comment by AnthonyBrunelli** [comment]
Je connais pas les tenants et aboutissants, mais en tout a bien l'air corrigé dans le code.
