### ISSUE TITLE
Dans le menu mobile, il y a une balise <ul class="nav navbar-nav navbar-left"> avec un <li role="separator"> vide. La supprimer ainsi que la balise <li>.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#959]
Tout est dans le titre.

Critère 9.3: Dans chaque page web, chaque liste est-elle correctement structurée ?

**Comment by ClemDee** [comment]
Les balises ul et li ont été retirées.

**Comment by lucaa** [comment]
Je rouvre pour traiter ce commentaire (ajustement purement technique): https://github.com/DISIC/wikidemarches/commit/564f7395388113bc7bcb453b64af875b74372528#r57204913 .

Il y a aussi https://github.com/DISIC/wikidemarches/commit/564f7395388113bc7bcb453b64af875b74372528#r57205027 mais je n'insiste pas vraiment pour corriger celui-ci, même si ça peut être utile.

**Comment by ClemDee** [comment]
* Rajout des macros retirées précédemment même si elle ne sont pas utilisées

Le point d'extension `org.xwiki.platform.topmenu.left` n'étant pas utilisé on peut le garder supprimé sans problème.

**Comment by AnthonyBrunelli** [comment]
@lucaa c'est technique ou il faut qu'on contrôle quelque chose là-dessus?

**Comment by lucaa** [comment]
> @lucaa c'est technique ou il faut qu'on contrôle quelque chose là-dessus?

il y a un contrôle, de markup, qui est lu par les lecteurs d’écran, si j'ai bien compris - y'avait un élément vide, maintenant il n'y a plus.

**Comment by AnthonyBrunelli** [comment]
Vu avec Ugo, ok.
