### ISSUE TITLE
Dans le footer, après le texte "Les sites publics", les liens doivent être dans une liste <ul>, chaque lien étant dans une balise <li>.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#961]
Tout est dans le titre.

Critère 9.3: Dans chaque page web, chaque liste est-elle correctement structurée ?

**Comment by slauriere** [comment]
Les sites publics du footer sont à présent structurés en liste `ul` avec un `li` par item.

**Comment by AnthonyBrunelli** [comment]
Vu ça me paraît bon. @amezyane tu veux regarder aussi?

**Comment by amezyane** [comment]
La liste est correctement implémentée, mais les espaces étant toujours présents, le lecteur d'écran les compte comme éléments de la liste et annonce 10 éléments au lieu de 5. Ex : "gouvernement.fr, lien, 3 sur 10"

**Comment by slauriere** [comment]
Intéressant ! La présence des espaces vient du mode `inline` utilisé pour un affichage horizontal de la liste. Le MDN [recommande](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace#spaces_in_between_inline_and_inline-block_elements) d'utiliser le mode d'affichage `flex` pour résoudre ce problème. J'ai retenu cette approche, je vous laisse valider et rouvrir le ticket si nécessaire.

**Comment by lucaa** [comment]
@slauriere C'est vraiment tres tres bizarre et spécial comme comportement (et n'a pas trop de logique pour moi...). 
Si je comprends bien, ce qu'ils expliquent c'est que, du fait que le parent ```<ul>``` est marqué comme "inline", tout d'un coup les fils texte (au moins les whitespace texte) sont honorés comme des noeuds texte: le ```<ul>``` reçoit du contenu texte, donc, alors que les specs ne disent rien sur le fait que du contenu texte serait accepté https://developer.mozilla.org/fr/docs/Web/HTML/Element/ul#r%C3%A9sum%C3%A9_technique  - voir aussi les specs HTML 5 et living standard linkées).

Une solution possible dans ce cas c'est de dire: ok, très bien, le ```<ul>``` inline se comporte comme un paragraphe, les noeuds texte sont relevants. Ce serait donc notre faute car on a écrit le HTML comme si c'était block:
```
<ul>
  <li>..</li>
  <li>..</li>
</ul>
```
on devrait l'écrire comme pour un paragraphe, tout sur la même ligne:
```<ul><li>..</li><li>..</li></ul>```

Mais, si **je** dois écrire le ```<ul>``` comme un paragraphe, personnellement je mettrait des whitespace entre les elements ```<li>``` car ce sont des mots, et les mots doivent être séparés entre eux dans un contexte inline par des espaces...

Mais, si on fait ça, on a exactement le même problème qu'au début car, apparemment, en plus du fait que le navigateur honore les noeuds texte dans le ```<ul>``` le lecteur d'écran les promeut au niveau d'_élément de la liste_, et les annonce comme tel. @amezyane: serait-il possible que ceci soit une limitation / bug du lecteur d'écran? En même temps, je comprends aussi le comportement du lecteur: les espaces sont là, il ne peut pas juste les ignorer, et il ne sait pas lire "liste séparée par des espaces" car ce n'est pas un concepte qui existe...

Finalement, malgré quelques mystères non résolus (pour moi) je pense que la seule nuance qui permet de réconcilier les choses est de dire que, finalement, nous ne sommes pas devant du contenu inline (comme dans un texte) mais bien devant du contenu block (tout comme la liste "nos univers") avec la seule différence que les éléments de l'énumération doivent s'empiler sur l'axe horizontale (contrairement à la liste "nos univers" qui s'empile sur la verticale). Effectivement, dans ce cas, le flex est une bonne réponse car fait pour gérer la problématique des axes.

Du coup, cela voudrait dire que, lors de l'implémentation du critère 9.3, il faudrait aussi faire attention à la nuance de "inline" vs. "horizontale".

**Comment by amezyane** [comment]
@slauriere @lucaa Désolé pour la réponse tardive, et mea culpa, après vérif c'était un bug de mon lecteur d'écran... je l'ai réinstallé et le soucis n'apparait plus... bref, je valide le ticket

**Comment by lucaa** [comment]
@slauriere je propose, donc, de revenir en arrière sur le commit, puisque l'implémentation initiale convient.

**Comment by slauriere** [comment]
J'ai reverté le commit en effet.
