### ISSUE TITLE
Tableau Observatoire: Les quatres liens permettant de partager la page en sont pas suffisamment explicites et sont vides (ex: "Via Twitter", "Via Facebook").

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#963]
Les quatres liens permettant de partager la page sont vides (ex: "Via Twitter", "Via Facebook"). Rajouter dans chaque lien un texte caché. Exemple pour le lien "Twitter" : 

```<a href="https://twitter.com/[...]" class="social-network" target="_blank" aria-label="Via Twitter"><span class="fa fa-twitter" aria-hidden="true"></span><span class="sr-only">Via Twitter</span></a>```

Critère 6.2: Dans chaque page web, chaque lien a-t-il un intitulé ?

Les quatre liens permettant de partager la page ne sont pas suffisament explicites (ex: "Via Twitter", "Via Facebook"). Rajouter dans leur attribut aria-label le texte "Partager". Exemple : "Partager via Twitter", "Partager via Facebook", etc.

Critère 6.1: Chaque lien est-il explicite (hors cas particuliers) ?

**Comment by slauriere** [comment]
Un texte de partage en mode "sr-only" a été ajouté à chacun des liens de partage (texte : "Via Twitter" etc.), et l'attribut "aria-label" de ces liens est à présent plus explicite : "Partager via Twitter" etc.
