### ISSUE TITLE
Des espaces sont utilisées dans le code HTML pour créer une marge

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#964]
"Des espaces sont utilisées dans le code HTML pour créer une marge entre les quatres liens ""Partager via Twitter"", ""Partager via Facebook"", etc (voir l'inspecteur de code).

De même, entre le bouton ""Filtrer"" et la <div> contenant le bouton ""Filtrer par"".
Ces espaces doivent être supprimés du code HTML et les marges recréées en CSS."

Critère 10.1 : Dans le site web, des feuilles de styles sont-elles utilisées pour contrôler la présentation de l’information ?

**Comment by lucaa** [comment]
> "Des espaces sont utilisées dans le code HTML pour créer une marge entre les quatres liens ""Partager via Twitter"", ""Partager via Facebook"", etc (voir l'inspecteur de code).

Pour moi, le contexte d'affichage ce ces liens est un contexte "inline" (pour clarification, j'aurais du probablement tout entourer d'un paragraphe). Dans ce cas particulier, ces espaces ne remplacement pas la gestion de l'agencement par le CSS, mais ont le même rôle de séparation que les espaces entre 2 mots du même paragraphe: indiquer au lecteur qu'un mot et fini et que le prochain commence. Pour moi, l'utilisation des espaces dans ces cas est même obligatoire (même si on pourrait arriver à obtenir une séparation visuelle par le CSS). La meilleure solution dans ce cas est probablement que les liens en question soient dans une liste (<ul>) car c'est une liste semantiquement.

Donc, par rapport au critère "Critère 10.1 : Dans le site web, des feuilles de styles sont-elles utilisées pour contrôler la présentation de l’information ?" (https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#topic10 ), dans ce contexte spécifique, je dirais que ce n'est pas complètement clair que les espaces sont bannis, car ils n'ont pas un rôle pur visuel, mais aussi pour séparer les "mots" du contenu entre eux.

> De même, entre le bouton ""Filtrer"" et la contenant le bouton ""Filtrer par"".

dans ce cas là, vu que le conteneur de "trier par" est un div, la même logique ne s'applique pas. Par contre, de mon point de vue, le conteneur pourrait / devrait être un élément inline (span) au quel cas la même logique s'applique. Mais j'admets que sur 2 boutons, le contexte inline se défend difficilement (beaucoup plus que pour le cas d'une énumération de réseaux sociaux).

**Comment by amezyane** [comment]
Pour les quatre liens vers les réseaux sociaux, je trouve également que la liste <ul> est la meilleure solution et un bon compromis sémantiquement. 

Pour les boutons "filtres" et "trier par"

**Comment by amezyane** [comment]
Pour les quatre liens (vers les réseaux sociaux), maintenant que tu le soulignes, les espaces sont appropriés vu le contexte "inline", mais une liste <ul> doit effectivement être utilisée ici, ce qui enlève le soucis des espaces.

Pour les deux boutons "Filtrer" et "Filtrer par" : 
- un <span> serait plus adapté pour "contenir" le bouton "trier par"
- pour moi, l'espace est visiblement utilisé pour créer un effet de marge (à part si je me trompe). Je vais me renseigner pour voir s'il est autorisé

**Comment by amezyane** [comment]
Pour le 2ème cas, l'espace n'ayant pas d'impact utilisateur (restitution), il peut être laissé.

**Comment by lucaa** [comment]
@slauriere à faire:
* remplacement des liens avec une liste
* remplacement, si possible et pas trop de bugs, du markup des boutons "filtrer" avec un span

**Comment by slauriere** [comment]
Le commit ci-dessus : 
* Utilise une liste pour les liens de partage en disposition flex pour ne pas introduire d'espaces entre les éléments
* Utilise un span pour le conteneur des boutons de filtre / tri et pour le conteneur du bouton de tri, avec modification des règles CSS associées pour conserver le centrage sur mobile

-> Je clos et vous laisse rouvrir si nécessaire.

**Comment by AnthonyBrunelli** [comment]
Vu avec Erwan, a priori pas d'impact utilisateur donc pas de problème pour la mise en prod. Issue à valider par Améziane pour la fermeture.

**Comment by AnthonyBrunelli** [comment]
Je passe en tested.
