### ISSUE TITLE
Tableau Observatoire: Dans les filtres, les champs de sélection "Tous les ministères" et "Tous les publics" n'ont pas de label.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#965]
Critère 11.1: Chaque champ de formulaire a-t-il une étiquette ?

"Dans les filtres, les champs de sélection ""Tous les ministères"" et ""Tous les publics"" n'ont pas de label.
Rajouter un attribut aria-label sur chaque balise <select> correspondante, avec pour valeur respective ""Filtrer par ministère"" et ""Filtrer par type de public"". 

Le champ ""Mot clé"" n'a pas de label également. Supprimer la balise <label> qui l'englobe, supprimer son attribut aria-controls et lui rajouter un attribut aria-label=""Filtrer par mot clé"": 
![Capture](https://user-images.githubusercontent.com/35567048/124137865-6468e180-da86-11eb-9a81-2b13c30beb0d.PNG)

**Comment by AnthonyBrunelli** [comment]
![Capture](https://user-images.githubusercontent.com/35567048/124137891-6c288600-da86-11eb-9844-d21116aacef4.PNG)

**Comment by lucaa** [comment]
> Rajouter un attribut aria-label sur chaque balise correspondante, avec pour valeur respective ""Filtrer par ministère"" et ""Filtrer par type de public"". Le champ ""Mot clé"" n'a pas de label également. Supprimer la balise qui l'englobe, supprimer son attribut aria-controls et lui rajouter un attribut aria-label=""Filtrer par mot clé"":

@slauriere voici le plan technique pour l'implémentation, modifié pour correspondre aux contraintes techniques:
* ajouter aria-label sur les 3 éléments de formulaire: ministere, publics, et Mots-clés
* le tag label autour de l'input mots-clés doit être changé en span (comme pour les autres éléments) -> attention à refaire tout le CSS pour qu'il s'applique correctement au nouveau markup
* pour l'attribut aria-controls: vérifie comment ça se fait qu'il est là, s'il a été ajouté pour un autre ticket. Si pas de bonne raison, tu peux l'enlever.

**Comment by slauriere** [comment]
* J'ai ajouté un `aria-label` aux trois éléments du formulaire de filtrage.
* La balise `label` est générée par le composant DataTables lui-même pour l'élément de recherche par mot-clé donc il est faisable mais non trivial de le remplacer par un `span`.
* L'attribut `aria-controls` est également généré par DataTables. Je ne connaissais pas cet attribut, qui semble indiquer [une relation entre deux éléments de la page](https://tink.uk/using-the-aria-controls-attribute/). N'est-ce pas le cas ici, entre le champ "mot clé" et le contenu du tableau ? De même pour les autres filtres, ou bien est-ce en fait effectivement hors sujet @AnthonyBrunelli, @amezyane ?

**Comment by amezyane** [comment]
Salut @slauriere,  
Pour la dernière remarque, bien vu, l'attribut `aria-controls` peut être laissé ici, au temps pour moi.

**Comment by slauriere** [comment]
Merci @amezyane pour ton feedback.

Concernant la balise `label` : comme celle-ci est générée par un composant que nous ne contrôlons pas (DataTables), je propose d'utiliser l'approche ["Associating labels implicitly"](https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly) plutôt que l'attribut `aria-label` si cela vous va ? Cela donnerait ceci : 

```
<label>
<span class="sr-only">Filtrer par mot clé</span>
<input type="search" class="" placeholder="Mot clé" aria-controls="top-demarches">
</label>
```

**Comment by slauriere** [comment]
Je note toutefois que la page WAI du W3C indique "Generally, explicit labels are better supported by assistive technology."...

**Comment by amezyane** [comment]
Cette méthode est possible, par contre :
- le champs `<input>` doit avoir un id unique et le `<label>` un attribut `for` égal à cet `id`.
- à cause de l'attribut `placeholder`, le lecteur d'écran lira "Filtrer par mot clé Mot clé" (contenu du label + `placeholder`) pour info

**Comment by slauriere** [comment]
Merci pour ces infos. J'ai opté pour un remplacement dynamique de la balise `label` par un simple `span` avec utilisation de l'attribut `aria-label`, ce qui donne ceci, je vous laisse vérifier que c'est ok : 

```
<span class="label-textfilter">
<input type="search" class="" placeholder="Mot clé" aria-controls="top-demarches" aria-label="Filtrer par mot clé">
</span>
```
