### ISSUE TITLE
Tableau observatoire. Dans le footer, le lien "Revenir en haut de la page" est vide. 

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#966]
Dans le footer, le lien "Revenir en haut de la page" est vide. Dans la balise <a href="#top"></a>, rajouter un texte caché en CSS "Revenir en haut de la page" : <a href="#top"><span class="sr-only">Revenir en haut de la page</span></a>.

**Comment by lucaa** [comment]
@AnthonyBrunelli il s'agit du même bouton "revenir en haut de page" que pour #971, correct?

**Comment by lucaa** [comment]
@slauriere même remarque par rapport à l'implementation que pour #971 .

**Comment by amezyane** [comment]
@lucaa Il s'agit bien du même bouton

**Comment by slauriere** [comment]
Le bouton de retour en haut de page comporte bien un texte à présent, avec la classe `sr-only` pour un affichage uniquement sur les lecteurs d'écran.

**Comment by slauriere** [comment]
[Extension d'origine](https://extensions.xwiki.org/xwiki/bin/view/Extension/Back%20To%20Top) mise à jour également.
