### ISSUE TITLE
Tableau Observatoire. Après le tableau, la phrase "Total : 244 démarches" doit être dans une balise <p>

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#967]
Après le tableau, la phrase "Total : 244 démarches" doit être dans une balise 
< p > : < div class="dataTables_info" id="top-demarches_info" role="status" aria-live="polite"  >< p >Total : 244 démarches</p></div>

Critère 8.9: Dans chaque page web, les balises ne doivent pas être utilisées uniquement à des fins de présentation. Cette règle est-elle respectée ?

**Comment by AnthonyBrunelli** [comment]
![Capture](https://user-images.githubusercontent.com/35567048/124145313-f83dac00-da8c-11eb-8a06-40ce5580b50d.PNG)

**Comment by slauriere** [comment]
Problème réglé via une option de callback dans DataTables pour wrapper le texte dans un "p". Voir aussi cette petite amélioration concernant ce message en pied de tableau : #987
