### ISSUE TITLE
Tableau observatoire : les balises  < tr > ne doivent pas avoir d'attribut role="row".

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#968]
Tableau observatoire : les balises < tr > ne doivent pas avoir d'attribut role="row".

Supprimer cet attribut pour chaque balise < tr >.

**Comment by lucaa** [comment]
Les premières recherches montrent que ce markup est celui généré par datatables.js, qu'on utilise pour dessiner ce tableau, donc la modification n'est pas pas immédiate.

Par contre, ce n'est pas clair si la présence de cet attribut représente une erreur d'accessibilité ou juste une préférence. D'après https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Row_Role#best_practices , ce ne serait pas vraiment interdit, même si l'usage est recommandé pour d'autres cas d'usage.

**Comment by AnthonyBrunelli** [comment]
Oui, désolé, @amezyane me signale que ce point avait été supprimé de l'audit. Donc je ferme et je fais disparaître ça!

**Comment by lucaa** [comment]
Note: Je viens d'utiliser le ```role=row``` pour faire marcher le placement des étiquettes pour #1003 , donc si jamais on revient sur la décision de l'enlever, il faudra trouver une autre solution pour #1003 (la qualification supplémentaire du ```tr``` est necessaire pour #1003 pour éviter l'ajout des étiquettes dans le ```tr``` avec les détails de la démarche.
