### ISSUE TITLE
Tableau observatoire. Dans les entêtes (balises < th >) du tableau, la balise < br > est utilisée pour faire un retour à la ligne.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#969]
Dans les entêtes (balises <th>) du tableau, la balise <br> est utilisée pour faire un retour à la ligne. Rajouter à chaque balise <br> l'attribut role="presentation", afin qu'elle ne soit pas lue par les lecteurs d'écran.

**Comment by slauriere** [comment]
L'attribut `role="presentation"` a bien été ajouté à la balise `br` des entêtes. Sur mobile, les libellés s'affichent bien sans retour à la ligne comme précédemment, avec correction d'un problème d'espace manquant pour le libellé "Dites-le nous une fois".
