### ISSUE TITLE
Tableau Observatoire. Lorsqu'on tabule, le bouton "Edition avril 2021" reçoit le focus avant les boutons "Filtres" et "Trier par".

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#970]
"Lorsqu'on tabule, le bouton ""Edition avril 2021"" reçoit le focus avant les boutons ""Filtres"" et ""Trier par"". Cela devrait être l'inverse. 
Placer le bouton ""Edition avril 2021"" après les deux boutons dans le code HTML."

**Comment by lucaa** [comment]
Techniquement, les filtres font partie du tableau (dans le sens ou c'est le même composant datatables qui affiche les filtres et le tableau) alors que le selecteur d'observatoire est un composant séparé, affiché avant. Visuellement, effectivement, les filtres sont à gauche et le selecteur à droite mais même du point de vue de l'usage, un utilisateur choisira d'abord quel observatoire il veut voir et ensuite comment le filtrer. 
Il faut peut-être changer l'agencement visuel pour guider cet usage ?

Étant donnée cette analyse, est-ce qu'il y a un critère d'accessibilité qui rend cette tache nécessaire ou c'est plutôt une préférence?

**Comment by amezyane** [comment]
Pour le RGAA, la correction est nécessaire car l'ordre de tabulation doit suivre l'ordre d'affichage des éléments (de gauche à droite, de haut en bas) : "_Critère 12.8. Dans chaque page web, l’ordre de tabulation est-il cohérent ?_".

Du point de vue de l'usage, il peut être préférable du coup de placer le sélecteur en premier et les filtres ensuite.

**Comment by lucaa** [comment]
@slauriere je pense que j'ai confondu les éléments qui font partie du tableau, je pense que ce sont que les filtres _une fois activés_, mais pas le bouton qui les active (le bouton "filtres"). Il est donc possible que l'ordre des 2 menus (filtres & selecteur de tableau) n'est pas si importante. Peux-tu vérifier et changer l'ordre, si possible?

![image](https://user-images.githubusercontent.com/657716/125747209-0a291ccc-6dbf-460d-a299-918498a6b676.png)

**Comment by lucaa** [comment]
>  Il est donc possible que l'ordre des 2 menus (filtres & selecteur de tableau) n'est pas si importante. 

Je viens de me rendre compte, il s'agit de l'affichage sur mobile, ou, du pdv visuel, puisque les 2 boutons (filtres & selecteur) s'affichent un en dessous de l'autre, il est important d'afficher les filtres juste au dessus du tableau pour garder la coherence visuelle:

![image](https://user-images.githubusercontent.com/657716/125748939-c43454e0-c1e3-4781-87a3-c6582e5ea7f7.png)


Du coup, la seule solution qui me semble rester est l'inversion de l'ordre des menus, y compris sur desktop.

**Comment by lucaa** [comment]
@slauriere donc, il faudra changer l'ordre des 2 menus sur desktop, pour correspondre à l'ordre du mobile et à l'ordre des tabs.

@AnthonyBrunelli comme le design de la page observatoire a été géré de manière assez stricte , je préfère que, de votre côté, tu valides que ce changement est acceptable. Nous allons livrer la modification en staging (pour pouvoir voir à quoi ça ressemble) asap.

**Comment by slauriere** [comment]
Changement d'ordre effectué. L'ordre de tabulation suit à présent l'ordre d'affichage de ces boutons. Je vous laisse aviser sur le statut du ticket du point de vue de la validation complète (design).

**Comment by AnthonyBrunelli** [comment]
Vu avec Erwan: ok pour la navigation clavier MAIS contrôler le fait qu'on n'accède jamais au chevron pour les informations complémentaires dans le tableau. Point à voir avec Améziane.
Pas de pb pour la mise en prod.

**Comment by lucaa** [comment]
> contrôler le fait qu'on n'accède jamais au chevron pour les informations complémentaires dans le tableau. Point à voir avec Améziane

Tu parles de ce ticket #827 ?

**Comment by AnthonyBrunelli** [comment]
C'est ça, on y accède pas par la tabulation, c'est bien ce qui est indiqué.
