### ISSUE TITLE
Tableau observatoire. Lorsqu'on survole le bouton "Retour en haut", le texte "Revenir en haut de la page" apparait. Il doit également apparaitre lorsqu'on a le focus sur le bouton.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#971]
Tout est dans le titre.

**Comment by lucaa** [comment]
Amélioration à faire dans l'extension back to top qui est utilisée pour cette fonctionnalité.
@slauriere il se peut que le code de l'extension est copié dans l'observatoire (et pas utilisé comme une dépendance), il faudrait mettre à jour l'extension néanmoins.

**Comment by slauriere** [comment]
Le texte "Revenir en haut de page" s'affiche à présent lors d'un focus sur le bouton en plus de s'afficher au survol.

**Comment by slauriere** [comment]
J'ai mis à jour [l'extension d'origine](https://extensions.xwiki.org/xwiki/bin/view/Extension/Back%20To%20Top) avec cette amélioration.

**Comment by amezyane** [comment]
Le texte n'est toujours pas visible à la prise du focus sur le bouton.

**Comment by slauriere** [comment]
Tout à fait. Erreur de ma part ! Le commit ci-dessus corrige le problème : les règles d'affichage du texte sont à présent attachées à l'ancre HTML et non plus à son conteneur, pour que ce soit bien l'état de l'ancre (survol, et surtout focus car son conteneur div ne peut pas recevoir le focus via le clavier) qui contrôle l'affichage du texte.

**Comment by slauriere** [comment]
J'ai également répercuté cette correction sur l'extension d'origine : extension [Back To Top](https://extensions.xwiki.org/xwiki/bin/view/Extension/Back%20To%20Top).

**Comment by AnthonyBrunelli** [comment]
Vu avec Erwan (et moi tout seul aussi hein): ça a l'air bon. Pas de problème pour la mise en prod, je laisse Améziane fermer si ok aussi pour lui.

**Comment by amezyane** [comment]
Testé sur FF, Chrome, Edge et Safari, validé en prod
