### ISSUE TITLE
Graphiques démarches. Le lien "Afficher le détail sur la démarche" et l'encart (balise < dl >) qu'il contrôle ne respectent pas le design pattern ARIA "disclosure"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#973]
Le lien "Afficher le détail sur la démarche" et l'encart (balise < d >) qu'il contrôle ne respectent pas le design pattern ARIA "disclosure" : 
- la balise < dl > doit avoir un attribut id="demarche-details" 
- le lien doit être un bouton (balise <button>), avec les attributs aria-controls="#demarche-details" et aria-expanded égal à "false" quand l'encart est fermé ou à "true" quand il est ouvert. 
- enfin, le bouton doit être activable avec les touches Espace et Entrée.

**Comment by lucaa** [comment]
@slauriere à mettre en deuxième priorité car cela me semble plus élaboré à mettre en place.

**Comment by slauriere** [comment]
J'ai pu effectué la modif sans trop de difficulté :-) -> je clos le ticket et vous laisse vérifier. J'ai réutilisé pour le bouton le même style que celui des boutons au-dessus du tableau de l'observatoire, peut-être faut-il ajuster les espacements / la taille de la police...

**Comment by slauriere** [comment]
PS : j'ai utilisé `aria-controls="demarche-details"` (sans dièse devant l'identifiant) car cela semble être plutôt l'usage sinon dites-moi ? (ref : https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role)

**Comment by amezyane** [comment]
@slauriere effectivement il s'agit d'un mauvais copier-coller, bien vu :)
