### ISSUE TITLE
Graphiques démarches. Le contraste est insuffisant pour les textes gris

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#974]
"Le contraste est insuffisant pour les textes gris suivants : 
- ""Public(s)""
- ""Champ ministériel""
- ""Données recueillies en ligne sur ce site, entre le 1er avril 2020 et le 31 mars 2021, auprès de 2 466 internautes.""
- ""Indice de satisfaction global""
- ""Répartition des avis""
Utiliser le site suivant pour trouver d'autres couleurs de texte offrant un contraste suffisant : 
https://contrast-finder.tanaguru.com/result.html?foreground=%23777&background=%23FFF&ratio=4.5&isBackgroundTested=false&algo=Rgb&distanceSort=asc"

**Comment by lucaa** [comment]
doublon partiel avec la #851, à fermer en même temps.

**Comment by lucaa** [comment]
> ""Public(s)""
> ""Champ ministériel""

Je suppose que ceci parle des informations affichés quand on clic sur "afficher le détail de la démarche" ...

**Comment by lucaa** [comment]
à utiliser le même gris que "Afficher le détail", qui semble être correct du pdv contraste.

**Comment by AnthonyBrunelli** [comment]
Yep, je dirais que c'est ça, je viens d'aller voir. Et le "indice de satisfaction globale" est le premier, au dessus de la note. @amezyane me corrigera si besoin.

**Comment by amezyane** [comment]
Il s'agit bien de ces textes là, ou plus précisément des balises `.demarche-details dt`en CSS

**Comment by amezyane** [comment]
<img width="274" alt="Capture d’écran 2021-07-05 à 11 56 50" src="https://user-images.githubusercontent.com/3500526/124454003-3f2aea80-dd88-11eb-8f1b-5213558a8dbd.png">

**Comment by slauriere** [comment]
Merci pour vos indications. La couleur utilisée pour tous ces libellés est à présent le gris clair `#666` (variable `@gray-light` déjà définie dans le thème), ce qui donne un niveau de contraste de 5.74 avec le fond. Je ferme #851 également.
