### ISSUE TITLE
Graphiques démarches. Le contraste est insuffisant pour le lien "?"

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#975]
"Le contraste est insuffisant pour le lien ""?""/""Comment est calculé le taux de satisfaction d'une démarche"".
Utiliser le site suivant pour trouver d'autres couleurs de texte offrant un contraste suffisant : 
https://contrast-finder.tanaguru.com/result.html?foreground=%23a6a6a6&background=%23FFF&ratio=4.5&isBackgroundTested=false&algo=Rgb&distanceSort=asc  "

**Comment by lucaa** [comment]
@slauriere comme d'habitude, si la couleur en question est une couleur du color theme, il faudrait vérifier la nouvelle couleur pour les autres usages. Il faut aussi vérifier que la couleur utilisée est une couleur de 'foreground' . Si réconciliation difficile, une couleur spécifique peut être choisie uniquement pour ce bouton.

**Comment by slauriere** [comment]
La couleur `@gray-light` (`#666`) est à présent utilisée pour ce lien comme pour les libellés mentionnés dans #974, ce qui résout le problème de contraste.
