### ISSUE TITLE
Graphiques démarches. Lorsqu'on survole le bouton "Retour en haut", un texte apparait. Il doit également apparaître lorsqu'on a le focus sur le bouton.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#976]
Tout est dans le titre.

**Comment by lucaa** [comment]
Amélioration à faire dans l'extension back to top qui est utilisée pour cette fonctionnalité.
@slauriere il se peut que le code de l'extension est copié dans l'observatoire (et pas utilisé comme une dépendance), il faudrait mettre à jour l'extension néanmoins.

**Comment by lucaa** [comment]
@AnthonyBrunelli on parle bien du bouton de retour en haut ajouté pour #823 ? Le titre de cette tache dit "graphiques demarche" et à priori ce bouton n'est pas affiché pour les graphiques mais pour l'observatoire...

**Comment by AnthonyBrunelli** [comment]
@amezyane Il me semble que effectivement cette issue est à supprimer car déjà traité dans #971 pour le tableau, et le bouton n'existe pas sur la page "Synthèse"/"Graphique" (j'ai renommé Graphique ce que tu appelais synthèse). Tu confirmes?

**Comment by AnthonyBrunelli** [comment]
Vu, erreur de notre part, on ferme.
