### ISSUE TITLE
Page de connexion. Les balises < dl>, < dt> et < dd> qui englobent le formulaire ne sont pas pertinentes ici et doivent être supprimées.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#978]
Tout est dans le titre.

**Comment by lucaa** [comment]
@AnthonyBrunelli ce n'est pas clair pour moi si cet élément pose un problème ou c'est une histoire de préférence (par exemple, moi je peux défendre que les dls autour des formulaires sont sémantiques :) ).
Ce markup fait partie d'un standard de formulaire de la plateforme XWiki (https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/FrontendResources/VerticalForms/) , et donc va apparaître au plusieurs endroits sur l'observatoire... 
Y a-t-il un critère d'accessibilité qui interdit ce markup? (comme ça on peut mettre à jour les recommandations de markup de la plateforme XWiki).

**Comment by AnthonyBrunelli** [comment]
...et je fais une passe à @amezyane  pour cette question :)

Améziane, je te présente Anca,
Anca, voici Améziane.

(désolé Améziane, je ne sais pas pourquoi ton tag est avec un 'y' au lieu du 'i' mais c'est pas moi!)

**Comment by amezyane** [comment]
Salut @lucaa ! 

C'est effectivement une histoire de préférence, l'utilisation des <dl> dans les <form> n'étant en effet pas interdite sémantiquement. Je serai curieux du coup de savoir quel est leur apport dans un formulaire ?

**Comment by lucaa** [comment]
> Je serai curieux du coup de savoir quel est leur apport dans un formulaire ?

Malheureusement, je ne peux pas citer la justification exacte du choix initial dans la plateforme car je ne retrouve pas le fil de conversation de la mailing list (mais apparemment on a directement fait le choix des dls juste après avoir passé l'étape "table": http://jira.xwiki.org/browse/XWIKI-386 ).
Je pense que originalement le choix était justifié par le fait d'essayer de toujours choisir les conteneurs qui portent le maximum de sens possible, en plus de pouvoir fournir les conteneurs nécessaires aux styles. Le sens du dl étant assez générique de "liste de paires de cle-valeur", il s'applique assez bien à un formulaire qui est une telle liste de paires, même si les éléments obligatoires du formulaire (labels & inputs) fournissent aussi cette sémantique.
La plupart des formulaires dans XWiki sont utilisés pour les méta-données attachées à une unité de contenu (e.g. dans le cas de l'observatoire une démarche ou un avis), la plupart du temps avec même markup et affichage en mode visualisation et modification, et pour ce cas le markup des listes de definition est idéal (car décrit une liste de méta-données et leurs valeurs).

Par contre, je suis plutôt d'accord que l'attachement du standard aux nom des éléments de la dl plutôt qu'a des classes aurait pu être évité, pour des raisons de flexibilité.

**Comment by amezyane** [comment]
Merci pour ta réponse exhaustive. Du coup @AnthonyBrunelli cet issue peut être fermé

**Comment by AnthonyBrunelli** [comment]
Ok, je ferme.

**Comment by AnthonyBrunelli** [comment]
Erratum: il reste un soucis avec la liste <dl>

**Comment by amezyane** [comment]
Dans la balise <dl> qui englobe le formulaire, la dernière balise <dd> doit être une balise <dt>.

**Comment by lucaa** [comment]
> Dans la balise <dl> qui englobe le formulaire, la dernière balise <dt> doit être une balise <dd>.

Effectivement ce ```<dt>``` a cet endroit est difficilement explicable, j'ai créé un ticket pour la plateforme XWiki : https://jira.xwiki.org/browse/XWIKI-18816 .

Par contre, il ne peut pas être un ```<dd>``` car, dans ce cas, il sera associé du point de vue sémantique avec le ```<dd>``` précedent (et associé au même ```<dt>```), ce qui n'est pas la réalité de son sens. Le meilleur choix me paraît de ne pas décrire les boutons du formulaire comme des paires nom-valeur (donc fermer le ```<dl>``` avant les boutons).

**Comment by amezyane** [comment]
@lucaa c'est encore mieux si on peut fermer le `<dl>` avant les boutons de soumission !

**Comment by slauriere** [comment]
Modification effectuée !

**Comment by amezyane** [comment]
@lucaa Dans le formulaire de connexion, la dernière balise `dt` est vide, la balise `dd` associée contenant à la fois le label et la checkbox. J'ai un doute sur comment améliorer la sémantique ou si on est obligé de garder les balises telles quelles dans ce cas ?

<img width="588" alt="Capture d’écran 2021-07-15 à 11 49 31" src="https://user-images.githubusercontent.com/3500526/125768276-e9f4258d-49d8-49ea-9835-b40e615a02df.png">
<img width="630" alt="Capture d’écran 2021-07-15 à 11 50 09" src="https://user-images.githubusercontent.com/3500526/125768279-4459cea2-4bc9-4550-817d-8be0bd951bfe.png">

**Comment by lucaa** [comment]
Oui, j'ai vu aussi la gestion de cette dernière option qui n'est pas idéale.
Je n'ai pas une idée claire de l'amélioration de ce markup, dans le standard pour les formulaires verticaux https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/FrontendResources/VerticalForms/ on recommande l'emplacement des ```<label>``` dans des elements dt, mais dans ce cas l'input est _dans_ l'element label (ce qui est bien), donc difficile à séparer en dt et dd .

**Comment by amezyane** [comment]
Si c'est facile à modifier, l'idéal serait effectivement la dernière solution (séparer la checkbox et son étiquette). Sinon tant pis je pense, le W3C nu validator n'invalide pas le `dt `vide...

**Comment by amezyane** [comment]
@lucaa Je n'ai pas réussi à trouver le ticket correspondant, mais dans le formulaire d'inscription, deux balises `dd `avec des champs cachés sont présentes à la fin du formulaire, il faudrait que la balise `dl `soit fermée avant ces deux champs.

**Comment by lucaa** [comment]
pour le formulaire d'inscription, pour moi il n'y a pas de problème que les 2 inputs cachés se trouvent dans des éléments dd, par contre, leur sémantique n'est pas la bonne.
D'après la spécification, il peut y avoir plusieurs elements dd un après l'autre, mais ils seront tous associés avec le dernier dt. Dans ce cas, le dernier dt est celui pour la captcha, qui n'est pas du tout la sémantique des dd cachés. 
Je vais ouvrir une nouvelle tache pour l'amélioration de la sémantique de ces formulaires

**Comment by lucaa** [comment]
J'ai ouvert le ticket #996 pour ces améliorations supplémentaires, que je n'ai pas planifié pour l'instant car, si j'ai bien compris de la conversation de ce ticket, ces changements n'impactent pas vraiment l'accessibilité.

**Comment by amezyane** [comment]
Effectivement, l'impact niveau a11y est faible, par contre côté RGAA le critère 9.3 reste invalidé du coup : _Dans chaque page web, chaque liste est-elle correctement structurée ?_

**Comment by AnthonyBrunelli** [comment]
Débat donc je laisserai Améziane prendre la main. Si j'ai bien compris, pas d'impact donc le test/ la réponse peuvent attendre son retour.

**Comment by AnthonyBrunelli** [comment]
Suivi par ailleurs, je passe en tested.
