### ISSUE TITLE
Page de connexion. Les champs obligatoires doivent être indiqués.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#979]
Les champs obligatoires doivent être indiqués. Rajouter un attribut required ou aria-required="true" aux deux champs. Ensuite, rajouter la mention "(obligatoire)" dans le label de chaque champ.

**Comment by slauriere** [comment]
J'ai bien ajouté l'attribut `required'` aux deux champs ainsi que la mention "(obligatoire)" dans leurs labels respectifs.
