### ISSUE TITLE
Page de connexion. Les champs doivent utiliser l'autocomplétion.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#980]
Les champs doivent utiliser l'autocomplétion. Rajouter au champ "Nom d'utilisateur" (balise <input>) l'attribut autocomplete="username", et au champ "Mot de passe" (balise <input>) l'attribut autocomplete="current-password".

**Comment by lucaa** [comment]
@slauriere verifie aussi, stp, si un ticket pour la plateforme XWiki a été créé pour ça entre temps.

**Comment by slauriere** [comment]
Il existe [un ticket sur ce sujet pour le formulaire du profil utilisateur](https://jira.xwiki.org/browse/XWIKI-18002) mais pas pour celui de connexion semble-t-il, j'en ai créé un  : [XWIKI-18811](https://jira.xwiki.org/browse/XWIKI-18811).

**Comment by slauriere** [comment]
J'ai bien ajouté l'attibut `autocomplete` aux deux champs avec les valeurs spécifiées.
