### ISSUE TITLE
Page JDMA. L'image du bouton "Je donne mon avis" et les deux flèches sont des images décoratives.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#981]
"L'image du bouton ""Je donne mon avis"" et les deux flèches sont des images décoratives et doivent être ignorées par les technologies d'assistance.
Pour chacune, supprimer la valeur de l'attribut alt."

**Comment by lucaa** [comment]
@AnthonyBrunelli ces modifications seront à faire du côté contenu, potentiellement en passant par l'editeur de syntaxe.
Il faut se rendre sur la page "Comment donner son avis" et utiliser le bouton Modifier pour modifier directement la page. L'editeur de syntaxe est disponible soit en choisissant le mode wiki lors de l'edition (tel que décrit ici https://github.com/DISIC/wikidemarches/issues/985#issuecomment-873058578 ) soit en passant par le bouton "source" de l'editeur visuel.
Le manuel pour la syntaxe est ici: https://observatoire.numerique.gouv.fr/XWiki/XWikiSyntax?syntax=2.1&section=Images&xpage=print . 

Par contre, comme l'attribut 'alt' était obligatoire dans certaines versions de HTML, il est implicite si pas spécifié, il faut essayer de le spécifier vide.

**Comment by AnthonyBrunelli** [comment]
Ok c'est fait! @amezyane ça devrait être bon en prod: je te laisse contrôler de ton côté et l'indiquer sur notre fichier de suivi?

**Comment by amezyane** [comment]
@AnthonyBrunelli Je ne vois pas les changements en prod (testé en nav privée aussi) :/

**Comment by amezyane** [comment]
Validé en prod et audit MAJ
