### ISSUE TITLE
Page JDMA. Pour les deux captures d'écran, dans la balise < img> correspondante, la valeur de l'attribut "width" doit être "600" et non "600px".

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#982]
Tout est dans le titre.

**Comment by lucaa** [comment]
@AnthonyBrunelli Il s'agit de cette page là, https://observatoire.numerique.gouv.fr/Aide/Donner%20son%20avis , non?

**Comment by AnthonyBrunelli** [comment]
Parfaitement :)

**Comment by slauriere** [comment]
Je rouvre ce ticket car la page en question doit en fait être éditée directement en production en tant que page de contenu. Elle est accessible depuis la page des [outils d'administration](https://observatoire.numerique.gouv.fr/Administration/). La modification de l'attribut `width` des images peut être effectuée soit en mode wysiwyg soit en mode wiki (cf explication dans [ce commentaire](https://github.com/DISIC/wikidemarches/issues/985#issuecomment-873058578) pour l'usage du mode wiki).

**Comment by AnthonyBrunelli** [comment]
Okey, c'est fait! Je te laisse gérer l'issue @slauriere mais j'ai bien apporté la correction.

**Comment by amezyane** [comment]
Validé sur la prod et sur l'audit :)
