### ISSUE TITLE
Connexion et inscription. Le lien d'accès au contenu n'est pas fonctionnel

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#983]
"Le lien d'accès au contenu n'est pas fonctionnel car l'ancre ""#xwikicontent"" vers lequel il renvoie n'est pas présente sur cette page. Deux solutions : 
1) Soit modifier la valeur de l'attribut href du lien pour ""#main"".
2) Soit rajouter une ancre < a id=""xwikicontent"">< /a> juste avant le contenu principal. Par ex, après la balise < div class=""main layoutsubsection"">. "

**Comment by lucaa** [comment]
@slauriere dans le code pour les liens d'accès rapide, il faut tester l'action de l'URL courante, pour toutes les actions autre que view, il faudrait pointer vers #mainContentArea au lieu de #xwikicontent , car #xwikicontent est uniquement affiché pour le mode 'view'.

**Comment by slauriere** [comment]
Le lien d'accès au contenu pointe bien à présent vers la zone de contenu sur les pages de connexion et d'inscription.
