### ISSUE TITLE
Page d'accueil. Modifications dans les textes.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#985]
Les textes des différentes tuiles seront modifiés par la Dinum (nous avons les droits).

Pas tout nous n'est modifiable. Il faudrait:

- Remplacer "Comment évaluons nous la qualité des démarches ?" par "Comment évaluons-nous la qualité des démarches administratives ?"
- Rajouter "concrètes" et "et de suivre" dans le paragraphe "Des questions ?" comme suit: "Notre objectif est l’amélioration concrète des 250 démarches administratives les plus utilisées par les usagers. Cet observatoire nous permet d’identifier et de suivre les démarches à améliorer en priorité."
- à venir: modification du texte d'intro.

**Comment by slauriere** [comment]
Anthony, Hormis le texte d'intro qui nécessitera notre intervention effectivement, vous pouvez modifier de votre côté les deux autres textes mentionnés dans ce ticket en accédant aux contenus en question depuis la [page d'administration](https://observatoire.numerique.gouv.fr/Administration/), section "Pages de textes explicatifs". Pour un contrôle fin du formatage il peut-être utile d'éditer ces pages en mode wiki plutôt qu'en mode wysiwyg : cela nécessite de passer en mode "avancé" depuis l'onglet "préférences" du profil utilisateur, puis de cliquer sur "Modifier > Wiki" depuis les pages de contenu.

**Comment by AnthonyBrunelli** [comment]
J'ai corrigé le point 2 (partie "Des questions?").

**Comment by lucaa** [comment]
Les modifications des textes faites par @AnthonyBrunelli ont été livrés en staging pour teste. @slauriere reste-t-il d'autres choses à faire pour cette tache ou on peut fermer?

**Comment by slauriere** [comment]
Sur cette tâche il reste deux points : 
* Remplacer "Comment évaluons nous la qualité des démarches ?" par "Comment évaluons-nous la qualité des démarches administratives ?". Pour cela : depuis [la page d'administration](https://observatoire.numerique.gouv.fr/Administration/) cliquer sur le lien "Explication des critères", et mettre à jour le titre de la page. Je te laisse faire la modification @AnthonyBrunelli ? À ta dispo.
* Nouveau texte d'intro : nous pouvons le mettre en place dès qu'il est prêt (il n'est pas modifiable directement par la DINUM en l'état)

**Comment by AnthonyBrunelli** [comment]
Nouveau texte d'intro:

Des démarches en ligne simples, accessibles à tous et compréhensibles simplifient la vie des citoyennes et citoyens. L’Observatoire vous permet de suivre la qualité de la numérisation des 250 démarches les plus utilisées.

**Comment by slauriere** [comment]
OK Anthony, texte d'intro mis à jour ! Et vu pour le titre, je clos cette tâche du coup.

**Comment by AnthonyBrunelli** [comment]
Okey pour le texte d'intro en staging MAIS le titre que j'avais changé en "Comment évaluons-nous la qualité des démarches administratives ?" n'est pas à jour (j'ai peur que ça écrase ma modif en prod après).

**Comment by lucaa** [comment]
> le titre que j'avais changé en "Comment évaluons-nous la qualité des démarches administratives ?" n'est pas à jour (j'ai peur que ça écrase ma modif en prod après).

Sur les pages qui sont prévues pour être modifiées en production on n'écrase jamais les contenus de la production. À priori toutes les pages pour lesquelles on t'a indiqué de faire la modification toi-même en production sont dans cette catégorie de pages "de contenu", prévues à être modifiées en prod.

Pour ces pages "de contenu", les contenus sont propres à l'instance (la prod avec ses contenus, le staging avec ses contenus, ainsi que le dev).
La seule raison pour laquelle tout les autres textes sont "à jour" sur staging c'est que j'ai rapatrié tout ça la semaine dernière (le 14) de la prod au staging, pour faciliter les tests. Ainsi, toute modification faite en prod après cette date n'a pas été reprise sur staging, mais cela ne veut pas du tout dire que la production sera écrasée avec la valeur du staging.
Je viens de vérifier en prod, la modification du titre date du 19/07.

Je referme le ticket pour marquer qu'il n'y a pas de problème par rapport à la livraison. @AnthonyBrunelli si tu veux avoir un staging identique à la production pour ces contenus, tu peux faire la modification et staging aussi.

**Comment by AnthonyBrunelli** [comment]
Ok compris, je verrai en prod, pas de danger majeur.
