### ISSUE TITLE
Page Graphique. Dans chaque balise < canvas>, dans la balise < table>, chaque balise < th> doit avoir un attribut scope="col".

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#986]
Tout est dans le titre (j'espère). Sinon, à voir avec Améziane.

**Comment by lucaa** [comment]
@slauriere cette modification me paraît du même type que #972 , à faire ensemble.

**Comment by slauriere** [comment]
J'ai bien ajouté un `scope="col"` à chaque `th` de la page des graphes. @lucaa : la modification est plus simple que celle à faire pour #972 car les tableaux sont générés par des scripts Wikidémarches contrairement à la balise `canvas` qui, elle, est générée par l'extension ChartJS.
