### ISSUE TITLE
Correction du message en pied de tableau

### ISSUE THREAD

**Issue by slauriere** [DISIC/wikidemarches#987]
Le message en pied de tableau affiche "démarches" au pluriel même si les résultats ne contiennent qu'une seule démarche. Par ailleurs en cas de filtrage s'affiche aussi "(filtrage appliqué sur 245 total entrées)" : sans doute supprimer "total" et / ou reformuler.

**Comment by slauriere** [comment]
Le singulier est à présent utilisé en cas de démarche unique dans les résultats.

**Comment by AnthonyBrunelli** [comment]
Vu et bien corrigé merci @slauriere d'avoir relevé ça.
