### ISSUE TITLE
Le site doit disposer d'une page "Plan du site" dédiée, en plus du menu de navigation.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#988]
@amezyane C'est dans le pied de page qu'il faut mettre le lien, c'est ça?

**Comment by amezyane** [comment]
Désolé @AnthonyBrunelli je viens de voir ton message. 

1. La page doit être accessible via un lien "Plan du site" dans le footer. Ce lien peut être rajouté après le lien "conditions générales" ou "accessibilité", à voir ce qui est le mieux dans ce contexte. Dans tous les cas, il doit être présent sur toutes les pages du site et situé au même endroit. 

2. Dans le RGAA : "il n’est pas nécessaire que le plan du site contienne les liens vers toutes les pages du site, en revanche il est nécessaire qu’à partir du plan du site, l’utilisateur puisse atteindre l’ensemble des pages du site". Pour moi, il faut du coup afficher les pages principales, excepté celles dédiées aux démarches (avec les graphiques) :

- L'observatoire
- En savoir plus sur l'observatoire
- A propos
- En savoir plus sur nos critères d'évaluation
- Comment donner son avis ?
- Conditions générales d'utilisation
- Accessibilité
- Contact
- Accès administration

J'ai repris l'ordre des liens depuis le footer. 

Enfin, à voir ce que l'on fait de la colonne "Plan du site" dans le footer ensuite

**Comment by lucaa** [comment]
La page dédiée plan du site a été implémentée dans le ticket #1011 , dans la version 4.9.

Par contre, elle ne contient pas tous les liens mentionnés par @amezyane dans le commentaire ci-dessus.

@AnthonyBrunelli est-ce qu'on ferme cette tâche à ce moment ou on la garde ouverte pour faire encore des changements dans la page? Il est facile de mettre à jour la page en question, donc autant le faire dans la 4.9, avec #1011.

**Comment by AnthonyBrunelli** [comment]
Ok j'ai la main pour modifier donc je ferme ici et je m'en charge par ailleurs pour la mise à jour.

**Comment by AnthonyBrunelli** [comment]
Ok pour le lien en pied de page donc c'est bon.
