### ISSUE TITLE
Tableau Obs. Dans chaque bloc contenant les détails d'une démarche, le lien vers la démarche (en bleu foncé) n'est pas assez contrasté avec le fond bleu clair.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#989]
Tout est dans le titre.

**Comment by slauriere** [comment]
Salut @AnthonyBrunelli, J'ai l'impression que [Tanaguru](https://contrast-finder.tanaguru.com/) nous indique un contraste de 4.6 entre ces deux couleurs non ? Doit-on cibler un contraste encore supérieur ? (avec comme foreground : #006be6 et comme background : #f2f7fe)  (et au survol : foreground = #00479a)

**Comment by amezyane** [comment]
@AnthonyBrunelli @slauriere Effectivement, erreur de ma part... j'ai dû mal lire le chiffre dans la console de firefox, désolé

**Comment by AnthonyBrunelli** [comment]
Ok, erreur, je supprime!
