### ISSUE TITLE
Pages de connexion  et d'inscription. Titres des pages.

### ISSUE THREAD

**Issue by AnthonyBrunelli** [DISIC/wikidemarches#990]
Le titre des pages de connexion et d'inscription doivent être "Connexion - L'observatoire..." et "Inscription - L'observatoire..." au lieu de 
"XWikiLogin - L'observatoire...".

**Comment by slauriere** [comment]
En effet ! Changement effectué sur le site de développement et signalé comme amélioration à apporter à XWiki de façon générale : [XWIKI-18814](https://jira.xwiki.org/browse/XWIKI-18814)

**Comment by lucaa** [comment]
Voir commentaire sur le commit ici https://github.com/DISIC/wikidemarches/commit/59b1c16691fe02dbcb60ddf1045165c868a73468#r53136162 .

**Comment by slauriere** [comment]
J'ai ajouté le traitement de l'action 'loginsubmit' qui manquait effectivement (et signalé cela aussi pour mémo sur [XWIKI-18814](https://jira.xwiki.org/browse/XWIKI-18814)). Le champ "title" de l'objet XWikiPreferences a à présent une longueur de 253 caractères proche de la taille max supportée par MySQL (255).
